### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by EMK2000** [yeriomin/YalpStore#10]
Hope to add a black mode for AMOLED screen.

**Comment by yeriomin** [comment]
Yalp is not an app, you have to use all the time, so screen battery drain should not be an issue here.

But it is an interesting suggestion. Could you point me to a opensource app which has dark mode? It seems it is not some "mode" or android feature, just a plain black ui theme.

**Comment by EMK2000** [comment]
For example this one: https://github.com/andDevW/getChromium/
