### ISSUE TITLE
Fixed Russian translation

### ISSUE THREAD

**Issue by ashed** [yeriomin/YalpStore#100]
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string-array name="blackOrWhiteValues">
        <item>black</item>
        <item>white</item>
    </string-array>
    <string-array name="blackOrWhiteLabels">
        <item>@string/pref_update_list_white_or_black_black</item>
        <item>@string/pref_update_list_white_or_black_white</item>
    </string-array>
    <string-array name="uiThemeValues">
        <item></item>
        <item>light</item>
        <item>dark</item>
        <item>black</item>
    </string-array>
    <string-array name="uiThemeLabels">
        <item></item>
        <item>@string/pref_ui_theme_light</item>
        <item>@string/pref_ui_theme_dark</item>
        <item>@string/pref_ui_theme_black</item>
    </string-array>
    <string-array name="updateIntervalValues">
        <item>0</item>
        <item>3600000</item>
        <item>86400000</item>
        <item>604800000</item>
    </string-array>
    <string-array name="updateIntervalLabels">
        <item>@string/pref_background_update_interval_never</item>
        <item>@string/pref_background_update_interval_hourly</item>
        <item>@string/pref_background_update_interval_daily</item>
        <item>@string/pref_background_update_interval_weekly</item>
    </string-array>
</resources>

<resources>
    <string name="about_developer_email_label">Почта разработчика:</string>
    <string name="about_logged_in">Ваш текущий аккаунт:</string>
    <string name="about_copied_to_clipboard">Скопировано в буфер обмена</string>
    <string name="about_self_update_checking">…проверяем</string>
    <string name="about_self_update_available" formatted="false">…доступна 0.%d</string>
    <string name="about_self_update_unavailable">…обновления нет</string>
    <string name="list_line_2_updatable" formatted="false">Обновлено %s</string>
    <string name="list_line_2_search" formatted="false">%s ↓, %.1f★, %s</string>
    <string name="list_empty_updates">Обновлений нет</string>
    <string name="list_empty_search">Ничего не найдено</string>
    <string name="list_incompatible">несовместимо</string>
    <string name="list_update_all">Обновить всё</string>
    <string name="action_about">О приложении</string>
    <string name="action_settings">Настройки</string>
    <string name="action_logout">Разлогиниться</string>
    <string name="action_search">Поиск</string>
    <string name="action_updates">Обновления</string>
    <string name="action_ignore">Не обновлять</string>
    <string name="action_unignore">Снова обновлять</string>
    <string name="action_whitelist">Белый список обновлений</string>
    <string name="action_unwhitelist">Не обновлять</string>
    <string name="action_categories">Категории</string>
    <string name="search_filter">Все приложения</string>
    <string name="search_title">Поиск приложений</string>
    <string name="dialog_title_application_crashed">В Yalp Store произошёл сбой</string>
    <string name="dialog_message_application_crashed">Вы можете помочь разработчику исправить это, отправив email с подробностями об ошибке. Нажмите OK чтобы открыть email-клиент с подготовленным письмом для разработчика.\n\nПожалуйста, опишите что вы собирались сделать когда произошла ошибка.\nЛичная информация отправляться не будет, проверьте текст письма, если сомневаетесь.</string>
    <string name="dialog_two_factor_cancel">Позднее</string>
    <string name="dialog_two_factor_create_password">Создать пароль</string>
    <string name="dialog_title_two_factor">Двухэтапная аутентификация</string>
    <string name="dialog_message_two_factor">Похоже, в вашем аккаунте включена двухэтапная аутентификация.\n\nПожалуйста, создайте пароль приложения для Yalp Store и используйте его для входа.\n\nНажмите \"Создать пароль\" для перехода на страницу создания паролей приложений.</string>
    <string name="dialog_title_logout">Разлогиниться?</string>
    <string name="dialog_message_logout">Вы уверены что хотите разлогиниться?</string>
    <string name="dialog_title_reviews">Получаем отзывы</string>
    <string name="dialog_message_reviews">Подождите. Получаем отзывы.</string>
    <string name="dialog_title_purchasing_app">Скачиваем</string>
    <string name="dialog_message_purchasing_app">Подождите. Запускаем закачку приложения.</string>
    <string name="dialog_title_loading_app_details">Подробности</string>
    <string name="dialog_message_loading_app_details">Подождите. Получаем подробности о приложении.</string>
    <string name="dialog_title_loading_app_list_search">Поиск</string>
    <string name="dialog_message_loading_app_list_search">Подождите. Ищем приложения по вашему запросу.</string>
    <string name="dialog_title_loading_app_list_update">Проверка обновлений</string>
    <string name="dialog_message_loading_app_list_update">Подождите. Ищем обновления для ваших приложений.</string>
    <string name="dialog_account_type_provided_by_user">Через мой аккаунт Google</string>
    <string name="dialog_account_type_predefined">Без аккаунта (экспериментально)</string>
    <string name="dialog_account_type_title">Как логиниться в Google Play Store?</string>
    <string name="dialog_title_logging_in">Входим</string>
    <string name="dialog_message_logging_in_provided_by_user">Пытаемся подключиться через ваш аккаунт</string>
    <string name="dialog_message_logging_in_predefined">Пытаемся подключиться через аккаунт, предоставленный Yalp Store</string>
    <string name="error_incorrect_password">Неверный email или пароль.</string>
    <string name="error_credentials_empty">Введите данные для доступа к аккаунту google</string>
    <string name="error_no_network">Нет соединения с сетью.</string>
    <string name="error_network_other" formatted="false">Сетевая ошибка: %s</string>
    <string name="error_not_purchased">Похоже, это приложение не было куплено.\nПерейти на его страницу в Play Store?</string>
    <string name="error_downloads_directory_not_writable">Каталог закачек недоступен для записи.</string>
    <string name="error_token_dispenser_problem">Подключиться без аккаунта не удалось. Попробуйте подключиться через ваш Google аккаунт.</string>
    <string name="details_category" formatted="false">Категория: %s</string>
    <string name="details_installs" formatted="false">%s ↓</string>
    <string name="details_rating" formatted="false">%.1f★</string>
    <string name="details_rating_specific" formatted="false">%d★ %d</string>
    <string name="details_updated" formatted="false">Обновлено %s</string>
    <string name="details_size" formatted="false">Размер apk %s</string>
    <string name="details_description">Описание:</string>
    <string name="details_changelog">Что нового:</string>
    <string name="details_screenshots">Скриншоты:</string>
    <string name="details_reviews">Отзывы:</string>
    <string name="details_rate_this_app">Оцените это приложение:</string>
    <string name="details_you_rated_this_app">Вы оценили это приложение:</string>
    <string name="details_permissions">Разрешения:</string>
    <string name="details_developer" formatted="false">Разработчик: %s</string>
    <string name="details_versionName" formatted="false">Версия %s</string>
    <string name="details_versionName_updatable" formatted="false">Версия %s → %s</string>
    <string name="details_download">Скачать</string>
    <string name="details_install">Установить</string>
    <string name="details_downloading">Скачиваем…</string>
    <string name="details_download_impossible">Несовместимо с этим устройством</string>
    <string name="details_review_dialog_title">Есть что добавить?</string>
    <string name="details_review_dialog_review_title_hint">вкратце</string>
    <string name="details_review_dialog_review_comment_hint">подробнее</string>
    <string name="details_review_dialog_fields_optional">Можно и не заполнять.</string>
    <string name="details_apps_by_this_dev">Приложения этого разработчика</string>
    <string name="details_similar_apps">Похожие приложения</string>
    <string name="details_users_also_installed">Пользователи также установили</string>
    <string name="details_to_play_store">Перейти в Play Store</string>
    <string name="details_signature_mismatch">Новая версия подписана ключом, отличным от старого. Перед установкой новой версии удалите старую. Сделайте это и попробуйте ещё раз. (При удалении приложения все его данные будут потеряны)</string>
    <string name="suffix_million">млн</string>
    <string name="suffix_billion">млрд</string>
    <string name="credentials_hint_email">e-mail</string>
    <string name="credentials_hint_password">пароль</string>
    <string name="credentials_title">Вход в аккаунт Google</string>
    <string name="credentials_message">Приложению требуются данные аккаунта Google.\n\nИмейте в виду, что это приложение нарушает договор использования Play Store. Так что безопаснее использовать любой одноразовый Google аккаунт, под которым вы хотя бы раз залогинились в Play Store.</string>
    <string name="activity_title_updates">Обновления</string>
    <string name="activity_title_search" formatted="false">Поиск: \"%s"</string>
    <string name="notification_installation_complete">Установлено обновление.</string>
    <string name="notification_installation_complete_toast" formatted="false">Приложение %s обновлено.</string>
    <string name="notification_installation_failed">Не удалось установить обновление.</string>
    <string name="notification_installation_failed_toast" formatted="false">Ошибка при обновлении %s. Нет root-доступа?</string>
    <string name="notification_download_complete">Готово. Коснитесь чтобы установить.</string>
    <string name="notification_download_complete_toast" formatted="false">Загрузка %s завершена. Для установки нажмите кнопку или уведомление \"Установить\".</string>
    <string name="notification_download_complete_signature_mismatch" formatted="false">Загрузка завершена. Подпись apk не совпадает с подписью установленного приложения.</string>
    <string name="notification_download_complete_signature_mismatch_toast" formatted="false">Загрузка %s завершена. Подпись apk не совпадает с подписью установленного приложения. Вы установили это приложение не из Google Play? Возможно, придётся сначала его удалить.</string>
    <string name="notification_updates_available_title">Есть обновления приложений.</string>
    <string name="notification_updates_available_message" formatted="false">Для %d приложений есть обновления.</string>
    <string name="pref_hide_nonfree_apps_summary_off">Сейчас платные приложения отображаются</string>
    <string name="pref_hide_nonfree_apps_summary_on">Сейчас платные приложения не отображаются</string>
    <string name="pref_hide_nonfree_apps">Скрывать платные приложения</string>
    <string name="pref_auto_install_summary_off">Приложения устанавливаются по щелчку на уведомлении</string>
    <string name="pref_auto_install_summary_on">Приложения устанавливаются сразу после завершения скачивания</string>
    <string name="pref_auto_install">Устанавливать приложения сразу</string>
    <string name="pref_delete_apk_after_install_summary_off">Сейчас .apk после установки не удаляются</string>
    <string name="pref_delete_apk_after_install_summary_on">Сейчас .apk после установки удаляются</string>
    <string name="pref_delete_apk_after_install">Удалять .apk после установки</string>
    <string name="pref_update_list_white_or_black_black">Выбранные приложения не будут обновляться</string>
    <string name="pref_update_list_white_or_black_white">Только выбранные приложения будут обновляться</string>
    <string name="pref_update_list_white_or_black">Чёрный или белый список обновлений</string>
    <string name="pref_update_list_black">Изменить список игнорируемых приложений</string>
    <string name="pref_update_list_white">Изменить список обновляемых приложений</string>
    <string name="pref_ui_theme">Тема</string>
    <string name="pref_ui_theme_none">По-умолчанию</string>
    <string name="pref_ui_theme_light">Светлая</string>
    <string name="pref_ui_theme_dark">Тёмная</string>
    <string name="pref_ui_theme_black">Чёрная</string>
    <string name="pref_background_update_interval_never">Только при запуске Yalp Store</string>
    <string name="pref_background_update_interval_hourly">Раз в час</string>
    <string name="pref_background_update_interval_daily">Раз в день</string>
    <string name="pref_background_update_interval_weekly">Раз в неделю</string>
    <string name="pref_background_update_interval">Периодически проверять обновления</string>
    <string name="pref_background_update_install_summary_off">Только уведомление</string>
    <string name="pref_background_update_install_summary_on">Обновления устанавливаются (root)</string>
    <string name="pref_background_update_install">Установить найденные обновления (root)</string>
    <string name="pref_no_root">Это возможно только на рутованных устройствах</string>
    <string name="download_manager_ERROR_UNKNOWN">Неизвестная ошибка.</string>
    <string name="download_manager_ERROR_FILE_ERROR">Неизвестная ошибка файлового хранилища.</string>
    <string name="download_manager_ERROR_UNHANDLED_HTTP_CODE">Сетевая ошибка. Попробуйте позднее.</string>
    <string name="download_manager_ERROR_HTTP_DATA_ERROR">Сетевая ошибка. Попробуйте позднее.</string>
    <string name="download_manager_ERROR_TOO_MANY_REDIRECTS">Сетевая ошибка. Слишком много редиректов.</string>
    <string name="download_manager_ERROR_INSUFFICIENT_SPACE">Недостаточно места на устройстве.</string>
    <string name="download_manager_ERROR_DEVICE_NOT_FOUND">Устройство хранения недоступно. Вынули SD карту?</string>
    <string name="download_manager_ERROR_CANNOT_RESUME">Сетевая ошибка. Попробуйте позднее.</string>
    <string name="download_manager_ERROR_BLOCKED">Загрузка прервана из-за настроек безопасности NetworkPolicyManager.</string>
</resources>

**Comment by yeriomin** [comment]
Please use [poeditor.com](https://poeditor.com/projects/view?id=95185) or a pull request to submit translations.

Хотя русского языка это не касается) Что с ним не так?

**Comment by ashed** [comment]
20  <string name="dialog_message_application_crashed">Вы можете помочь
разработчику исправить это, отправив email с подробностями об ошибке.
Нажмите OK чтобы открыть ваше email-приложение с письмом для разработчика,
готовым к отправке.\n\nПожалуйста, опишите что вы собирались сделать когда
произошла ошибка.\n\nНикакой чувствительной и личной информации отправлено
не будет, проверьте текст письма, если сомеваетесь.</string>


99  <string name="credentials_message">Для работы приложения требуетются
данные для доступа к аккаунту Google.\n\nИмейте в виду, что это приложение
нарушает договор использования Play Store. Так что безопаснее использовать
любой одноразовый Google аккаунт, под которым вы хотя бы раз залогинились в
Play Store.</string>


требуетются != требуются



108  <string name="notification_download_complete_toast"
formatted="false">Загрузка %s завершена. Нажмите на кнопку \"Установить\"
уведомление чтобы установить.</string>

на кнопку \"Установить\" уведомление != на кнопку уведомления
\"Установить\"



115 <string name="pref_auto_install_summary_off">Приложения устанавливаются
по щелчку на уведомление</string>

на уведомление != на уведомлении



116 <string name="pref_auto_install_summary_on">Приложения устанавливаются
сразу после завершения скачки</string>

после завершения скачки != после завершения скачивания



118 <string name="pref_delete_apk_after_install_summary_off">Сейчас .apk
после остановки остаются на месте</string>

после остановки остаются на месте !=  после установки не удаляются



2017-03-10 22:03 GMT+05:00 Sergey Yeriomin <notifications@github.com>:

**Comment by ashed** [comment]
Видимо ошибки в переводе всё же наличествуют.

Прикладываю правленный вариант. Не сочтите за труд с ним ознакомиться.

12 марта 2017 г., 14:47 пользователь ash ed <craysy@gmail.com> написал:

**Comment by yeriomin** [comment]
@ashed Спасибо, изменения внесены. Кроме замечаний про уведомления. Раз возникли сомнения, пусть слово "уведомление" будет использоваться как в [документации](https://developer.android.com/guide/topics/ui/notifiers/notifications.html?hl=ru).
