### ISSUE TITLE
Yalp Store opens not the app that I've selected from update list

### ISSUE THREAD

**Issue by teod0r** [yeriomin/YalpStore#101]
I pressed "4PDA" app from update list, but Yalp Store opened other app from update list ("LeanDroid")

**Comment by teod0r** [comment]
Кстати, когда LeanDroid открылось заместо 4PDA, оно было прокручено вниз, т.е. показало не самый верх страницы, просто до этого я уже открывал LeanDroid, и, видимо, оно открылось как-то из памяти. Возможно, это как-то связано с багом "BACK'.

**Comment by teod0r** [comment]
Ещё одна вещь, которая, возможно, связана с багом. До этого я пытался обновлять приложения, но они не скачивались из-за того, что на устройстве было мало памяти на внутренней карте. Среди приложений, которые я пытался качать было 4PDA и, возможно, LeanDroid.

**Comment by syl3nt** [comment]
I can choose the app like any other app, are you sure it's an issue of the app ? it could be your screen that failed on you if you have sweaty hands, i mean, that's the only reason for the random scroll on the app list

**Comment by teod0r** [comment]
I'm shure that there was a problem of the app. There was distance between those two apps in half of my screen

**Comment by syl3nt** [comment]
where you using the split screen ? in a nougat rom , i presume 
but no one else seems to have this issue for now.

**Comment by teod0r** [comment]
I don't use split screen

**Comment by teod0r** [comment]
This thing happened again. It happend after I opened the program after "BACK" bug.

**Comment by yeriomin** [comment]
Duplicate of #4
