### ISSUE TITLE
Feature request: Show "ad supported" and "In App Purchases" indicator like on Play Store

### ISSUE THREAD

**Issue by grupypix** [yeriomin/YalpStore#102]
I cannot see these indicators on the details page when searching for an app.

Would be even greater if they could show on the search results list already, but I understand that may not be possible (if it is not included there). But then please show at least when I select details.

[There are often several apps for the same purpose where according to the description I cannot tell which is better. I usually want to test the ad-free app first in that case.]

**Comment by yeriomin** [comment]
Was working on this before you wrote the issue!

In search a line with price, whether or not app contains ads, whether or not app depends on google services added. In details a block with price, whether or not app contains ads, in-app purchases cost, specific google dependencies list added.

It is worth mentioning that "no ads" indicator is not always true, it probably depends on what developer chooses. Also, having a Google services dependency does not mean that the app won't work without them. In most cases the Google services functionality of the app is negligible (showing ads, installation tracking, maps and so on), and the app can still carry out its main function.

Implementation is in master.

**Comment by grupypix** [comment]
Thank you for adding it so quickly, it works great :-)


Yes I know some developers say no ads but they have ads, but most developers are honest here as they risk getting bad reviews or having their app flagged if they lie.
