### ISSUE TITLE
delay before updated apps show up

### ISSUE THREAD

**Issue by fkooman** [yeriomin/YalpStore#104]
### Expected behaviour
When an update is available, it is already shown in play.google.com, it is not yet available through Yalp and usually I have to wait a couple of days before it is shown in Yalp.

I noticed this first with the Signal, the version that was supposed to work without Google Play, it took ~3 days before it became available through Yalp. I also noticed it with Firefox (52).

### Actual behaviour
Update should be immediately available. I realise this may be out of your control, but it would be interesting to know what is going on...

### Steps to reproduce
1. Install an app through Yalp;
2. Wait for an update to be published to Google Play for this app;
3. See that it is not available for a couple of days in Yalp.

### Info about your device

Samsung Galaxy S3 (i9300) running LineageOS 14.1-20170308-NIGHTLY-i9300 (without Google Play/Apps).

**Comment by killoid** [comment]
it is happening from past 4-5 days. i've faced it too. before it was all ok. i think something is changed from google & it is affecting the app too.

**Comment by yeriomin** [comment]
@fkooman @killoid Thanks, I will look into it. Which apps have the most frequent updates?

**Comment by fkooman** [comment]
Not sure, it seems Signal updates rather frequently. I noticed I got an update today of Signal that was released yesterday, so only 1 day delay this time...

**Comment by killoid** [comment]
now in my side everything is working fine. don't know what happened, strange! :/
got app updates as usual, no delay.

**Comment by yeriomin** [comment]
@fkooman @killoid As far as I can see, this seems to be some load-balancing measure by google. The time when update becomes available does not seem to depend on what Yalp does. It only depends on the account I use. Using the same account in Play and Yalp makes the same updates available in both apps for me. Any other observations?

**Comment by fkooman** [comment]
I'm using the "built in" account by the way. The load balancing (maybe even geo load balancing based on location of the device) seems like a good explanation. It seems now updates are delayed <= 1 day. So I guess all is fine :) Thank for investigating!

**Comment by yeriomin** [comment]
No news on this issue for a week now, so I am closing it.
