### ISSUE TITLE
Does not download APKs since update to android 7 nougat

### ISSUE THREAD

**Issue by tpeg5stan** [yeriomin/YalpStore#105]
### Expected behaviour
The APKs should dowload when I press the download button

### Actual behaviour
Nothing actually happens, with or without a google account

### Steps to reproduce
product = Lenovo moto G4
change=official update to android 7 nougat (with a factory reset because the update broke everything on my phone)
I can still browse the apps, see what needs to be update, read the reviews, etc. 
But it won't do anything if I press the "download" button.

**Comment by yeriomin** [comment]
Could you check app's permissions? Please provide logs if possible. I don't think it has anything to do with android **nougat** specifically.

**Comment by tpeg5stan** [comment]
Permissions : storage.
When I tap the "all the authorizations" I get  (not sure about the exact name, my device is in French)
modify or delete the SD card data,
 see the SD card data
complete network access
launch on startup

I do not get any specific error, where to get the logs of the app ?

I think it is linked with the way moto/lenovo manages its updates. It is the second app with a problem since the upgrade.

**Comment by yeriomin** [comment]
I see.

Android can make generic bug reports with recent logs. You can take a bug report from the Developer Options menu. The menu can be enabled by going into Settings, selecting About Phone, and tapping on Build Number seven times.

After this is done, make the app reproduce the problem. Generate the report. Finally, please, send it to yalp.store.dev@gmail.com (watch for a notification to appear).

**Comment by tpeg5stan** [comment]
The only thing I got is : W/InoutEventReceiver (14974) : Attempted to finish an input event but the input event receiver has already been disposed.

I fear it may not be useful... I am looking into the bug report of the developer menu, let's see if I find something more interesting...

**Comment by yeriomin** [comment]
`03-16 13:50:51.784 26643 26643 E com.github.yeriomin.yalpstore.DownloadOrInstallManager$3: Unknown exception java.lang.IllegalArgumentException Unknown URL content://downloads/my_downloads`

This log line makes me think you (or the update you installed) disabled DownloadManager. You can check if my guess is right if you go to Settings -> Apps, enable showing system apps, find "Download Manager" click it and check if you can "Enable" it. Let me know if this helps.

I'll add the DownloadManager status check to Yalp.

**Comment by tpeg5stan** [comment]
Yes, it works !

Thanks for the tip, I would never have thought about that.
On the other hand, firefox and newpipe seem to work fine with or without download manager.

There is no way to get past the download manager, i imagine ?

**Comment by yeriomin** [comment]
>firefox and newpipe seem to work fine

They must have re implemented DownloadManager stuff themselves.

>There is no way to get past the download manager, i imagine ?
I would have to re implement it. It does a lot more than open a byte stream. It shows a neat progress bar in the notification area, notifies the user when the download completes resumes the download on loss of connectivity and reconnection, keeps the list of recent downloads...

Some people want Yalp to work on androids older than api 9, so I think I should do it, but it is a relatively big task. For v0.12 I will just add the check.

**Comment by tpeg5stan** [comment]
Ok, thanks for the answer, I understand perfectly.

It could be useful to ass a download-manager-check in the app, so that one can understand what happens :+1:

**Comment by burunduk** [comment]
I have a similar bug:
LineageOS 14.1, YalpStore (build from git 9feb0eb), permission is granted.
CatLog:
`W/DownloadManager(4425): Path appears to be invalid: /storage/emulated/0/Download/org.coolreader.1002.apk`
File size = 0

A similar error is described here: [NewPipe/issues/143](https://github.com/TeamNewPipe/NewPipe/issues/143)

**Comment by yeriomin** [comment]
@burunduk This bug is fixed and closed. If enabling DownloadManager does not help, your problem is unrelated to this one. Please create a new issue and provide steps to reproduce it, it does not happen on my LineageOS 14.1 device.
