### ISSUE TITLE
Unable to handle complex passphrases

### ISSUE THREAD

**Issue by tchncs** [yeriomin/YalpStore#11]
Heyo,
it seems like YalpStore cannot handle a 64char random passphrase with all kinds chars like 
````
^]Y&fyhg-'e/z;#:6~Wg [...]
````
It just does nothing after trying to login so i guess it is a similar problem as raccoon has for me.

**Comment by yeriomin** [comment]
^]Y&fyhg-'e/z;#:6~Wg worked fine.
0123456789012345678901234567890123456789012345678901234567890123 (64 chars) also worked fine.

Post the whole non-working password, please.
And thanks for the issue.

**Comment by yeriomin** [comment]
You might want to look at issue #36. Closing for now.
