### ISSUE TITLE
Automatically delete old obb file after downloading the new one.

### ISSUE THREAD

**Issue by killoid** [yeriomin/YalpStore#112]
after updating an app with obb file, i've to manually delete the old obb file of that app. is it possible to automatically delete it everytime after the app update?

**Comment by yeriomin** [comment]
There is a size check before downloading an obb. Yalp deletes obbs if the size of the new one differs from the size of the old one. Considering that resources are stored there, it is unlikely that obbs would be the same size if they are updated.

* What app are you tying to update?
* Does it have obbs with same size but differing content before and after update?
* Does Yalp simply fail to delete the obbs?

**Comment by killoid** [comment]
i updated Tap Titans 2 & yes the size of the obb was not the same before & after update as it was a big update according to the app.

**Comment by yeriomin** [comment]
Can not reproduce. Yalp deletes old obbs properly if their content changes. Play Store interface is not the only way to get the obbs, though. Every app developer may choose to handle obbs without Play Store servers. Maybe, your app works like that.

I've added some logging messages to catch any similar problems.
