### ISSUE TITLE
Apk doesn't get deletet after installation

### ISSUE THREAD

**Issue by ring0000** [yeriomin/YalpStore#113]
Apk remains in download folder after installation. Happens with every App I installed. 

### Steps to reproduce
1. G-Mail account
2. Option for instantly installation checked
3. ?Dark Theme?

### Info about your device
Moto G 2015, 7.1.1 LineageOS

**Comment by yeriomin** [comment]
Cannot reproduce. Are you sure "Delete .apk after installation" option is checked?

**Comment by ring0000** [comment]
Everything works fine now. I reinstaled Yalp and tested one APP. Keep up the good work.
