### ISSUE TITLE
Cannot install app v0.12

### ISSUE THREAD

**Issue by ashed** [yeriomin/YalpStore#117]
### Expected behaviour
install new version of app

### Actual behaviour
error of installing.
analyze error

### Steps to reproduce
1. download app v0.12
2. try to install
3. got error

### Info about your device
Device model, android falvour
Lenovo k910s, android v 4.4.2 vibe rom

**Comment by yeriomin** [comment]
"error of installing." That probably means the error happens before the app starts working, which means there is nothing I can do.
"got error" This gives me no information.

Where did you get the app from? Try f-droid. What exactly does the error say? Can you attach a screenshot?

**Comment by ashed** [comment]
Приложение из плеймаркета. В f-droid лежит старая версия программы.

В гитхабе этого проекта проскакивало сообщение и смене мин. версии SDK.
М.б. дело в этом?
Сообщение - "ошибка анализа"

[image: Встроенное изображение 2][image: Встроенное изображение 1]

2017-03-27 15:31 GMT+05:00 Sergey Yeriomin <notifications@github.com>:

**Comment by yeriomin** [comment]
"Приложение из плеймаркета." О каком приложении вы говорите? Yalpа нет в плеймаркете. Yalp распространяется через f-droid, так как нарушает пользовательское соглашение Play Store (см. README).

Вы не можете поставить Yalp? Попробуйте взять его с [этой](https://f-droid.org/repository/browse/?fdid=com.github.yeriomin.yalpstore) страницы.
Или Yalp что-то поставить не может? Тогда проблема, скорее всего, в том приложении. Yalp не ставит ничего своими силами, только открывает системный диалог установки.

**Comment by ashed** [comment]
Yalp успешно установился. OctoDroid - выдавал ссылку на старую версию. 
Сейчас проверил в apkpure & blackmarket - Yalp не обнаружен. Но ведь кривая версия откуда-то взялась... 
Ладно. Спасибо за ссылку. Всё работает.

**Comment by yeriomin** [comment]
Кривые версии могут взяться откуда угодно. Исходники-то открыты. Раньше с релизом выкладывал и debug-apk. Недавно прекратил.
