### ISSUE TITLE
Privileged extension

### ISSUE THREAD

**Issue by Sirove** [yeriomin/YalpStore#123]
Can you make a flashable zip to install YalpStore as a system app that supports background updates?
Like F-Droid: https://f-droid.org/repository/browse/?fdid=org.fdroid.fdroid.privileged.ota

**Comment by yeriomin** [comment]
I'll see what I can do.

**Comment by burunduk** [comment]
Maybe add a rule to backup the application when update OS?
(For lineageos and similar: addon.d [file)](https://github.com/mar-v-in/MapsAPI/blob/master/com.google.android.maps/in/10-mapsapi.sh)

**Comment by Alexandero89** [comment]
Is this issue maybe finished and can be closed so we can bump to version 0.14?

**Comment by yeriomin** [comment]
Seems complete.

To build an ota zip with a debug version of Yalp, run `:app:generateOtaZip` gradle task.

To build an ota zip with a signed release version, run `:app:generateOtaZipStable`. It downloads the apk from f-droid, so it won't work until f-droid compiles the new version.
