### ISSUE TITLE
Two-step authentication pop-up disappears

### ISSUE THREAD

**Issue by nwn9** [yeriomin/YalpStore#124]
### Expected behaviour
I have enabled two-step authentication in my Google account. I wanted to log in, type the password and, after that, a code either from my authentication app or the one sent to my mobile phone.

### Actual behaviour
I typed the password and, after that, a pop-up asking for the two-step auth code appeared. I'm unable to complete the dialogue, due to it being displayed only for a extremely short time. Process tend to repeat in an endless loop. So, as a result, I'm unable to login to Yalp Store with my account extra protected.

### Steps to reproduce
1. Enable two-step authentication in Google account
2. Login, then wait for pop-up
3. Look as the dream of logging in with that extra protection fades out

### Info about your device
Samsung Galaxy S5, Android 6.01

**Comment by yeriomin** [comment]
I won't let your dreams be dreams.

The dialog you were seeing is a message about how Yalp doesn't properly support 2-Step verification, asking you to create an app-specific password and use it to log in. I will fix the dialog in v0.13, but nothing is stopping you from creating the app password now. Google will let you in.

You can read more in issue #23. In short: Play Store app does not use the ordinary documented API for auth. So I have to reverse engineer it. I can detect the 2-Step-enabled accounts, but I failed to catch the whole process when I tried. I'm not closing that issue and I will probably do the whole process properly when I get my hands on it.

![2017-04-01 00 14 18](https://cloud.githubusercontent.com/assets/554737/24573331/9a92f4ae-168a-11e7-8fca-4d0e9ce171ef.png)

**Comment by nwn9** [comment]
Thanks for quick and extensive reply. I will keep my fingers crossed for you and follow your suggestion - and the biggest of kudos for the awesome work you did on this app!
