### ISSUE TITLE
Can't use "." in manual Version-Download

### ISSUE THREAD

**Issue by Alexandero89** [yeriomin/YalpStore#129]
Hey,
I'm trying to download an App which can't be downloaded automatically, so i try to download it via version number.
The actual version of the app in the play store for my device is 9.06 but i can't use the dot "." when i try to enter the version-number into the textfield.
And because version "9" is not the latest version i think he tells me "this version not found"

with regards

**Comment by yeriomin** [comment]
Manual download expects a version **code**, not version string. It is always an integer. 

The message on the manual download page mentions this. This might be a problem with translation. What is the default language of your device?

**Comment by yeriomin** [comment]
If you think the message on the manual download page is not clear enough about the version code, you are welcome to fix it on [Yalp's POEditor](https://poeditor.com/join/project/LUPUijv2Cs) page. It is a free crowd sourcing translation service.

Closing this, as it is not an issue.
