### ISSUE TITLE
Anonymity / Tor mode

### ISSUE THREAD

**Issue by OffifialMITX** [yeriomin/YalpStore#13]
I know it's not the main goal of the app but it would be cool if there was an option not only to download but also to browse apps without signing in and best if even trough Tor.

Nice app but not useful for me yet. Keep up the good work!

**Comment by yeriomin** [comment]
This is impossible.
Yalp mimics native android Play Store app, which requires a google account.
Also, it is already possible to run this app through orbot.

Thank you for writing an issue, though.

**Comment by OffifialMITX** [comment]
Well, Orbot becomes kind of pointless if you're using an account but thanks for answering.

Am 12. Januar 2017 23:48:19 MEZ, schrieb Sergey Yeriomin <notifications@github.com>:
>This is impossible.
>Yalp mimics native android Play Store app, which requires a google
>account.
>Also, it is already possible to run this app through orbot.
>
>Thank you for writing an issue, though.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/yeriomin/YalpStore/issues/13#issuecomment-272308650

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.
