### ISSUE TITLE
New search methods

### ISSUE THREAD

**Issue by utack** [yeriomin/YalpStore#131]
### Expected behaviour
Search returns a list of apps

### Actual behaviour
Search just returns one app

### Steps to reproduce
1. Search for something specific, like "Firefox"
2. Observe how only one app is listed in the results

The problem and a workaround is detailed in the Raccoon Blog:
http://blog.onyxbits.de/looks-like-google-changed-the-play-protocol-again-614/

**Comment by yeriomin** [comment]
Fixed in master. Will be out with v0.14.
