### ISSUE TITLE
Always show "Update All Apps"

### ISSUE THREAD

**Issue by Alexandero89** [yeriomin/YalpStore#135]
Hey First of all:
You are awesome! and your App is even better. Thx very much for that!

Now the Request:
I noticed that the "Update all"-Button is only shown when i choose to check and install Updates automatically by Yalp.
But maybe i would like to update all Aps allthough i choose to not check for updates in the background.
By the way: Root is available.

Thx

**Comment by Marat1995** [comment]
+
