### ISSUE TITLE
Make „delete after download“ the default?

### ISSUE THREAD

**Issue by nomeata** [yeriomin/YalpStore#136]
I just filled my phone with downloaded apks from Yalp (which, because my phone is a Jolla with btrfs and through some unfortunate chain of events which are not Yalp’s fault made me brick the installation…), only to now find out that there would have been an option to have Yalp clean up after itself.

Judging from the code, this option is off by default, and I wonder why. What (common) use-case is there in keeping the apkg after installation that would people prefer this by default?

**Comment by yeriomin** [comment]
Yalp is not supposed to be a full-featured replacement for Play Store. It's an app to download apps from Play Store, create an archive. Until recently it didn't even have an option to install apps, only download. README mentions this.

Apparently, people use it as a replacement in spite of that. Maybe it is time to change this default. Lets see if other users support your issue.

**Comment by akoyaxd** [comment]
I would also prefer the apks deleted automatically as default.

**Comment by ranomier** [comment]
Yes I also think that's better. Then you'll have a clean system.
One feature more would be to keep the current and the version you had just before. Because if some app breaks you can rollback to the version you had ;)

+1

**Comment by marat1995** [comment]
+

**Comment by kristbaum** [comment]
+1 for deleting by default

**Comment by transifex3** [comment]
+1

**Comment by zelleb** [comment]
-1

I vote for an option to set another download path. I want to keep the apks downloaded from yalp, but not in the downloads folder.

**Comment by dimqua** [comment]
+1

**Comment by RalfJung** [comment]
I wasn't even aware that it would put the apks into the Downloads folder, so when I just found the option to "delete after download", it took me a while to even figure out where thing are stored. I suppose an archive is useful, but an unexpected archive is just using up space. If things are not deleted per default, at least it should be clear somehow where things are stored.

**Comment by krayon** [comment]
yeriomin wrote:
> Yalp is not supposed to be a full-featured replacement for Play Store. It's an app to download apps from Play Store, create an archive.

+1 for someone to fork this project and go create a Play Store alternative with this option and leave Yalp Store alone :P

**Comment by yeriomin** [comment]
>with this option

What do you mean? The option exists. The issue is about making it default.
