### ISSUE TITLE
rating apps: buttons not accessible when long comment entered

### ISSUE THREAD

**Issue by treakiandroid** [yeriomin/YalpStore#138]
### Expected behaviour
Tell us what should happen
i write a comment for an app that has more then just one sentence i want to send this.

### Actual behaviour
Tell us what happens instead
if the comment text (and the containing view) gets longer you are unable to reach the top/bottom of the view anymore. It lookes like the scroll feature is missing completely. so tou cant access the buttons anymore and so also dont send your comment if it is to long.

### Steps to reproduce
1. search for an app
2.install if
3.use it
4. go back to the yalp view where you have installed, expand the rating view, give it some stars, write a title and a comment with about 500 characters. try to send it, fail

### Info about your device
Device model, android falvour
android 6 cyanogen, model not relevant just some ordinary xhdpi smartphone.

thanks in advance for a fix here

**Comment by yeriomin** [comment]
Hello. I have a strange question for you. When did you open this issue?

Today I suddenly get 6 issue notifications (this one and #21, #39, #40, #66, #67) from you dating from January to May. I haven't seen them before.

So you either opened them today and github is reporting the date improperly, or the date is correct and that means they were **not visible** to me this whole time.
