### ISSUE TITLE
Use pay apps

### ISSUE THREAD

**Issue by jedr93** [yeriomin/YalpStore#139]
Hello, good afternoon .. I find this application fabulous as raccon  I have been using raccon in my pc for several months .. within the app just like raccon I see unnecessary to put download the apks pays, They can not be verified or used.
 I have 2 applications bought in the playstore and necessarily For to verify the license I need to have the google play application enabled .. so I think it is wrong on the part of google since I should check the licenses of the apps through its play services ... I do not know if later it would open A way to verify the licenses of the apps purchased through play services and install the raccon pay apks and Yalp Store.
I also want you to continue this project just like raccon ..

**Comment by yeriomin** [comment]
Hello. Thank you for your kind words.
Any payment-related functions are almost impossible to implement because the API is not documented which would make me buy stuff (a lot) for any minor change. Sorry, I cannot implement your suggestion.
