### ISSUE TITLE
View and write app reviews

### ISSUE THREAD

**Issue by teod0r** [yeriomin/YalpStore#14]
It'll be nice if there will be ability to view and write rewies of apps

**Comment by teod0r** [comment]
REVIEWS sorry for my bad english

**Comment by yeriomin** [comment]
I will add an ability to read reviews soon. Not sure about writing, but I will try.

**Comment by avently** [comment]
Рановато закрыл. Не работает
При клике на звезду вот что:
01-23 10:01:24.292 E/AndroidRuntime(21148): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.github.yeriomin.yalpstore.model.Review.getComment()' on a null object reference
01-23 10:01:24.292 E/AndroidRuntime(21148): 	at com.github.yeriomin.yalpstore.DetailsActivity$9.onClick(DetailsActivity.java:360)
01-23 10:01:24.292 E/AndroidRuntime(21148): 	at android.view.View.performClick(View.java:5637)

**Comment by teod0r** [comment]
А как оставлять ревью? Я нажимаю на звезду, и ничего не происходит

**Comment by teod0r** [comment]
Можно как-то улучшить внешний вид этих reviews? Подгружается всего по 3, кнопки листания очень маленькие (трудно попасть) да и ещё скачат вниз, когда открываются большие отзывы

**Comment by yeriomin** [comment]
"Рановато закрыл" - В самый раз.
"улучшить" - улучшить можно всё. "внешний вид" не приоритет + Web версия выглядит именно так. Готов принять pull request.

Пожалуйста, будьте внимательнее, ставя задачи, @teod0r, @avently. Последние ваши несколько задач не конструктивны.

Test master branch at your own peril. Its unstable by nature.
Please write issues in English.

**Comment by teod0r** [comment]
Попробовал оставить отзыв в одном приложении. Показывает мой отзыв не среди других отзывов, а выше числа рейтинга? Почему так? Надеюсь другие видят отзыв который я оставил?

**Comment by yeriomin** [comment]
Потому что это удобно + так же делает Play Store. "Надеюсь другие видят" то есть ты не знаешь, есть проблема или нет и решил поныть?

**Comment by teod0r** [comment]
Проблема есть. Я переустановил программу и в отзывах нету моего отзыва!

**Comment by yeriomin** [comment]
Пишу отзыв. Закрываю приложение и открываю его снова. Отзыв есть. Иду в web-интерфейс Play Store, сортирую по новизне. Отзыв есть.

**Comment by teod0r** [comment]
"сортирую по новизне" -- может дело в этом?  в Yalp Store как отсортированы? и проверял свой отзыв я в 0.4, потому что с 0.5 какая-то жесть с поиском творится
