### ISSUE TITLE
automatic language based on system 

### ISSUE THREAD

**Issue by syl3nt** [yeriomin/YalpStore#146]
Hi, i am translating the app for my native language, i would appreciate having a quick way to change language on the app, without changing my device language.
that way i would be able to quickly verify the context of some text in the app, to better suit the translation.
thanks.

**Comment by yeriomin** [comment]
I am supporting two languages for Yalp Store, so I'm aware of this problem. But I haven't found a viable solution.
* Reloading strings without recreating the activity requires a lot of coding which will add no features except ease of debug.
* Adding a language selector to the app settings is not better/faster than using the system language selector.

If you can point me to a project which solved this problem without coding a custom refresh trigger for every TextView, I'll add something similar to Yalp.

**Comment by syl3nt** [comment]
Yeah, you are right, i also think the same, perhaps we can make a custom icon in our launcher just to quickly switch languages, via terminal or something like that, that's the cleanest solution i am seeing right now

**Comment by yeriomin** [comment]
I'm on github at least once a day (usually more often). I also check yalp.store.dev@gmail.com frequently.

**Comment by yeriomin** [comment]
I'll close this as I don't think it can be solved by coding. I will keep looking for a way to make translations easier. Maybe adding screenshots (to github wiki or poeditor somehow) with string ids instead of translations would help.

If you have any specific suggestions don't hesitate to contact me.
