### ISSUE TITLE
Doesn't download or update specific app.

### ISSUE THREAD

**Issue by killoid** [yeriomin/YalpStore#147]
it doesn't download or update [this app](https://play.google.com/store/apps/details?id=com.beesquare.almostahero). also it doesn't show the app in already up to date apps list. using the built-in google account.

**Comment by yeriomin** [comment]
Successfully downloaded and installed it with v0.13. Are you sure it is still compatible with your device? Any other details/info you can provide?

**Comment by killoid** [comment]
sorry for troubling, i contacted with dev & he said he has restricted it with some device specific screen resolution & dpi. will close the issue.
