### ISSUE TITLE
GooglePlayException on trying to view apps which are no longer available on Gooogle Play

### ISSUE THREAD

**Issue by marat1995** [yeriomin/YalpStore#149]
I find a bug.
There is an app App builder and developer deleted this app from Google Play.
YalpStore show this app in category There is an update.
I click and see 
Network error.
com.github.yeriomin.playstoreapi.GooglePlayException
Malformed request.
Better to have shown that the Application was removed/not found.

**Comment by marat1995** [comment]
Bug.
If you search an app without Internet, you see
java.io.EOFException null
Better to have shown You isn't  have Internet.
Sorry for bad English.

**Comment by yeriomin** [comment]
`com.github.yeriomin.playstoreapi.GooglePlayException` does not happen in master.
`java.io.EOFException` never encountered that. There must be some other condition to trigger it. What else were you doing at that time?

**Comment by marat1995** [comment]
Try it yourself.
Search app without Internet.

**Comment by yeriomin** [comment]
Cannot reproduce.
