### ISSUE TITLE
2-step Verification: Unable to connect + Explanation

### ISSUE THREAD

**Issue by EvoWizz** [yeriomin/YalpStore#15]
When we have the 2 Step verification on our account, we can't log in with our own password. Here are 2 ways to fix this (as the user I mean...):
First solution - Disabling the 2 step verification mode
Second solution - Generate an app password for the app by clicking [HERE](https://security.google.com/settings/security/apppasswords)

I'm posting it here because I think you should make a popup to prevent user if they can't log in :)

**Comment by yeriomin** [comment]
Thank you for the issue and an explanation.
I will add a message about 2-step verification and look into making it work properly later.

**Comment by EvoWizz** [comment]
Great! :)
