### ISSUE TITLE
More features

### ISSUE THREAD

**Issue by marat1995** [yeriomin/YalpStore#152]
Google Play is a store with apps, games, music and videos.
Plz add support for music and videos to Yalpstore.

**Comment by AlfaOmega33** [comment]
+1

**Comment by syl3nt** [comment]
I am not certain if google lets you do that.. you cant have a copy of the music, and you cant have a copy of the movie, only accessing it via the google play services that loads the video player for the movies and the play music app for the music, now for the books, i dont know ..

**Comment by marat1995** [comment]
@syl3nt  mb you are right.

**Comment by yeriomin** [comment]
Most of books, music and movies in Play Store are paid. Reverse engineering the closed API Google uses for buying stuff is not something I can do (without exhausting my savings).
