### ISSUE TITLE
Uninstall apps in root mode

### ISSUE THREAD

**Issue by marat1995** [yeriomin/YalpStore#153]
Sometimes I can't install the application because the installer says the Application is already installed.
Please add in root mode the uninstall option of the application without deleting the application data.

**Comment by yeriomin** [comment]
You should uninstall such applications manually (deleting their data, unfortunately).

This is not a malfunction nor is it random. The OS is telling you that the application you are installing is older than the application already installed. Or that the signature of the new app does not match the installed app (which means it comes from a different source e.g. someone modified and recompiled it).

In both cases it would be wrong to override this behavior.

First case. Every app developer makes sure that their app works well after an upgrade, but no app developer can provide a safe way for a downgrade.

Second case. Overwriting the app with a different signature would be a security risk.
