### ISSUE TITLE
Yalp сбой

### ISSUE THREAD

**Issue by marat1995** [yeriomin/YalpStore#155]
Я включил в Yalp показ системных приложений.
Перешел на главную страницу приложения и получил ошибку
в Yalp произошел сбой.
Исправьте пожалуйста.
Да, я написал issue #140 , а Вы его не включили в описании релиза 0.14

**Comment by marat1995** [comment]
В новом релизе было добавлено много годных фич.
Отдельное спасибо за установку приложений root способом.

**Comment by yeriomin** [comment]
>в Yalp произошел сбой.

Этого не происходит у большинства пользователей. Пожалуйста, заполните issue по шаблону. Пришлите crash report (если присылали, то ваш email отличается от вашего username).

>Да, я написал issue #140 

Изменений в 0.14 было много, а #140 очень небольшое.

>Нельзя не показывать приложения, которых нет в Google Play на главной странице.

Поясните, пожалуйста.

Ещё просьба: пожалуйста, называйте issue значащими именами. Под описание "Bug" и "Yalp сбой" подходят все issue кроме просьб нового функционала. К тому же, "Перешел на главную страницу приложения и получил ошибку в Yalp произошел сбой" не даёт мне никакой информации. Как вы можете предположить, у меня этого не происходит. Я не могу исправить то, чего нет.

**Comment by teod0r** [comment]
Я тоже включил показ системных приложений и тоже получил краш

**Comment by teod0r** [comment]
оказывается это не только после включения показа системных приложений. просто при обновлении сбой. @yeriomin, ты хоть один релиз программы можешь сделать, который не крашится?

**Comment by yeriomin** [comment]
@teod0r Нет, не могу. Не мучай себя, удаляй.

**Comment by marat1995** [comment]
@yeriomin вот характеристики устройства:
Android 5.0.2, Экран 10.1 1280*720, камень snapdragon 400(вроде, не помню точно).

**Comment by marat1995** [comment]
@yeriomin поясняю:
предположим есть прога Привет, которой нет в Google Play.
Зачем показывать ее, что обновлений для нее нет?
Это же логично, что их нет.
Можно добавить в Настройках чекбокс типо Показывать приложение, отсвтсвующие в Google Play.

**Comment by yeriomin** [comment]
@marat1995 Понятно. В настройках есть чекбокс "Показывать только обновления", включённый по-умолчанию. Если его выключить, показываются все приложения. Это нужно тем пользователям, которые хотят удалить/сделать системным/получить apk приложения, которого нет в Play Store.

А что со сбоем на главной странице? Если вы можете его повторить, пожалуйста пришлите bugreport, как просит сообщение об ошибке и напишите в письме, что это вы (marat1995) или номер issue (155).

**Comment by marat1995** [comment]
@yeriomin не смог повторить снова, закрываю issue.
