### ISSUE TITLE
Тотальное разочарование

### ISSUE THREAD

**Issue by xuno17** [yeriomin/YalpStore#156]
Великие ожидания и тотальное разочарование

1. Тотальный ужас в юзабилити и дело далеко не в материал-дизайне. Дизайн в стиле "сдизайнено лучшими программистами". Особенно "понравились" выпадающие пункты в описании приложения, логику я смог понять не сразу.
2. А зачем мне включать при загрузке ваше приложение? Где опция "заткнись и сдохни"? Или это такой тонкий квест "убери пермишшен и пересобери сам"?
3. Почему я НЕ могу вообще навсегда выключить апдейты? Не раз в неделю что-либо чекать, а вообще НЕ ДЕЛАТЬ НЕ НУЖНЫХ МНЕ ЗАПРОСОВ **НИКОГДА**?
4. Настройки при вылете приложения НЕ сохраняются. Очень весело заново выбирать опции из длинных списков.
5. Я так и не смог увидеть какого-либо прогресс-бара для скачивания файла, как собственно и скачивания, как и ошибок.
6. Постоянная перерисовка списков приложений с включенной фильтрацией "без платных" и "без рекламы" раздражает. Я понимаю, что делается апдейт всему списку, но похоже иконки еще и скачиваются заново.
7. Насколько приватным является адрес yalp.store.user.one@gmail.com? Ведь люди под ним логинятся, засвечивая свои девайсы и IP. Я так и не понял, чем оно занимается при первом запуске, перед выдачей диалога.

Удивляюсь, как можно было собрать столько антипаттернов.

**Comment by marat1995** [comment]
@xuno17 
Йо чувак ты что!
У всякой проги свои минусы есть, спокойно.
Не нравится- не юзай.

**Comment by xuno17** [comment]
Если не юзать, то ЧТО юзать? Ракун? Или сразу гуглоплей?
И в отсутствии рабочих альтернатив, не юзать, как-то не получается.
Единственный выход - написать аналог самому.

Но я ленивый и уже года 3 как планировал портировать Ракун, но руки все никак не дошли. И я обрадовался, что появилась какая-то альтернатива, а пост выше - это как раз разочарование от этой радости, но быть может, это позволит сделать прогу чуток юзабельнее.

**Comment by yeriomin** [comment]
>Великие ожидания

Вот главная проблема.

>заткнись и сдохни

Settings - Apps - Yalp Store - Uninstall

Всё что вы перечислили либо не является проблемой либо вызвано вашей невнимательностью. Когда успокоитесь, почитайте как оформить [feature request](https://en.wikipedia.org/wiki/SMART_criteria) или [bugreport](http://lmgtfy.com/?q=submitting+a+good+bug+report).

**Comment by xuno17** [comment]
> Settings - Apps - Yalp Store - Uninstall

Что я и сделал. И посоветовал сделать всем, кого знаю.

> Когда успокоитесь

Значит по делу сказать нечего?

**Comment by xuno17** [comment]
В общем, автор (@yeriomin) давать комментарии свои давать не хочет, исправлять ничего тоже. Предпочитает отмолчаться. Окей, я давал ему шанс, ему же хуже, что он им не воспользовался.

**Comment by avently** [comment]
@xuno17, целью этого поста было донести эмоцию, а не указать на конкретные недочеты. Эмоция доставлена. А исправления недочетов будут тогда, когда будет чётко указано, что не так и как должно быть. Поэтому-то у вас спустя три года не появился аналог yalpstore - цель поставлена неверно. Иначе бы уже написали прогу.
