### ISSUE TITLE
Automatically add apps to whitelist

### ISSUE THREAD

**Issue by mtbu** [yeriomin/YalpStore#157]
Would it be feasible to add an option so that when you install an app with Yalp Store, it then adds that app to the whitelist so updates get checked?

**Comment by akoyaxd** [comment]
What about using the black list?

**Comment by syl3nt** [comment]
I think you don't need an auto whitelist, just enable the auto updates..

**Comment by ranomier** [comment]
I think that would be awesome. Then yalp will only check for updates, for the apps you installed wit yalp and not another app store (play, f-droid).

+1

**Comment by yeriomin** [comment]
I'm quite sure you just need the black list.

>so updates get checked

If updates are not checked at all, its an issue completely unrelated to black/white lists.

>for the apps you installed wit yalp and not another app store (play, f-droid)

@ranomier That's not going to work for apps installed before Yalp is installed. This feature is logically inconsistent.

**Comment by fletch31337** [comment]
For apps installed with Yalp (when Yalp is whitelisting rather than blacklisting), it is easy to forget to select the whitelist option when an app is installed. Would be good to have a whitelist/blacklist option upon installation.
