### ISSUE TITLE
Downloadable ZIP for privileged extensions

### ISSUE THREAD

**Issue by Alexandero89** [yeriomin/YalpStore#158]
Could you maybe offer an downloadable zip file after you finished #123 (privileged extensions) ?

Just FYI:
https://f-droid.org/repository/browse/?fdid=org.fdroid.fdroid.privileged.ota

Thx in advance!

**Comment by Sirove** [comment]
+1

**Comment by yeriomin** [comment]
I had added an instruction on how to generate the zip in the #123 befoere closing it 10 ago. Also, you can get the zip from the [Release page](https://github.com/yeriomin/YalpStore/releases).

I guess I should add this to readme too.
