### ISSUE TITLE
duplicated function

### ISSUE THREAD

**Issue by syl3nt** [yeriomin/YalpStore#159]
you have created a button to "check updates" and there is a button on the menu to do the same .. personally the button down stays and the button on the menu goes ..
[edit] well, actually is seems that the button on the menu clears the updates, i press the check updates button and they appear again, am i wrong about the button on the menu ? what's it purpose ? 
[/edit]

**Comment by yeriomin** [comment]
The main menu item sends the user to the app list page. Depending on what the user chooses in settings, it might not be just updates there. The "check updates" button is to check for updates if the automatic checking is disabled.

I guess I should rename the main menu item to "Your apps" in case the setting is set to show all apps.
