### ISSUE TITLE
New filtering option.

### ISSUE THREAD

**Issue by killoid** [yeriomin/YalpStore#160]
would be great if there is a filtering option to show or not show apps which are google play services & google play games dependent, like the option to show or not show apps which has ads.

**Comment by yeriomin** [comment]
Most apps which depend on google services can work perfectly fine without them. Most apps need google services for some small feature like cloud sync.

This filter would filter out mostly working apps.

Consider the "Depends on gsf" label a warning, not a sign that the app won't work if you don't have gapps installed.
