### ISSUE TITLE
small modification please!

### ISSUE THREAD

**Issue by mostmaz** [yeriomin/YalpStore#161]
### Expected behaviour
can you please change the app modules to take the list of apps from a custom list? like from database ?

if you are willing to do that can you please make a gist or another version that have the custom list?

**Comment by yeriomin** [comment]
Please, be more specific. What exactly are you proposing? App list for what? Update? How would it be used?

**Comment by mostmaz** [comment]
i have an app with best app of the week that take the package name from mysql database and just want to use the google play api to crawl the screenshots and users review only.
i managed to use part of the code from your app , but failing to get the library for google api to be compiled by the gradle it show me error :
Error:(40, 13) Failed to resolve: com.github.yeriomin:play-store-api:0.14

**Comment by yeriomin** [comment]
[play-store-api](https://github.com/yeriomin/play-store-api) has a readme explaining how to build it. It has always been separate. No need to modify anything in Yalp Store and no need for you to use it, just use play-store-api.
