### ISSUE TITLE
cannot login after logout with changing device name

### ISSUE THREAD

**Issue by transifex3** [yeriomin/YalpStore#163]
### Expected behaviour
Should be logged in with properly changed device name

### Actual behaviour
Cannot login without or with error message "incorrrct username or passeword"
Both actual account and fake account.

### Steps to reproduce
1. login with fake account
2. change device variant
3. logout
4. try to login

### Info about your device
Redmi 4 Prime, Android 6.0.1 (MIUI)

**Comment by yeriomin** [comment]
Are you sure your Yalp Store is v0.14?

**Comment by transifex3** [comment]
oh that was 0.13. forgot about updating ;(
thanks yeriomin for comment! works awesome now
