### ISSUE TITLE
"Incorrect email or password" when trying to use fake Yalp Store account.

### ISSUE THREAD

**Issue by ryaniskira** [yeriomin/YalpStore#164]
### Expected behaviour
Yalp Store to log in

### Actual behaviour
Yalp Store never logs in, even when I create a fake account just to use with Yalp Store, it never logs in. It prompted me about 2FA on my secondary account once, but NEVER accepted the created app password.

### Steps to reproduce
1. Log in
2. Spoof to a different device then log out
3. Try to log in again.

### Info about your device
Google ADT-1, Chromebook.

**Comment by yeriomin** [comment]
Are you sure your Yalp Store is v0.14? This looks like a duplicate of #163, #151, #128.

**Comment by ryaniskira** [comment]
Yes, it is 0.14 on both the Chromebook and the ADT-1.

**Comment by yeriomin** [comment]
Does clearing app data and trying to log in without device spoofing work?

**Comment by ryaniskira** [comment]
On the Chromebook sometimes it does, sometimes it does not. On the ADT-1 it works every time.

**Comment by ryaniskira** [comment]
Update. On the Chromebook full functionality was restored after a ChromeOS update, ARC version did change. On the ADT-1, not much of an issue for me and the device was only for Google I/O attendees.
