### ISSUE TITLE
Не обновляются приложения

### ISSUE THREAD

**Issue by marat1995** [yeriomin/YalpStore#165]
### Expected behaviour
Программы не обновляются.
### Steps to reproduce
1. Я так понимаю нужно поставить настройки приложения так же, как у меня.
Т.е: во всех чекбоксах нет галочек, установка root способом.
### Info about your device
Samsung T531, Android 5.0.2

**Comment by yeriomin** [comment]
Что происходит вместо обновления? Yalp не будет автоматически обновлять приложения если у нового apk не совпадает подпись с установленным или если изменились разрешения, которые требует устанавливаемое приложение. В этом случае в области уведомлений появится сообщение.

**Comment by marat1995** [comment]
@yeriomin  Yalp просто ничего не показывает.

**Comment by marat1995** [comment]
@yeriomin  обновлено: 
похоже Yalp не обновляет приложения, если файлы в папке
/data/data/yalp/ изменены.

**Comment by yeriomin** [comment]
Почему эти файлы изменились? Это внутренний каталог приложения. Ни одно приложение не ожидает внешнего вмешательства туда.

**Comment by marat1995** [comment]
@yeriomin я сам там что-то поменял(интересно было).
вроде где-то true заменил на false.
я конечно понимая, что прогу сломал сам я и тут нет Вашей вины, но было бы очень круто
если бы Yalp не ломался бы от этого.
