### ISSUE TITLE
Uncommon device definitions wanted

### ISSUE THREAD

**Issue by schnatterer** [yeriomin/YalpStore#166]
As an android TV user, I'd like to spoof android TV IDs, in order to get a proper choice of android TV apps from google play.

A prominent candidate for this would be the NvidiaShield Android TV.
I found some device info [here](https://github.com/mc-imperial/shader-compiler-bugs/wiki/nvidia-shield-tv).
I'd created a PR, but I couldn't find out from your code how the `device-*.properties` files make it into the apk 😉

Really appreciate your work!

**Comment by yeriomin** [comment]
`device-*.properties` come from [play-store-api](https://github.com/yeriomin/play-store-api) library. The information contained in them is quite specific and I haven't found any other way to get in except building it on the device itself. Android docs [describe](https://developer.android.com/google/play/filters.html) what part of it is definitely used. It is impossible to say if the rest is somehow used too, but it is required to login (specifically to check-in and generate device id).

Yalp Store builds `device-*.properties` on crash and attaches it to crash reports. Also, it is attached to email if you send it through the About page. So far no one has submitted a crash report from NvidiaShield. Yalp must work perfectly there ;).

I'll add a different android tv device for now.

A request to the users:
**If you have an uncommon (very old or very new, a tv, a laptop, any device where android shouldn't run but runs) device, please send me an email by clicking on my email address on the About page in Yalp Store.** Your device info will be attached to it and other users will be able to download apps which are available for your device. Don't worry, no personal info is sent.

**Comment by schnatterer** [comment]
Hi @yeriomin, 
Thanks for your fast answer, including an android TV's device info and for the new release!

I followed your request and emailed you a couple of android device infos.
On some of these devices I didn't have any email provider installed, so it was a bit complicated. Maybe you could add an option for saving the properties file to the device instead of attaching it to the email?

I tried to use the `MBX m201 Smart TV` device info you added, but it didn't work out the way I hoped.
Here's my use case:
There are some apps on Play that have a normal and a special TV version. Depending on your device info Play either ships one APK or the other when you hit download. On the Android TV hardware I have, I always get the normal APK, but I'd like to have the TV one. That's why I like to use the device info of some other device.
My example app is [Synology's DS Video App](https://play.google.com/store/apps/details?id=com.synology.dsvideo).  The normal APK has version 3.3.1 whereas the TV APK has version 1.1.3. You can also get the APKs [here](https://usdl.synology.com/download/Mobile/).
What worked for me was using the Android TV Emulator - I can install the TV apk using YalpStore.

Could you please add the  Android TV Emulator device info to YalpStore?
