### ISSUE TITLE
Поделиться и темы

### ISSUE THREAD

**Issue by marat1995** [yeriomin/YalpStore#167]
Пожалуйста, добавьте кнопку поделиться на странице приложения, как в Google Play.
Потом темы.
Различия между Темной и Черной вообще есть?
Лучше бы добавили бы другую, кроме белой и темной.

**Comment by marat1995** [comment]
Нашел баг с одним приложением.
Вот оно:
https://play.google.com/store/apps/details?id=com.serakont.appbuilder
Баг заключается вот в чем:
Yalp пишет, что последняя версия это 1.6 и что этого приложения нет в Google Play.
Так оно есть!

**Comment by marat1995** [comment]
Чуть не забыл.
Еще, я думаю, много людей обрадовалось бы возможности оставлять отзывы о приложениях
через Yalp, а не Google Play.

**Comment by yeriomin** [comment]
Решение вашей первоначальной задачи в мастере. Закрываю.

Пожалуйста, описывайте одну проблему/предложение в одной задаче. Здесь не форум, а система управления задачами. Если напишете по английски, остальные пользователи дополнят вашу задачу.

>этого приложения нет в Google Play
>Так оно есть!

При переходе по вашей ссылке:
![screencapture-play-google-store-apps-details-1495648468680](https://cloud.githubusercontent.com/assets/554737/26417966/475e3a10-40c3-11e7-84a9-94504ea703d7.png)

Разработчик что-то изменил. Приложение было, но перестало быть доступным. Не баг.

**Comment by marat1995** [comment]
@yeriomin хм у меня ссылка работает.
ок, забью на этот App builder
