### ISSUE TITLE
Проблема с поиском при подмене устройства

### ISSUE THREAD

**Issue by dimqua** [yeriomin/YalpStore#168]
При смене используемого устройства ("притворяться другим устройством") результаты поиска значительно сокращаются, либо поиск не находит вообще ничего. 

Пытаюсь притвориться Wileyfox Swift, Google-аккаунт Yalp Store. У меня устройство на Snapdragon 410.

**Comment by yeriomin** [comment]
Most likely, this is happening to gapps-dependent apps. I've updated gapps version in the device definitions and the crash report is going to detect installed gapps version from now on.

**Comment by dimqua** [comment]
@yeriomin К сожалению, проблема с Wileyfox Swift не исчезла, но с Xiaomi Mi5 работает.
