### ISSUE TITLE
Remove Google dependencies?

### ISSUE THREAD

**Issue by AlfaOmega33** [yeriomin/YalpStore#17]
I hope that is not a stupid request, but is possible add, like future feature, an ability to work without Google Account? Like Aptoide or the same F-Droid? There are an apps that allow you to download APKs without registration..

**Comment by yeriomin** [comment]
Unfortunately, it is impossible. The point of yalp is to get apks from Google Play Store and it requires having an account. It is not something I can influence on. Both Aptoide and F-Droid already have a (semi)light open-source app, so there is no point for me to duplicate it.
