### ISSUE TITLE
Yalp Store OTA update is not working

### ISSUE THREAD

**Issue by piiiggg** [yeriomin/YalpStore#170]
### Expected behaviour
I download Yalp Store 0.14 from F-Droid, since we have 0.15
Yalp Store should update into 0.15 on About
But instead it's telling no update found

### Info about your device
Xiaomi Redmi 3s, Android 6.0.1 (AOSP 6.0.1)

**Comment by yeriomin** [comment]
Every application from f-droid is compiled by f-droid. This is not something I do, and not something I can influence. I just tag the version when it is ready. They usually update apps once a week.

For further info check out [Yalp Store's f-droid wiki page](https://f-droid.org/wiki/page/com.github.yeriomin.yalpstore).
