### ISSUE TITLE
french translations don't fit in button

### ISSUE THREAD

**Issue by jooola** [yeriomin/YalpStore#171]
### Expected behaviour
Clean button without overflow

### Actual behaviour
![tmp_28044-screenshot_20170525-1615341766000129](https://cloud.githubusercontent.com/assets/19195485/26454072/36c8f7fa-4166-11e7-8ae2-a7cff4008b39.png)

### Info about your device
Smartphone 5"

Sorry this is a fast written issue because i'm on the phone

**Comment by yeriomin** [comment]
**You** can solve this =)

The translations are managed through [poeditor](https://poeditor.com/join/project/LUPUijv2Cs). It is a simple web service which lets people with no technical knowledge contribute translations to opensource projects.

If you care and have time, please visit [poeditor](https://poeditor.com/join/project/LUPUijv2Cs), search for that string and fix it. It shouldn't take more than 10 minutes even if you have never done this before.

**Comment by jooola** [comment]
Could you tell which string code this is ?
dialog_title_purchasing_app
or
details_downloading

**Comment by yeriomin** [comment]
details_downloading

**Comment by jooola** [comment]
Done ! Really nice app Yalp Store ! Thanks !
