### ISSUE TITLE
SIGABRT (possibly due to stack underflow due to excessive recursion)

### ISSUE THREAD

**Issue by mirabilos** [yeriomin/YalpStore#175]
I have a HTC Desire (bravo) with Android 4.4 LiquidSmooth with MicroG and BlankStore on it and installed Yalp Store 0.15 via F-Droid.

After starting, it immediately FCs during the login attempt.

Once Yalp Store was installed, BlankStore also FCs, so I removed the latter, but Yalp Store still does not work.

I managed to get a logcat but github lets me neither upload it nor put it inline due to size limit.

**Comment by mirabilos** [comment]
[x.zip](https://github.com/yeriomin/YalpStore/files/1034445/x.zip)

**Comment by yeriomin** [comment]
The recursion happens within google's protobuf library. I also have HTC Bravo, but with Gingerbread, so the device is not the reason...

The crash happened during the checkin - when Yalp sends device info to google. So Yalp generates something that protobuf cannot serialize, probably. I'd appreciate it if you posted your build.prop.

If you have time, check out [the class which builds the device info request](https://github.com/yeriomin/YalpStore/blob/master/app/src/main/java/com/github/yeriomin/yalpstore/NativeDeviceInfoProvider.java). Maybe you'll guess what irregularity of your android build triggers the crash.

Also, please try some previous version of Yalp. The device info building process was a lot dumber before (so it might work). Try [v0.11](http://4pda.ru/forum/dl/post/9850417/com.github.yeriomin.yalpstore_11.apk).

Tell me if it helps or if you learn anything.

**Comment by mirabilos** [comment]
Oy! 404! (I think.)


Ой! Ошибка 404.
Запрашиваемая информация не существует, перемещена или удалена.
Для поиска необходимой информации, Вы можете посетить:
Сайт | Форум

**Comment by mirabilos** [comment]
v0.13 could still be installed from F-Droid. This one works. Should I also try v0.14?

**Comment by yeriomin** [comment]
0.13 doesn't crash? Please try 0.14. Thanks.

**Comment by mirabilos** [comment]
On Sun, 28 May 2017, Sergey Yeriomin wrote:

> 0.13 doesn't crash? Please try 0.14. Thanks.

0.14 crashes.

Thanks.

**Comment by yeriomin** [comment]
Should be fixed in master.

**Comment by mirabilos** [comment]
Sergey Yeriomin dixit:

>Should be fixed in master.

Can you put a test/nightly build up somewhere
so I can test that before the next release and
give good feedback?

Thanks!

**Comment by yeriomin** [comment]
https://downloads.buddybuild.com/api/download/download-apk?buildID=592ec5f05d513d00010e14cf&application_variant=release

Its just a link to the latest built apk. Unfortunately, buddybuild does not allow public access, so a nightlies list is impossible.

**Comment by mirabilos** [comment]
Hm, that one FCs too, I'll get a logcat later

**Comment by yeriomin** [comment]
I've looked at your log again and the crash happens when protobuf tries to parse the checkin response, not build request.

```
I/com.github.yeriomin.yalpstore.NativeHttpClientAdapter(15500): Requesting https://android.clients.google.com/checkin
I/com.github.yeriomin.yalpstore.NativeHttpClientAdapter(15500): HTTP result code 200
F/art     (15500): art/runtime/indirect_reference_table.cc:93] JNI ERROR (app bug): local reference table overflow (max=512)
```

No wonder Blank store crashes too. This crash does not even produce an exception I can catch. Unfortunately, without the response content its hard to know how to prevent this.

**Comment by mirabilos** [comment]
Sergey Yeriomin dixit:

>No wonder Blank store crashes too. This crash does not even produce an
>exception I can catch. Unfortunately, without the response content its
>hard to know how to prevent this.

Hm, ouch. Does this use SSL or can I just tcpdump the traffic?

Or maybe you can add a debug flag in which it logs the response?

**Comment by yeriomin** [comment]
SSL. I use [Packet Capture](https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture) to sniff traffic on live devices.

Debug request/response dumps is probably a good idea too... will add it soon.

**Comment by yeriomin** [comment]
@mirabilos If you still care, I've modified Yalp to dump requests/responses to /sdcard/YalpStoreDebug in debug builds. Headers are dumped in plain text, bodies in binary (they are protobuf mostly).

**Comment by mirabilos** [comment]
Sergey Yeriomin dixit:

>@mirabilos If you still care, I've modified Yalp to dump
>@requests/responses to /sdcard/YalpStoreDebug in debug builds. Headers
>@are dumped in plain text, bodies in binary (they are protobuf
>@mostly).

Sure, just point me to a debug build, I should be able to get
this tested.

**Comment by yeriomin** [comment]
https://40-76187413-gh.circle-artifacts.com/0/tmp/circle-artifacts.RvYzJQ7/apk/app-debug.apk

**Comment by mirabilos** [comment]
Funnily enough, I have yet to get a crash with that version…

**Comment by yeriomin** [comment]
@mirabilos Good. I'm closing this then. If it happens again don't hesitate to open a new issue.

**Comment by mirabilos** [comment]
Oh, looking at #244, interesting, because only the debug build did not crash. (Although I’ve not yet tried the newer F-Droid versions.)
