### ISSUE TITLE
"Page or URL has been blocked" with http in the US

### ISSUE THREAD

**Issue by Eloston** [yeriomin/YalpStore#176]
When connecting from within the US, all downloads result in a 136-byte HTML file stating that the page or URL has been blocked. This happens regardless of device info being used or account being used.

I was able to resolve this issue by [modifying DownloadRequestBuilder in getDownloadUri](https://github.com/yeriomin/YalpStore/blob/a5e1b827713cc3c950e3a16c200c02f9ca35af22/app/src/main/java/com/github/yeriomin/yalpstore/DownloadRequestBuilder.java#L46) to replace `http://` with `https://` (but it would probably work by not doing any replacement since your `play-store-api` library uses https everywhere by default).

I'm not really sure how you want to solve the issue, so I refrained from making a pull request. I was thinking that adding an option to use https, deciding based on the device's region, or checking the downloaded file's contents could solve the issue.

**Comment by yeriomin** [comment]
Thanks for a detailed issue.

The replacement is there because downloads go through system DownloadManager, not through Yalp Store, by default and it does not support https on old androids.

The fix is in master. If you can, check it out.

**Comment by Eloston** [comment]
It's working now. Thanks!
