### ISSUE TITLE
com.google.android.gms version detection breaks with UnifiedNlp

### ISSUE THREAD

**Issue by Eloston** [yeriomin/YalpStore#177]
The "no GAPPS" version of UnifiedNlp (as available on F-Droid) uses the name `com.google.android.gms`. This breaks the detection introduced in 2d4e9865f940b3642a8e358abc2d37bcbdb65026 in [line 185](https://github.com/yeriomin/YalpStore/commit/2d4e9865f940b3642a8e358abc2d37bcbdb65026#diff-8ade29b6410d5504588694f9db61ea07R185).

**Comment by yeriomin** [comment]
How does it break it? Every installed app has versionCode populated. At most it would make Yalp report a seriously outdated GSF version.

**Comment by Eloston** [comment]
It breaks searching entirely. Even typing in the package name fails to do anything.

For apps that have updates, it no longer reports the new version available. It just shows the current version.

**Comment by yeriomin** [comment]
Thanks. I'll check it.

**Comment by yeriomin** [comment]
>breaks searching entirely

Search works, search suggestions too, admittedly there are _slightly_ less apps, because the current GSF version is close to 10548448 and version of com.google.android.gms provided by UnifiedNlp is 20187.

If search on your device is broken _entirely_, its not because of the commit you mentioned. Please describe the problem in more detail. Are there crashes?..

**Comment by Eloston** [comment]
I inspected adb logcat and exceptions are thrown. When UnifiedNlp is installed, the same exceptions are thrown as the situation where UnifiedNlp is not installed and no results were found.

Based on what you said, it's possible that Google responds differently to GSF versions in different regions. So this probably isn't a fault of your parsing implementation, but a discovery in server behavior.

Here are snippets of the logcat when UnifiedNlp was installed if you need them:

1. Trying to view a category:

```
I com.github.yeriomin.yalpstore.NativeHttpClientAdapter: Requesting https://android.clients.google.com/fdfe/list?ctr=apps_topselling_free&c=3&cat=ANDROID_WEAR
I ActivityManager: Displayed com.github.yeriomin.yalpstore/.CategoryAppsActivity: +153ms
I com.github.yeriomin.yalpstore.NativeHttpClientAdapter: HTTP result code 200
D com.github.yeriomin.yalpstore.CategoryAppsActivity$1: java.lang.IndexOutOfBoundsException caught during a google api request: Index: 0, Size: 0
E com.github.yeriomin.yalpstore.CategoryAppsActivity$1: Unknown exception java.lang.IndexOutOfBoundsException Index: 0, Size: 0
W System.err: 	at com.github.yeriomin.yalpstore.CategoryAppsIterator.next(CategoryAppsIterator.java:22)
W System.err: 	at com.github.yeriomin.yalpstore.CategoryAppsTask.doInBackground(CategoryAppsTask.java:24)
W System.err: 	at com.github.yeriomin.yalpstore.CategoryAppsTask.doInBackground(CategoryAppsTask.java:9)
V com.github.yeriomin.yalpstore.CategoryListActivity: Stopping activity
```

2. Trying to perform a search:

```
V com.github.yeriomin.yalpstore.SearchResultActivity: Starting activity
I com.github.yeriomin.yalpstore.SearchResultActivity: Searching: google
I com.github.yeriomin.yalpstore.NativeHttpClientAdapter: Requesting https://android.clients.google.com/fdfe/search?q=google&c=3
V com.github.yeriomin.yalpstore.SearchResultActivity: Resuming activity
I ActivityManager: Displayed com.github.yeriomin.yalpstore/.SearchResultActivity: +399ms
I com.github.yeriomin.yalpstore.NativeHttpClientAdapter: HTTP result code 200
D com.github.yeriomin.yalpstore.SearchResultActivity$1: java.lang.IndexOutOfBoundsException caught during a google api request: Index: 0, Size: 0
E com.github.yeriomin.yalpstore.SearchResultActivity$1: Unknown exception java.lang.IndexOutOfBoundsException Index: 0, Size: 0
W System.err: 	at com.github.yeriomin.yalpstore.AppSearchResultIterator.next(AppSearchResultIterator.java:25)
W System.err: 	at com.github.yeriomin.yalpstore.SearchTask.getNextBatch(SearchTask.java:48)
W System.err: 	at com.github.yeriomin.yalpstore.SearchTask.doInBackground(SearchTask.java:36)
W System.err: 	at com.github.yeriomin.yalpstore.SearchTask.doInBackground(SearchTask.java:10)
```

Checking for updates:

```
I com.github.yeriomin.yalpstore.NativeHttpClientAdapter: Requesting https://android.clients.google.com/fdfe/details?doc=com.google.android.gms
V com.github.yeriomin.yalpstore.DetailsActivity: Resuming activity
I ActivityManager: Displayed com.github.yeriomin.yalpstore/.DetailsActivity: +263ms
I com.github.yeriomin.yalpstore.NativeHttpClientAdapter: HTTP result code 200
D com.github.yeriomin.yalpstore.DetailsActivity$1: java.lang.IndexOutOfBoundsException caught during a google api request: Index: 0, Size: 0
E com.github.yeriomin.yalpstore.DetailsActivity$1: Unknown exception java.lang.IndexOutOfBoundsException Index: 0, Size: 0
W System.err: 	at com.github.yeriomin.yalpstore.PlayStoreApiWrapper.getDetails(PlayStoreApiWrapper.java:81)
W System.err: 	at com.github.yeriomin.yalpstore.DetailsTask.doInBackground(DetailsTask.java:31)
W System.err: 	at com.github.yeriomin.yalpstore.DetailsTask.doInBackground(DetailsTask.java:10)
```

**Comment by yeriomin** [comment]
>responds differently to GSF versions in different regions

This makes me sad.

If you can, please post a real GSF version of any device you have. They might not even be sequential. If you have time, try using 10548448.

**Comment by Eloston** [comment]
> If you have time, try using 10548448.

I've been using Yalp Store by not having UnifiedNlp installed, so `10548448` works fine for apps that I use.

> please post a real GSF version of any device you have

I don't have any other devices, but according to Open GApps, there is a version of `com.google.android.gms` named `11.0.55 (448-156917137)` with version `11055448`. You can get this by going to [opengapps.org](http://opengapps.org/), selecting platform ARM64, Android 7.1, any variant, and clicking "Source Report" at the bottom of the pane. I'm pretty sure the Source Report varies by platform & Android version.

Interestingly, this is newer than the version that Yalp Store has (which has `10.2.98 (440-146496160)`). Attempting to manually download `11055448` fails. I'll try and see if building with `11055448` will affect the version I can see.

This is a tangent, but I compared several different Source Reports and there seems to be some correlation between the last digit of the GSF version and the DPI:

* nodpi -> 0
* 160 -> 2
* 240 -> 4
* 320 -> 6
* 480 -> 8

**Comment by yeriomin** [comment]
Thanks for your help. I'm going to keep the fallback version code up to date from now on.

Here is what I've found out:
The version code seems to consist of the version string without dots and some flags (which are probably not used for app filtering). The DPI flag seems to be redundant, as there is a specific field for DPI sent during login (checkin) process. To filter apps version code of `com.google.android.gms`, not `com.android.vending` is used. All apps which depend on google services, mention specific `com.google.android.gms` version code they depend on.

**Comment by Eloston** [comment]
I see. Is it possible to get the GSF version required?
