### ISSUE TITLE
Аккаунт менеджер

### ISSUE THREAD

**Issue by marat1995** [yeriomin/YalpStore#179]
Добавьте в Yalp менеджер аккаунтов, как в Google Play.
Переключаться с одного аккаунта на другой было бы круто.
И еще.
Когда я разлогиниваюсь в менюшке Yalp все равно есть кнопка Разлогиниться.
Лучше уж залогиниться сделать для ситуацию, когда ты не вошел в аккаунт.

**Comment by yeriomin** [comment]
Что такое аккаунт менеджер?

Походив по приложению Google Play обнаружил разве что список заказов и подписки. Никакого отношения к функционалу Yalp это не имеет.

Или вы имеете в виду системный раздел настроек Google, где настраивают способ входа итп? Там переключаться с одного аккаунта на другой возможности нет.

В любом случае, большинство пользователей Yalp входят через встроенный аккаунт, а большинство остальных пользуются одним аккаунтом. Такая функция не будет стоить потраченного времени. Чем и кому будет полезно то что вы предлагаете?

**Comment by marat1995** [comment]
Под менеджером аккаунтов я подразумеваю наличие функции переключения между 2 и более аккаунтами, которые есть на устройстве(т.е в которые пользователь уже вошел).
