### ISSUE TITLE
Ошибка при смене языка

### ISSUE THREAD

**Issue by marat1995** [yeriomin/YalpStore#180]
Я поменял язык запросов к Google Play на Русский(Россия).
Результат - всех программ нет в Google Play(хотя должны быть).
Технические подробности:
Samsung SM T531, Android 5.0.2, Yalp Store 0.15

**Comment by yeriomin** [comment]
>всех программ нет

Это значит ни одной? Каких нет например?

Не воспроизводится. Попробуйте очистить данные приложения.

**Comment by marat1995** [comment]
Есть очень известная игра Clash of Clans(пример это, не реклама).
Она в Google Play точно есть, а Yalp пишет, что нет.
https://play.google.com/store/apps/details?id=com.supercell.clashofclans

>Попробуйте очистить данные приложения
Я конечно могу так сделать.
Но у других то это проблему не решит.

**Comment by marat1995** [comment]
Найдено решение:
1. Перелогиниться.
2. Перезапустить Yalp

**Comment by yeriomin** [comment]
>Но у других то это проблему не решит.

Сначала нужно решить существует ли проблема и сменой ли языка она вызвана. Вы можете снова вызвать проблему у себя на устройстве?

**Comment by marat1995** [comment]
@yeriomin не смог повторить.
закрываю.
если еще раз столкнусь и выйдет повторить снова, то напишу.
