### ISSUE TITLE
How do you fake device?

### ISSUE THREAD

**Issue by matlink** [yeriomin/YalpStore#181]
It's not a real issue, but I wonder how you fake devices in yalpstore? I tried to read the code but I only found `SpoofDeviceManager.java` except that I don't understand how it works.
It would be interesting for `gplaycli` to fake device. 
Thanks

**Comment by marat1995** [comment]
Open Yalp Store.
Open settings.
Click on button 
Pretend to be a different divice.
Plz close this issue.

**Comment by matlink** [comment]
I mean in THE CODE, how in Java for ANDROID you do to fake device?

**Comment by marat1995** [comment]
@matlink I don't know.
You can see:
github.com/yeriomin/playstoreapi

**Comment by yeriomin** [comment]
To log in and do anything with Google Play Servers you need to check-in first. This process requires sending a lot of information about your device. Naturally, you can get it from anywhere. [play-store-api](https://github.com/yeriomin/play-store-api) library has some [device definitions](https://github.com/yeriomin/play-store-api/blob/master/src/main/resources) which I get with users' crash reports. You see these definitions list in Yalp's settings.
