### ISSUE TITLE
Ignore new permissions when Yalp auto installing

### ISSUE THREAD

**Issue by piiiggg** [yeriomin/YalpStore#184]
Like the title, please make this option on Yalp Store !

**Comment by yeriomin** [comment]
The warning is there because you **should** check the new list of permissions yourself. Just press the install button and the default android installation dialog will tell you everything.

**Comment by piiiggg** [comment]
I mean, when new permission on new update. It didn't auto install for me, so I just use Yalp to install one app : Spotfy. And I never check new permission for this app

**Comment by yeriomin** [comment]
I'm sorry, I don't think we understand each other fully. Yalp not auto/background-installing apps when new permissions are found is intended behavior. It is supposed to make you look at the new list. You are asking to introduce a security problem.

**Comment by piiiggg** [comment]
You can made that as a option on menu !

**Comment by yeriomin** [comment]
1. Creating an option for every small thing is not a good idea. It makes the code unmanageable.
2. The option you are proposing would be an anti-feature.

**Comment by hansWURSCHT10000** [comment]
> the default android installation dialog will tell you everything
When I get the notification that an app needs new permissions the android installation dialog says that the app does not require any special access. Where can I see the new requested permissions?

**Comment by yeriomin** [comment]
@hansWURSCHT10000 Unless you are running a very old android which does not support signature checks properly, this might be a bug.

What android are you running? What package are you trying to install?

**Comment by hansWURSCHT10000** [comment]
@yeriomin 
I run Android 7.1.2 (Omnirom)
For example I want to update Google Maps form 9.45.1 to 9.56.1.
Yalp gives me the notification that maps needs new permissions.
Android installer says this:
![hnogwyfcr_ohiwro37c2pa_a731cc0ecfa59fd4f16a5f371dc50c472ae35eee](https://user-images.githubusercontent.com/15198431/27885993-736c3f02-61da-11e7-9d88-8f17a2b2fb28.jpg)
I took a look at the permissions with `adb shell dumpsys package com.google.android.apps.maps | grep permission `
Only these two lines changed:
new: `perm=Permission{1795153 com.google.android.apps.maps.permission.PREFETCH}`
old: `perm=Permission{c6c3631 com.google.android.apps.maps.permission.PREFETCH}`

new: `perm=Permission{a11a90 com.google.android.apps.maps.permission.C2D_MESSAGE}`
old: `perm=Permission{1d9ca97 com.google.android.apps.maps.permission.C2D_MESSAGE}`

So not really a new permission?

Other example:
Signal from 3.28.4 to 4.7.4
Yalp says new permission.
This time the installer says this:
![la3mv8e-rxg5es4y9knhya_24c95a8e7d8cfb9d72e910e008a22ee1d3d8ccb7](https://user-images.githubusercontent.com/15198431/27886735-a57777de-61dd-11e7-95a7-92ad1f0b7b1d.jpg)
I looked again for differences via adb:
new: `android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS`
new: `android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS: granted=true`
new: `me.everything.badger.permission.BADGE_COUNT_READ`
new: `me.everything.badger.permission.BADGE_COUNT_WRITE`
changed: 
new: `perm=Permission{7454af1 org.thoughtcrime.securesms.permission.C2D_MESSAGE}`
old: `perm=Permission{7a73d5b org.thoughtcrime.securesms.permission.C2D_MESSAGE}`

**Comment by avently** [comment]
Да, вот этот момент и мне кажется странным. Ялп предлагает просмотреть изменившиеся разрешения, но в установщике эти новые разрешения не выводятся. Смысл тогда всего этого действа? Так бы устанавливал потихому и ладно. А если какие-то важные разрешения добавятся, типа доступа к контактам, местоположению и т.д., то система сама спросит, можно ли дать доступ. Правда работает на более новых версиях этот механизм

**Comment by yeriomin** [comment]
@hansWURSCHT10000 @avently Not only added but also *removed* permissions were taken into account. Fixed.
