### ISSUE TITLE
Баг при загрузке приложения

### ISSUE THREAD

**Issue by marat1995** [yeriomin/YalpStore#187]
Версия Yalp Store 0.15, Android 5.0.2, SM T531.
Может уже и пофиксили в 0.16
На странице обновления приложений нашел приложение, которого нет в Google Play.
Удалил.
Предложили скачать снова.
Нажал(просто интересно было, что будет)->
Malform request 
Пофиксите плз.
Про версию.
Плз выкладывайте Yalp куда-нибудь кроме Fdroid.
Например на 4пда.

**Comment by marat1995** [comment]
Почему выкладывать и на пда?
Выкладывать потому что Fdroid проверяет все приложения долго и скачать Yalp можно только дней через 10 после релиза.
Почему 4пда?
Я знаю, Еремин есть на пда и на пда есть официальная страница Yalp.

**Comment by yeriomin** [comment]
В теме на 4pda я написал почему только f-droid. И увидев хаос на 4pda я перестал прикладывать к релизам apk. 

>скачать Yalp можно только дней через 10 после релиза

Это не долго. И можно собрать из исходников.
