### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by marat1995** [yeriomin/YalpStore#188]
It would be cool to add new features.
For example, when you enter a link to the app in the search bar it would open the application page.
Also add an age restriction on the application page.
If possible, please add a wish List from Google Play.

**Comment by yeriomin** [comment]
>It would be cool to add new features.

That's a horrible approach to software development.

>For example, when you enter a link to the app in the search bar it would open the application page.

Implemented already. Type in package id and Yalp will skip search and take you to the app's page.

>age restriction

Would be useful, but Google does not seem to enforce it. Search "sex" on Google Play and most apps will be "Rated for 3+".

>wish List

Useless for free apps.

Please, write issues separately.
