### ISSUE TITLE
Integrated Download Manager

### ISSUE THREAD

**Issue by Sirove** [yeriomin/YalpStore#190]
Can you implement an integrated Download Manager? 

The issue without one is, that apps with blocked internet access can bypass firewall restrictions to connect to the internet via the systems own download manager. Currently Yalp is the only one of my apps that depends on the download managers open firewall rule which poses a security and privacy risk.

I understand you want to keep Yalp as small and compatible as possible but shouldn't security always be a priority?

**Comment by yeriomin** [comment]
Yalp already has a fallback download manager. It is used when the android built-in one is [unavailable](https://github.com/yeriomin/YalpStore/issues/105) or [unreliable](https://github.com/yeriomin/YalpStore/issues/174). You can disable it (Settings -> Apps -> Show System -> Download Manager -> Disable) and Yalp will use its own download manager. Would this solve the problem?

**Comment by marat1995** [comment]
@yeriomin I think not.
need to make a option in the settings to use Yalp's download manager.

**Comment by Sirove** [comment]
Tried it, it works! But deactivating a system app is not a smooth solution... I suggest setting Yalps own download manager as the default and add an option to use the systems as an alternative.

**Comment by yeriomin** [comment]
By the way, your previous issue #189 is a good example of why I'm not ditching DownloadManager. I need 3 lines of code to implement it with DownloadManager and a lot more without. Plus I will have to demand another permission form the user or bypass android APIs altogether and treat an android device as a unix machine. Like here 00c98eb0afc7e090b176068c9090daceeac80ab8.

>Yalp is the only one of my apps that depends on the download managers open firewall rule

>deactivating a system app is not a smooth solution

Looks like a suitable solution for your case.

>I suggest setting Yalps own download manager as the default

System download manager is 7 years old, so it is well tested and feature-rich. Yalp's download manager is very minimalistic and setting it as default when 99% devices have a system download manager in working condition would be wrong.
