### ISSUE TITLE
Detect if Android System WebView is installed

### ISSUE THREAD

**Issue by Laicure** [yeriomin/YalpStore#193]
### Expected behaviour
- Open any app page without errors/crashes

### Actual behaviour
- Yalp Store crashes when opening an app page; points to **Android System WebView** not present/installed in device

### Steps to reproduce
- Just open any app page _without_ Android System WebView

### Info about your device
SM-n910c cf-rooted, Lollipop 5.1.1, no GApps, no xposed, manual debloated

**Comment by yeriomin** [comment]
I'm not using WebView directly and disabling it does not make Yalp crash. Maybe the crash happens on attempt to view specific apps? Please, attach a crash log. You can use built-in crash reporter to email it, too.

**Comment by Laicure** [comment]
oh /hmm ok let me try that one today around 11:30am pst, I will update you once checked.

It's just weird, on a newly flashed (stock firmware, I don't flash custom roms) note 4 (device info above); after removing/uninstalling (via [SD Maid](https://play.google.com/store/apps/details?id=eu.thedarken.sdm)) all gApps (including [WebView](https://play.google.com/store/apps/details?id=com.google.android.webview)), Yalp crashes on viewing an app page (like [Samsung Internet](https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser) and like [SuperSU](https://play.google.com/store/apps/details?id=eu.chainfire.supersu)).

Thanks!

**Comment by yeriomin** [comment]
Reproduced it. The fix will be in 0.18.

**Comment by Laicure** [comment]
Great thanks! ;)
