### ISSUE TITLE
Cancel download button

### ISSUE THREAD

**Issue by marat1995** [yeriomin/YalpStore#196]
В Yalp Store не хватает опции для отмены загрузки приложения и истории запросов поиска.
Можно добавить в Настройки Yalp чекбокс Сохранять историю запросов.
Еще стоит добавить видео на страницу приложения(если они есть).

**Comment by rugk** [comment]
Speaking English would be preferred here, so everyone can understand what your issue is about and can add comments.

**Comment by marat1995** [comment]
@rugk ok.
plz add videos on app's page and plz add history of searching

**Comment by rugk** [comment]
Ah, and so we have a dupe (I did not knew it, of course): https://github.com/yeriomin/YalpStore/issues/211 :smile:

**Comment by yeriomin** [comment]
The issue is actually three issues in one (as usual from @marat1995 ;-) ). It mentions a way to cancel running downloads. It can be done.

**Comment by marat1995** [comment]
@yeriomin what about history of searching?
