### ISSUE TITLE
Arabic language

### ISSUE THREAD

**Issue by haroon-ali** [yeriomin/YalpStore#197]
I've completed the translation to Arabic, I hope you can add it to the next release on F-Droid.
Hoping it's included in 0.17 release.
Thanks for the excellent app.

**Comment by yeriomin** [comment]
Thank you for your effort!

0.17 is tagged already, f-droid is just a bit slow. I will add your translation to 0.18.

Arabic is the first right-to-left language in Yalp Store, so it will probably look wrong here and there. Don't hesitate to email me or leave an issue if some buttons or strings obstruct each other or are out of place.

**Comment by haroon-ali** [comment]
I highly suggest that you use https://hosted.weblate.org/ for translation. 
It give much more controls and boosters for the translator.
I cannot even use "Ctrl+v" in the current system. Very annoying.

**Comment by yeriomin** [comment]
I'll look into it.
