### ISSUE TITLE
Provide an option for loading custom device info property files

### ISSUE THREAD

**Issue by schnatterer** [yeriomin/YalpStore#198]
As a YalpStore user, I would like to load custom device infos from property files, so that I can dynamically add devices to the ones shipped with YalpStore.

This would make the whole mechanism so much more flexible, considering there is [such as huge library of device infos](https://github.com/yeriomin/play-store-api/tree/alldevices/src/main/resources) plus every use can extract additional ones, if required.

**Comment by marat1995** [comment]
+1
I wanted to write a similar issue, but forgot :-(

**Comment by yeriomin** [comment]
Half done. It is a "hidden" feature for now.

Yalp will now scan Downloads directory for files named like this `device-<device name>.properties`. And show them in the spoof list. Modify the `UserReadableName` property inside the file to change its label in Yalp UI.

**Comment by marat1995** [comment]
@yeriomin close issue plz

**Comment by yeriomin** [comment]
@nagayev It is not complete.
