### ISSUE TITLE
Background installation not possible with yalp-store-ota-17.zip

### ISSUE THREAD

**Issue by bungabunga** [yeriomin/YalpStore#199]
### Expected behaviour
On Yalp store 0.17 automatic installation of packages in the background is not possible as in 0.15 although the settings are right.

### Actual behaviour
After klicking install button system notification appear to allow unknown sources (which shouldn't be necessary).

### Steps to reproduce
1. Flash yalp-store-ota-17.zip (fresh or over v0.15)
2. Try to install new or updated app
3. You get system notification to allow unknown sources

### Info about your device
Sony Xperia XZ, Android 7.1.1., stock, rooted

**Comment by akoyaxd** [comment]
Can confirm. Same issue here!

**Comment by yeriomin** [comment]
@bungabunga @akoyaxd Fixed in master. Default UI installer was being used for all UI installs. Background (scheduled updates, "update all" button) were being installed with system privileges.
