### ISSUE TITLE
Option for YalpStore to ignore an app

### ISSUE THREAD

**Issue by subiol** [yeriomin/YalpStore#20]
In a mobile that has Fdroid installed or other app manager different than the PlayStore, sometimes the version of the program installed through Fdroid is different than the one in the PlayStore, but we might want to retain the Fdroid version. YalpStore detects that the app is installed and has a new version from the PlayStore so it offers the actualization. It would be great if each app had a button or menu that would mark the app to be ignored by YalpStore and not offer to actualize it.

**Comment by yeriomin** [comment]
Will do.
Thanks for writing an issue.

**Comment by paride** [comment]
Will you consider also implementing the opposite, i.e. selection which app to monitor for updates, instead of selection which apps to ignore?

Personally I would find this more convenient, as most of my apps are from f-droid, while just a couple are from the play store.

**Comment by yeriomin** [comment]
What do you mean? All installed apps (regardless of their source) are monitored for updates. You want to monitor non-installed apps, or monitor only the apps you whitelist?

**Comment by paride** [comment]
I'd like to monitor only the apps I whitelist (a subset of the installed apps, of course).

**Comment by yeriomin** [comment]
I will keep this in mind, but it is going to need new UI, so it is not a priority.

**Comment by Paviluf** [comment]
> monitor only the apps I whitelist
> most of my apps are from f-droid

That feature is useful because the apps from f-droid are patched or compiled to remove some Google things for better privacy (among other things).

Thanks !

**Comment by paride** [comment]
@subiol I understand, but "whitelisting" is probably more suited for the typical user of this app, who gets most apps from f-droid, but also needs one or two things from the play store. But I understand that the current UI is not very well suited for this. Thanks @yeriomin for this much needed app.

**Comment by yeriomin** [comment]
Looks like this issue is important. Priority goes up ^^

**Comment by logic** [comment]
Is it possible, with the information you have via the Play Store and from the locally-installed apps, to confirm whether the signature of the Play Store app is a match for what's locally installed? That might solve the biggest use-case here: installing a mix of software from F-Droid/other sources and the Play Store, and seeing "updates" that can't be applied from the Play Store.

**Comment by papjul** [comment]
I agree with @logic, that's how Play Store works, it checks for signature and if mismatches, it doesn't show up in Updates.
However, I think that would be a good thing to still see if F-Droid apps are outdated while knowing that updating through Yalp Store will not work since it has a different signature, so maybe we can grey out these apps to differentiate them?
Maybe for users that don't want to see them at all, add a checkbox in settings: Don't show apps with different signature from Play Store?

**Comment by papjul** [comment]
The idea of @paride is also good for privacy since you don't send all of your apps installed to Google but only a few apps you select ;)

**Comment by yeriomin** [comment]
@papjul @logic Thanks for suggestions. I will look into it, but this is going to be a different issue. Meanwhile, black/white list is in v0.5.
