### ISSUE TITLE
Bug: version details truncated

### ISSUE THREAD

**Issue by JonnyTech** [yeriomin/YalpStore#202]
Version details are truncated if it does not fit on a single line making it impossible to see new build number, see image:

![img_20170618_164217_097](https://user-images.githubusercontent.com/3584732/27262172-19193eae-5449-11e7-8d31-770c962242d3.jpg)

**Comment by yeriomin** [comment]
Fixed

**Comment by JonnyTech** [comment]
Confirmed, many thanks
