### ISSUE TITLE
option: check/download updates only on wifi

### ISSUE THREAD

**Issue by ilf** [yeriomin/YalpStore#203]
Yalp currently does not distinguish between data connection and wifi. F-Droid has a nice setting "Only on Wi-Fi" - it would be really cool to have something like this in Yalp.

Thanks, and keep up the good work!

**Comment by yeriomin** [comment]
Duplicate of #189.

**Comment by ilf** [comment]
Sorry, I promised I searched before I posted. :) Thank you!
