### ISSUE TITLE
App crash while trying to manually download APKs

### ISSUE THREAD

**Issue by kowith337** [yeriomin/YalpStore#204]
### Expected behaviour
The app should manually download APKs with the specific version that user given, or latest version number that obtained from server in the "Manual download" screen.

### Actual behaviour
Get "Sorry, Yalp store crashed" screen instead,  none of download tasks started or queued.

### Steps to reproduce
1. Open app details (maybe any apps) in Yalp store app
2. Press `...` > `Manual Download`
3. Input the specific number of app version and/or wait until `Checking` button changed to `Download`
4. Press `Download` and see result.

### Info about your device
**Hardware**: HTC One E9+ Dual Sim (Not Root)
**OS Software**: Android 5.0.2 (Lollipop) running with SenseUI 8
**Device/Log/StackTrace**: https://gist.github.com/kowith337/9f1dbed651d1c5737ba3a5919506a00b

**Comment by JonnyTech** [comment]
Which version of Yalp Store. Did you try uninstalling then reinstalling?

**Comment by kowith337** [comment]
Currently using version 0.17
Tried switch between my own account and this app account, still occur.
Tried clear app data and re-login, still occur.

**Comment by yeriomin** [comment]
Fixed in master.
