### ISSUE TITLE
Invalid email or password on fake credentials

### ISSUE THREAD

**Issue by 321fasd** [yeriomin/YalpStore#206]
### Expected behaviour
Log in with Yalp Store credentials and start downloading.

### Actual behaviour
Version 0.17 gives the toast 'invalid email or password' after ~1 second and returns to the dialog box with own credentials vs fake.
Version 0.15-0.16 hangs for a long while, maybe 30-60 seconds before reaching the same conclusion.

This started happening ~4 hours ago.
I had no problems using my old account ever.

### Info about your device
LineageOS 14.1 [7.1.2]
Samsung Galaxy S6 with Magisk 12.0

**Comment by yeriomin** [comment]
Must be some anti-abuse measure. Started working after I changed the password. This probably means that a pool of throwaway emails is needed... A single email used as the default for Yalp Store is starting to become a weak link.

Thanks for writing. Good call.
