### ISSUE TITLE
Отображать индикатор ожидания только при проверке обновлений

### ISSUE THREAD

**Issue by dimqua** [yeriomin/YalpStore#207]
Если выставить ручной режим проверки обновлений, то при запуске приложения отображается индикатор ожидания, создвется ложное впечатление, что программа проверяет обновления.

![](http://i.imgur.com/yGIlrAp.png)

Думаю было бы привычней, если бы индикатор не отображался при логине и т.п. (в режиме ручной проверки обновлений), а только, если пользователь инициировал проверку обновлений.

**Comment by yeriomin** [comment]
Индикатор ожидания показывает что идёт какой-то процесс. Как индикатор рядом с курсором мыши. Это не индикатор проверки обновлений и даже не индикатор работы по сети. Этот индикатор системный и используется во многих приложениях для индикации любых длительных задач. Связывать его именно с проверкой обновлений было бы неверно.

На вашем скриншоте происходит составление списка установленных приложений. Это может быть долго, особенно если включён показ системных.
