### ISSUE TITLE
Баг в 0.18

### ISSUE THREAD

**Issue by marat1995** [yeriomin/YalpStore#210]
Захожу на страницу приложения, которого нет в Google Play.
Мне предлагают поделиться на него ссылкой. Пофиксите плз.
Еще один баг: в инфо о приложении кнопка еще от разраба наконец-то нормально работает.
а вот в поиске pub:developer не работает нормально.

**Comment by yeriomin** [comment]
> Мне предлагают поделиться на него ссылкой.

Так и должно быть. Для перехода в Play Store есть отдельная кнопка.

> в поиске pub:developer не работает нормально

Из-за этого не работала кнопка "Приложения от X", и понадобилась задача #194.
