### ISSUE TITLE
Feat.Req: disable images

### ISSUE THREAD

**Issue by rosc2112** [yeriomin/YalpStore#212]
Would be helpful to have a config option to disable loading images & thumbnails.

My 3g data is extremely limited in speed (slower than dialup! Or for those who never had 'dialup' - it would be faster to walk to the google server to get the images transferred manually =) That, and a tight data quota (Assurance Wiresless freebee phone only allows 500Mb/month) makes the wait for images to load both a painfully slow process and mostly unneeded/unwanted.

Thanks for the useful program. :)

**Comment by yeriomin** [comment]
Good suggestion. Will do.

**Comment by Laicure** [comment]
yey! 👍  or add a low/original res resolution setting?
