### ISSUE TITLE
Pokemon GO doesn't show up nor is downloadable

### ISSUE THREAD

**Issue by Espionage724** [yeriomin/YalpStore#213]
### Expected behaviour
When searching for Pokemon GO, it should appear in the app list to download

### Actual behaviour
Most of the time, Pokemon GO does not show. Sometimes it will show, but trying to download it presents me with another screen to try to guess a version number.

### Steps to reproduce
1. Open Yalp Store
2. Search "Pokemon GO"
3. If Pokemon GO isn't at or near the top of the list, it isn't showing
4. If Pokemon GO does show at or near the top of the list, it will have you guess a version number

### Info about your device
Nexus 6 + crDroid Android + microG

**Comment by marat1995** [comment]
@Espionage724 I think, pokemon go doesn't exist on Google Play.

**Comment by Espionage724** [comment]
https://play.google.com/store/apps/details?id=com.nianticlabs.pokemongo

**Comment by rugk** [comment]
Maybe that's, because of SafetyNET? Same [as Netflix](https://www.xda-developers.com/netflixs-safetynet-exclusion-is-actually-a-new-feature-in-the-google-play-console/)…

**Comment by Espionage724** [comment]
I pass SafetyNet (Magisk passes, and if I download Pokemon GO's apk and install it, it runs fine). Netflix shows up in Yalp Store and can be downloaded as well.

**Comment by marat1995** [comment]
@Espionage724 play store said pokemon go didn't available on my country(Russia)

**Comment by Espionage724** [comment]
I'm in the US, but also have a VPN for any other location (currently Switzerland). Both countries don't show Pokemon GO in Yalp Store.

Perhaps it might be related to the Yalp Store account? I'm using the fake Yalp account that's default. Although I recall using my own account (US-based) and don't think it made a difference (I'll re-try it later on).

**Comment by JonnyTech** [comment]
Is it marked as incompatible with your device? Does Play Store find it?

**Comment by rugk** [comment]
BTW what does "it will have you guess a version number" mean? How is it asking for a version number?

**Comment by Espionage724** [comment]
With Play Store (with microG and regular Gapps), I can download Pokemon GO under the same device conditions no problem.

As for the version number, it asks for it as soon as I hit download. Here's a video: https://www.youtube.com/watch?v=S5cd7DHB5Ck

I seem to be able to make Pokemon GO show up in the downloads list now by manually selecting my language to English US, (was set at system default before, and that's English as well), and my device to a Nexus 6P or Pixel (api 23 and 25). I use a Nexus 6 which according to that list, is also API 23.

**Comment by rugk** [comment]
Interesting, I think the important sentence is the last one there. Play Store deems the app to be incompatible with your device.
Also what about the notification where it already shows "download complete"? Can't you touch that and it should just start the installation?

I mean when the version number selection is shown, this surely happens _before_ the app has been downloaded, so I am quite surprised by the notification.

**Comment by Espionage724** [comment]
The notification was from when the download for Pokemon GO happened to complete. I'm not sure why it happened once, but I haven't been able to repeat it (now I only get the version entry prompt).

**Comment by Espionage724** [comment]
I think I've figured something out. I force-stopped Yalp Store, cleared the data/cache for it, and basically put it in a clean-state. I then started it up, it logged into the default Yalp Store account, and I immediately tried searching Pokemon GO. It didn't show up.

I then set my device to the Google Pixel, closed Yalp Store, and re-opened it. I tried searching Pokemon GO and it showed up.

I had a previous download of the apk that wasn't complete or something. Yalp had the install button shown, but when I tried it, I got a parsing error. I backed out of the AOSP package installer, and was taken to a version screen, but this time, it had a pre-filled value for it of 2017062000.

I deleted the apk, re-opened Yalp Store, downloaded Pokemon GO, and it installed. Just to be sure, I repeated the above process (cleaned Yalp Store, re-set the Google Pixel device setting), and was able to download Pokemon GO still. I also repeated the process again manually selecting Nexus 6 as my device, and it seems to work still too.

I'm not entirely certain what the inconsistency was before (hoping it doesn't happen again). 

The problem now though seems to be with how my original device info is presented. I have a Nexus 6, but using the "Your original device info" under the "Pretend to be a different device" option doesn't work. Manually selecting "Nexus 6 (api23)" works though.

**Comment by yeriomin** [comment]
@Espionage724 Hi. Could you send me your original device info? You can do it by tapping on developer's address on Yalp's about page/activity.

Google requires **a lot** of info about your device on login. Check out [Nexus 6 device info](https://github.com/yeriomin/play-store-api/blob/master/src/main/resources/device-shamu.properties) which I have bundled with Yalp Store. Any difference between your device and this info might make Google servers consider your device incompatible with this or that app. If you send me your device info I might be able to prevent your problem from happening again.

This might have been a single glitch. Pokemon GO is not available in my country, but through VPN I was able to download it immediately, without device spoofing. Re-logging in might be needed (clearing app info does the same thing).
