### ISSUE TITLE
Going back looses updates

### ISSUE THREAD

**Issue by gerroon** [yeriomin/YalpStore#214]
### Expected behaviour
Tell us what should happen

It should keep the updates list intact.

### Actual behaviour
Tell us what happens instead
Updates are lost

### Steps to reproduce
1. Check for updates
2. Find an app to instal -> Install it
3. Try to go back to previous window(which is updates window). You no longer have your updates, you have to re update.

### Info about your device
Device model, android falvour

Lollipop Samsung phone

**Comment by yeriomin** [comment]
Implementation is in master.
