### ISSUE TITLE
FR: Show v ersion numbers

### ISSUE THREAD

**Issue by gerroon** [yeriomin/YalpStore#215]
### Expected behaviour
Tell us what should happen
It should show version numbers in the update window

### Actual behaviour
Tell us what happens instead
It does not show any version numbers uner or next to the apps

### Steps to reproduce
1.open the update window
2.check for updates 
3.

### Info about your device
Device model, android falvour
Lollipop

**Comment by yeriomin** [comment]
Google does not return version strings on update check. Only on details request. Sorry.
