### ISSUE TITLE
Игнорировать минорные обновления

### ISSUE THREAD

**Issue by dimqua** [yeriomin/YalpStore#218]
Предлагаю добавить в приложение возможность (опцию) отображать только значительные обновления. То есть, только если в номере версии изменилась первая цифра, либо вторая (после точки), если есть.

У некоторых популярных приложений минорные обновления выходят чуть ли не ежедневно, поэтому загружать и переустанавливать приложения из-за незначительных изменений нет никакого желания, как и смотреть каждый раз какие там изменения произошли. А так, Yalp бы отфильтровывал всё сам и было бы очень удобно и вместе с #200 позволило бы значительно сократить трафик. Правда, скорее всего, это решение не универсальное, т.к. у разных программ [нумерация отличается](https://en.wikipedia.org/wiki/Software_versioning). Или Google Play накладывает свои ограничения на нумерацию?

**Comment by yeriomin** [comment]
Способа отличить минорные от не-минорных нет. Текст версии может быть в любой форме и ни для чего кроме показа пользователю ни в Yalp ни в Play не используется. Используется номер версии (int).
