### ISSUE TITLE
Отображать номер версии на странице обновлений

### ISSUE THREAD

**Issue by dimqua** [yeriomin/YalpStore#219]
На данный момент, информация о версиях доступна только на странице приложения. Было бы полезно видеть на какую версию происходит обновление приложения, не открывая его страницу, например, 0.1 -> 1.0. Поскольку информация о времени последнего обновления зачастую малоинформативна её можно скрыть.

**Comment by marat1995** [comment]
@dimqua привет. наконец-то кто-то на русском.
В #215 вроде сказано, что это не будет сделано.

**Comment by yeriomin** [comment]
Duplicate of #215.

Информация о версии на запрос обновлений не возвращается.
