### ISSUE TITLE
Загрузчик Yalp

### ISSUE THREAD

**Issue by marat1995** [yeriomin/YalpStore#220]
Было бы неплохо интегрировать в Yalp собственный загрузчик.
Это даст кучу плюсов, например управление трафиком(перенаправлять через Tor), отмена загрузки приложения(и не нужно оставливать системный загрузчик).

**Comment by yeriomin** [comment]
Встроенный загрузчик есть. И давно. Используется когда недоступен системный. На эту тему было много задач. И вы в некоторых сообщения оставляли. Будьте внимательнее.

> Это даст кучу плюсов, например управление трафиком(перенаправлять через Tor), отмена загрузки приложения(и не нужно оставливать системный загрузчик).

Ровно наоборот. Это всё легче с системным загрузчиком.

>перенаправлять через Tor

Системный загрузчик этому не мешает.

**Comment by avently** [comment]
@yeriomin
Почему-то у меня не работает Yalpstore с системным загрузчиком. После обновы только встроенный в программу загрузчик работает, хотя с системным все впорядке. Что не так делаю?
LOS 14.1
