### ISSUE TITLE
"Ignore further updates" button in signature mismatch notification

### ISSUE THREAD

**Issue by yeriomin** [yeriomin/YalpStore#221]
Signature mismatch on update often means the new apk is from a different source than the installed one. Further updates are likely to be mismatched too. So, in addition to apps list in preferences and ignore button on the details page a button below the notification would be useful.

**Comment by rugk** [comment]
…and this button should also delete the downloaded APK for convenience (at least if the "delete APK after installation" setting is active)…

Ref: https://github.com/yeriomin/YalpStore/issues/69#issuecomment-311955147
