### ISSUE TITLE
Provide an option to download apps already installed on my phone with different signature

### ISSUE THREAD

**Issue by JoseDavid3** [yeriomin/YalpStore#222]
Yalp store would be useful for me to download apks updates for apps that i modify and customize, but when i try to download an app that it's already installed on my phone with different signature modified by me, Yalp store  warns me that I must first uninstall the app because it has a different signature, before I can download and install it.

Can you provide an option for advanced users to activate the possibility to get apks from apps already installed on the phone with different signature?
Thanks.

**Comment by yeriomin** [comment]
@JoseDavid3 You can get apks of the installed apps if you press "..." near run button and choose "Get local apk". Yalp will put it into your downloads directory and name it like this: <package name>.<version code>.apk

Is this what you wanted?

**Comment by kowith337** [comment]
Maybe about the app signature, not about older version of apps.

You can't get the same app with the different signature on Google Play, this app provide the function to download app directly from Google play, this doesn't about download apps with diff sigs or changing them.

If you want to seek the app that have different signatures, you might search them or compile by yourself, or use F-droid repo app to find them.

Note: Only few apps available in both GPlay and F-droid but in F-droid you will get the diff sig than GPlay.

**Comment by JoseDavid3** [comment]
![img_20170702_184250](https://user-images.githubusercontent.com/29835487/27771834-bb156936-5f56-11e7-8d6f-e83f3c6cbc26.jpg)
@yeriomin  no, I want, if it's possible, be able to download an apk in this situation (view image) without uninstall the same but modified app that I have installed. 

Because I know that I won't be able to install it directly without modify the apk or uninstall the modified apk, but I want get the latest version of an apk to customize it and update the modified app that I have Installed. 

Sorry for my bad english and thank you very much for your attention.

**Comment by yeriomin** [comment]
@JoseDavid3 If you see this message, the apk is already on your device. To check the signature apk needs to be downloaded first. It is in your downloads folder with name `<package name>.<new version code>.apk`.

**Comment by JoseDavid3** [comment]
@yeriomin yes, it's true, the apk is on my device on the download folder. 

Sorry for open this thread without noticing that the apk was downloaded, I thought that I couldn't download when always seen the message.

Thank you very much for this fantastic app

**Comment by yeriomin** [comment]
@JoseDavid3 Thank you for your kind words!
