### ISSUE TITLE
Add to FAQ: Is the android device id sent to google

### ISSUE THREAD

**Issue by micressor** [yeriomin/YalpStore#225]
It would be great if a few info on how YalpStore uses the Google API would be in the FAQ.

**Comment by yeriomin** [comment]
YalpStore does not send device id to google. A new device id is generated every time you log out/in. Otherwise device spoofing would not work.

I will extend the "How does it work?" section.

**Comment by micressor** [comment]
Thanks a lot for this. In the text you added, I did not understand the difference between Device ID and GSF.
How long is the token valid? Do I have to log off until a new device ID is generated? What if I'm not logging into (YalpStore uses default account), does the device ID change from time to time?

Thanks a lot.

**Comment by yeriomin** [comment]
>the difference between Device ID and GSF

>Each time you log in a new Google Services Framework id (also known as device id) is generated

Two names of the same thing.

>How long is the token valid?

Months. Don't know exactly.

>Do I have to log off until a new device ID is generated?

Yes.

>What if I'm not logging into (YalpStore uses default account), does the device ID change from time to time?

Default account uses the same procedure. A new GSF id is generated when you log in and does not change until you log out. You can see your current email and GSF id on the About page.
