### ISSUE TITLE
Suggestion: display cpu architecture and screen dpi information in device list

### ISSUE THREAD

**Issue by Rikk** [yeriomin/YalpStore#227]
Hello, I would like to make a suggestion:
Display CPU architecture and screen dpi in device selection list (spoofing).

On other topic, is it planned to implement logout/login without restarting the app? In a way we could refresh the open app page after we change device spoofing.

Thanks for this nice app.

**Comment by Rikk** [comment]
PS: is there any device using mips cpu in the list?

**Comment by yeriomin** [comment]
>Display CPU architecture and screen dpi in device selection list (spoofing).

This is not the only important info in the device definition ([example](https://github.com/yeriomin/play-store-api/blob/master/src/main/resources/device-sailfish.properties)). Putting it all into the radio button list will make it unreadable. I think I will add a long press action which just opens the text file with the definition.

> is it planned to implement logout/login without restarting the app?

It takes a couple of seconds to do it, and considering that you will not do it frequently, I don't think it *should* be done.

> PS: is there any device using mips cpu in the list?

No, but if you have a mips device, send me a bug report from it (tap on developer's email on the About page) and I will add your device info.

**Comment by Rikk** [comment]
>>is it planned to implement logout/login without restarting the app?

> It takes a couple of seconds to do it, and considering that you will not do it frequently, I don't think it should be done.

One use-case could be downloading the same app for more than one device, one after the other.
Another case is that the app doesn't properly retrieve the version for the changed device, but only after a logout/login. And another is when opening a Play Store link from another app: it often fails to retrieve the version available to download, also requiring a logout/login. Mixing this second case with changing devices, this results into a boring workflow: open link, change device, logout, close app, open link again, login. And even then, it is possible the app still doesn't detect the correct version available, and the procedure need to be repeated once again. Btw, when the app doesn't detect the correct version available, "manual download" also doesn't work.

One alternative solution would be a button to force-check (refresh) the available app version for the current device.

**Comment by Rikk** [comment]
"Force stop"¹ the app is an alternative to logout/login when changing devices.

¹ Alternative: make sure all windows are closed, then open and close a new instance using launcher icon to make sure the app process is dead.

Is 0.19 apk available somewhere? Does it fix part of the refresh issues?

**Comment by yeriomin** [comment]
>One use-case could be downloading the same app for more than one device, one after the other.

Yalp is not for play store scraping. You can use [play-store-api](https://github.com/yeriomin/play-store-api) library and build the app which does it.

> the app doesn't properly retrieve the version for the changed device, but only after a logout/login

Nothing wrong or unexpected here. If you choose not to logout/login, new device definition is not sent.

> a refresh after changing devices, without the need to re-login, would be nice.

This is technically impossible. The device definitions are sent to google at login. Implementing background login requires storing user password. It will not be done.

To reiterate: logout/login is **required** for Yalp to function properly after device definition change.

**Comment by yeriomin** [comment]
Long pressing device list item will now open the device definition in a separate activity.
