### ISSUE TITLE
Во время поиска ищется по предыдущему запросу

### ISSUE THREAD

**Issue by avently** [yeriomin/YalpStore#228]
Когда я запускаю Ялп, нажимаю поиск, набираю текст, нажимаю энтер, то вижу результат поиска по предыдущему запросу.  Когда же я вижу эти результаты поиска и пробую снова набрать нужный запрос, то просто ничего не происходит после нажатия энтер. А вот если нажать на подсказку автодополнения, то поиск-таки отображает нормальные результаты. 

Под предыдущим запросом я понимаю запрос, который я вводил еще до запуска программы.

Это странное поведение уже несколько версий длится. Причем так случается не в 100% случаев. Не знаю, как тебе это можно воспроизвести, если раньше ты с таким не встречался.

**Comment by yeriomin** [comment]
Как и #229 это поведение связано с поддержкой старых версий android. Изменить это, не ломая стек активностей нельзя. К тому же, пользоваться это тоже не мешает.

Подробнее:

https://issuetracker.google.com/issues/36909641
http://stackoverflow.com/questions/23446120/onnewintent-is-not-called

**Comment by avently** [comment]
@yeriomin 
Сергей, скажи пожалуйста, у тебя есть какая-то статистика по поводу того, какие версии ОС чаще используются с этой программой? Не получится ли так, что ты пытаешься поддерживать старые версии, при этом ломая юзабилити на более новых версиях, а реально мало кому нужна поддержка старых?
Если из за 2.х ты убиваешь напрочь удобство в 4х+, то, думаю, стоит провести какой-то опрос или провести аудит крэш репортов. 
Ну а по поводу "это не мешает" - и в #229, и тут это ужасно мешает. Спроси кого-нибудь еще, если мои слова для тебя не такой серьезный аргумент

**Comment by nagayev** [comment]
@avently статистика у Сергея Есть.
Ему принадлежит аккаунт yalp.store.user1@gmail.com или как там его и он может отслеживать 
в личном кабинете Google какие устройства заходили на него через Yalp Store

**Comment by yeriomin** [comment]
@avently @nagayev То, что ты описываешь происходит на *старых* андроидах (<api21). Чтобы это произошло нужно начать поиск при помощи кнопки на экранной клавиатуре пока есть активный старый экземпляр страницы поиска. Три условия одновременно. То есть это происходит редко. Удобство не напрочь не убито.

Альтернатива - сменить режим запуска страницы поиска на singleTop, тогда не будет истории поиска (будет храниться только одна страница поиска) на всех версиях. Тогда заноют пользователи.

Буду рад pr, если знаете как это изменить, не меняя остальное поведение.

**Comment by avently** [comment]
yeriomin, но у меня Андроид 7.1.2 и это выше апи 21. 
После твоего коммента понял, как это повторить. 
То есть я что-то ищу. Выбираю результат поиска, потом понимаю, что поиск следует подкорректировать и набираю другой запрос. В результате поиск показывает 
результаты старого запроса. У меня это частая стратегия. И повторюсь, седьмой андроид.

**Comment by dimqua** [comment]
Тоже 7.1.2 и такая проблема имеется.

_Sent from my ARK Benefit A3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
