### ISSUE TITLE
Кнопка Назад скрывает все приложение

### ISSUE THREAD

**Issue by avently** [yeriomin/YalpStore#229]
С главного экрана введи что-нибудь в поиск. Например, instagram. Перейди на найденный инстаграм. Нажми кнопку Домой. Затем из запущенных приложений перейди на YalpStore. Потом нажми кнопку назад. Вместо перехода на экран со списком поисковых результатов программа просто скроется на рабочий стол. 

Нужно логику навигации подправить..

**Comment by marat1995** [comment]
@avently здорова. лучше пиши по-английски, здесь русских не очень много.
Конечно, Еремин и еще некоторые поймут,а остальные нет.

**Comment by yeriomin** [comment]
Это не проблема.

Это не мешает пользоваться приложением + чтобы это изменить нужно бросить поддержку старых ОС.
