### ISSUE TITLE
Перенести changelog вверх

### ISSUE THREAD

**Issue by avently** [yeriomin/YalpStore#230]
Когда программа есть в списке обновления, можно на нее нажать и посмотреть changelog. Только вот этот текст в сааамом низу расположен и даже не выделен жирным шрифтом, или отступами, или еще как. 
Считаю, что именно changelog нужно перенести вверх в том случае, если программа установлена. Ведь тогда описание значения не имеет, а изменения в последней версии важны.

**Comment by rugk** [comment]
Can I assume this issue asks about showing the changelog for app updates? :smile:

**Comment by avently** [comment]
@rugk no, I'm asking about changing place of changelog text on a page. Now it's located under description and it's not easy to find it. Would be cool to see it above description for already downloaded apps.

**Comment by rugk** [comment]
Ah, yeah. And as I did not see this changelog (there) my issue is basically the same… :smile:
