### ISSUE TITLE
Unable to be asked to use its own credentials

### ISSUE THREAD

**Issue by Exagone313** [yeriomin/YalpStore#231]
### Expected behaviour
When logged out, be asked to use its own Google credentials to log in (or Yalp Store credentials)

### Actual behaviour
It forces to use Yalp Store credentials, I'm not able to use my own credentials

### Steps to reproduce
1. Open Yalp Store the first time (directly logs in using Yalp Store credentials)
or:
1. Log out
2. Open Yalp Store again (not logged out actually)

I tried the versions 0.14 to 0.18 and they're all affected. It's odd because I hadn't this issue before... I haven't found any config file that would do this.

### Info about your device
Android 7.1.2, LineageOS 14.1 (self built)

**Comment by yeriomin** [comment]
>not logged out actually

How do you know? What is happening exactly?

>I haven't found any config file that would do this

Yalp stores configuration using SharedPreferences, so nothing unusual or non-standard. As all other apps the configuration is in `/data/data/<package name>/shared_prefs/<package name>_preferences.xml`

It does seem that settings can not be saved for some reason. Try changing any option and see if it survives app restart. Have you tampered with anything you shouldn't tamper with?

**Comment by Exagone313** [comment]
Uninstalling the app would remove settings right? Because I did it multiple times.
