### ISSUE TITLE
V0.19 always checks for updates

### ISSUE THREAD

**Issue by JonnyTech** [yeriomin/YalpStore#235]
### Expected behaviour
Check for updates manually

### Actual behaviour
Check for updates on application launch

### Steps to reproduce
1. Settings = check for updates manually
2. Restart application

### Info about your device
Yalp 0.19 from F-Droid on Android 7.1 with no G-Apps

**Comment by JonnyTech** [comment]
To fix:
Stop Yalp Store
Edit```/data/data/com.github.yeriomin.yalpstore/shared_prefs
com.github.yeriomin.yalpstore_preferences.xml```
Set ```<string name="PREFERENCE_BACKGROUND_UPDATE_INTERVAL">0</string>```

**Comment by nagayev** [comment]
@JonnyTech 0.19?
on fdroid i see only 0.19(17 july,2:18pm)

**Comment by JonnyTech** [comment]
Yes: https://f-droid.org/repo/com.github.yeriomin.yalpstore_19.apk

**Comment by nagayev** [comment]
@JonnyTech thanks.

**Comment by yeriomin** [comment]
Fix is in master.
