### ISSUE TITLE
Некорректная обработка "Вид страницы обновлений"

### ISSUE THREAD

**Issue by LVware** [yeriomin/YalpStore#236]
При выключенных настройках
Только обновления (Сейчас показываются все приложения) и
Системные приложения (Сейчас системные приложения спрятаны)
системные приложения прячутся только из блока "Есть обновления" и присутствуют в блоке "Нет обновлений".
В 18й версии при тех же настройках системные приложения прятались из обоих блоков.

**Comment by nagayev** [comment]
@LVware аналогично в 0.19

**Comment by yeriomin** [comment]
Fix is in master. Version 0.20 will be out in a couple of days.
