### ISSUE TITLE
Притворяться другим устройством

### ISSUE THREAD

**Issue by LVware** [yeriomin/YalpStore#237]
Не могу притвориться Sony Xperia Z3 Compact (api 25)
После разлогинивания и входа предлагает выбрать аккаунт, но дальше выбора аккаунта не пускает. Войти в программу можно только после очистка данных приложения.
Любым другим устройством из списка притвориться могу.

### Info about your device
Xiaomi Mi Pad 2, x86-64, api 22

**Comment by nagayev** [comment]
@LVware друг а какая у тебя версия Yalp Store?
Если не 0.19, то скачай ее.

**Comment by LVware** [comment]
Баг был замечен в 0.18 и присутствует в 0.19.

**Comment by yeriomin** [comment]
Fix is in master. Version 0.20 will be out in a couple of days.
