### ISSUE TITLE
Updatable apps are no longer shown in main window...

### ISSUE THREAD

**Issue by repsorp** [yeriomin/YalpStore#238]
Message "No apps need to be updated" even when some apps have to be updated.

Have to look for updatable apps by typing their names in search menu...

Android 7.1.2

Yalp store 0.19     

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by theo546** [comment]
I have exactly this problem too, first, i tought its because i didn't installed the apps on Yalp (i used Play Store to install them, then i want Yalp to replace Play Store)

**Comment by bungabunga** [comment]
i have the same problems. became suspicious after few days of not having any updates. then i cleared the data of the app and after i got logged in again updatable apps magiccialy appeared.

but then there was one new problem right away: after clearing data of an app the settings set manually are gone, so i had to set them up again. and the app crashes (nearly) every time i tap on "settings" (crash logs sent by email).

for now i had to go back to 0.18 which has it's own bugs.

**Comment by theo546** [comment]
Temporary fix: Switch auto check update to manually!

**Comment by repsorp** [comment]
Works !
Thanks
Didn't even think to do that.. :-(

**Comment by yeriomin** [comment]
Fix is in master. Version 0.20 will be out in a couple of days.

**Comment by repsorp** [comment]
Thanks to you yieriomin
Keep up the good work
