### ISSUE TITLE
Yalp crashes after fresh installation (0.19 and 0.20)

### ISSUE THREAD

**Issue by hansWURSCHT10000** [yeriomin/YalpStore#244]
### Expected behaviour
Yalp Store should open

### Actual behaviour
YalpStore 0.19 (but also self build 0.20) crashes 

### Steps to reproduce
1. (fresh) install YalpStore 0.19 from F-Droid (or compile and install from Github)
2. Start YalpStore

### Info about my device
OnePlus 3 Android 7.1.2 (Omnirom)

Logcat for 0.19 and 0.20:

[yalp_0.19_crash_logcat.txt](https://github.com/yeriomin/YalpStore/files/1177066/yalp_0.19_crash_logcat.txt)
[yalp_0.20_crash_logcat.txt](https://github.com/yeriomin/YalpStore/files/1177065/yalp_0.20_crash_logcat.txt)

Maybe it has something to do with microG?
`07-26 17:14:05.005  2881 14749 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms } U=0: not found`
`07-26 17:14:05.007  2591  7265 E GmsClient: unable to connect to service: com.google.android.gms.measurement.START on com.google.android.gms
`

**Comment by JonnyTech** [comment]
Which version of microG? Works fine with 0.2.4-103 for me.

**Comment by hansWURSCHT10000** [comment]
Yes 0.2.4-103
The problem only really occured on a fresh install of YalpStore.

**Comment by nagayev** [comment]
@hansWURSCHT10000 plz send link to yalp store 0.20 apk.

**Comment by hansWURSCHT10000** [comment]
@nagayev 
[app-release.zip](https://github.com/yeriomin/YalpStore/files/1178953/app-release.zip)
Self compiled & self signed

**Comment by nagayev** [comment]
@hansWURSCHT10000 thanks alot

**Comment by yeriomin** [comment]
> Maybe it has something to do with microG?

Yalp does not have anything to do with microG.

Those two log lines are not written by Yalp.

Your crash logs indicate that the crash happens in google's protobuf library, while parsing the checkin response. This looks exactly like #175. Maybe I can invent a workaround if I know what exactly causes it to crash.

Debug builds of Yalp Store dump every request and response to Download directory. If you can, please send me the last couple of responses before the crash. If you cannot do that, please, send me a letter through Yalp's About page. Your device info will be attached to it, which might let me reproduce this crash.

**Comment by hansWURSCHT10000** [comment]
I just build the debug apk (from exactly same source) and installed it but the debug version does not crash O.o
When I uninstall the debug version and install the normal release apk it still crashes.

**Comment by yeriomin** [comment]
@hansWURSCHT10000 That's interesting. Still couldn't reproduce it even with the release version. But I'll keep looking.

**Comment by yeriomin** [comment]
@hansWURSCHT10000 @mirabilos Is this still happening? Several recent changes *might* have fixed this.

**Comment by hansWURSCHT10000** [comment]
Thanks for asking but I didn't have any issues with YalpStore since a while. I moved to Android 8.1.0 (Omnirom) last week and it works great too. Sometimes when I am updating I still see this behavior: https://github.com/yeriomin/YalpStore/issues/184#issuecomment-313239832 but I didn't look more into that.
