### ISSUE TITLE
Install notifications sometimes appear, sometimes don't

### ISSUE THREAD

**Issue by adolfintel** [yeriomin/YalpStore#246]
### Expected behaviour
After the download is completed, the app should be installed using the method specified in the settings. In the default case, that's a notification saying Tap to install

### Actual behaviour
After the latest update of Yalp Store, the notifications appear only about 20% of the time, and I'm forced to download the app multiple times. Playing around with settings didn't help. It used to work with the previous version.

### Steps to reproduce
1. Download an app

### Info about your device
Oneplus 3T with LineageOS 14.1 (Android 7.1.2), no gapps.

**Comment by yeriomin** [comment]
Cannot reproduce.

> After the latest update of Yalp Store

Which one? 0.19 or 0.20?

> and I'm forced to download the app multiple times.

If the apk already exists, new download will not start, instead installation will.

Please be specific in "Steps to reproduce". For example:
1. Opened app details page
2. Tapped "Download" button
3. Waited for the download to finish

Or:
1. Opened Yalp Store
2. Tapped "Update all" button
3. Left the page

Please reproduce it, and use the built-in issue reporter.

**Comment by adolfintel** [comment]
Clarification: it only seems to happen with the "Update all" button, not all apps. Next time an app gets updated I'll record the screen and show you the issue.

**Comment by yeriomin** [comment]
The bulk updater wasn't creating notifications for already downloaded apks and in case of failures to download apk. Maybe this was causing the confusion. Still didn't find any randomness in how notifications appear.

**Comment by adolfintel** [comment]
Hmm it could be. I'll close the issue then and let you know if it happens again, hopefully with more details
