### ISSUE TITLE
Showing incompatible applications in search results

### ISSUE THREAD

**Issue by Kabouik** [yeriomin/YalpStore#249]
It seems that applications incompatible with the Android version Yalp is being run from are not shown in search results. I'm using Yalp on a Jolla C with Aliendalvik mimicking Android 4.4.4, and some applications were visible while they were not from a Jolla 1 with an Aliendalvik mimicking Android 4.1.2 (N26 banking application for instance). Yet, this would be useful at least for downloading the .apk files or when one wants to try forcing the installation anyway, in the hope that the application would still install and partly work. 

Could it be a togglable option in the settings, or just show a warning that the application will probably not install correctly on the device being used?

Thanks for the great work, really enjoying Yalp so far and I'm glad someone came with a Play store alternative.

**Comment by Kabouik** [comment]
Forget it, I just noticed that Yalp offers an option to fake smartphone brands/models, and therefore api, which allows showing corresponding compatible applications in search results regardless of the actual device beong used. Very convenient, sorry for opening this issue.

**Comment by yeriomin** [comment]
Thanks for your kind words.

To clarify:

Compatibility checks are all done on the google server side. The only way Yalp might influence that is during login: user's account and device parameters are used for compatibility checks. Technically, google never says anything about the app being incompatible, it just doesn't return the app version code which is required to start the download. There is nothing I can do in this case, except offering workarounds like device spoofing and manual input of version code (did you notice the "manual download" option?).

**Comment by Kabouik** [comment]
I did notice the manual download option, and in fact I need it quite often with my Jolla C since many apps tend to drop compatibility with 4.4.4 over time, so I have to download old versions and then blacklist updates. It's not easy to guess the incremental number to type in Yalp to get a specific version when the maintainers of the application you want to download do not disclose a clear changelog anywhere (typically big companies and closed applications), which makes it hard to know how many new versions there have been between the last one and the one you want.

After my second post here yesterday, I played a bit with my Jolla (Aliendalvik with 4.1.2 compatibility) and set Yalp to spoof it as a Jolla C. Then, after restarting Yalp, I was able to display the page of the N26 banking application that was previously invisible to the Jolla. However, from there, when I tried to manually download the apk, I could not. Yalp said something like "Google considered your device as incompatible and therefore did not return a version number", something like that. Yet on the real Jolla C, I could download and install the application from Yalp. It seems that Google manages to see incompatibilities despite the Yalp device spoofing.

**Comment by yeriomin** [comment]
> Yet on the real Jolla C, I could download and install the application from Yalp.

Device definition contains [a lot](https://github.com/yeriomin/play-store-api/blob/master/src/main/resources/device-JP-1601.properties) of info. The definition of Jolla C in Yalp Store might not be precise enough.

Please send me an empty bug report from Yalp UI and I will update the definition.

**Comment by Kabouik** [comment]
I will. Thank you.

Please note that at some point, the recent updates of Google Store seemed to blacklist Jolla C in some way, it was not possible to download or update any application unless the Play store itself was downgraded and prevented to update. Since the last Sailfish update, I am not seeing this issue anymore, but maybe additional feedback would be good before concluding whether it's really solved or not. Just mentioning that to say that maybe the device definition for Jolla C is/was "filtered" in some way by Google because it's not an Android device, not sure.
