### ISSUE TITLE
Скрыть платные приложения из списка

### ISSUE THREAD

**Issue by avently** [yeriomin/YalpStore#25]
Привет. Спасибо за программу. Думаю, если будешь продолжать ее развивать, то много тысяч человек, желающих уйти с гуглопрограмм найдут уютное местечко в твоей программе. Количество пользователей microG тому показатель. 

Было бы неплохо иметь возможность скрыть предложение обновить программы, которые обновить все равно не получится - а именно платные программы. Ну или добавить опцию в настройки, с помощью которой можно включить и отключить показ обновлений для платных программ.

**Comment by yeriomin** [comment]
Добавил опцию чтобы скрывать платные приложения. Есть в master и будет в v0.3.
Давать пользователям возможность скачивать платные приложения страшновато. Но сделать можно. Кажется, все хотят.

Спасибо за багу!

**Comment by avently** [comment]
проверил, все круто, новый функционал работает на ура (почти, об этом ниже), спасибо. Пару вопросов возникло, но issue открывать как то не то.
- темной теме можно сказать "до  свидания"?
- насколько правильно делать все через Activity, а не через FragmentActivity? 
- вот эта анимация между переключением окон прикольна лишь пару раз, а когда постоянно туда-сюда по списку приложений ходишь, то кажется лишней. Можно использовать не активити, а фрагменты, и подгружать их естественным способом, добавляя в стек друг за другом без анимации (а не открывая новый активити каждый раз). Будет шустрее работать.
- Зачем поиск обновлений при переходе назад на главный экран? Нажал на приложение, обновил, к примеру, нажал назад и снова запрос обновлений. Лишнее, я считаю. 

Набрал в поиске программу. Нажал на любой результат. Скачать. При скачивании программы в шторке показался прогресс, затем докачалась программа, затем Yalp Store закрылся с ошибкой.
Ошибка такова:
java.lang.RuntimeException: Unable to start receiver com.github.yeriomin.yalpstore.DownloadBroadcastReceiver: /путьдофайлапроги/ exposed beyond app through Intent.getData()
Android 7.1.1

Теперь эту же программу скачать нельзя - при нажатии на Скачать ничего не происходит. 
С обновлениями все тоже самое. И с включенной и с выключенной опцией Устанавливать сразу.

**Comment by yeriomin** [comment]
По пунктам:
* Yalp использует дефолтную тему устройства. Если на устройстве по-дефолту темно, то и в ялпе по дефолту темно. Так было с первого коммита и ничего не изменилось. Так сделано чтобы приложение выглядело как остальные приложения на данном устройстве.
* FragmentActivity не поддерживается в api 10.
* см. пункт 1. Никакого перехода конкренто в ялпе не указано, используется системный. Переходы можно настроить/отключить в Developer Options устройства.
* чтобы не хранить список приложений (который надо модифицировать каждый раз).

"Unable to start receiver" такое было раньше, но больше не наблюдаю.

Спасибо за отзывы.

**Comment by avently** [comment]
1. у меня испольуется Субстратум для тем. Видимо, после перезагрузки снова включилось темное оформление. Так что все ок
3. Может стоит тогда указать? Ибо анимация какая-то прыгающая. Из одного окна выпрыгивает другое и заднее уменьшается в размере на заднем плане. Такого нет ни в одном приложении. В опциях девелопера можно лишь указать время анимации,а не ее тип. АОСП.
4. Можно не хранить и обновлять только при заходе в программу и при нажатии кнопки Обновления. Во всех остальных случаях это лишние телодвижения. Ведь очевидно, что, если пару минут назад не было обновлений, то и сейчас не будет. 
Что значит, что такое было, а сейчас нет? У меня все также. Скачать не получается. Со второй версией все норм было.

**Comment by yeriomin** [comment]
Не помогает ли переустановка приложения? Пожалуйста, пришли logcat.

**Comment by yeriomin** [comment]
Уже не надо, нашёл багу.

**Comment by yeriomin** [comment]
Починил.

**Comment by avently** [comment]
Не совсем. 
Скачивает приложение. Затем крэш. Перезахожу в это приложение, нажимаю скачать, начинается установка приложения. 
![screenshot](https://cloud.githubusercontent.com/assets/7953703/21960242/c84c94b2-daf4-11e6-859f-674394acac25.png)

**Comment by avently** [comment]
С новым коммитом работает отлично! Благодарю.

**Comment by yeriomin** [comment]
И тебе спасибо за отзывы.
