### ISSUE TITLE
Yalp Store offers updates to disabled apps

### ISSUE THREAD

**Issue by sp-1234** [yeriomin/YalpStore#250]
### Expected behaviour
In the list of available updates YalpStore shouldn't show disabled packages.

### Actual behaviour
It shows all packages which can be updated, even disabled.

### Steps to reproduce
1. Get a device which comes with google apps, any one will do I guess.
2. Disable some of these packages (Youtube and Chrome for example)
3. YalpStore will still list them in available updates

### Info about your device
Nexus 5X, latest official ROM (Android 7.1.2)

**Comment by yeriomin** [comment]
Hi.

Why do you think disabled apps should not receive updates?

**Comment by sp-1234** [comment]
@yeriomin because there is no point, they aren't being used. These updates only reduce visual signal to noise ratio basically.  
IMO at least these useless updates should be opt-out…

**Comment by LVware** [comment]
IMHO, It's not a bug, it's a feature!

**Comment by Laicure** [comment]
An option/toggle for auto opting-out for disabled apps would be good as I freeze apps that I still use _once a week/month_ that I don't like running in background.

**Comment by ayanamist** [comment]
@yeriomin Oh no, it seems it disable update for disabled app without an option. I agree it is a feature to receive update for disabled app, i am using https://play.google.com/store/apps/details?id=com.catchingnow.icebox to disable tens of rare used apps, but i still need updates for them.

**Comment by ale5000-git** [comment]
My opinione is that there should be a configurable option.

**Comment by yeriomin** [comment]
@ayanamist @ale5000-git Not many users care about disabled apps and within those who care the majority want them gone. This issue is not big enough to make it configurable. If I added every option requested, there would be around 30 of them already. This would make the app preferences confusing and the code unmanageable. Sorry.

**Comment by matlink** [comment]
@ayanamist @ale5000-git I've made a fork, if you want to have such an option in preferences. it's implemented using this commit https://github.com/matlink/YalpStore/commit/ad8716138c3c7a182e448fa07b6ac5d92b74a5f2
