### ISSUE TITLE
Yalp don't show reviews correctly

### ISSUE THREAD

**Issue by nagayev** [yeriomin/YalpStore#251]
### Expected behaviour
Yalp shoud show reviews

### Actual behaviour
Yalp don't show comments if range of comments is 4-6

### Steps to reproduce
1.Open [page](https://play.google.com/store/apps/details?id=com.kurilevlabs.d0dge) using Google Play.
2.You can see app have 5 reviews
3.Open this page using Yalp and you can see 3 reviews.

### Info about your device
Yalp 0.21, Android 5.0.2

**Comment by yeriomin** [comment]
Cannot reproduce.

**Comment by nagayev** [comment]
@yeriomin легко повторить.
выполни инструкцию и в yalp нажми на кнопку больше отзывов(я про >)
