### ISSUE TITLE
Beta app support?

### ISSUE THREAD

**Issue by rugk** [yeriomin/YalpStore#252]
Does YalpStore offer a way to use the beta version of an app? If so, how?
Google Play offers this feature since a few versions. You can just click on a button in the app and you will get beta updates. Also, you can submit feedback to the developer.

If not, take this as a feature request.

@nagayev

**Comment by yeriomin** [comment]
> Does YalpStore offer a way to use the beta version of an app?

If you sign up for the beta, the apks you get as updates will be beta.

> You can just click on a button in the app and you will get beta updates.

Have never seen it. What apps have it available?

**Comment by rugk** [comment]
> If you sign up for the beta

So you have to do this is the Web Google Play version?

> What apps have it available?

Many, [Threema](https://play.google.com/store/apps/details?id=ch.threema.app) e.g. Their instructions are [here](https://threema.ch/en/public-beta).

**Comment by dimqua** [comment]
@rugk yes, but you need to use your own Google account (obviously).

**Comment by yeriomin** [comment]
Found it.

Not on Threema though. You have to install the app to see the beta button.

**Comment by rugk** [comment]
> @rugk yes, but you need to use your own Google account (obviously).

Ah nice so web interface works. Would be still nice if the button is also available in YalpStore.
