### ISSUE TITLE
App link in the search suggestions dropdown.

### ISSUE THREAD

**Issue by nagayev** [yeriomin/YalpStore#254]
In addition to search term suggestions, direct link to the most likely searched app can be displayed.

**Comment by yeriomin** [comment]
You can.

Please describe your situation more specifically.

**Comment by nagayev** [comment]
@yeriomin на русском будет проще объяснить.
в google play я могу нажать на подсказку поиска и перейти на страницу приложения, в 
yalp же только отобразить результат поискового запроса.

**Comment by nagayev** [comment]
@yeriomin Can you implement this feature?

**Comment by yeriomin** [comment]
Done in master.
