### ISSUE TITLE
/system doesn't update apps

### ISSUE THREAD

**Issue by CHEF-KOCH** [yeriomin/YalpStore#255]
### Expected behaviour
Yalp never updates apps when it's installed as priv-app and /system is used as install/update method. Updating apps as 'root' works as expected.

### Actual behaviour
Infitiy loop 'updating' or 'installing' which never ends or updates the app.

### Steps to reproduce
1. Installed Yalp Store as priv-app.
2. Go to an app which needs to be updated.
3. Press install, it always shows updating without anything. Same goes when you press 'update all' button on the main screen.
4. pressing the back button, revokes this state and you can again press update button which does the same as mentioned.

### Info about your device
* LineageOS 14.1 (Android 7.1.2)
* I9100, Huawai P10, S8+
* Xposed, Lineagesu and NanoMod installed
* Yalp Store 0.22 (latest as of writing this) 

Edit:
Found the issue for some reason during another Rom update or because another nanomod update the app got converted back onto a normal app. However in settings nothing got changed. 

So I suggest to add a check to avoid the trouble which offers you to re-enable it. Otherwise you habe to uninstall and reinstall the app to get it working again.

**Comment by yeriomin** [comment]
> Otherwise you habe to uninstall and reinstall the app to get it working again.

Changing the installation mode to default or root would be enough.

I've added a notification in case permission is revoked for some reason.
