### ISSUE TITLE
[Question]  How does Yalp verify downloads?

### ISSUE THREAD

**Issue by soaringowl2145** [yeriomin/YalpStore#256]
Is there any sort of gpg key verifying and/or checksum verifying with the Yalp Store?

**Comment by nagayev** [comment]
@soaringowl2145 you can look at code of this repository.

**Comment by yeriomin** [comment]
@soaringowl2145 No, it does not. There is some signature returned with the download link, but it doesn't look like anything standard (mdX, SHA...), so It is impossible to use it for integrity checks.

Considering that system DownloadManager is used by default, transmission errors should not be a concern.

**Comment by soaringowl2145** [comment]
Thank you.
