### ISSUE TITLE
Скриншоты

### ISSUE THREAD

**Issue by avently** [yeriomin/YalpStore#26]
Без скриншотов нереально найти какую то неизвестную программу. Надеюсь, добавить скриншоты есть в списке to do. Еще бы комментарии в режиме read only...но это, наверное, будет не так просто.

**Comment by yeriomin** [comment]
Сделаю. Про ревью задача уже есть.

**Comment by avently** [comment]
Я так понимаю, ты сначала хочешь добавить мастхэв функционал, а потом собираешься заняться интерфейсом и юзабилити?

**Comment by avently** [comment]
И это рановато закрыл. Ведь невозможно скриншоты пролистывать, только открыть одну картинку на весь экран, затеи закрыть, открыть следующую. А ведь можно сделать пролистывание как фотографий в галерее или как в плей маркете
