### ISSUE TITLE
Problem downloading an apk

### ISSUE THREAD

**Issue by meaz** [yeriomin/YalpStore#260]
I have last version of Yalp Store on my Galaxy S5 mini with Lineage OS.
Yalp Store works great, except for one app that I can't download: Aurasma.

Here is what I do: I open Yalp Store, I search for Aurasma. I click on it. There, I don't have "Download" at the bottom. Instead, I have three dots. When I click on it, I have a "Manuel downloading" message that appears. I click on it. I then have a page that says that I need to enter the app version that I want. But not any number that I can type works.

Before I installed Lineage, I tested with the native Android app: I was able to download Aurasma with the Google Play app. So it's not a problem with the Galaxy S5 mini.

**Comment by yeriomin** [comment]
Please follow [this instruction](https://github.com/yeriomin/YalpStore/blob/master/.github/ISSUE_TEMPLATE.md) and send me a bug report. It is impossible to say anything specific without your device info. Maybe you don't have gapps installed and Aurasma requires it?

**Comment by meaz** [comment]
Thanks, you were right: I addn't the gapos installed. I installed microg and it works like a charm, so I was able to download Aurasma.
