### ISSUE TITLE
Version code

### ISSUE THREAD

**Issue by nagayev** [yeriomin/YalpStore#264]
I installed the latest version of Qpython3 app.
But in Google Play I can't download this version of Qpython3 app and Yalp
wants to update Qpython3 from 1.2.0 version to 1.0.3
I  suggest check version code of app.

**Comment by yeriomin** [comment]
>I suggest check version code of app.

Yalp (or Play) have always used version code. Version string is purely cosmetic.

1.2.0 is beta, 1.0.3 is the latest stable. The issue is with Qpython3, not Yalp.

**Comment by nagayev** [comment]
@yeriomin но если вышла более новая версия приложения и она недоступна в Google Play
то зачем же обновлять с новой версии на старую?

**Comment by yeriomin** [comment]
@nagayev 

>  код версии у 1.2.0 выше, чем у 1.0.3

Тогда обновления не было бы предложено. Ничего кроме кода версии не проверяется.

Поставил 1.2.0 [отсюда](https://github.com/qpython-android/qpython3/releases). Обновления Yalp не предлагает.

**Comment by nagayev** [comment]
@yeriomin окей, спасибо.
значит дело правда в qpython.
но мне обнову предлагает
