### ISSUE TITLE
When is a new installable zipfile released?

### ISSUE THREAD

**Issue by johanw666** [yeriomin/YalpStore#266]
The last Yalp version that could be installed in /system via a custom recovery was 0.18. When will a new one be released? Or can I just install the 0.24 apk and move it to /system with Titanium or something similar? (Some apps won't work if you do that so I'm asking before I try).

**Comment by yeriomin** [comment]
I've added `yalp-store-ota-24.zip` to the release page.

> can I just install the 0.24 apk and move it to /system

Yes, you can. Or:

* if you try to set installation method to "Using system permissions" and Yalp detects it is not a system app, it can *convert itself* to system app.
* you can also build the OTA zip yourself. `gradlew :app:generateOtaZipStable`

The only added benefit of using the OTA zip is that Yalp won't be demoted to normal app during OS updates.

**Comment by johanw666** [comment]
I didn't get the gradle stuff working but creating the zipfile manually worked fine. I just needed to put the apk from F-Droid in the yalp-store-ota-zip folder and zip it.
