### ISSUE TITLE
Ошибка поиска

### ISSUE THREAD

**Issue by nagayev** [yeriomin/YalpStore#268]
Если я ищу в поиске имя пакета, то поиск ничего не находит и не предлагает 
перейти на страницу приложения.
Сейчас:
Я ищу com.supercell.clashroyale
Ничего не находит
Должно:
Я ищу com.supercell.clashroyale.
Находит приложения, которые находит Google Play на этот запрос и должен предлагать
перейти на страницу пакета com.supercell.clashroyale 
Инфо об устройстве
Yalp 0.24, Android 5.0.2

**Comment by nagayev** [comment]
И ище одна ошибка поиска.
Если я ищу без интернета,то отображается
Сетевая ошибка:java.io.EOFException null
Было бы лучше если бы показывал
Сетевая ошибка. Проверьте свое подключение к Интернету.

**Comment by nagayev** [comment]
Также пишет, что многих приложений нет в play store.
помню так было очень давно, как будто бы в зависимостях стоит play-store 0.14 какой-нибудь.

**Comment by shamolvshu** [comment]
@nagayev can you writhe the issues or response by English, thank you!

**Comment by nagayev** [comment]
@shamolvshu if I search app package, Yalp don't suggest to open app's page.

**Comment by yeriomin** [comment]
> com.supercell.clashroyale

Ввёл в поиск. Нашлось и предложение перейти было. Проверено на 2.3.7, 5.1.1, 7.1.2

**Comment by nagayev** [comment]
@yeriomin какая версия Yalp?
0.24?

**Comment by nagayev** [comment]
@yeriomin в 0.25 такой проблемы нет.
отлично.

**Comment by nagayev** [comment]
@yeriomin 
И ище одна недоработка поиска.
Если я ищу без интернета,то отображается
Сетевая ошибка:java.io.EOFException null
Было бы лучше если бы показывал
Сетевая ошибка. Проверьте свое подключение к Интернету.

**Comment by yeriomin** [comment]
> в 0.25 такой проблемы нет.

Как и в предыдущих. В 0.25 не было связанных с этим изменений.

> Если я ищу без интернета,то отображается

Не воспроизводится. Возможно, вы описываете условия появления ваших неудобств недостаточно подробно.

**Comment by nagayev** [comment]
@yeriomin странно, но у меня в 0.24 clash royale не исаался нормально, в 0.25 все норм.
попробуй поискать приложения без интернета.
увидешь некрасивое сообщение об ошибке java.io.EOFException null
