### ISSUE TITLE
Downloads not working

### ISSUE THREAD

**Issue by yeriomin** [yeriomin/YalpStore#271]
The protocol has changed. Download links are no longer returned.

For technical details see #270.

Looking for a solution.

**Comment by onyxbits** [comment]
Not a final solution:
http://blog.onyxbits.de/raccoon-error-when-downloading-continued-662/

**Comment by nagayev** [comment]
adapt to Google the latest protocol:
https://github.com/onyxbits/raccoon4/commit/416fb54afb166ab252cf8575d436d08a121e0a71

**Comment by yeriomin** [comment]
@onyxbits I have a solution. https://github.com/yeriomin/play-store-api/commit/02a4ebd50dbd69f4121b2370d80c4310e662d03c

New download workflow:
1. `purchase` request which returns a download token. The request is not different from the old way.
2. `log` request which puts the app into user's app library. Response is empty and probably irrelevant.
3. `delivery` request with the download token in the query.

**Comment by onyxbits** [comment]
@yeriomin 

You can skip step 2. If the DocV2 says that a checkout flow is required, simply do a "purchase" and discard the answer, then do a delivery. Appearently, purchase is suppose to register an app with your account.

See https://github.com/onyxbits/raccoon4/commit/0aa9ceb29f1207bc0f0bf525763173b76d317634

**Comment by yeriomin** [comment]
@onyxbits 

> Appearently, purchase is suppose to register an app with your account.

I see. It wasn't doing that before.

> If the DocV2 says that a checkout flow is required, simply do a "purchase" and discard the answer, then do a delivery.

If I don't supply the download token from the purchase response to delivery, no download link is returned. This might depend on the reported version of gapps or something.

**Comment by onyxbits** [comment]
@yeriomin 
I can't confirm that, but I only tested with the Raccoon default device profiles so far.
I'm not quite sure, why you should need anything from purchase in delivery, though. But hey ... it's Google code. One should probably not assume that the name of something (still) has anything to do with it's semantics.

**Comment by shamolvshu** [comment]
Thanks the author contribution,
@sharifStrudent if you not pull the author least commit, you can change the the User-Agent: "Android-Finsky/4.4.3 (api=3,versionCode=8016014,sdk=23,device=hammerhead,hardware=hammerhead,product=hammerhead)".

**Comment by yeriomin** [comment]
@onyxbits @shamolvshu 
On older devices `purchase` is still required. On api>=21 `delivery` is enough.

**Comment by zelleb** [comment]
I can't download paid apps after updating to 0.25

```
09-15 21:25:03.991: W/InputMethodManagerService(1221):  Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@17eaf45 attribute=android.view.inputmethod.EditorInfo@b5d69a, token = android.os.BinderProxy@685bef8
09-15 21:25:04.298: D/OpenGLRenderer(23474):  endAllActiveAnimators on 0x73e4f52800 (MenuPopupWindow$MenuDropDownListView) with handle 0x73e521a3a0
09-15 21:25:04.615: I/MSM-irqbalance(679):  Decided to move IRQ224 from CPU0 to CPU3
09-15 21:25:05.725: V/com.github.yeriomin.yalpstore.DetailsActivity(23847):  Resuming activity
09-15 21:25:07.686: D/WifiStateMachine(1221):  updateCapabilities for config:Lucerna1-5false,false
09-15 21:25:07.940: I/com.github.yeriomin.yalpstore.NativeHttpClientAdapter(23847):  Requesting https://android.clients.google.com/fdfe/purchase
09-15 21:25:08.036: I/com.github.yeriomin.yalpstore.NativeHttpClientAdapter(23847):  HTTP result code 500
09-15 21:25:08.037: E/com.github.yeriomin.yalpstore.NativeHttpClientAdapter(23847):  Exception java.io.FileNotFoundException https://android.clients.google.com/fdfe/purchase
09-15 21:25:08.060: D/com.github.yeriomin.yalpstore.fragment.details.ButtonDownload$LocalPurchaseTask(23847):  com.github.yeriomin.playstoreapi.GooglePlayException caught during a google api request: Server error
09-15 21:25:08.072: W/InputMethodManagerService(1221):  Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@a3e9116 attribute=null, token = android.os.BinderProxy@22b3b2c
09-15 21:25:09.667: I/MSM-irqbalance(679):  Decided to move IRQ200 from CPU0 to CPU3
09-15 21:25:10.630: V/com.github.yeriomin.yalpstore.DetailsActivity(23847):  Pausing activity
09-15 21:25:11.455: V/com.github.yeriomin.yalpstore.DetailsActivity(23847):  Stopping activity
09-15 21:25:11.575: W/WindowManager(1221):  Attempted to remove non-existing token: android.os.Binder@33c1631
09-15 21:25:13.756: D/WifiStateMachine(1221):  updateCapabilities for config:Lucerna1-5false,false
09-15 21:25:14.668: I/MSM-irqbalance(679):  Decided to move IRQ47 from CPU0 to CPU3

```
