### ISSUE TITLE
App claims signature is different when download has not completed yet

### ISSUE THREAD

**Issue by rugk** [yeriomin/YalpStore#274]
### Steps to reproduce
1. Download an app update.
2. When the "is downloading update" window disappears and the button changes to "install update", click it.
3. Popup: "The signature is different[…]"
4. One or two seconds later a notification appears: "Update finished downloading. Click to install"

### Actual behaviour
The app seems to release the "install" button too fast, before the update finished downloading and thus the apk signature of course seems to be different/broken.
When clicking on the notification, the update can be installed without any problem.

### Expected behaviour
Enable the button to install the app, only after the update has been (completely) downloaded.

### Info about your device
v0.24
LineageOS 14

**Comment by dimqua** [comment]
I have the same problem on CM13.

**Comment by yeriomin** [comment]
Delta patching process takes several seconds sometimes. If the user tapped install during that time, the apk would be corrupt and would trigger the signature warning.
