### ISSUE TITLE
Auto start Yalp after reboot

### ISSUE THREAD

**Issue by Sirove** [yeriomin/YalpStore#275]
F-Droid does automatically update even after a reboot. Yalp doesn't. I have to start it manually after every reboot and then it works. Is there a solution without involving a third party app?

**Comment by yeriomin** [comment]
If you set "Check for updates periodically" to Hourly or above, Yalp will start at boot and check for updates.

This seems like a duplicate of #46.

**Comment by Sirove** [comment]
I already set this a long time ago. It doesn't help. :(

**Comment by yeriomin** [comment]
Just checked. After reboot updates are checked.

Check your logs. Yalp logs stuff if it runs on boot. Are you running a f-droid version of Yalp Store?
