### ISSUE TITLE
Remember "use fake google account" after Yalp update

### ISSUE THREAD

**Issue by Sirove** [yeriomin/YalpStore#276]
After every update of Yalp itself you have to choose again if you want to use a fake account. Can you implement a settings option to configure it permanently?

**Comment by yeriomin** [comment]
It does it by default. Just checked. Installed v0.22 -> launched -> it logs in with a default account without asking -> I check for updates and see Yalp Store -> I  tap update -> Yalp Store does not ask anything after relaunch.

Cannot reproduce.

**Comment by Sirove** [comment]
F-Droid updates Yalp.

**Comment by yeriomin** [comment]
Same thing.
