### ISSUE TITLE
Ошибка с меню

### ISSUE THREAD

**Issue by nagayev** [yeriomin/YalpStore#278]
Сейчас если я с помощью Yalp захожу в список приложений, выбираю приложение,
которого нет в Google Play, то в менюшке этого приложения будет вариант Ручное скачивание.
Зачем оно там?
Предлагаю сделать его недоступным для приложений,которых нет в Google Play.

**Comment by yeriomin** [comment]
Не ошибка.

Google при ошибке не возвращает почти никакой информации. Некоторые приложения, которые я поставил из Google Play, дают такую же ошибку. То, что приложения нет в Google Play это **догадка**. Запрещать скачивать вручную основания нет.
