### ISSUE TITLE
Impossible to blacklist yalp store update

### ISSUE THREAD

**Issue by YoyPa** [yeriomin/YalpStore#279]
### Expected behaviour
Yalp Store is blacklisted inside itself.
Yalp Store app updates should not be listed.

### Actual behaviour
Yalp Store update is shown even if it is blacklisted.
Other selected apps are not shown as expected.

### Steps to reproduce
1. Settings/Choosen app are ignored
2. Settings/Blacklist/Check Yalp Store
3. Check for update and Yalp Store is still shown

### Info about your device
Meizu Pro 5 / Flyme 5.1.8(Android 5.1)
Issue is/was present on Yalp 0.22 / 0.23 / 0.24, can't check 0.25 as 0.26 doesn't exist =D

**Comment by yeriomin** [comment]
Should be fixed in 0.26.
