### ISSUE TITLE
"Ignore this update"

### ISSUE THREAD

**Issue by dimqua** [yeriomin/YalpStore#280]
I suggest to add a feature that F-Droid has: "Ignore this update" checkbox.

**Comment by radasbona** [comment]
Or better "ignore all updates". Yalp always tries to download the paid apps from my real Gmail account.
I don't want to blacklist them, because i want to get the notification about the new version.

**Comment by Primokorn** [comment]
@radasbona Is there a problem with updating paid apps from Yalp?

**Comment by radasbona** [comment]
It's only working if you using your real gmail account. I do not, as recommended.

Am 12. Oktober 2017 09:48:31 MESZ schrieb Primokorn <notifications@github.com>:

**Comment by yeriomin** [comment]
@radasbona 

> ignore all updates

There is an update blacklist in the settings.

> Yalp always tries to download the paid apps from my real Gmail account.

It doesn't if you use built-in account.
