### ISSUE TITLE
download button on search results page

### ISSUE THREAD

**Issue by hodanli** [yeriomin/YalpStore#281]
hi, can you add download button on search results page. that makes the app easier to use. thanks for the great app by the way.

**Comment by yeriomin** [comment]
This does seem convenient, but there is no place for this button in current ui. There is too much of everything on the search page already. This requires ui rework.

**Comment by zelleb** [comment]
would if you add a long-press menu?

**Comment by yeriomin** [comment]
@hodanli @zelleb Issue #328 adds a long-press menu.
