### ISSUE TITLE
[question] Способ фоновой установки

### ISSUE THREAD

**Issue by dimqua** [yeriomin/YalpStore#283]
Какой способ фоновой установки использовать предпочтительней: с root-правами или с системными?

**Comment by yeriomin** [comment]
>предпочтительней

Смотря для чего. Скорее всего не имеет значения. Все три способа, включая непривелегированный способ по-умолчанию, делают одно и то же.

Root и системный способы нужны для фоновой установки.

Системный способ даёт возможность фоново обновлять приложения без рута и с выключенным флагом "Unknown sources".

Для таких обсуждений можно использовать "[чатик](https://gitter.im/YalpStore/Lobby?utm_source=issue&utm_medium=issue&utm_campaign=issue)".
