### ISSUE TITLE
Paid app download does not work anymore

### ISSUE THREAD

**Issue by cao-** [yeriomin/YalpStore#286]
Starting from the latest version on F-Droid, which is version 0.25, I can't download anymore purchased paid apps when I'm logged in with my own Google account.  If I go back to version 0.24, it works fine.

**Comment by johanw666** [comment]
It appears to be fixed in 0.26 but F-Droid is terribly slow in updating. I'll build myself instead of waiting on F-Droid.

**Comment by nagayev** [comment]
@johanw666 plz give us your version

**Comment by yeriomin** [comment]
There has been a protocol change related to downloads recently. Paid apps support should be back in 0.26.

**Comment by johanw666** [comment]
@nagayev You can download the installable zip from https://mega.nz/#!9QJB3KSb!TaAQ8EHRMLB0UiVQoDh6Q5gFEBBZlm1LuX2zkrExAWU
