### ISSUE TITLE
Fake yalp login is not working (tokendispenser-yeriomin.rhcloud.com down?)

### ISSUE THREAD

**Issue by jypma** [yeriomin/YalpStore#292]
### Expected behaviour
Using the fake yalp store should allow me to view and download APKs

### Actual behaviour
The UI shows a generic server when selecting "fake yalp store account", and logcat shows
```
10-02 22:22:47.809  8835  9377 I com.github.yeriomin.yalpstore.PlayStoreApiAuthenticator: Login attempt #1
10-02 22:22:47.811  8835  9377 I com.github.yeriomin.yalpstore.NativeHttpClientAdapter: Requesting http://tokendispenser-yeriomin.rhcloud.com/email
10-02 22:22:48.177  8835  9377 I com.github.yeriomin.yalpstore.NativeHttpClientAdapter: HTTP result code 503
10-02 22:22:48.179  8835  9377 E com.github.yeriomin.yalpstore.NativeHttpClientAdapter: Exception java.io.FileNotFoundException http://tokendispenser-yeriomin.rhcloud.com/email
10-02 22:22:48.230  8835  8835 D com.github.yeriomin.yalpstore.AccountTypeDialogBuilder$AppProvidedCredentialsTask: com.github.yeriomin.playstoreapi.GooglePlayException caught during a google api request: Server error
10-02 22:22:51.788  3293  3293 W WindowManager: Attempted to remove non-existing token: android.os.Binder@66f5466
```
That's accurate, since a manual curl of `http://tokendispenser-yeriomin.rhcloud.com/email` (whatever that is...) yields
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Temporarily Unavailable</title>
</head><body>
<h1>Service Temporarily Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
<hr>
<address>Apache/2.2.15 (Red Hat) Server at tokendispenser-yeriomin.rhcloud.com Port 80</address>
</body></html>
```
(at least, it does right now). Maybe it's an intermittent problem, I'll re-try later.

### Info about your device
Galaxy note 2, Android 7.1.1 (Cosmic OS ROM)

**Comment by procyon12lotor** [comment]
Also experiencing this issue.

**Comment by yeriomin** [comment]
@jypma @procyon12lotor Yes, there is a problem with the hosting. I'm moving token dispenser now.

**Comment by Guara111** [comment]
thanks

**Comment by RSDamasceno** [comment]
Same here

**Comment by paul8klee** [comment]
same situation but thanks for working on it!

**Comment by yeriomin** [comment]
@jypma @procyon12lotor @Guara111 @RSDamasceno @paul8klee See the [releases page](https://github.com/yeriomin/YalpStore/releases)

**Comment by breversa** [comment]
Naive question : what's the use of the yalp-store-ota-27.zip file on the release page ?

**Comment by yeriomin** [comment]
@breversa It can be used to install Yalp Store as a system app if you have your bootloader unlocked.

**Comment by breversa** [comment]
Thanks, that's what I thought. But why is the zip file smaller than the apk ? Is the content the same, but with more (efficient) compression ?

**Comment by yeriomin** [comment]
@breversa apk files are not ordinary zip files. To work on android apk files are *zipaligned*. It is a process which adds empty padding to most files in the apk to make them start at some predictable offset. This lets the android OS pick files out of apks without decompressing it all. See [the docs](https://stuff.mit.edu/afs/sipb/project/android/docs/tools/help/zipalign.html) for details.

**Comment by procyon12lotor** [comment]
@yeriomin is there any way you can delete the @ mention of my name in your post above (Oct 4, 2017) Thanks!

**Comment by procyon12lotor** [comment]
Another on Oct 3
