### ISSUE TITLE
Download AND install all

### ISSUE THREAD

**Issue by Primokorn** [yeriomin/YalpStore#293]
### Expected behaviour
When several apps have to be updated, selecting *Download all* button downloads all updates and automatically launch the package installer in the background (root or system permissions).

### Actual behaviour
Updates are only downloaded. No automatic installation. We have to hit on each app notification to install the updates.

### Steps to reproduce
1. You need apps with available updates
2. Hit *Download all* button from the main screen

### Info about your device
OnePlus 3T
Android 7.1.2_r29 using Unofficial Resurrection Remix custom ROM
Yalp Store 0.26

Thank you.

**Comment by yeriomin** [comment]
Select root or privileged installation mode in the settings to turn on background installs.

With the default installation dialog it does not make sense, because it would just pop up randomly as the downloads complete. It would be confusing.

**Comment by Primokorn** [comment]
I know and it's working when updating app one by one. Background installations don't work when I try to update them all in one go.

**Comment by yeriomin** [comment]
@Primokorn They do if you select root or privileged installation mode in the settings. For each failed installation you will get a notification with a brief reason.

**Comment by Primokorn** [comment]
@yeriomin Then please tell me what's wrong with my setup: https://ncloud.zaclys.com/index.php/s/29rTcBdnr0jtl1S

**Comment by yeriomin** [comment]
@Primokorn Found the issue.
