### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by teod0r** [yeriomin/YalpStore#3]
It'll be better if you add categories of applications for searching from. I don't use google play, but I'm shure that there are categories

**Comment by yeriomin** [comment]
There are categories, but I haven't used them even once. I just use the search. Categories are helpful only if you don't know what you want, in my opinion.
I will implement this in some way, but this is not a priority.

**Comment by yeriomin** [comment]
Partially implemented. Category line in details activity, category filter in search activity.

**Comment by teod0r** [comment]
А будет такое, что можно открыть категории без ввода запроса в поиск?  Тоесть посмотреть, что есть в категории, не вводя ничего в поиск.

**Comment by yeriomin** [comment]
Будет.

**Comment by avently** [comment]
Попробуй ввести в поиске слово English. Увидишь баг. Отображает: Фильмы, музыка, книги      и    Приложения

**Comment by yeriomin** [comment]
@avently Это не имеет отношения к категориям + у тебя старая версия.

**Comment by yeriomin** [comment]
Implemented in master.

**Comment by avently** [comment]
@yeriomin  старая отосительно чего? Твоих правок у себя на компьютере? Может быть, но у меня с гита собранная версия с последними коммитами. Я бы выложил скрин, да он на пол экрана выйдет.
