### ISSUE TITLE
Crash with error "Unfortunately, Yalp Store has crashed" when trying to open the app

### ISSUE THREAD

**Issue by francois90** [yeriomin/YalpStore#30]
This started to happen after downloading two apps using yalpstore on adroid 6. I tryed uninstalling and reinstalling it without success. Uninstalling the last app i downloaded with it didn't work either.

**Comment by yeriomin** [comment]
This is really vague. Version 0.4 is out on f-droid. Please update and check if it is still happening. If it is, please provide more info on what ROM you have. A logcat would be ideal.

**Comment by francois90** [comment]
Yes,  the last update fixed the issue. Thanks a lot!
