### ISSUE TITLE
Недоработка в отправке отзыва

### ISSUE THREAD

**Issue by nagayev** [yeriomin/YalpStore#302]
Yalp пишет спасибо, даже когда интернет выключен и телефон не может отправить сообщение
и когда описание проблемы и/или email отсутствуют.

**Comment by yeriomin** [comment]
1. Это не проблема. Не предотвращает использование ни одной функции приложения.
2. Чем меньше код, управляющий отправкой багрепорта, тем меньше вероятность что багрепорт не будет отправлен на каком-нибудь устройстве.
3. "Спасибо" лишним не бывает. ;)
