### ISSUE TITLE
Google play service not available via yalp store

### ISSUE THREAD

**Issue by Krawei** [yeriomin/YalpStore#304]
### Expected behaviour
When I take a look in the google play store I see the google play services, ready for download: 
https://play.google.com/store/apps/details?id=com.google.android.gms . So I'm expecting the same possibility via yalp store.

### Actual behaviour
My yalp store v0.28 doesn't list the google play services neither via the search function nor via the the "show same from Google LLC" menu entry.

### Steps to reproduce
See above.

### Info about your device

OS: Android 7.1.1
Device: BQ Aquaris X

**Comment by yeriomin** [comment]
Play Store app doesn't show Play Services in search/similar apps either. There is no block or anything specific which would prevent Play Services from showing up in search. All results returned by Google are shown.

Updates are possible, though:
![screenshot_20171110-170458](https://user-images.githubusercontent.com/554737/32926226-3582bd1a-cb57-11e7-8af3-30a13baab099.png)
