### ISSUE TITLE
Application names cut off

### ISSUE THREAD

**Issue by wongjustin99** [yeriomin/YalpStore#305]
### Expected behaviour
Text should be completely visible and not cut off.

### Actual behaviour
Application list text is cut off unless I change my entire OS's font size to be smaller.

It should not cut off for the default "Regular" size.

### Steps to reproduce
1. Download Yalp Store
2. View any list

### Info about your device
SH-01J, 5.1.1

I've created a device report as well. I think this should be fairly simple, as allowing larger font-sizes.

Screenshot also attached below with font at the "regular" size.
![2017-10-20 13 10 42](https://user-images.githubusercontent.com/1584142/31822996-a09f61a6-b578-11e7-86b8-59eb7cdfb5e4.png)

**Comment by yeriomin** [comment]
The cutoff should be fixed in 0.29. Cannot do anything about the size without affecting other devices, though.

P.S. I'm curious, what are those "Submenu" and "Select" buttons?

**Comment by wongjustin99** [comment]
Submenu & select are part of my phone's UI. 

Cutoff looks good in 0.29, thanks!
