### ISSUE TITLE
Exit?

### ISSUE THREAD

**Issue by nmyshkin** [yeriomin/YalpStore#307]
I really like the Yalp Store, especially that it runs on my Nook Simple Touch as well as a Nook Tablet with CM 13--too little RAM for GApps there.

Is it possible to add an "exit"? I freely admit to having a thing about apps with no clean exit. On the NST I can "exit" by logging out. That means I must log in each time. I could do the same with CM 13 but have been using the "recent apps" feature to close out the YalpStore. That way I don't have to log in each time all over again.

Obviously I could just back up repeatedly until I escape, much like the PlayStore. But an "exit" option would be much better :-)

**Comment by yeriomin** [comment]
This is against android recommendations, sorry. Developers are not supposed to provide a way to kill the app.

Android is supposed to manage processes by itself and it does it quite well. The fact that the app is sitting in memory does not mean this memory is unrecoverable. Also it is unclear what would be "exit" in android. Force-closing the app would also kill its background processes.
