### ISSUE TITLE
Make it easier to abort Downloads

### ISSUE THREAD

**Issue by rgh36167** [yeriomin/YalpStore#309]
took me a long while to figure out that I have to open the Download manager. 

Maybe tapping on the notification could open the download manager or otherwise offer an option to abort the download?

**Comment by rgh36167** [comment]
Also, it would be nice to have an easy way to abort or pause all downloads?

**Comment by yeriomin** [comment]
There is a cancel button on each individual app page. I have no control over the notification since they are created by the android download manager.
