### ISSUE TITLE
Search in app description

### ISSUE THREAD

**Issue by teod0r** [yeriomin/YalpStore#31]
Ability to search word or phrase in app description would be a great feature

**Comment by yeriomin** [comment]
This is either happening already, or will never be. I'm just using the methods Play Store is using. I don't have access to the app database, so I am not free to choose the search method. And the method Google Play uses is not documented and not supposed to be used by anything other than the official app.

**Comment by teod0r** [comment]
I don't mean to search apps by word in description, I mean search in description.  When you select an app from search list sometimes it is usefull to know if description contains certan phrase.

**Comment by teod0r** [comment]
Добавь поиск в выбранном приложении. Кнопку поиск, чтобы как в фаерфоксе появлялась панель, куда вводишь фразу для поиска по странице
