### ISSUE TITLE
Yalp Store forces the user to relogin often

### ISSUE THREAD

**Issue by yeriomin** [yeriomin/YalpStore#311]
There has been a change in Google API. The auth token which is used to sign all the requests to the Google API now has a limited validity time.

**Comment by yeriomin** [comment]
The issue should be *mostly* resolved if you use the built-in account. User's account should work when version 0.29 is out (in a couple of days).

Keep in mind, that testing this requires time (quite obviously). I don't know a way to determine when the token expires, except waiting. Any observations are welcome.

**Comment by Technowix** [comment]
Actually, each time I open the app I'm asked to re-log into my account / yalp's one.

Only happen when using root/system permissions for installation

**Comment by msdos** [comment]
> Actually, each time I open the app I'm asked to re-log into my account / yalp's one.

This is happening to me as well. I just opened https://github.com/yeriomin/YalpStore/issues/315, is related to this issue?

**Comment by Primokorn** [comment]
Since 0.29 I disconnected and connected again. Now everything is working flawlessly including installing several apps in one go.
No need to relogin on my end. Thanks.

**Comment by Technowix** [comment]
Same, working flawlessly. Gj @yeriomin !

**Comment by MartinX3** [comment]
Thank you, it works now! :D

**Comment by msdos** [comment]
0.29 works here as well, I'm using a custom account. Thanks!

**Comment by yeriomin** [comment]
The issue is fixed properly for user's own account - no more timeouts. For built-in account the issue is fixed by detecting an error and requesting a new auth token automatically.
