### ISSUE TITLE
What are token dispenser mirrors and is it secure to use them?

### ISSUE THREAD

**Issue by KOLANICH** [yeriomin/YalpStore#312]
https://github.com/yeriomin/YalpStore/blob/master/app/src/main/java/com/github/yeriomin/yalpstore/TokenDispenserMirrors.java

**Comment by yeriomin** [comment]
You can read about them [here](https://github.com/yeriomin/token-dispenser). There is also a discussion  [here](https://github.com/yeriomin/YalpStore/issues/297).

Yalp Store uses them to get auth tokens for the built-in account. When you log in two `GET` requests are made to one of the token dispensers, see [here](https://github.com/yeriomin/play-store-api/blob/master/src/main/java/com/github/yeriomin/playstoreapi/TokenDispenserClient.java).
