### ISSUE TITLE
Eliminate sensitive data leakage and espionage

### ISSUE THREAD

**Issue by KOLANICH** [yeriomin/YalpStore#313]
All the sensitive info must be replaceable (by user's choice) with user-specified values, the default one must be ```DEFACE``` (the default one in [xprivacy](https://github.com/M66B/XPrivacy)) to reduce uniqueness (lot of people use xprivacy on original play store and play services). The spoofing must be enabled by default.

Here is the (possibly incomplete) list:

* https://github.com/yeriomin/YalpStore/blob/master/app/src/main/java/com/github/yeriomin/yalpstore/NativeDeviceInfoProvider.java#L79L80
* https://github.com/yeriomin/YalpStore/blob/master/app/src/main/java/com/github/yeriomin/yalpstore/bugreport/BugReportDeviceInfoBuilder.java#L113-L117
* https://github.com/yeriomin/YalpStore/blob/master/app/src/main/java/com/github/yeriomin/yalpstore/bugreport/BugReportDeviceInfoBuilder.java#L96-L98

**Comment by yeriomin** [comment]
1. It is impossible for an app which communicates directly to Google severs to be private.
2. By default, Yalp Store logs in using a built-in account, so your device info is not directly connected to your account. There is an option to pretend to be a different device in the settings.
3. The info you mentioned is not more or less sensitive than the other info sent during login. Also, most of it can be derived from the device name. Here is an [example](https://github.com/yeriomin/play-store-api/blob/master/src/main/resources/device-sailfish.properties) of the info sent during login.
4. The info you mentioned is used on the server side to filter apps available to the user. Sending it has a purpose.

What you are demanding will not give "more privacy" to the users, but will take a small bit of usefulness from the app.

There are many ways to get some apk from the internet. Getting them directly from Google is the distinguishing feature of Yalp Store. For that reason it is never going to be perfectly "private". [F-Droid](https://f-droid.org/) is a great alternative to Google Play Store. Or [apk mirror](https://www.apkmirror.com/) if you want apps from Play Store.

**Comment by KOLANICH** [comment]
>It is impossible for an app which communicates directly to Google severs to be private

I used xprivacy on play store and google services. At least IMEI, MAC, other unique identifiers and the info about operator were blocked. Worked fine.

>By default, Yalp Store logs in using a built-in account, so your device info is not directly connected to your account.

I know.

>There is an option to pretend to be a different device in the settings

It has nothing to do with operator.

>The info you mentioned is not more or less sensitive than the other info sent during login.

It is sensitive because it discloses my operator (I haven't done mobile phone activation and I'm not going to) and my location.

>What you are demanding will not give "more privacy" to the users, but will take a small bit of usefulness from the app.

This must be adjustable.

And not only Google collects these identifiers, your app includes them into bug reports. Why do you need our sim and cell operator info, roaming state, timezone, screen densities, hardware model info, etc? Can you develop the app without collecting such info?

**Comment by yeriomin** [comment]
> At least IMEI, MAC, other unique identifiers

Yalp Store does not use those.

> It has nothing to do with operator.

Since this information is asked during registration of a device, it does.

> This must be adjustable.

It is. By choosing a different device in settings.

> Why do you need our sim and cell operator info, roaming state, timezone, screen densities, hardware model info, etc?

To test why this or that app does not show up in search, for example.

> Can you develop the app without collecting such kind of info?

I already did. You do not **have to** send bug reports. And, as I've said already, removing this info would impact app compatibility filtering.

**Comment by KOLANICH** [comment]
>Since this information is asked during registration of a device, it does.

As I see from the source code, the only source this info is taken is TelephonyManager. I wonder why there is no option to send the fake one and why it is not acyivated by default.

>You do not have to send bug reports. 

I do not. But it is [claimed](https://github.com/yeriomin/YalpStore/blob/5e5be9c889ef1f6ce2c73e98bb2a4150ff4adebc/app/src/main/res/values/strings.xml#L227) that
>No private or sensitive information is collected

The info about operator is the sensitive one. Other info is also considered as sensitive by me. So that claim is not true. The users who have not looked into the source code can be cheated into sending the info they in fact are not going to share. I guess a user must have a granular control over what he shares. There must be a list  with switches, when a switch is on, that info is sent. The tool should send the actual info sent to Play Store (the fake one if the fake one is sent to Play), not always the real one.
