### ISSUE TITLE
Structure the source into folders for better readability

### ISSUE THREAD

**Issue by KOLANICH** [yeriomin/YalpStore#314]

**Comment by yeriomin** [comment]
Unfortunately, there is no standard project structure beyond [this](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html).

Have you seen android [source](https://github.com/AndroidSDKSources/android-sdk-sources-for-api-level-23/blob/master/android/app/Activity.java) [code](https://android.googlesource.com/platform/packages/apps/Messaging/+/android-8.0.0_r24/src/com/android/messaging)? Or F-Droid? More files per directory, a lot more lines per file, multiple classes per file. Besides, a new developer will most likely browse the project through Android Studio which makes directory structure less important.
