### ISSUE TITLE
Fake login will only work if I connect it once using Google Play on android itself?

### ISSUE THREAD

**Issue by msdos** [yeriomin/YalpStore#315]
I've created a fake login in the browser and when I try to use, I get "Incorrect email or password". I haven't logged this user in Google Play on the device itself. Is this needed to make it work?

**Comment by msdos** [comment]
I know this is not related to your project, but I was able to download the apk with my credentials using `gplaycli`, using the username and password instead of a token:

`gplaycli -c /Users/user/.config/gplaycli/yalp.conf -dc hammerhead -d com.glasswire.android`

**Comment by msdos** [comment]
I tested with Yalp login, and having the same error.

So, I closed the application, opened it again and, before trying to search for apps, I went to Yalp settings and tried "logout". Then, my personal credentials worked. I think the error here may be related to https://github.com/yeriomin/YalpStore/issues/311 so I'm closing it.

Do you accept donations to this project?

**Comment by yeriomin** [comment]
> Fake login

Whats that? The built-in account?

> I've created a fake login in the browser

This means it is quite real.

> I haven't logged this user in Google Play on the device itself. Is this needed to make it work?

As far as I know, yes. Things change, so maybe it isn't required anymore.

> I think the error here may be related to #311

No, #311 is about auth *timeout*. Login failures haven't happened for a long time.

> Do you accept donations to this project?

Donations are appreciated. There are links on the "About" page in the app.
