### ISSUE TITLE
May I use Yalp Store's google account on Raccoon ?

### ISSUE THREAD

**Issue by garywill** [yeriomin/YalpStore#318]
Sometimes on PC I need to download apks with Raccoon.

Yalp Store provide a shared google account for users. So I am wondering is it possible to use this account on Raccoon ? (I believe it's technically possible) 

In other issue I see onyxbits says he doesn't intent to give user a shared account. So I am trying to figure out how I can do it.

**Comment by yeriomin** [comment]
There is nothing special about the account Yalp Store uses. So please register your own.

> is it possible to use this account on Raccoon ?

Without modifying raccoon, no. Raccoon's UI expects a username-password pair. Raccoon's underlying library is derived from the same project as Yalp Store's library, so it would not be difficult to modify. But I don't see a point in that.

> So I am trying to figure out how I can do it.

Registering a throwaway account doesn't take longer than writing this issue. If you are the only person who is going to use it, why reinvent the wheel?

**Comment by garywill** [comment]
because it's very hard to register google in my country

**Comment by yeriomin** [comment]
I see. Email me here: yalp.store.dev@gmail.com

**Comment by garywill** [comment]
Sent. My mail: acadsear@yahoo.com
