### ISSUE TITLE
Обновление Yalp Store

### ISSUE THREAD

**Issue by C-500** [yeriomin/YalpStore#319]
С тех пор, как пункт обновления приложения был вынесен из настроек и приложение Yalp Store появилось в списке остальных приложений, каждый раз, когда приложение "ломается" с сетевой ошибкой - я не могу его обновить из самого приложения. До настроек я могу легко добраться, но там больше нет кнопки обновления, а при нажатии на Yalp Store в списке остальных приложений сетевая ошибка не дает мне залогиниться, и это в свою очередь не допускает меня до обновления самого Yalp Store. Судя по скриншоту, приложение даже не проверяет наличие новой версии, пока я не войду в аккаунт, и это при том, что приложения нет в Google Play и наличие/отсутствие аккаунта здесь вроде как не играет никакой роли. В итоге обновиться из самого приложения попросту невозможно, свежий apk приходится скачивать с f-droid или 4pda (и так уже случалось несколько раз). В связи со всем этим, предлагаю каким-то образом вывести приложение Yalp Store "за скобки" и предоставить к нему доступ вне зависимости от того, залогинен пользователь или нет. Ну или вернуть обновление приложения в настройки, на что вы врядли пойдете)
![s71108-020659](https://user-images.githubusercontent.com/18071718/32559387-112e5b90-c4b8-11e7-9f4d-07e57215b739.jpg)

**Comment by yeriomin** [comment]
На странице приложения (то, что на скриншоте) больше не нужно будет логиниться в Google Play Store, чтобы увидеть обновление для Yalp Store.

**Comment by C-500** [comment]
о, круто, благодарю.
