### ISSUE TITLE
Ask "How would you like to login" before trying

### ISSUE THREAD

**Issue by rancidfrog** [yeriomin/YalpStore#321]
Currently, app tries connecting immediately with  credentials provided by Yalp:
![](https://i.imgur.com/8Uxxsyh.png)

If it fails, the options appear:
![](https://i.imgur.com/Bit9r4f.png)

It should be the other way round.
It should ask first, "How would you like to login" before trying to login automatically.

**Comment by yeriomin** [comment]
> It should be the other way round.

It was.

Built-in account was introduced in 0.7. Judging by the bug reports, 95% of users used the built-in account. So since 0.14 it is used automatically on first launch. Why make the user choose? Decisions are hard.

**Comment by rancidfrog** [comment]
Because using default gsf might cause issues by downloading wrong apk type.
I have both arm64v8 and v7, so I would rather download apk v8 for that device.
This mostly affects media apps...
But this is 1 example

**Comment by rancidfrog** [comment]
At least having it is settings:
Such that the dialog appears when you select option,
![](https://camo.githubusercontent.com/d7d83eddea1fe9927c0459abe7f067f9f993709f/68747470733a2f2f692e696d6775722e636f6d2f426974397234662e706e67)
Like how clicking blacklist apps, opens dialog to select which apps to white/black list, this will open dialog to select which to use

**Comment by yeriomin** [comment]
> Because using default gsf might cause issues by downloading wrong apk type.

This should be fixed directly instead of this crutch you are suggesting. Write a separate issue about it. What apps does this happen to? Provide package names, please. Does Play Store app download them properly?

Even if such problem exists, you can log out and choose your account after that.
