### ISSUE TITLE
Update check fails silently if the token is stale

### ISSUE THREAD

**Issue by yeriomin** [yeriomin/YalpStore#322]
### Expected behaviour
Update list or an error message should be displayed

### Actual behaviour
Empty list is displayed, no attempt to relogin is made.

### Steps to reproduce
1. Log in with the built-in account
2. Wait until auth token is invalid
3. Check for updates

In this case Google does not answer with the standard 401 error, instead an ordinary blank answer is returned.

**Comment by JonnyTech** [comment]
Aha - that explains why I have to log out then back in to see updates. How long is the token valid for before it goes stale?

**Comment by yeriomin** [comment]
@JonnyTech Depends on other users' activity. This is not related to #311, because it is not really a timeout. When a new token is issued for the same account, the old tokens seem to be invalidated now. This is relatively recent, and there is still no fix for the shared built-in account, except detecting an error and doing the request again with a new token.

If you use your own account, this does not happen.

**Comment by yeriomin** [comment]
Making any request before the update check fixes this by making Yalp Store autorefresh the auth token.
