### ISSUE TITLE
Refactor "Your apps" page to make it more useful

### ISSUE THREAD

**Issue by rancidfrog** [yeriomin/YalpStore#323]
Currently, Your apps list does not have indicator if app is on update list.
![](https://i.imgur.com/HxUQyIk.png)
It would be useful to have a small indicator, on the right side since there is many space.
The indicator could be an icon which shows that this app will be checked for an update (regardless if using black or white list). For example, if blacklist is being used - all blacklisted apps would **not** have an icon.
And, if white-list is used - all white-listed apps **will** have an indicator.

Also, adding the ability to long-click app in app list to remove from white-list or add to black-list would be helpful,
![](https://i.imgur.com/Pwxib6k.png)

**Comment by yeriomin** [comment]
There would be no point in the update list then. Also, this requires a request to Google Play Store and the reason to create "Your apps" page was to avoid that.

**Comment by rancidfrog** [comment]
I.E. sync icons below but much much smaller,
![](https://cdn.iconscout.com/public/images/icon/premium/png-128/reload-recycle-sync-loop-repeat-refresh-cycle-3aed2f711e3b74b9-128x128.png)
![](https://cdn.iconscout.com/public/images/icon/free/png-512/reload-retry-again-update-restart-refresh-sync-359abf62da7f6afa-512x512.png)
![](https://www.flaticon.com/premium-icon/icons/svg/201/201958.svg)

For example, if blacklist is being used - all blacklisted apps would **not** have an icon.
And, if white-list is used - all white-listed apps **will** have an indicator.

**Comment by rancidfrog** [comment]
@yeriomin
What do you mean:
>  this requires a request to Google Play Store 
No.
It uses your update list to add icon beside App to indicate that it will be checked for update.
It is just an indicator to display that this app is not blacklisted or this app is whitelisted for update

**Comment by rancidfrog** [comment]
![](https://s33.postimg.org/3swpsje7j/3_DTywu_VNh_Zye.png)
Example above shows that only Instagram and k9mail will be updated when you check for updates, and not keyboard. This info is taken from blacklist/whitelist 

For example, if blacklist is being used - all blacklisted apps would **not** have an icon.
And, if white-list is used - all white-listed apps **will** have an indicator.

**Comment by rancidfrog** [comment]
Can this menu open also on long click of app in Your app list?
![](https://s33.postimg.org/9xxex9srj/Screenshot_20171109-231802_01_01.png)

Now, you have to click app and then click three dots in bottom right corner, see yellow arrow.
@yeriomin
