### ISSUE TITLE
Using keyboard "Enter" command does not apply when a search has already been made

### ISSUE THREAD

**Issue by necioerrante** [yeriomin/YalpStore#325]
After making an initial search, my example below _vlc_
If you click search icon (top right corner) and **change** search, my example _fx file_
Search will not take place on "Enter" key from keyboard, it just returns to current search
However selecting search from drop dow menu will search again for new keyword

### Expected behaviour
When clicking "Enter" key, new search should take place

### Actual behaviour
Returns to current search list

### Steps to reproduce
1. Search for  _vlc_
2. click search icon (top right corner) and **change** search, I.E. _fx file_
3. Click  "Enter" key from keyboard
4. Returns to Search list
Tested both AOSP keyboard and Hackers Keyboard

![](https://s17.postimg.org/q6e60f1nj/Screenshot_20171111-155103.png)

**Comment by rancidfrog** [comment]
[0.30] Search still does not work when clicking 'Enter' key from keyboard when already in search.
To reproduce:
- Click _Search_ icon in _Appslist_ view
- Enter search keywords and click `Enter` key
- Search works
- Now, click  _Search_ icon in **Search**  view
- Type in _new_ search keywords and click 'Enter' key from keyboard when already in search view.
- Returns to Search view, no new search, not works

**Comment by avently** [comment]
@rancidfrog he knows about that since July #228
He thinks it's ok and we want it more than alternative

**Comment by yeriomin** [comment]
I'd welcome a pull request which fixes this and does not break anything else.

@avently No need to twist my words.

> He thinks it's ok

No, I think fixing this is not a good idea if it makes the app incompatible with old devices or breaks the search history.

> we

Never said anything about you. People want different and sometimes contradicting things. You are not the only user.

**Comment by avently** [comment]
@yeriomin
>Тогда заноют пользователи.

Я - пользователь. Следовательно "мы" я сказал как раз к месту. Don't twist your words.
А по поводу PR. Я себе сделал, но не знаю, будет ли это работать на старых андроидах и проверить негде.

**Comment by nagayev** [comment]
@avently себе сделал говоришь?
кинь apk,у меня есть гаджет на 2.3.6 и 4.2.2 могу проверить.

**Comment by avently** [comment]
[yalpstore.zip](https://github.com/yeriomin/YalpStore/files/1524161/yalpstore.zip)
Тут есть и другие изменения, которые делал для себя. Скачанный .zip файл переименовать в .apk.

**Comment by avently** [comment]
@nagayev  ну и, проверил?
