### ISSUE TITLE
beta channel updates half the time, stable channel half the time using built in account

### ISSUE THREAD

**Issue by phunkular** [yeriomin/YalpStore#326]
Title says it all. For a while now I have sometimes been offered beta updates. But now it's almost 50/50 as to whether I will be able to see beta or stable channel apps when logging in on yalp store. I noticed first with we view going backwards and forwards with version 62/63, but it's happening with all apps (WhatsApp/Gboard...

thanks

**Comment by yeriomin** [comment]
Built-in account does not support beta updates at all. It is strange that you see them at all. Please be specific, what apps behave like that?

**Comment by phunkular** [comment]
well at first I noticed that I was being offered beta updates from time to time but now as I said, it's pretty much fifty fifty. Currently I have WhatsApp on the latest beta as I updated it by accident and am being offered mi drop 1.6.0 and Android webview 63.* instead of mine drop 1.5.9 and webview 62.*

If I search for a new app, it will offer me the beta channel version. But in a while it will surely shift back to stable channel for apps.

I have tried reinstalling and so on but the issue persists.

**Comment by phunkular** [comment]
so to be clear, it affects all apps that have a beta channel at once... but it is only the case about half the time and I can't see how to predict what's happening. Is there anything I can check for you?

I am on MIUI 9, Android 6.0.1 and have almost all the Google stuff disabled

**Comment by phunkular** [comment]
Have noticed same phenomena on my Nexus 7 tablet with 5.1.1

Not sure about frequency because I don't update apps very often on it, but I was offered beta webview and firefox focus 2.4. When I logged out and came back neither were shown to have updates.

**Comment by yeriomin** [comment]
This appears to be connected to *one* of the built-in accounts, but not all of them. When this happens again could you check which account is active (main menu -> "About" -> "You are logged in as")?

**Comment by phunkular** [comment]
yalp.store.user.one

**Comment by yeriomin** [comment]
This should no longer happen. If you see it happening, please open a new issue with a list of apps.
