### ISSUE TITLE
yalp store does not login automatically with manual updates option

### ISSUE THREAD

**Issue by phunkular** [yeriomin/YalpStore#327]
if I open yalp and tap on any app, the app's page will open and yalp store will try to login with the built in account. That works great.

However, if I open yalp store and tap "update applications" button at the bottom first, it shows an empty list and doesn't log in automatically.

If I have logged in one way or another first, then my uodates list is populated with updates.

thanks

**Comment by yeriomin** [comment]
Duplicate of #322.
