### ISSUE TITLE
Feature Request: Search filtering by GSF dependence

### ISSUE THREAD

**Issue by samnob** [yeriomin/YalpStore#329]
Thanks for a great tool.

On devices with no GSF, it would be great to filter out all the GSF-depending cruft.

An additional tickbox in settings would be much appreciated.

**Comment by zelleb** [comment]
Has been requested a few times now, see [#160](https://github.com/yeriomin/YalpStore/issues/160)

**Comment by samnob** [comment]
Ah, sorry for the DUP.
Would still like the feature, though of course if there was a better 'filter out the ones that won't work for me' option that'd be even better.
