### ISSUE TITLE
Can't donwload Lydia app (versionCode == 0)

### ISSUE THREAD

**Issue by pomarec** [yeriomin/YalpStore#334]
### Expected behaviour
On Lydia (com.lydia) app detail, I should see the download button (as it's not installed yet on my device)

### Actual behaviour
Button download does not appear

### Steps to reproduce
1. search for lydia
2. tap on first result
3. see result in app detail

### Info about your device
Huawei 5C, lineage OS 14.1

### Current investigation
After some debugging, i noticed that `versionCode` in `appDetails` during `AppBuilder.build()` is set to `0`. Then YalpStore check the current device installed app version (which is `0` when not installed) and see no difference. Based on that info, it does not show the download button which makes sense.

**Comment by pomarec** [comment]
I'm not familiar enough with android code architecture to find where the api call is made and inspect it.
My guess is that API returns version value in an unexpected format (or a wrong value). Can someone help me with that ?

**Comment by nagayev** [comment]
@pomarec
Hi,download button didn't appeared maybe
because your device doesn't support this app

**Comment by yeriomin** [comment]
Google API does not return `versionCode` when it considers the app incompatible with your device. This compatibility filtering happens on the server side and can not be controlled by Yalp Store (it just sends your device info at login). 

You can "Pretend to be a different device" in the settings (choose Google Pixel if you are not sure), it will let you download it, but the apk you download might actually be incompatible with your device.

**Comment by pomarec** [comment]
Thanks for your prompt answer.
Do you have any idea why this would happen ?
Anyway, this does not fix the issue (i tried with google pixel and nexus 6). Can someone download the `com.lydia` app ?

**Comment by yeriomin** [comment]
> Do you have any idea why this would happen ?

App developers define which features are required to run their apps. Apparently, your phone lacks something. Can you download it with the original Play Store app?

> Can someone download the com.lydia app ?

It is not available in my country. Maybe it isn't available in yours either.

**Comment by pomarec** [comment]
Sorry I don't have the Google Play Store.
I checked, it is available in my country.
Is there a way of listing the requirements of an app ? Is it just based on API version ?

Thanks

**Comment by yeriomin** [comment]
> Is there a way of listing the requirements of an app ?

No, the choice is made on the server side. Unfortunately, finding out what's wrong requires trial and error.

> Is it just based on API version ?

No, here is a list of things it might be based on: https://github.com/yeriomin/play-store-api/blob/master/src/main/resources/device-gemini.properties It is one of the device definitions which Yalp Store sends while logging in.

**Comment by pomarec** [comment]
Thanks for your enlightment.
What do you think we should do with this issue then ?

**Comment by pomarec** [comment]
I installed `https://github.com/microg/android_frameworks_mapsv1/releases` and everything works :)
Sorry for the troubles, definitely has nothing to do with YalpStore, just my misunderstanding of the situation.

**Comment by yeriomin** [comment]
I'm glad you found a solution.
