### ISSUE TITLE
F-droid build

### ISSUE THREAD

**Issue by JonnyTech** [yeriomin/YalpStore#337]
F-droid have not built a version 30 apk, they still host build 29. Is there a reason for this? Now that version 31 has been released, how can a new build be triggered there?

**Comment by yeriomin** [comment]
> Is there a reason for this?

F-Droid infrastructure has some trouble with build-tools 27.0.1 which are **required** to build 0.30 and 0.31 due to #316. See https://gitlab.com/fdroid/fdroiddata/issues/979

> how can a new build be triggered there?

No one except f-droid devs can do it AFAIK. Once they fix their build server, they will rebuild the failed apps.
