### ISSUE TITLE
Add button "Show changelog" to update notification

### ISSUE THREAD

**Issue by rugk** [yeriomin/YalpStore#341]
### Expected behavior
For automatic update notifications, you should have a button in the notification "Show changelog" which opens the changelog/the usual page in YalpStore instead of installing the update.

### Actual behaviour
I have to install the app.

But I usually also want to review/have a look at the changelog. If I want to do so, I have to manually search the app in YalpStore (if I already installed the update) or, at least, have to go through some menus. This is not so good UX, and I asume many people have the desire to have a look at the changelog.

### Steps to reproduce
1. Enable auto-downloading updates.
2. Wait for update.

**Comment by yeriomin** [comment]
"App installed" notification will now redirect to app page instead of disappearing.
