### ISSUE TITLE
Feature request: autoupdating list enhancements

### ISSUE THREAD

**Issue by kolya-ay** [yeriomin/YalpStore#343]
I have Android without GSF, use F-Droid repos as primary installation source and complement it with Yalp to install a couple of apps from Play Store. Seems that this scenario is pretty common and one of the most popular reasons for using your great app. 

I want Yalp to be less obstructive and not to try to update the installed F-Droid apps in some automatic fashion. Here is my suggestions:
  
  * ~~Autoblacklist F-Droid installed apps. Not sure that it's possible though~~.
  * Option to autowhitelist apps that were installed through Yalp.
  * Highlight somehow the whitelisted/blacklisted apps in default view

**Comment by yeriomin** [comment]
Hello.

Autoblacklist/autowhitelist has been suggested and discussed several times (#39, #69, #262, #285).

Marking whitelisted/blacklisted apps can be done.

**Comment by rugk** [comment]
Mhh good idea with auto white listing. Could you do so optionally?
So one can choose the "blacklist mode" and check a box "automatically whitelist apps installed through Yalp"?
That would already help FDroid users.

**Comment by kolya-ay** [comment]
Ah, I see. I should have searched for existing requests. Sorry for that.
However the second suggestion would imply just a defaults change, not source detection. E.g. when you install some new app mark it as autoupdatable (have an option for that). That would be a partial solution of course, but it would solve the problem

**Comment by kolya-ay** [comment]
@rugk you got here first while I were writing;)
