### ISSUE TITLE
Request: more clarity about "Depends on: Google Play services"

### ISSUE THREAD

**Issue by wolftune** [yeriomin/YalpStore#346]
### Expected behaviour

I would expect that apps that depend on Google Play services couldn't work on my phone that has absolutely no GAPPs installed.

### Actual behaviour

I can install apps that have that dependency listed in Yalp and they work (i.e. Firefox)

### Info about your device

OmniROM 4.4 on Galaxy S2

**Comment by yeriomin** [comment]
This is also a duplicate (#160, #284, #329). Please search the issues before opening a new one.

Play Store apps use Google Play services for location, auth, cloud storage and other things. So whether or not the app works depends on how each app is coded. If you don't have Google Play Games you won't be able to save game progress, but you will still be able to play...

**Comment by Sophira** [comment]
I think the issue then is the use of the word "depends". It normally means something is *necessary*.

Maybe saying "uses Google Play Services" instead of "depends on Google Play Services would help?

**Comment by wolftune** [comment]
Yeah, I agree that "depends" is confusing in this case, and "uses" would be more broad.

**Comment by yeriomin** [comment]
@wolftune @Sophira This sounds like a good idea. Some apps actually do depend on google services though. This might make people think that "uses" means "it will to work without". I guess "uses" is still a better word for it.
