### ISSUE TITLE
Thousands of junk files on sdcard

### ISSUE THREAD

**Issue by avently** [yeriomin/YalpStore#347]
On /sdcard I have thousands files generated by every request from yalpstore. 
Some of them contains text like this:
```
HTTP/1.1 200 OK Alt-Svc: hq=":443"; ma=2512000; quic=51378431; quic=51378339; quic=51378338; quic=51378337; quic=51378335,quic=":443"; ma=2399000; v="14,14,38,35,23" Cache-Control: private, max-age=1800 Content-Encoding: gzip Content-Type: application/protobuf Date: Mon, 11 Dec 2017 13:26:36 GMT ETag: 1151572180 Expires: Mon, 11 Dec 2017 13:26:36 GMT Server: GSE Transfer-Encoding: chunked X-Android-Received-Millis: 1512998794669 X-Android-Response-Source: NETWORK 200 X-Android-Selected-Protocol: http/1.1 X-Android-Sent-Millis: 1512998793302 X-Content-Type-Options: nosniff X-DFE-Content-Length: 3392 X-DFE-Firm-Rpc-Timeout: 0 X-DFE-Firm-TTL: 1800000 X-DFE-Hard-TTL: 72000000 X-DFE-Soft-TTL: 1800000 X-Frame-Options: SAMEORIGIN X-XSS-Protection: 1; mode=block
```
Names like this: datefromutc.response.fdfe.cluster.ecp

**Comment by yeriomin** [comment]
You are using a debug build. These are request/response dumps.

https://github.com/yeriomin/YalpStore/blob/7d7d46c6b095edcb72f3389d69cf6095cb1fc83c/app/src/main/java/com/github/yeriomin/yalpstore/PlayStoreApiAuthenticator.java#L152

**Comment by avently** [comment]
Maybe, to add a different config variable to build.gradle for enabling /disabling this feature? A little bit hardcoded.

**Comment by yeriomin** [comment]
@avently it **is** a gradle variable. `./gradlew :app:buildDebug` vs `./gradlew :app:buildRelease`
