### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by ale5000-git** [yeriomin/YalpStore#348]
@yeriomin

Look here: https://f-droid.org/wiki/page/com.github.yeriomin.yalpstore
It say:
> 0.32
> We can't build this version: The build for this version appears to have failed. Check the build log.

**Comment by zelleb** [comment]
Have you checked the buildlog?

https://f-droid.org/wiki/page/com.github.yeriomin.yalpstore/lastbuild

It says 0.32 succeeded?

**Comment by ale5000-git** [comment]
On the [download page](https://f-droid.org/en/packages/com.github.yeriomin.yalpstore/) it doesn't list 0.32 so something gone wrong.

**Comment by yeriomin** [comment]
https://gitlab.com/fdroid/fdroiddata/issues/1032 has more details.

Tag 0.32 was successfully built by travis-ci at least, so the only thing left to do is wait.

**Comment by ale5000-git** [comment]
Ok, thanks for he reply.
