### ISSUE TITLE
Filter search results of incorrect google search

### ISSUE THREAD

**Issue by teod0r** [yeriomin/YalpStore#35]
Sometimes google search shows results that does not contain search words at all. See search for "patch" for example, first result of search list is app "Path". Neither name nore descriptiont don't contain "patch". It would be nice if Yalp Store will have search filter that will remove incorrect results

**Comment by teod0r** [comment]
That problem is also in youtube. I already reported it for New Pipe application

**Comment by yeriomin** [comment]
I'm positive this is not a bug or an unexpected behavior. People often don't know how to spell the things they search for. So those results are not *incorrect*.

A filter might be a good idea though.

**Comment by teod0r** [comment]
Filter? Optional checkbox in settings? Sounds good

**Comment by teod0r** [comment]
And, maybe, to have ability to select where to search in name or in description or in both

**Comment by yeriomin** [comment]
I've played with the search and apps which contain search query in their name are always first in the list. So implementing this will just give you the same app list, but shorter, so I don't see the point.

Please provide a search query which gives apps not containing query earlier than apps which do.

**Comment by teod0r** [comment]
search query "I2P"

**Comment by yeriomin** [comment]
"I2P" results don't contain i2p at all. There are 11 results. They are most relevant. So there is no point in filtering out those, because they are not hiding any more relevant results.

There would be a reason to filter out results which do not contain "I2P" if, for example, they went like this:

1. Orfox
2. Orbot
3. I2P client

Nothing like this is happening. The most relevant results are first.

The fact that [net.i2p.android](https://play.google.com/store/apps/details?id=net.i2p.android&hl=en) is not in the list is not something I can fix. Play Store says it is incompatible with the devices I have (api 10, api 22, api 25). You probably don't see it for the same reason.

**Comment by teod0r** [comment]
You are wrong. "Dee Browser" does contain "I2P" in description!

**Comment by yeriomin** [comment]
Description is not available in the search request result, only in details request result.

**Comment by teod0r** [comment]
Всмысле? Ищет только по названию? Но в другом issue где я просил сделать поиск в описании, ты писал, что по описанию тоже ищет. Я кстати имел ввиду не поиск по описанию, а поиск внутри описания, ты меня неправильно понял. Загляни в то issue.

**Comment by yeriomin** [comment]
"This is either happening already, or will never be." Либо уже ищет, либо не будет искать никогда. Нет, тут не написано, что "по описанию тоже ищет".

"Description is not available in the search request result, only in details request result." В ответе на поисковый запрос нет описаний, только в ответе на запрос подробностей о приложении. Это значит, что при поиске отфильтровывать по описанию нет возможности. По названию отфильтровывать бессмысленно по тем причинам, которые я в прошлых сообщениях описал.

**Comment by teod0r** [comment]
Тогда поисковый запрос "torrent". В 19-ом результате Transdrone в названии нет "torrent", а в последующих -- есть. Как ты не поймёшь?

**Comment by yeriomin** [comment]
На 19(!) позиции абсолютно релевантный запросу результат. Извини, это не проблема. Не неполадка. Так сделано специально. Это не стоит менять. Ты один, а остальные пользователи (например, я) будут ожидать такого поведения поиска как сейчас.

**Comment by teod0r** [comment]
Какой же он релевантный, если в названии нет "torrent"? Сам просил дать тебе запрос, который не содержит слово, раньше чем результаты, которые содержат. Так трудно добавить в настройки отключаемый фильтр?

**Comment by yeriomin** [comment]
Потому что первое приложение поставили в 10 раз больше человек. Почитай [определение релевантности](https://ru.wikipedia.org/wiki/%D0%A0%D0%B5%D0%BB%D0%B5%D0%B2%D0%B0%D0%BD%D1%82%D0%BD%D0%BE%D1%81%D1%82%D1%8C_(%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B8%D1%81%D0%BA)). С поиском под-строки оно не связано.

Реализация твоего предложения повредит Yalp Store. Но ты можешь форкнуть и реализовать сам. Поиск подстроки это не сложно.

**Comment by teod0r** [comment]
почему повредит, если оно галочкой в настойках будет? полюбому найдутся люди кроме меня, кому это нужно

**Comment by teod0r** [comment]
ввожу в поиск "man man" в надежде найти программу с таким названием, мало того что её нету первой по списку, так с 3-его по 7-ой результаты -- вообще полный бред. где логика? ты и дальше будешь утверждать что гугл правильно ищет?

**Comment by yeriomin** [comment]
"ты и дальше будешь утверждать что гугл правильно ищет?" Да.
Даже если бы гугл искал неправильно, исключение результатов из поиска не сделает выдачу "правильнее". Ещё раз обращаю внимание, что поиск в гугле - НЕ поиск подстроки.

**Comment by teod0r** [comment]
что значит не поиск подстроки? ищет не совпадения слов?
