### ISSUE TITLE
Can't download anything anymore.

### ISSUE THREAD

**Issue by tsjnachos117** [yeriomin/YalpStore#351]
That title much says it all. It doesn't matter if I use a real account or a take Yalp account. I've tried using this app on a Samsung Galaxy s6 with the stock Android 5.1 system, and a Samsung Galaxy Tab 2.0 with LineageOS 13 (Android 6.0), and both give me the same issue.

Here's what happens: I browse the store and attempt to download something. (It doesn't matter if I'm installing updates or downloading a new app.) When I click the download button, the download icon appears in the notification area. However, the download speed is always stuck at 0k/s. Here are no error messages, the download just hangs indefinitely. 

I've tried logging or and loving back in, enabling delta updates, disabling delta updates, uninstalling/reinstalling the app, and everything else I could think of. Both of my decides are running Yalp 0.32, which I installed from F-Droid.

**Comment by tsjnachos117** [comment]
Update: looks like it's working on my Galaxy s6 just fine. I just wish I could make it work on my Tab 2.0.

**Comment by yeriomin** [comment]
You can force Yalp to use the fallback download manager like this: Settings -> Apps -> Show system -> Download Manager -> Disable.

If you send me a bug report through Yalp Store main menu, I might be able to detect your situation automatically in the next version. Please mark your bug report with your username or this issue number.

**Comment by tsjnachos117** [comment]
I just noticed that I can't download anything with my webview-based browser (Lightning), which also uses Download Manager (same issue). I am using a daily build of LineageOS (since that's all they have), so I guess it's an OS bug.

On that note, disabling Download Manager as suggested didn't quite solve the issue. I was able to download a handful of updates, but according to my tablet, every downloaded package "appears to be corrupt." Once again, toggling the delta updates option doesn't appear to have helped (I made sure to delete the apks before toggling the option, to make sure the updates were re-downloaded). I'll be filing a separate bug report through the menu as suggested, so stay tuned for that.

In any case, thanks for you reply, and more importantly, thanks for this awesome program. It truly beats the bloated Google software.

**Comment by tsjnachos117** [comment]
Hmm... those "corrupt" apks can be installed after all. I just have to copy them to my computer, and then install them with adb, using this commandline: `adb install -r [package.apk]`. Interesting how they can't be installed via Yalp or my file browser. I guess it must be another OS bug. That future bug report I mentioned doesn't seem necessary anymore, so I guess I'll have to start bugging the LineageOS devs instead.

**Comment by yeriomin** [comment]
If you are curious, you can get a specific reason why the apk is "corrupt" - android package installer (which Yalp uses unless you choose the root installation option) logs a message for each installation attempt.

Don't hesitate to open a new issue if you find out it can be fixed in Yalp Store.
