### ISSUE TITLE
Cannot launch Yalp Store on Android 2.1

### ISSUE THREAD

**Issue by nmyshkin** [yeriomin/YalpStore#352]
Something funky with download/installation for Nook Simple Touch, Android 2.1. The last version to install/function is 0.28. Version 0.29 (from GitHub) gives package parsing error on install attempt. Versions 0.30-0.31 give Chinese (?) characters rather than app name, install but do not run. Same result from packages at F-Droid. Version 0.32 from F-Droid installs but will not run.

**Comment by yeriomin** [comment]
Apparently, new build-tools (specifically aapt2) generate apks which are unusable on old androids.
