### ISSUE TITLE
Additional mock device request

### ISSUE THREAD

**Issue by jnrfalcon** [yeriomin/YalpStore#355]
Would you add mock devices for any Sony Bravia Android TV (with current android 7.0 official build)? Amazon video is only available with Sony TV and Shield TV, Sony version may be more down-to-earth while Shield TV version is designed for more powerful Tegra chips. I can find download for Shield version but it stutters a lot on MiBox. I'm trying to see if Sony version is better.

**Comment by yeriomin** [comment]
Unfortunately, I don't have that device definition. Maybe someone who has this device will send me a bug report...

**Comment by yeriomin** [comment]
Someone **has** submitted this device definition. That was fast!

Put the `.properties` file from this archive into your Yalp Store download directory and it will appear in the device list. I will add it to the library later too. Adding all the devices would make the apk very big, so I add only the most useful ones. See all devices [here](https://github.com/yeriomin/play-store-api/tree/alldevices/src/main/resources).

[device-BRAVIA_ATV2.zip](https://github.com/yeriomin/YalpStore/files/1583824/device-BRAVIA_ATV2.zip)
