### ISSUE TITLE
[Feature Request] Play Store like list of Apps

### ISSUE THREAD

**Issue by jojo313** [yeriomin/YalpStore#356]
Hey, thx for your work on this great app.
I think it could look a lot better and clear, if each item would be smaller, thus having more items on the screen at once. This looks kind of cheap and the size doesn't really make any sense. Cherry on top would be an update button next to each app. Maybe make a "sort apps" button, where you can choose between the current view, the smaller view, and maybe a 2 colon view.
Thanks

**Comment by tomasz1986** [comment]
I would argue that the PlayStore's list is a little too small. I would prefer something in between that and the current YalpStore, or just a setting to choose your preferred icon size.

**Comment by TomJansen** [comment]
In my opinion, the icons in the list are a bit too big.

**Comment by jojo313** [comment]
@tomasz1986 yeah just make a "big" "medium" "small"

**Comment by TomJansen** [comment]
Or just that you can set the icon px?

**Comment by jojo313** [comment]
@tomasz1986 Just the px size of each "tab". idk the px of the tab without considering the icon, that could limit it right? But if the minimum px for the text is low, that could work. I'd then just call it "tab size" for simplicity.

**Comment by yeriomin** [comment]
I'm glad you find Yalp Store useful.

I know Yalp Store could look better, but it is not a priority. As the readme states, the priority is size and backward compatibility.

>This looks kind of cheap

That's a matter of taste, not an objective characteristic.

>Just the px size

Setting any sizes in px is against android guidelines.

>an update button next to each app

See #281.
