### ISSUE TITLE
Сетевая ошибка. Попробуйте позднее.

### ISSUE THREAD

**Issue by Baltazar500** [yeriomin/YalpStore#357]
В маркете по неизвестным причинам отвалилась закачка приложений - загрузчик входит в loop ничего на загружая и через пару-тройку минут безостановочного перезапуска закачки выдаёт "не удалось загрузить приложение xxx из-за ошибки 495". 

Думал обойду эту проблему заюзав YalpStore, да не тут то было - при закачке приложений загрузчик так же куролесит по кругу ничего не качая, а в конце YalpStore выдаёт "Сетевая ошибка. Попробуйте позднее."

Андроид 4.2.2, файерволл отключён (рут есть), данные маркета, сервисов и встроенного менеджера загрузок очищал - не помогает. На других устройствах в той же сети приложения маркетом и YalpStore качаются.

**Comment by yeriomin** [comment]
>В маркете по неизвестным причинам отвалилась закачка приложений
>На других устройствах в той же сети приложения маркетом и YalpStore качаются.

Проблема определённо не с Yalp Store, а с вашей сетью. [Вам в поисковик](https://www.google.ru/search?q=http+response+code+495).

**Comment by Baltazar500** [comment]
> На других устройствах в той же сети приложения маркетом и YalpStore качаются. 

Никаких vpn'ов, проксификаторов и прочего редиректящего софта не используется.

Проблема не в сети. А в каком-то общем компоненте, которым пользуются как маркет, так и YalpStore. У YalpStore есть возможность отладки, дабы поглядеть где он "спотыкается" ? В logcat'e видно что идёт цикличный перезапуск закачки как у маркета, так и у YalpStore, но там слишком много мусора, чтобы понять, что к чему.

**Comment by yeriomin** [comment]
Если Yalp не крашился и не выводил сообщений об ошибках, это значит, что он не "спотыкался".

Выдача поисковика полна возможных [ответов](http://techno.bigmir.net/help/1532400-Oshibka-495--kak-ispravit--problemu-na-telefone-s-Android).

В [FAQ](https://github.com/yeriomin/YalpStore#faq) тоже есть:
> You can force Yalp Store to use the fallback download manager like this: Settings -> Apps -> Show system -> Download Manager -> Disable.

> А в каком-то общем компоненте, которым пользуются как маркет, так и YalpStore.

Значит вам [сюда](https://source.android.com/setup/report-bugs). Здесь не форум, где отвечают на любые вопросы. Это репозиторий, а каждая issue (в идеале) - баг Yalp Store или просьба нового функционала в Yalp Store. Ваша проблема не связана с Yalp Store.
