### ISSUE TITLE
Keep getting "incorrect email or password"

### ISSUE THREAD

**Issue by dvarum12** [yeriomin/YalpStore#36]
The title says it all, but is there some way to get more information about what goes wrong, because it is the right email and password?

**Comment by 1337sup3rh4x0r** [comment]
Are you using two factor auth? Then you need an APP password

**Comment by dvarum12** [comment]
no I am not

**Comment by yeriomin** [comment]
I cannot ask for your password, but you could create one more gmail account with a different password and check if it works. If it does, there is an issue with the password somehow. If it doesn't its an issue with Yalp on your device.

Either way, please post the version of Android and version of Yalp you have. If one password works, but the other doesn't, please tell the difference.

**Comment by yeriomin** [comment]
Also, this might be related to #11

**Comment by dvarum12** [comment]
I got it to work, I just had to enable the function "Allow less secure apps".
http://wololo.net/wagic/wp-content/uploads/2015/09/google_allow_less_secure_apps_on.jpg

**Comment by yeriomin** [comment]
Thanks for letting me know.

If I were you, I would create a second account instead of lowering security on your primary account. Yalp might violate Google ToS (see readme).
