### ISSUE TITLE
RFE: Add other reputable updating sources

### ISSUE THREAD

**Issue by TPS** [yeriomin/YalpStore#362]
> _N.B.: I apologize in advance for ignoring the entire issue template, but it seems completely geared toward bugs, while the following is a_ feature request.

Since folks running Yalp Store are likely running @ least 1 other appstore-type app (F-droid), it'd be great to extend YS to support other app update sources, such as F-droid-compatible repos, Amazon Appstore, APKMirror, &c, to manage everything centrally.  _(I especially would appreciate having to _never_ run Amazon Appstore manually, as each update becomes even more cumbersome.)_

**Comment by yeriomin** [comment]
This FR can not be implemented in this form. It is not [SMART](https://en.wikipedia.org/wiki/SMART_criteria). Sorry.

1. Yalp Store is built around **one** application source. Multiple sources would require rework in every part of Yalp Store. It is a huge task.
2. Yalp Store is built around **Google Play Store**. F-droid app is good enough to not need an alternative, IMO. And there is little benefit in an alternative for Amazon as most apps can be found in Play Store.

**Comment by TPS** [comment]
I do understand that perspective, but consider that many app _categories_ banned from Play Store (e.g., commercial adblockers) have found their home on Amazon.  Also, I've _purchased_ many apps from Appstore, so that does influence my request.

Perhaps keep this as a long-term tracking FR?

**Comment by yeriomin** [comment]
@TPS This feature is so big it requires starting a new project. Like I did with [Play Store API](https://github.com/yeriomin/play-store-api/).

> I've purchased many apps from Appstore

I can not even tell you if this is possible to reimplement this. Technically Play and Amazon are quite different.

**Comment by TPS** [comment]
Thanks, _now_ I get it. :bow:

**Comment by Drui7** [comment]
Жаль, что в планах нет поддержки амазона. Не весь список приложений гугла и амазона пересекается. Кроме того yalp не может обновить сам себя, поскольку не может быть размещён в гугле, а от поддержки f-droid (где он есть) тоже отказывается.

**Comment by yeriomin** [comment]
@Drui7 
> Кроме того yalp не может обновить сам себя

Неправда. Если сеть новая версия, она появится в списке обновлений.

> поскольку не может быть размещён в гугле

Не имеет значения. Yalp Store есть на guthub и f-droid.

> а от поддержки f-droid (где он есть) тоже отказывается

Тоже неправда.
