### ISSUE TITLE
Getting "signed with different key" on every app I try to update.

### ISSUE THREAD

**Issue by jrswab** [yeriomin/YalpStore#367]
### Expected behaviour
In the past the Yalp would only show this message when the app was from another source. Which is very helpful.

### Actual behaviour
Now it shows this on very app I chose to update even on the second and third updates.

### Steps to reproduce
I do non have any steps to reproduce this issue. The only thing I did was sign in with my account on a fresh install of Yalp to grab some paid for apps and then went back to the main account.

### Info about your device
One Plus 3T running [LinageOS with microG](https://lineage.microg.org/)

**Comment by yeriomin** [comment]
Did you try the usual clear data/reinstall? What Yalp Store version are you using?

>Now it shows this on very app

When did this "now" start? Maybe when you updated Yalp Store? There hasn't been any changes which could cause this lately...

Cannot reproduce this on my devices.

**Comment by jrswab** [comment]
> Did you try the usual clear data/reinstall?

yes

> What Yalp Store version are you using? 

0.32

> When did this "now" start?

After I changed my OS to Linage with microG

**Comment by yeriomin** [comment]
> After I changed my OS to Linage with microG

It is logical to assume that the problem is with your los build. What build are you running exactly?

I'm running an ordinary los build `lineage-14.1-20171212-nightly-gemini-signed.zip` and do not have this problem. Maybe they will fix it in a week or so.

**Comment by jrswab** [comment]
The build is:
`14.1-2018112-oneplus3`

I'll mess around in the microG settings to see if I can find if the issue is there.

**Comment by jrswab** [comment]
After messing arounding in the settings for microG (believe I just turned it off and on again lol) Yalp seems to be working fine again. Thank for being present <3

**Comment by yeriomin** [comment]
@jrswab I flashed the microg fork and still could not reproduce this. But I found the following issue in lineageos bugtracker: https://jira.lineageos.org/browse/BUGBASH-259. Try asking there if you encounter the problem again.
