### ISSUE TITLE
List apps that are currently black/white listed

### ISSUE THREAD

**Issue by fletch31337** [yeriomin/YalpStore#369]
I think it would be helpful to display a list of blacklisted/whitelisted apps.

If "Chosen apps are going to be ignored when checking for updates" is selected, then give the ability to list all apps chosen to be ignored.

If "Only the chosen apps will be checked for updates" is selected, then give the ability to list all apps chosen for update checks.

**Comment by yeriomin** [comment]
There is a "Change apps white/black list" option on the preferences screen. It shows you a checkbox list of all installed apps with white/black listed apps checked.
