### ISSUE TITLE
Signing commits on github

### ISSUE THREAD

**Issue by techge** [yeriomin/YalpStore#371]
Hi,

would you mind signing your commits with your PGP key, at least for releases. User who download from Github can be (quite) sure that you actually did this commit and not some nasty person who owns your credentials. (https://stackoverflow.com/questions/39708082/what-pr%e2%b2%9fblem-or-threat-does-commit-signing-solve#39708317)

Kind regards
techge

**Comment by HorlogeSkynet** [comment]
👍 for releases only (http://git.661346.n2.nabble.com/GPG-signing-for-git-commit-tp2582986p2583316.html)

Thanks for the good work 👋

**Comment by yeriomin** [comment]
@techge @HorlogeSkynet Can do.
