### ISSUE TITLE
Search results are practically invisible when using the white theme after 0.34 update

### ISSUE THREAD

**Issue by Biskvit** [yeriomin/YalpStore#372]
After updating to the latest version, when searching for an app, the search results when using the white (default) theme are now also written with white letters.  With the default theme being white, the results just aren't visible. There **are** results (i.e. the actual searching works just fine, and nothing is broken there). The results can be (just slightly) seen when you press and hold them.

![screenshot_20180119-095855](https://user-images.githubusercontent.com/35448657/35140740-0ba36d74-fd01-11e7-9836-5bf3c2275546.png)

### Steps to reproduce
1. Open the app when using the stock (white) theme
2. Search for something

### Info about your device
Sony Xperia L, Android 7.1.2. (microG+LineageOS fork)

**edit**: Another, but still related minor issue: the magnifying glass icon also doesn't adapt when changing themes. It looks just fine now with the white theme, but when you switch to the dark (or black) theme, the icon stays black and it looks rather weird.

**Comment by yeriomin** [comment]
By default Yalp Store does not override the default UI theme and does not do any styling at all. Also, no non-standard components/dependencies are used. Did this specifically to make Yalp Store look like the other apps on each device. This should work well unless he ROM defaults are off...

There is a workaround: you can force the UI theme in Yalp Store settings. Any theme except the default will do.

This does not happen on non-lineage ROMs or on old lineage ROMs. Seems to be a lineage issue... I wonder if *they* would consider it a bug. I wouldn't want to make a special workaround for lineage. I'll try to create an issue in their bugrtacker.
