### ISSUE TITLE
Corrupt download prevents installation of app

### ISSUE THREAD

**Issue by sheddup** [yeriomin/YalpStore#374]
### Expected behaviour
Allow user to re-download app / Auto detect corrupt download

### Actual behaviour
Can't delete downloaded app from Yalp, app download is corrupt so installation can't finish.  
(you can manually delete the app in Downloads folder to fix)

### Steps to reproduce
Disable wifi during app download

### Info about your device
Android 7.0 on Huawei device

**Comment by yeriomin** [comment]
Thanks writing an issue, fix is in master.
