### ISSUE TITLE
Download purchased apps

### ISSUE THREAD

**Issue by Wiredframe** [yeriomin/YalpStore#375]
I really like the idea of YalpStore. Right now I use Raccoon on my PC. With Raccoon it's possible to download paid apps (those that you've actually really purchased of course). That's very handy. 

You might want to get in touch with the dev, he might want to contribute to adding this feature to YalpStore. 

http://raccoon.onyxbits.de/

**Comment by yeriomin** [comment]
I'm glad you find Yalp Store useful. Downloading purchased apps has been implemented almost at the start, see #8.

If you cannot download purchased apps, it is a bug.

**Comment by Wiredframe** [comment]
Thanks for clarification! I must have skipped out on that.

**Comment by 5chdn** [comment]
Nice, I didn't know that. Works well!
