### ISSUE TITLE
Login with own credentials not working

### ISSUE THREAD

**Issue by cryptomilk** [yeriomin/YalpStore#377]
Logging in with own credentials doesn't work:

```
5526 01-26 11:41:22.750  4610  5810 I NativeHttpClientAdapter: Requesting https://android.clients.google.com/auth
5527 01-26 11:41:22.766  1610  1610 I LatinIME: Starting input. Cursor position = 10,10
5528 01-26 11:41:22.927  4610  5810 I NativeHttpClientAdapter: HTTP result code 403
5529 01-26 11:41:22.929  4610  5810 E NativeHttpClientAdapter: IOException java.io.FileNotFoundException https://android.clients.google.com/auth
```

If I look at how the yalp store account logs in, I see it uses: https://android.clients.google.com/checkin

Is it using the wrong URL?

Using 0.43 from fdroid store ...

**Comment by yeriomin** [comment]
Cannot reproduce.

> Is it using the wrong URL?

No, checkin request is a part of the login process. Your device info is submitted in the checkin request.

`https://android.clients.google.com/auth` answers with `403`, which in most cases means the password is incorrect. Maybe your password is unusually long or has some unprintable character? Do you have any special security measures enabled in your google account?

**Comment by cryptomilk** [comment]
Ok thanks. Magically it works now. So sorry for the noise and thanks for the explanation.
