### ISSUE TITLE
 [Feature request] organised permissions list

### ISSUE THREAD

**Issue by moshpirit** [yeriomin/YalpStore#379]
On F-droid when we want to install any app, we can see the required permissions are organized into some categories (storage, Android system, corporal sensors, Camera, SMS, Phone, Location, Contacts, Calendar, ...) and permissions are explained: "Enable bluetooth" and "sync with bluetooth devices" instead of "android.permission.BLUETOOTH" and "android.permission.BLUETOOTH_ADMIN". I find this **incredibly** helpful and intuitive. 

Thank you so much for your hard work!!

**Comment by yeriomin** [comment]
Done. I tried to copy the f-droid look mostly.

Glad you find Yalp Store useful.

**Comment by moshpirit** [comment]
Thank you so much!! :)
