### ISSUE TITLE
Похожие & приложения конкретного разработчика & вам также может понравится

### ISSUE THREAD

**Issue by avently** [yeriomin/YalpStore#38]
Думаю, если еще добавить вот этот функционал, то гугл плэй удалю за ненадобностью: 
- кликабельную ссылку, ведущую на другие приложения разработчика программы, которая в данный момент отображается. Или, быть может, блок иконок программ разработчика. 
- похожие приложения на текущее. В маркете есть такой блок. Наверное, оттуда больше всего скачиваю.
- в маркете есть блок "вам также могут понравиться". Не знаю, в чем отличие от похожих прог, но тоже удобная штука. 

P.s. немного не в тему. Убрал блок скриншотов наверх, выше описания, и сделал его автоматически развернутым. Также убрал элемент, при нажатии на который скрывается и показывается этот блок. Выглядит круто. Пробовал?

**Comment by yeriomin** [comment]
* Сделаю.
* Можно. Но именно такие вещи меня в маркете и бесят. Слишком много хлама.
* см пункт 2.

P.s. - Ещё одна вещь, которая захламляет экран. В маркете всегда прокручиваю мимо к тексту. Я сдвинул их не от балды.

Вобщем подумаю куда можно это впихнуть, не испортив UI (который мне пока нравится ^^).

**Comment by avently** [comment]
2) ну тогда можно скрываемым сделать этот блок через настройки...
Не знаю, видимо, тебе больше текстовая информация кажется ценной. Я смотрю на текст в 1 из 10 программ. Остальное выбираю по скринам. Выбор почти всегда огромен (а значит дизайн выходит на первое место) или наоборот - есть единственная в своем роде прога. Тогда и описание ни к чему:)

**Comment by teod0r** [comment]
Какого ещё функционала нехватает, что есть в гугл плэй? Там есть возможность устанавливать предыдущие версии програм и даты отзывов? Я думаю, надо реализовать все возможности что есть

**Comment by yeriomin** [comment]
"Какого ещё функционала нехватает, что есть в гугл плэй?" цели копировать Google Play у меня нет, см. README.

**Comment by teod0r** [comment]
А я и не говорил, что надо копировать гугл плэй, я говорил, что надо реализовать все возможности. Если в гугл плэе есть возможность устанавливать предыдущие версии программ, это надо реализовать обязательно, это очень важно. Часто последние версии программ содержат ошибки, из-за которых их нельзя использовать. У меня таких программ 4 в F-Droid'е и 4 в Yalp Store. Приходится делать локальное хранилище апков для всех установленных программ

**Comment by yeriomin** [comment]
"надо реализовать все возможности" [не согласен](https://en.wikipedia.org/wiki/Unix_philosophy).
"возможность устанавливать предыдущие версии программ" такой возможности нет. apk-свалки такие как apkmirrorfull, apkpure просто хранят скачанное ими раньше.

**Comment by ranit8** [comment]
These lists no longer display on my device since v0.29, unless I fake my device info.
My device is Moto G XT1078, Android 6.0.1.
