### ISSUE TITLE
Playstore like wishlist integration

### ISSUE THREAD

**Issue by killoid** [yeriomin/YalpStore#381]
it would be really handy to have this feature on yalpstore. i often come across some apps that i wanna try later so this will help a lot. also id it shows the wishlist of your own account, that would be great!

**Comment by Rikk** [comment]
Personally, I would like a wishlist (list of favorite/bookmarked apps) restricted to YalpStore app only (without touching accounts information), that could be accessed with Yalp fake accounts too.
Cc @yeriomin
