### ISSUE TITLE
[Feature request] Add Option to ignore updates from apps installed via F-Droid 

### ISSUE THREAD

**Issue by hansWURSCHT10000** [yeriomin/YalpStore#385]
It would be nice if the updater automatically filters apps which have been installed via F-Droid, because usually the same update will arrive in F-Droid after a few days.
I always prefer the F-Droid variant of an app if it is available in both stores because I trust F-Droid more. 
Technically YalpStore could check if the installed app is signed by F-Droid.
The F-Droid App does the same and only displays updates from Apps which are signed by F-Droid.

**Comment by 2SI3NX** [comment]
Yes but F-Droid is NOT always reliable, by that i mean.. some apps in F-Droid - the developers of those apps dont always push through the update on F-Droid but they push it through on google play.
for example. KDE-Connect was last updated on F-Droid in August 2017, yet there is a recent update on playstore, so the developer has completely ignored pushing updates to F-Droid,
in which case completely ignoring an F-Droid app in Yalp will be useless.

Thats why i have explained here: https://github.com/yeriomin/YalpStore/issues/336 that having a multi-select option is the best choice for any user to keep tabs about his/her updates whether they are too late on F-Droid or completely ignored.

However thats not to say that completely ignoring F-Droid should not be included (for some users)

**Comment by yeriomin** [comment]
@hansWURSCHT10000 @2SI3NX This has been discussed many times. #343, #69, #39...

This won't be done because:
* It is impossible to reliably implement.
* F-Droid apps (most likely) won't be updated anyway because of a signature mismatch.
* There is an autowhitelist option and many other ways to selectively update apps.
