### ISSUE TITLE
Suggestion: enable downloading directly to the SD Card

### ISSUE THREAD

**Issue by Rikk** [yeriomin/YalpStore#386]
I see that the Download Location input in Settings apply a path relative to the internal storage (/storage/emulated/0 or /sdcard). It would be helpful to be able to choose a path in the SD card (/storage/extSdCard). YalpStore is great for avoiding Play Store limitations to install apps when the free space on internal storage is low, but the need to save in the internal storage can be troublesome in such situation.

Is this on plans already?

Thanks for this nice store app.

**Comment by yeriomin** [comment]
Actually, the path is relative to [external](https://developer.android.com/guide/topics/data/data-storage.html#filesExternal) storage. There is usually no shortage of space on external storage. On old devices it is usually an sd card. On new devices it is usually a multigigabyte "external" storage emulated by internal storage. So sorry, no, this isn't planned.

**Comment by Rikk** [comment]
Then, there is a problem. Because Yalp only allows me to save in "internal storage", which Android wrongly name "sdcard", and which is mounted at /emulated/0 (main location) , /emulated/legacy , /sdcard and /data/media/0
The "external storage" (actually a removable SD Card) is mounted at /storage/extSdCard (main) and /mnt/media_rw/extSdCard , and maybe somewhere else I don't know.

**Comment by Rikk** [comment]
@yeriomin Would it be possible for you to implement a button to Share the direct download link? It would be possible to download to ext-SD using another app.

**Comment by yeriomin** [comment]
@Rikk Maybe. Sometimes the link is not enough, a special cookie is required too. It would depend on the device (as far as I know).

...But is it important enough to add another menu item which requires manual interaction with a component which has no defined package name and is most likely not installed? I can put it as the long press action on the download button.

**Comment by Rikk** [comment]
Frequently downloading apks to internal disk and then moving to SD card means a great degradation in the long-term of the phone medium which is not replaceable as is an external SD card. Any option to download directly to the SD card would be very appreciated by me.

**Comment by Rikk** [comment]
Frequently downloading apks to internal disk and then moving to SD card means a great degradation in the long-term of the phone medium which is not replaceable as is an external SD card. Any option to download directly to the SD card would be very appreciated by me.
I would like to test if other app can retrieve these files and if it requires or not a cookie. I remember some time ago I sniffered a link from Yalp and it worked properly for a short period of time in a browser.

**Comment by Rikk** [comment]
Many thanks for this addition, working ok. Just a minor detail: after the long-press, the toast message (copied to clipboard) takes some seconds to appear, giving the impression the user needs to hold pressed for all this time.

Btw, would it be hard for you to make this change: instead of copying to clipboard, display a list of apps that can handle the link? (like a typical Share button)

**Comment by yeriomin** [comment]
> instead of copying to clipboard, display a list of apps that can handle the link?

Ok. Makes sense.

**Comment by Rikk** [comment]
Would it be good if you send a test build so I can see if it works ok before a release?

**Comment by yeriomin** [comment]
@Rikk Its not device dependent, so there should be no need for that.

**Comment by Rikk** [comment]
There appeared situations where I want copy the URL or to send it to a file manager. The intent ACTION_VIEW seems to display only browsers. I know there is an intent that shows all apps that can handle URLs. I think it is the ACTION_SEND. Do you agree making this change?

**Comment by Rikk** [comment]
No, it shows only browsers. You are displaying only browsers, I wanted to say the same as a browser's Share function, which my research indicates is the ACTION_SEND, which displays both browsers and apps that can handle links.
MiXplorer Copy To, for example, is not a browser but is a handler of URLs.

**Comment by Rikk** [comment]
1. File managers can download files from Internet and they appear in Send, not View.
2. MiXplorer is the best file manager, (except some powerful things only Total Commander can do), and is very well coded, not even as hacky as YalpStore.
3. I would like a lot to test a build with this change, but if you refuse to do the change, well, good luck. Really, I hate arguing with obstinate developers.

**Comment by yeriomin** [comment]
@Rikk 
> File managers can download files from Internet and they appear in Send, not View.

Ad-hoc solutions are never a good idea. The docs state that ACTION_SEND is for raw strings. I'm sure there are apps which use view, send, telepathy, astral projection or whatever to exchange data, it does not make them good.

> MiXplorer is the best file manager

Opinion

> and is very well coded

It is not open-source, so it is impossible to know.

> not even as hacky as YalpStore

What's hacky about Yalp Store? I mean besides the fact that it is based on reverse engineering of an undocumented API?

> and the dev takes care about users' desires.

I'm not running a business. I'm not implementing desires/requests. I'm implementing good suggestions. My aim is making *good* software, not *popular* software.

> but if you refuse to do the change, well, good luck.

Why are you being so passive-aggressive about a *hidden* feature which most likely only you use? I'm  not here to implement your every whim. Your previous suggestion was mostly invisible to other users, that's why it was implemented. Now you are suggesting an n-th change (which will actually make it less intuitive) to make it work with a specific non-standard app.

**Comment by Rikk** [comment]
I'm just wanting **more options** to where send the url and process it.
I imagine it won't be any less intuitive, as all programs have their Share button. How have you conceived this idea?
So, if I want to **test/try** a change to a suggestion I made -- and maybe that only me is using -- do I need my own fork? No, I wouldn't be happy to learn and install an entire Android-sdk environment to compile just this.

**Comment by Rikk** [comment]
😒
I meant is is a matter of seconds for you to compile a test build while for me it would take a long time.

In programming, I wouldn't tell with certainty such small modifications are bad without first taking a look on how it works.

Perhaps, your boss are the users of your app.
