### ISSUE TITLE
All apps gets listed when first opening Yalp store - instead of latest updates

### ISSUE THREAD

**Issue by 2SI3NX** [yeriomin/YalpStore#387]
As the headline states,
The issue is that when first opening Yalp Store, it shows the list of ALL apps and not apps that actually need updating.
A proper refresh of all latest updates should be shown on first open.

Version: 0.35

**Comment by yeriomin** [comment]
This is intended behavior.

Update check takes time and requires a login. Some people don't want that. Update list is one tap away and that lets people do other things like search or go to settings.
