### ISSUE TITLE
Swipe Refresh for latest Updates

### ISSUE THREAD

**Issue by 2SI3NX** [yeriomin/YalpStore#388]
A faster method for retrieving latest updates would conveniently be to swipe down and get a list of latest updates, instead of Menu > Updates

Version: 0.35

**Comment by yeriomin** [comment]
[Swipe down means "refresh"](https://material.io/guidelines/patterns/swipe-to-refresh.html). Swiping to go to updates from the installed apps list would not make sense. Also, both a swipe and a tapping a button take one touch to the screen. Also, a button is visible unlike a gesture.
