### ISSUE TITLE
Update system apps on stock android, without a google account?

### ISSUE THREAD

**Issue by vvug** [yeriomin/YalpStore#389]
One question I can't find answered in the FAQ: if I install YALP Store on a phone running stock android, with the google apps installed, but without a google account set up, will I be able to update the system apps such as WebView?

**Comment by Locash** [comment]
Yalp store uses TWO ways to login so you can download apps.
 #1 Your own account {only use this way to get your paid apps downloaded} 
 #2 A generic google account
It does not matter what one you use to check if you can update system apps. It goes off the apps currently on the phone when requesting a update check.

**Comment by yeriomin** [comment]
> One question I can't find answered in the FAQ

This Q not FA. ;)

It does not matter whether gapps are installed or not. System app updates are exactly the same as user app updates, the system partition is not altered. So yes, you will be able to update the system apps .
