### ISSUE TITLE
detect froid apps

### ISSUE THREAD

**Issue by treakiandroid** [yeriomin/YalpStore#39]
hi and thanks alot for your grate work with this app, now i can finally install commercial apps without any google software with ease. but there are two things I would like:

cache updatable app screen and only reload on user request (faster load of the screen and prohibit send to the store all the time)

detect fdroid apps and don't show them or dont update them using yalp like  ApkTrack dose.

thanks a lot in advance

**Comment by yeriomin** [comment]
It is possible to detect app installations, but there is no way to know if the app is an f-droid app. ApkTrack tries to find every app on every update source available, which is a long and imprecise process.

You can add f-droid apps to update blacklist if they annoy you.
