### ISSUE TITLE
Entering preferences screen causes a crash on Amazon devices

### ISSUE THREAD

**Issue by suepryugo** [yeriomin/YalpStore#392]
### Expected behaviour
Settings opens

### Actual behaviour
Bug report opens

### Steps to reproduce
1.　Press the menu button
2.　Select settings
3.　Bug report opens

### Info about your device
firetv stick 1

**Comment by yeriomin** [comment]
Are you sure you are using the latest version? Issue #363 which is quite similar to yours, was fixed in version 0.34.

**Comment by suepryugo** [comment]
Yes. I am using version 0.35.

**Comment by yeriomin** [comment]
Please try version 0.37.

**Comment by suepryugo** [comment]
I tried version 0.37, but a bug report has opened.

**Comment by yeriomin** [comment]
@suepryugo Looks like its the same story as the #363. This problem is limited to Amazon devices. I don't have one and cannot reproduce or test this, unfortunately.

We will have to wait for someone who has time and an Amazon device to help us.

**Comment by yeriomin** [comment]
This bug is theme-related. It happens on Amazon devices when there is no theme set in Yalp Store (this is default). Forcing any theme seemed to have helped in #363. Apparently, not entirely.

**Comment by sherpya** [comment]
You missed a return, I've made a PR, also please look at my screenshot with dark theme using store+

**Comment by yeriomin** [comment]
@sherpya Thanks!
