### ISSUE TITLE
The ability to omit Ad free\paid apps from search results. 

### ISSUE THREAD

**Issue by Locash** [yeriomin/YalpStore#393]
The ability to omit paid apps and/or app with ads from search results, was removed starting at ver. 34.
I'm sure this was intended but It is one of the top reasons what's great about YALP and should be included in recent versions.

**Comment by zelleb** [comment]
Search for something and tap that signal bar button, uncheck what you don't want to see.

**Comment by Locash** [comment]
I asked that question just as I got off the short bus.😁 Thank you @zelleb
