### ISSUE TITLE
Indicate whether an app is bought or not

### ISSUE THREAD

**Issue by rugk** [yeriomin/YalpStore#396]
### Expected behaviour
When an app is not bought:
* the money may be highlighted
* the "Download" button may instead be labeled "Buy".
* also, when clicking on it, it may redirect to Google Play. (does not do so in my tests, think this was the behavior in previous versions)

### Actual behaviour
In my test I could click on "Download", but it more or less did not start the download. Just canceled it without any feedback.

### Steps to reproduce
1. Go to a app you have to pay for.

### Info about your device
LineageOS 14.1/Android 7

**Comment by yeriomin** [comment]
This can probably be done.

I don't have paid apps on any of my accounts. I can build you a modified apk which would most likely detect if the app is bought. Would you be willing to test it?

**Comment by rugk** [comment]
Yeah, I can test it.

**Comment by rugk** [comment]
Yeah, I can test it.

**Comment by rugk** [comment]
Yeah, I can test it.

**Comment by rugk** [comment]
Yeah, I can test it.

**Comment by rugk** [comment]
Yeah, I can test it.

**Comment by rugk** [comment]
Yeah, I can test it.

**Comment by rugk** [comment]
Cannot install it as I've installed the official version from f-Droid. Can you provide a build with a different package name, so I can install it side by side?

**Comment by yeriomin** [comment]
Unfortunately, this has to be rolled back. The implementation I made is not reliable enough. Most likely, Play Store app operates on an assumption that it either buys all the apps itself, or gets push notifications when the apps are bought. Yalp Store can not do that. Checking if the app is purchased by attempting a download every time is not a good solution.
