### ISSUE TITLE
ifruit apps not downloaded completely

### ISSUE THREAD

**Issue by treakiandroid** [yeriomin/YalpStore#398]
### Before creating an issue
1. Make sure you are running the latest version of Yalp Store. Check [here](https://f-droid.org/packages/com.github.yeriomin.yalpstore/).
Yea it was the latest from fdroid
2. Search for similar issues [here](https://github.com/yeriomin/YalpStore/issues?q=is%3Aissue+is%3Aclosed).

3. Send developer a bug report using Yalp's built-in crash tool. Or go to Yalp's About page and tap on the developer's email. This creates a email with your device info and recent logs attached. 
There was no crash
4. Number 3 is important. Please do it. It helps a lot.
5. Use the following template to write the text of your issue.

### Expected behaviour
Tell us what should happen
Applist of ifruit apps should come up
### Actual behaviour
Tell us what happens instead
See screenshot, lookes like sth is missing
### Steps to reproduce
1. Open https://play.google.com/store/apps/details?id=com.rockstargames.ifruit in yalp
2. Press download
3. Press install and follow android installer
4. Press open
5. Get the screenschotted error, try everything from restarting app, reinstalling, rebooting, reinstalling again.
6. Nothing working, i guess yalp misses some pice of data to be extracted/installed after install
7.  Give up, uninstall anot working ifruit apps again

### Info about your device
Device model, android falvour

Lenovo yoga tab ptoo (see third shot)

Thank s for any help in advancet

![screenshot_2018-02-15-03-04-57-199](https://user-images.githubusercontent.com/7935237/36291247-1a9bf614-12ca-11e8-8ba8-f42088d1fc2b.jpeg)

![screenshot_2018-02-15-03-02-34-926](https://user-images.githubusercontent.com/7935237/36291215-ede0bccc-12c9-11e8-9f05-fc0ccb3df468.jpeg)

![screenshot_2018-02-16-03-30-44-667](https://user-images.githubusercontent.com/7935237/36291219-f6a16956-12c9-11e8-83cc-4ddc043449d7.jpeg)

**Comment by yeriomin** [comment]
Hello. The only thing Yalp Store does is downloading apks. Once the apk is downloaded, Yalp Store's job is over. Since android OS successfully installed it, the downloaded file was not corrupt.

I downloaded that app and successfully installed and ran it too. Do you have gapps installed? Your app might require gapps.
