### ISSUE TITLE
Correct way of installing Yalp Store for background updates? / Yalp Store OTA is no longer a system app after OS upgrade

### ISSUE THREAD

**Issue by bugreport0** [yeriomin/YalpStore#399]
### Before creating an issue
1. Make sure you are running the latest version of Yalp Store. Check [here](https://f-droid.org/packages/com.github.yeriomin.yalpstore/).
2. Search for similar issues [here](https://github.com/yeriomin/YalpStore/issues?q=is%3Aissue+is%3Aclosed).
3. Send developer a bug report using Yalp's built-in crash tool. Or go to Yalp's About page and tap on the developer's email. This creates a email with your device info and recent logs attached. 
4. Number 3 is important. Please do it. It helps a lot.
5. Use the following template to write the text of your issue.

### Issue
Hello Friends, I have installed F-Droid with privileged extension. It works as expected, updates apps in background and after OS update it keeps working just fine. Now I am wondering what is the correct way of installing Yalp Store to be able to upgrade apps in background? As I understand (I dont have root) if I want to do this, I have to install OTA package. If I install Yalp store via F-Droid, I wont be able to upgrade (Yalp) apps in background or would I?

And here comes my observation - every time I install new OS update, Yalp store is no longer an system app and background updates stop working, I have to "reflash" it again. I think some apps (such as F-Droid with privileged extension) can "survive" OS updates. As far as I know it uses some script located in "addon.d" folder. Please may I ask for a feature request to have this function present also in Yalp Store OTA? To make it able to "survive" OS updates? Or should I install Yalp store from F-Droid and it will work also with background updates? Thank you very much for any answer and help.

Have a nice day

### Expected behaviour
Yalp Store OTA should remain system app after OS upgrade

### Actual behaviour
Yalp Store OTA is no longer a system app after OS upgrade

### Steps to reproduce
1. Install Yalp Store OTA as system app
2. Upgrade OS
3. Yalp Store is no longer a system app

### Info about your device
Lineage OS

**Comment by yeriomin** [comment]
>if I want to do this, I have to install OTA package

Yes.

>If I install Yalp store via F-Droid, I wont be able to upgrade (Yalp) apps in background or would I?

You won't.

>As far as I know it uses some script located in "addon.d" folder.

Yalp Store has it. Unfortunately, at some point a problem was introduced, which was recently fixed by #394. OTA zips are not signed, unlike apks so, I included the fix into the previous build [here](https://github.com/yeriomin/YalpStore/releases/tag/0.35).

Flash it and it *should* survive OTA updates. If not, write again.

**Comment by bugreport0** [comment]
@yeriomin thank you very much, now it is working without flaw :)
