### ISSUE TITLE
Back

### ISSUE THREAD

**Issue by teod0r** [yeriomin/YalpStore#4]
After I select an app from update list and after I download it when I press BACK the app closes instead of going back.
Also the app not always refreshes list of updates. It shows apps which I've already updated, so I have to press "Updates" 2 times

**Comment by teod0r** [comment]
Actualy there is another problem. After I update an app, after I press "Updates" to go back, when I select an app next to the app that I've just updated it does not opens an app that I selected but opens the app that I've updated!!!

**Comment by teod0r** [comment]
Also if I install an app, then uninstall the program closes instead of BACK

**Comment by yeriomin** [comment]
Fixed in master, will be in v0.3.

**Comment by teod0r** [comment]
NO! It still dos not work in 0.3. I opend an app from search list. I made "BACK" gesture and YalpnStore closed  instead of going back!!! After restarting the program it opens that previous app instead of update list!!!

**Comment by yeriomin** [comment]
Cannot reproduce this. Please provide info on your device and android flavor you are using. Also, v0.4 is out on f-droid. If possible, please provide a logcat.

**Comment by teod0r** [comment]
My device is samsung galaxy tab 4 10.1 with cyanogenmod based on android 4.4.4. Tried 0.4 -- the same problem. I open the app, press SEARCH, enter "torrent" (for example), select "flud" (problem, probably, not with all apps), press DOWNLOAD, switch to another window, then back to Yalp Store, then press BACK HW button and Yalp Store closes. After next run the program starts with previous app opened. I have logcat, how can I send it to you?

**Comment by teod0r** [comment]
Выяснилось что когда открыто приложение из поиска когда переключения на другое приложение, потом обратно на Yalp Store после нажатия BACK программа всегда выходит заместо перехода назад!

**Comment by yeriomin** [comment]
Non-issue.

**Comment by teod0r** [comment]
What do you mean?

**Comment by teod0r** [comment]
В 0.5 проблемы уже нет

**Comment by teod0r** [comment]
если выбрать приложение из поиска, нажать Similar apps, потом на какое-то приложение, потом НАЗАД возвращает не туда!

**Comment by teod0r** [comment]
вобщем даже в 0.6 полностью не исправлено. рано закрыл. если после выбранного из поиска приложения нажать users also install, потом на какое-нибудь приложение, потом НАЗАД, потом ещё раз НАЗАД -- Yalp Store закрывается, а при попытке повторного запуска умирает!!!

**Comment by teod0r** [comment]
Полностью не исправлено!
Если выбрать приложение, потом нажать на хардварную кнопку "предыдущие приложения", потом вернуться в Yalp Store и нажать BACK, программы закрывается, заместо того чтобы перейти назад!

**Comment by teod0r** [comment]
открывай давай баг. всё время при открытии какого-нибудь приложения  после после старта программы, который был сделан после закрытия программы на другом открытом приложении, открывается та программа, которая была открыта до закрытия заместо той, которую выбираешь!!!
ошибка где-то в запоминании предыдущей программы

**Comment by teod0r** [comment]
программа делает двараза "назад"!
1)ищем что-нибудь
2)нажимаем updates
3)выбираем из списка
4)нажимаем BACK
программа делает назад два раза заместо одного
