### ISSUE TITLE
[Question] Privacy concern around app downloads.

### ISSUE THREAD

**Issue by Sk1pp3r** [yeriomin/YalpStore#401]
Right from the starters, this might be a bit of a stupid question, but I'm going to ask it anyway.
In the description it is said that there is no need for a Google account to download free apps, and it is only needed for paid ones.
The question is the following: Does Yalp download free apks by built-in account or by Google account registered with the phone?
For example I have registered an account account@gmail.com and I have a couple of apps that I've bought and installed (those are handled by registered account judging from FAQ). Now I want to install Netflix. Will it be installed with account@gmail.com or the built-in one?
Sorry for the stupid question.

**Comment by yeriomin** [comment]
Yalp Store uses only one account at a time. If you use your own account, both paid and free apps will be downloaded using it. The question is not stupid.

**Comment by Sk1pp3r** [comment]
Maybe this can be converted to a **new feature request**. I mean install only paid apps through registered account, but all the free ones with the built-in one. Seems not hard to implement, but it gives quite some push in the privacy domain

**Comment by yeriomin** [comment]
@Sk1pp3r There was a FR about that already. #205 

> but it gives quite some push in the privacy domain

It does not. Half-privacy does not exist. If you have bought apps, you have given Google a lot of info and hiding free app downloads from them is useless.

**Comment by Sk1pp3r** [comment]
@yeriomin not necessarily...
One thing is giving Google info when you purchase something (which might be as little as 1 to 2 apps, bought with different credit cards with a difference in time span of more than 2 years), and a totally different thing is downloading all if the apps via your account.
Ex.: Most people have at least 20 apps downloaded, and let's say 2 are paid apps.
Now you give them info on usage of 2 apps vs 20... It's not halfway privacy, it's decreasing the amount of info they have on you.

**Comment by generalmanager** [comment]
I was actually about to open a feature request precisely about this when I found this one. My reasoning is the same: that it makes a big difference how much about ones usage habits and attack surface (as every app has real or potential vulns and/or can be used for further recon as is the case with social networks etc.) is revealed.
And if the setting for automated update check intervals were also dependent on the account used, even less information could be retrieved & correlation can't be used to connect the requests for updates of paid and free apps.

@yeriomin what exactly is currently sent during a request (if that's already documented somewhere, I'll gladly search again)? And would you reconsider opening this as a feature request?
