### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by Eloston** [yeriomin/YalpStore#403]
Is it possible to add IPv6 support? My current ISP assigns my device both an IPv4 address and an IPv6 address, but connections to Google only work through IPv6.

I am running LineageOS 14.1.

**Comment by yeriomin** [comment]
Yalp Store does not make the choice between IPv4 and IPv6. Android apps are mostly Java apps. Java supports IPv6 since forever. HttpsURLConnection (which Yalp Store uses) supports whatever Java supports.

The choice between v4 and v6 is done inside the HTTP client, so if you are sure that your infrastructure supports it, the reason for v4 choice is probably the implementation of HttpsURLConnection on your device. There is even an [RFC 6555: Happy Eyeballs](https://tools.ietf.org/html/rfc6555) which deals with this choice which says that IPv6 will be tried first.

So what is happening exactly? Yalp Store fails to connect?

**Comment by Eloston** [comment]
Yes, it fails to connect. For example, when I try to check for updates, it will spin for a while before "No network connection." shows up in the middle of the screen.

I dug around a bit at the network level, and I discovered that Yalp is trying to connect to `ti-in-fXXX.1e100.net` addresses (where XXX is 3 decimal digits), which don't have AAAA records associated with them.

The only document I could find about Google IPv6 domains [is this document](https://github.com/lennylxx/ipv6-hosts/wiki/Google) (with [a subpage specifically about 1e100.net](https://github.com/lennylxx/ipv6-hosts/wiki/1e100.net)). What I don't know yet is why the IPv6 services are not being selected in Yalp, but work in my web browsers (I've tried Fennec F-Droid and Brave Browser).

**Comment by yeriomin** [comment]
The only hardcoded google-related address in Yalp Store is https://android.clients.google.com. Everything else is returned in the api responses. Those ti-in-fXXX.1e100.net addresses are part of some google cdn, most likely. If I had to guess, I'd say they are either for app icon storage or apk storage. Either way, they are returned by the google api.

Your isp might have some blocking rules for google specifically, while supporting ipv6 overall.

Does the original Play Store app work?

**Comment by yeriomin** [comment]
There are many complaints about how Play Store does not work with ipv6 for example: https://productforums.google.com/forum/#!msg/play/SdB39Dy7KCM/k6oHRb5ruY8J

This question is rather old, but seems similar to your problem. Are you in China?

>would it be possible to mimic the hosts file behavior from Yalp

That would be a bad idea. It can easily break more things than it fixes. If your device is not rooted, Yalp can not do it. If your device is rooted, its not Yalp's job to do it - you should add it to the device's global `hosts`.

**Comment by Eloston** [comment]
Yes, my ISP is in China.

> That would be a bad idea. It can easily break more things than it fixes. If your device is not rooted, Yalp can not do it. If your device is rooted, its not Yalp's job to do it - you should add it to the device's global hosts.

I see. This is now diverging from the original topic, but is it possible to add an option for a SOCKS5 proxy (and let the SOCKS server handle DNS requests)? I could re-use an existing setup this way.

**Comment by yeriomin** [comment]
Added proxy support to master. Build it yourself and try it out, or wait for version 0.38.

**Comment by Eloston** [comment]
Awesome! I'll check it out when 0.38 comes around.
