### ISSUE TITLE
Add recently-updated page with apps changelog

### ISSUE THREAD

**Issue by p-to-the-h** [yeriomin/YalpStore#404]
Would be nice to have a page showing all recently updated apps and their changelog.

Currently you have to see the changelog before updating the app, which is not useful when you have automatic updates

**Comment by Rikk** [comment]
Can't you open the page of the app that was updated and take a look at the changelog?

**Comment by p-to-the-h** [comment]
As I said, the issue is when multiple apps are updated in the background. In that case, you have to go into each app's page and check the release notes. A single "Recently updated" page like in the Play Store would solve that.

**Comment by yeriomin** [comment]
Makes sense. Will do.

**Comment by nagayev** [comment]
404 :-)
