### ISSUE TITLE
Yalp

### ISSUE THREAD

**Issue by tonglob** [yeriomin/YalpStore#405]
### Before creating an issue
1. Make sure you are running the latest version of Yalp Store. Check [here](https://f-droid.org/packages/com.github.yeriomin.yalpstore/).
2. Search for similar issues [here](https://github.com/yeriomin/YalpStore/issues?q=is%3Aissue+is%3Aclosed).
3. Send developer a bug report using Yalp's built-in crash tool. Or go to Yalp's About page and tap on the developer's email. This creates a email with your device info and recent logs attached. 
4. Number 3 is important. Please do it. It helps a lot.
5. Use the following template to write the text of your issue.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Info about your device
Device model, android falvour

**Comment by yeriomin** [comment]
Yalp.
