### ISSUE TITLE
Integrate Exodus warnings

### ISSUE THREAD

**Issue by Rudloff** [yeriomin/YalpStore#406]
[Exodus](https://reports.exodus-privacy.eu.org/) is a website that publishes reports about trackers found in Android apps.
It would be nice if Yalp could retrieve data from their API and display a warning if the app contains trackers.

The API is pretty straightforward, you just need to send the app ID:
https://reports.exodus-privacy.eu.org/api/search/com.snapchat.android

**Comment by yeriomin** [comment]
Thanks for your suggestion. Seems useful.
