### ISSUE TITLE
YalpStore should use system permission by default if installed as priv-app

### ISSUE THREAD

**Issue by shuhaowu** [yeriomin/YalpStore#407]
Not sure if this is possible, but YalpStore should use system permission to install apps if it is built into a ROM/installed as priv-app. FDroid already does this but it detects if the privileged extensions are available whereas this app probably need to do something like [this](https://developer.android.com/training/permissions/requesting.html#java).

**Comment by yeriomin** [comment]
If no installation method is explicitly chosen in the settings and installation privilege is granted, privileged installer will be used from now on. If the user manually chooses any method in the settings, that method will be used from that point.

This affects only new installs.
