### ISSUE TITLE
Why was the option to hide ignored application removed?

### ISSUE THREAD

**Issue by Hund** [yeriomin/YalpStore#408]
Why was the option to hide ignored application removed?

**Comment by yeriomin** [comment]
I'm not sure what you mean. How exactly was the option called? Where was it? In what version? Blacklist-related stuff hasn't changed much lately.

**Comment by Hund** [comment]
You used to be able to hide ignored applications from the list of installed application. I have about 3 applications from Play Store and the list have more than 50 applications.

I don't know when this feature was removed, but some time last year I guess? I rarely use the application itself so I haven't really cared about until now.

**Comment by yeriomin** [comment]
The point of ignoring an app is to prevent updates for it. There is no point in hiding it in the installed apps list. If that happened, it was a bug and now it is fixed. Update blacklist should not make apps invisible in the installed apps list.

**Comment by Hund** [comment]
Oh, bummer. Would you consider adding it as a feature?

**Comment by yeriomin** [comment]
No, sorry. I don't think it makes sense to hide apps from **all** the lists.

**Comment by yeriomin** [comment]
There is update list and installed apps list. Only update list is affected by the update blacklist.
