### ISSUE TITLE
GPLv2 is incompatible with Apache 2.0

### ISSUE THREAD

**Issue by relan** [yeriomin/YalpStore#409]
Hi,

F-Droid maintainer here. I've noticed that Yalp's license says "GPLv2". This version of GPL is incompatible with Android Support Library license (Apache 2.0), see https://www.apache.org/licenses/GPL-compatibility.html.

Please resolve this collision. An obvious option is to state that your code is actually under "GPLv2 or later", so that we could choose GPLv3, which is compatible with Apache 2.0. Would be nice to reflect this in README and add license headers into Java files as recommended by FSF.

**Comment by PorygonZRocks** [comment]
There's another issue with this: Raccoon, which the README says this is derived from, is under the Apache 2.0. That means this can't be under the GPLv2 at all.

**Comment by yeriomin** [comment]
@relan Added the headers. Mentioned "GPLv2 or later" in the README. Do I have to change license in the f-droid metadata?

@PorygonZRocks I occasionally look through Raccoon's source, but Yalp Store shares no code with it (and never did). You are welcome to check. Note, that all the work with Google API is done in a separate library [play-store-api](https://github.com/yeriomin/play-store-api). It is GPLv3. It is derived from [google-play-crawler](https://github.com/Akdeniz/google-play-crawler) which has a GPL-compatible license. So *formally* "derived" is not the right word for this project I guess.

**Comment by relan** [comment]
Thanks for resolving this issue! I've fixed Yalp license in F-Droid metadata in [this commit](https://gitlab.com/fdroid/fdroiddata/commit/afa12904e5f707973357e4b6d44e3d40d194f2eb).

> "derived" is not the right word for this project

_Derived work_ is a legal term meaning that some parts of the original work were used. When you don't borrow any code it's better to avoid this word.
