### ISSUE TITLE
[Feature suggestion] Route traffic through Tor

### ISSUE THREAD

**Issue by faissaloo** [yeriomin/YalpStore#410]
F-Droid has this feature implemented using The Guardian Project's NetCipher library.

**Comment by yeriomin** [comment]
Done.

**Comment by eighthave** [comment]
I know that NetCipher's HttpsURLConnection library does not currently
support TLS 1.3.  Patches welcome!  I haven't had time to look into why,
but I imagine it shouldn't be hard to fix.

NetCipher's OkHTTP or Volley libs might.
