### ISSUE TITLE
[Feature request] Add location faking just like device faking

### ISSUE THREAD

**Issue by iamrohanbro** [yeriomin/YalpStore#411]
Hi developer, as you can understand from the title, adding location spoofing would be great for users who are geo restricted from using few apps. 
I think spoofing the location as USA will do enough.
Thank you.

**Comment by johanw666** [comment]
Location spoofing might be a great idea butthe US is certainly not enough. In Europe, a lot of stuff is only available in certain countries (like apps to access some media video material). So adding the EU countries has a use case. I don't know how that is with other countries.

**Comment by iamrohanbro** [comment]
You can add just a few regions at first, see how it works out and then add more according to user demands.

**Comment by yeriomin** [comment]
Play Store servers decide your location by looking at your ip address. There is no way (that I know of) to override this, except external tools like VPN. Sorry.

Also, it is a duplicate of #213, #267.
