### ISSUE TITLE
Build is fiailing

### ISSUE THREAD

**Issue by DineshGuptaa** [yeriomin/YalpStore#414]
### Expected behaviour
I download the project and just run the build in Android Studio 3.10
Just build the project through
gradlew --stacktrace bulild 

and got below error. Please Help me

[git_stacktrace.txt](https://github.com/yeriomin/YalpStore/files/1890356/git_stacktrace.txt)

Regards,
Dinesh Gupta

**Comment by yeriomin** [comment]
Hello.

It appears you don't have git installed. Run `git clone https://github.com/yeriomin/YalpStore.git` first for the build to succeed. Git is required to generate a version name with some info about the recent changes like this: `0.35-118-gdd9cdef`.

Regards.

**Comment by DineshGuptaa** [comment]
Hi Yeriomin,

I have git installed on my machine & successfully cloned. Would you please help me to generate the version. Please provide me steps to generate version.

Thanks,
Dinesh
