### ISSUE TITLE
YalpStore 0.36 crashes, when entering its settings

### ISSUE THREAD

**Issue by Olf0** [yeriomin/YalpStore#416]
### Expected behaviour
Settings window opens, as YalpStore 0.35 does on the same device.
Thus this constitutes a regression.

### Actual behaviour
YalpStore 0.36 crashes.
Logs (filtered for "yalp"): [Main log](https://github.com/yeriomin/YalpStore/files/1904238/alogcat.2018-04-12-18-50-54.0200.txt) and [Event log](https://github.com/yeriomin/YalpStore/files/1904240/alogcat.2018-04-12-18-50-24.0200.txt)

### Steps to reproduce
1. Start YalpStore 0.36
2. Tap on its menu button in the upper right corner 
3. Tap on the menu entry "Settings"

### Info about your device
Jolla 1 (sbj) with AOSP 4.1.2 (API level 16) based Android runtime environment (AlienDalvik)

### Notes
This seems to differ from issue #363 (and #392), which is already fixed.

**Comment by wine** [comment]
#415 should be fixed in 712c614b1799d72805face8eaea56bdc0c72e07f

Wait for F-Droid to build `0.37` or install latest version from [here](/yeriomin/YalpStore/releases).

**Comment by yeriomin** [comment]
This should be fixed by https://github.com/yeriomin/YalpStore/commit/efa9dda7d7fd094cc520665e84622d7d7313bcec

**Comment by Olf0** [comment]
It is, tested with v0.37 from F-Droid.

Thanks!
