### ISSUE TITLE
可以增加下载完成后的评论功能么？

### ISSUE THREAD

**Issue by liuyuabnn** [yeriomin/YalpStore#418]

**Comment by yeriomin** [comment]
"Can I increase the commenting feature after the download is complete?" Says google translate...

I don't speak Chinese. I'm not entirely sure what you mean, but if you want to review an app, you need to use your own account, not the built-in account.

**Comment by liuyuabnn** [comment]
I mean, download and install a APK, can you comment on APK like Google Play?

**Comment by yeriomin** [comment]
"can you comment on APK like Google Play?" What is that?

Like I already said: if you want to review an app, you need to use your own account, not the built-in account. It was implemented a long time ago.
