### ISSUE TITLE
Hello, can you increase the function of application evaluation? Like GooglePlay.

### ISSUE THREAD

**Issue by liuyuabnn** [yeriomin/YalpStore#419]
###Hello, can you increase the function of application evaluation? Like GooglePlay.

**Comment by yeriomin** [comment]
" can you increase the function of application evaluation?" this google translate quote makes no sense in English. What's the point of creating this issue again?

**Comment by liuyuabnn** [comment]
Sorry, I mean, can you rate your app like Google Play? Can YalpStore do this?

**Comment by liuyuabnn** [comment]
However when I finished downloading I could not submit a comment on YalpStore

**Comment by liuyuabnn** [comment]
However, when I downloaded it, I could not submit a comment on my downloaded app in YalpStore.

**Comment by yeriomin** [comment]
Did you use your own account?

**Comment by liuyuabnn** [comment]
Yes, I use it. I have found my own review in the Google Store. thank you!
