### ISSUE TITLE
v0.36 crashes on start

### ISSUE THREAD

**Issue by repsorp** [yeriomin/YalpStore#420]
Yalp v0.36
Android 7.1.2

Yalp  crashes on opening

04-13 11:45:17.388 I/ActivityManager(974): Process com.github.yeriomin.yalpstore (pid 2656) has died
04-13 11:45:17.412 I/ActivityManager(974): Process com.github.yeriomin.yalpstore:report_process (pid 2624) has died
04-13 11:45:28.099 I/ActivityManager(974): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.github.yeriomin.yalpstore/.InstalledAppsActivity bnds=[407,118][585,334] (has extras)} from uid 10505 on display 0
04-13 11:45:28.151 I/ActivityManager(974): Start proc 3064:com.github.yeriomin.yalpstore/u0a368 for activity com.github.yeriomin.yalpstore/.InstalledAppsActivity
04-13 11:45:28.211 W/System  (3064): ClassLoader referenced unknown path: /data/app/com.github.yeriomin.yalpstore-1/lib/arm64
04-13 11:45:28.351 W/System.err(3064): 	at com.github.yeriomin.yalpstore.PreferenceUtil.getStringSet(PreferenceUtil.java:84)
04-13 11:45:28.351 W/System.err(3064): 	at com.github.yeriomin.yalpstore.BlackWhiteListManager.<init>(BlackWhiteListManager.java:35)
04-13 11:45:28.351 W/System.err(3064): 	at com.github.yeriomin.yalpstore.task.AppListValidityCheckTask.doInBackground$1059dc3f(AppListValidityCheckTask.java:105)
04-13 11:45:28.351 W/System.err(3064): 	at com.github.yeriomin.yalpstore.task.AppListValidityCheckTask.doInBackground(AppListValidityCheckTask.java:38)
04-13 11:45:28.353 I/ActivityManager(974): START u0 {flg=0x14000000 cmp=com.github.yeriomin.yalpstore/.BugReportActivity (has extras)} from uid 10368 on display 0
04-13 11:45:28.395 I/WindowManager(974): WIN DEATH: Window{dd3eb36 u0 com.github.yeriomin.yalpstore/com.github.yeriomin.yalpstore.InstalledAppsActivity}
04-13 11:45:28.396 I/ActivityManager(974): Process com.github.yeriomin.yalpstore (pid 3064) has died
04-13 11:45:28.396 W/ActivityManager(974): Force removing ActivityRecord{3c8b85f u0 com.github.yeriomin.yalpstore/.InstalledAppsActivity t3548}: app died, no saved state
04-13 11:45:28.414 I/ActivityManager(974): Start proc 3089:com.github.yeriomin.yalpstore:report_process/u0a368 for activity com.github.yeriomin.yalpstore/.BugReportActivity
04-13 11:45:28.462 W/System  (3089): ClassLoader referenced unknown path: /data/app/com.github.yeriomin.yalpstore-1/lib/arm64
04-13 11:45:28.693 I/ActivityManager(974): Displayed com.github.yeriomin.yalpstore/.BugReportActivity: +294ms (total +556ms)
04-13 11:45:28.742 I/LatinIme(4276): onActivate() : EditorInfo = Package = com.github.yeriomin.yalpstore : Type = Text : Learning = Enable : Suggestion = Show : AutoCorrection = Enable : Microphone = Show : Incognito = Disable
04-13 11:45:29.812 I/ActivityManager(974): Start proc 3120:com.github.yeriomin.yalpstore/u0a368 for service com.github.yeriomin.yalpstore/.bugreport.BugReportService
04-13 11:45:29.922 W/System  (3120): ClassLoader referenced unknown path: /data/app/com.github.yeriomin.yalpstore-1/lib/arm64

**Comment by pboesch** [comment]
Hello, same here. Updated from fdroid.

LineageOS 15.1

**Comment by repsorp** [comment]
Updated from fdroid too

**Comment by algorithminflux** [comment]
Same issue for me.

**Comment by pboesch** [comment]
Ok thanks. I'll wait this version on fdroid.

**Comment by repsorp** [comment]
@pboesch or you can go to "Releases" and download 0.37 directly from here

**Comment by xenithorb** [comment]
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.github.yeriomin.yalpstore.txt#L227

Should be a matter of time now, looks like they grabbed the new update and disabled 0.36

**Comment by capshort** [comment]
I can confirm that the app crashes on my phone with the very similar stack trace as in #415, i.e.

![photo_2018-04-13_21-07-58](https://user-images.githubusercontent.com/25132855/38753519-ef1d9f12-3f5e-11e8-8a27-daca8f062137.jpg)

**Comment by TPS** [comment]
Actually, check your Yalp version: 0.37 w/ the fix just rolled out. ☺

**Comment by ReekyMarko** [comment]
Can confirm 0.37 fixes the issue
