### ISSUE TITLE
 "Error receiving or processing data occurred ad the HTTP level"

### ISSUE THREAD

**Issue by cubagithub** [yeriomin/YalpStore#421]
### Before creating an issue
1. 0.37 on Lineage 14.1
2. Search for similar issues showed one vague issue, closed from inactivity.
3. Sent bug report - title set as bug comment.

5.### Expected behaviour
Tell us what should happen
Updates download and install seamlessly as root - configured in settings and working until recently.

### Actual behaviour
Tell us what happens instead
Download Manager tries and fails repeatedly to download the apks - they appear in Downloads as queued.

### Steps to reproduce
1. Click "check for updates"
2. See toast show attempts to download each app update without progress.
3. Yalp notification for each app: "Error receiving or processing data occurred ad the HTTP level"

### Info about your device
HTC 10 MicroG Lineage 14.1

**Comment by yeriomin** [comment]
This seems to be a problem with the DownloadManager. If the downloads are queued, Yalp Store has done its job. Please read the [FAQ](https://github.com/yeriomin/YalpStore#faq) for possible solutions.
