### ISSUE TITLE
'No apps need to be updated'

### ISSUE THREAD

**Issue by Rikk** [yeriomin/YalpStore#422]
As of today, Updates page always return empty, with the message "No apps need to be updated". What's going on? Did Google change something?

**Comment by JonnyTech** [comment]
Confirmed, v0.37 fdroid

**Comment by johanw666** [comment]
Same here with 0.38.

**Comment by JonnyTech** [comment]
Updated to v0.38 fdroid, still the same.

What is interesting is that if I select an app from the installed apps list that I know has an update then I can download it from yalp manually.

So it is just the update notification and reporting that is broken.

**Comment by yeriomin** [comment]
@Rikk @JonnyTech @johanw666 

> Did Google change something?

Yes, they did.

> Updated to v0.38 fdroid, still the same.

0.38 was tagged before this change.
