### ISSUE TITLE
Can't update system apps without ROOT

### ISSUE THREAD

**Issue by PureCity** [yeriomin/YalpStore#429]
Thank you for YalpStore help me a lot. Should you let the system apps install without ROOT? I am very sad when i see "Android System WebView" updated but can not install.
Thanks very much.

**Comment by yeriomin** [comment]
Updating system apps does not require root. If you cannot update some app, it is not because it is a system app. Most likely, it means that signatures don't match - Yalp Store notifies you about this.

Regards.
