### ISSUE TITLE
One time donations

### ISSUE THREAD

**Issue by DPTJKKVH** [yeriomin/YalpStore#430]
I see you are using bitcoin and liberapay. The latter probably because they don't take away a percentage of your donations.

I pledged 50€ for you on liberapay but instead of giving approximately a dollar per week I would much rather just give you 50€ upfront. Is there any way to make bigger one time donations or do you actually prefer ongoing small donations?

**Comment by ale5000-git** [comment]
I think you can donate 50€ per week and then after the first donation got "done" then undo the donation so only the first remain (if I'm not wrong).

**Comment by DPTJKKVH** [comment]
That's possible indeed but it's a tad clumsy and probably stops quite some people from simply placing a one time donation for yeriomin.

Not me of course but I want to know what kind of donations yeriomin prefers so I can donate accordingly.

**Comment by yeriomin** [comment]
@DPTJKKVH @ale5000-git

In my opinion trust is a big issue for anything related to money. For that reason PayPal would be ideal even in spite of the fees. Unfortunately, PayPal would not let me receive transfers with my own name right away. And fixing this would make me go into legal trouble which would cost me more than the donations would bring (that's how PayPal operates in my country, I guess).

Searching F-Droid metadata for projects with developers with Russian-sounding names makes me think I'm not the only one having this problem. I might be wrong.

Is there any other donation platform which users would trust (which deals with more than two and a half projects)?

Anyway, I'm really glad Yalp Store is useful enough to receive donations. Thanks, guys.

**Comment by DPTJKKVH** [comment]
@yeriomin 

Yalp is incredibly useful to anyone who wants to build or use an Android phone without Google software but still wants to access the play store and receive automatic updates. (So mostly users of Lineage for MicroG.) You do an excellent job and I hope you will receive many more donations. I will send at least 50 € per year to you.

I'm very sorry that PayPal is giving you trouble. Their service is easy to use but they behave very badly for no reason from time to time.

As for alternatives:
Well the most common and trusted platform for continuous/regular donations is https://www.patreon.com/ .
This is used by virtually everyone may them be artists, open source developers or anything else.

Many creators that have problems with Paypal use https://www.skrill.com/ . Skrill is basically the same service like PayPal but they are less restrictive on what their service used for. People can donate up to 1500 € each without signing up to Skrill, as far as I know.

**Comment by Nutomic** [comment]
Cryptocurrency is actually pretty good for one-time donations, just give it a try. Not much more complicated than Paypal. 

@yeriomin It would be nice if you could accept some other cryptocurrencies, like Bitcoin Cash or Ethereum. Bitcoin has really high fees at times.

**Comment by setuidroot** [comment]
Agreed with cryptocurrencies... I'd recommend Monero.  It's private, secure and the transaction fees are low.  You can make your own wallet (CLI or GUI) with the downloads from getmonero.org... but the blockchain data file is 50GB and takes almost 24 hours to sync.  Or you could make a web wallet from mymonero.com (considered to be the only legitimate website for monero web wallets) but web wallets obviously aren't as secure.
