### ISSUE TITLE
Repository request

### ISSUE THREAD

**Issue by linuxdude96** [yeriomin/YalpStore#432]
Hi, I just installed the latest update of k-droid. it looks beautiful! I was looking around and came across a repository settings page. I was wondering if, I could have your repository info? I'd like to add that to k-droid. It's that nice looking!

**Comment by yeriomin** [comment]
>k-droid

What is that? Google gives me nothing.

>repository info

Again, what is that?

I'm sorry, I don't understand.

**Comment by linuxdude96** [comment]
![](https://i.imgur.com/O4Dt11K.jpg)![](https://i.imgur.com/XGg2rYa.jpg)

**Comment by linuxdude96** [comment]
Sorry it f-droid and they offers thr feature to add repositories and I want to add Google Play Stores app repositories. Anyway you could make something like that?

**Comment by yeriomin** [comment]
> Anyway you could make something like that?

Unfortunately, no. That would require getting **all** apps from Play Store which is impossible.
