### ISSUE TITLE
#412 continues in v0.39

### ISSUE THREAD

**Issue by murkom** [yeriomin/YalpStore#433]
Link to apk in #412 works great.
Version 0.39 from fdroid crashes. It seems to be the same issue.
Here's a log:
https://upload.disroot.org/r/UhKyHquX#0KR4gWZwTSKTX2OyFKABZosn2+VAMstAVwDdWacVlTQ=

**Comment by ale5000-git** [comment]
The fix referenced is committed in the repository but there isn't yet a new version with it so it is perfectly normal.

**Comment by murkom** [comment]
Thought it was already in last version. This is not an issue, then. Can be closed.
Thanks

**Comment by ale5000-git** [comment]
You can see the commits [here](https://github.com/yeriomin/YalpStore/commits/master).
Everything that is above the "Bumping version to 0.39" isn't yet released.

**Comment by yeriomin** [comment]
0.39 had been released before #412 was fixed. The fix will be in 0.40.
