### ISSUE TITLE
Malformed request

### ISSUE THREAD

**Issue by stemy2** [yeriomin/YalpStore#434]
### Before creating an issue
1. Make sure you are running the latest version of Yalp Store. Check [here](https://f-droid.org/packages/com.github.yeriomin.yalpstore/).
2. Search for similar issues [here](https://github.com/yeriomin/YalpStore/issues?q=is%3Aissue+is%3Aclosed).
3. Send developer a bug report using Yalp's built-in crash tool. Or go to Yalp's About page and tap on the developer's email. This creates a email with your device info and recent logs attached. 
4. Number 3 is important. Please do it. It helps a lot.
5. Use the following template to write the text of your issue.

### Expected behaviour
Downloading the app.

### Actual behaviour
Does nothing and shows «malformed request».

### Steps to reproduce
1.Go on a random app page.
2. Click on download.

### Info about your device
Fairphone open on Fairphone 2

**Comment by yeriomin** [comment]
Cannot reproduce.

Does it happen all the time?

Does the Play Store app work properly? Do you use proxies/vpn/adblockers?

**Comment by stemy2** [comment]
The issue is vanished for whatever reason.

**Comment by yeriomin** [comment]
@tuxayo @ale5000-git 

I got it too. Seems to happen only to delivery requests (the one which returns the download link). Comes and goes.

My guess is that there are too many people using the built-in account now. Knowing if it happens on ordinary users' accounts would help. According to google search, it does and even with the Play Store app. But maybe google is just inconsistent with using this error code (for example in #422 bulk details request stopped returning 401 if the auth token is stale, it returns 200 in this case now).

`Retry-After` is not included.

I'll have to observe this for a couple of days.

**Comment by ale5000-git** [comment]
I'm not sure how it works, but as hypothesis in case YalpStore "retrive" the download link when opening the information page of an app then it could be delayed to only retrive the download link when the user effectively press the download button so that if the user just view the page without download there is on less request.

**Comment by yeriomin** [comment]
@ale5000-git 
> it could be delayed to only retrive the download link when the user effectively press the download button

Download link is and has always been retrieved on download button click.

**Comment by ale5000-git** [comment]
If the info page of a single app it is opened 3 times, every time it do a new request or is it cached?

**Comment by ale5000-git** [comment]
Well, I imagine there isn't any solution other than detect the error and auto-retry after a certain amount of time.

**Comment by yeriomin** [comment]
@ale5000-git @tuxayo I did a certain *thing* to the built-in account. Could you check if at least the frequency of this problem became lower? Also, did you notice this happening on your own accounts?

> detect the error and auto-retry after a certain amount of time

The only I caught it, it lasted for a couple of minutes (all delivery requests returned 429) and then went away. Waiting for minutes is not a good idea. Sorry.
