### ISSUE TITLE
#info

### ISSUE THREAD

**Issue by RedMoonOTInetwork** [yeriomin/YalpStore#436]
Hi, What is the difference between yalp store and yalp store +? Are you always the Dev?

**Comment by ale5000-git** [comment]
I cannot say it exactly because you haven't posted any link, but Yalp Store + (from the name) looks like a fake/scam version.

**Comment by Rikk** [comment]
Where is it? If it's not inside his account (https://github.com/yeriomin) could be a fork or a fake.

**Comment by ale5000-git** [comment]
@RedMoonOTInetwork: Could you please post the download link where you get it?

**Comment by RedMoonOTInetwork** [comment]
From xda https://labs.xda-developers.com/store/app/com.github.yeriomin.yalpstore

**Comment by ale5000-git** [comment]
So, where is the +?
It look like the same app.

**Comment by RedMoonOTInetwork** [comment]
@ale5000-git no, it's Alpha, it is written

**Comment by RedMoonOTInetwork** [comment]
https://tlgur.com/d/wg2dzZa8

Look here

**Comment by RedMoonOTInetwork** [comment]
I think that on xda is an Alpha while from github is a stable, solved mystery, I think

**Comment by Rikk** [comment]
This is indeed curious. Looks like a real build by our @yeriomin but different from the one published here.
@yeriomin what can you say?

**Comment by Rikk** [comment]
I haven't installed it, but I see the app version in apk includes the '+', versionCode is different, size is larger, permissions are the same, and I guess signature is also official (but I need to learn how to compare signatures).

**Comment by Rikk** [comment]
@ale5000-git Right, I've just installed it. It is legit, same signature. This version has an improved interface, more modern, material design, and white theme. Screen transitions seems to work way much better! Rest of functions are the same, just some buttons with different placement.

![screenshot_2018-05-04-05-58-26](https://user-images.githubusercontent.com/2916485/39620084-563b0c46-4f60-11e8-8846-20468528f9ea.png)

**Comment by RedMoonOTInetwork** [comment]
@Rikk I had said it lol

**Comment by ale5000-git** [comment]
It is still unclear before a reply of @yeriomin.

**Comment by yeriomin** [comment]
@RedMoonOTInetwork @Rikk @ale5000-git 

> What is the difference between yalp store and yalp store +?

See #439.

> Are you always the Dev?

If you got it from xda, yes.

> This version has an improved interface, more modern, material design

That's pretty much it.

**Comment by RedMoonOTInetwork** [comment]
Yes, it's very beautiful, thank you for your work
