### ISSUE TITLE
When 'What's new' is the last part in a description, Yalp doesn't display it in a collapsible section

### ISSUE THREAD

**Issue by Rikk** [yeriomin/YalpStore#438]
When 'What's new' is the last part in the description of an app, YalpStore does not display it in a collapsible, separate section.

**Comment by yeriomin** [comment]
It is intended behavior. 'What's new' is not important when the app is not installed.

**Comment by Rikk** [comment]
Ok, I didn't notice this relation (installed vs not installed) before. And I may disagree about the importance of changelog for apps not installed; perhaps, for not installed apps you could make it appear below description but still collapsible.

Now, maybe this could be a bug: 0.40 sporadically failing to load What's New part and showing it blank instead.

**Comment by yeriomin** [comment]
>  0.40 sporadically failing to load What's New part and showing it blank instead.

Most likely it is just blank. App developers do not have to fill it out.

**Comment by Rikk** [comment]
I can reproduce. I think it depends from where you accessed the app page.
When I access from Your Apps:
![screenshot_2018-05-06-07-56-53](https://user-images.githubusercontent.com/2916485/39672587-888221a4-5103-11e8-9002-e179f50af53c.png)
When I access from it after opening "Apps by Google":
![screenshot_2018-05-06-07-56-33](https://user-images.githubusercontent.com/2916485/39672589-8dc72754-5103-11e8-9813-f9a08fb018e5.png)

**Comment by yeriomin** [comment]
This should happen no longer.
