### ISSUE TITLE
Quiet (background) installation and updates (needs root)

### ISSUE THREAD

**Issue by avently** [yeriomin/YalpStore#44]
Установка и обновление программ одним кликом - так можно сделать? То есть по типу того, как это в плэй маркете и титаниуме сделано. Нажал кнопку, программа скачалась и в фоне установилась. Появилась кнопка "Открыть" в интерфейсе. Естественно, нужен рут на устройстве.

**Comment by yeriomin** [comment]
В версии, которая распространяется через f-droid нельзя. Нужно добавлять системные разрешения и устанавливать как системное приложение. Первое запрещено, второе невозможно.

Нужно делать отдельный apk и писать инструкцию чтобы пользователи сами его ставили. Попробую, но удобно и в-один-клик вряд ли получится.

**Comment by Lesik** [comment]
Translating the issue for interested contributors:

"Installing and updating programs with one click – is that possible? Similarly to how the Play Store and Titanium Backup do it. Press a button, the program is downloaded and installed automatically in the background. [...] Obviously, that requires root."

"In the version of Yalp Store that is distributed through F-Droid that is impossible. For this to work, the app must require system permissions and installed as system app. With F-Droid, the former is forbidden, the latter impossible.

A separate apk download is required, alongside with instructions for people to install Yalp as system app. I'll try, but it's unlikely going to be a one-click-install."

**Comment by Lesik** [comment]
Титаниум имеет закрытые исходники, но F-Droid есть open source. Я помню они тоже пытались запрограмировать такую функцыю, то-есть посмотря в их код можно изучить, как это делается.

We can't look into Titanium's source, but F-Droid is open source. I remember they too tried to implement this function, that means by looking into their code one can examine how to do this.

**Comment by avently** [comment]
Я вообще не понимаю, в чем проблема. 
su
pm install -r /path/to/file
Все. Если есть рут, то данный функционал легко сделать. А если фдроид по каким то необъяснимым причинам не пускает с рутом, то можно проверку сделать на то, откуда установлена прога по сертификату, например. И резать этот функционал, если уж очень надо. Либо сделать опцию в конфигурационном файле, включив которую человек сам может собрать апк с дополнительным функционалом в виде автоустановки приложений. А в обычном билде по умолчанию это будет отключено. Типа, используй на свой страх и риск и собирай сам.

**Comment by Lesik** [comment]
Так если всё так просто, значет проблем нету! :)

@yeriomin просто сказал, что для такой функции нужно быть системной апликацыой (т.е. инсталяцыя не через нажатие на apk, а через adb или терминал).

Если это не так, а просто нужен root, то без проблем. F-Droid такое разришает.

**Comment by avently** [comment]
Вот, что я написал вот здесь https://github.com/yeriomin/YalpStore/blob/master/app/src/main/java/com/github/yeriomin/yalpstore/DownloadBroadcastReceiver.java#L85  а эту строчку по ссылке закомментировал.
```
 try {
       Process process = Runtime.getRuntime().exec("su && pm install -r " + file.getAbsolutePath());
       BufferedReader reader = new BufferedReader(new InputStreamReader(process.getErrorStream()));
       Log.w(file.getAbsolutePath(), "Autoinstall error log " + reader.readLine());
} catch (IOException e) {
        e.printStackTrace();
}
```
Эта функция запрашивает рут доступ, а затем устанавливает скачанный апк. И все. Как сделать установку в фоновом процессе, чтобы не блочить main, я не знаю. Кто-то знает - подскажите. Буду только рад, если @yeriomin запилишь в основной бранч этот метод в красивой оболочке, вроде установки в параллельном процессе и с какой-то визуальной индикацией.

**Comment by yeriomin** [comment]
@avently @Lesik Спасибо за старание и не обижайтесь, но я тоже могу загуглить как работать с su. "в красивой оболочке с какой-то визуальной индикацией" это 95% любого приложения для android, так как эта ос рассчитана на потребление, а не на работу. Всё, что вы сказали верно, и ничего сложного в этом действительно нет. Просто это надо делать. Буду рад pull requestу.

**Comment by avently** [comment]
@yeriomin можно взять предложенный мной код, добавить код, меняюший текст на кнопке внизу на "установка...", к примеру. Затем, после установки, менять текст на "открыть". Это делается тоже не сложно, у тебя уже "инфраструктура" для этого готова. Заодно обратишь внимание, что для одинаковых версий в плейсторе и на девайсе можно писать на кнопке "открыть", а не "скачать" один и тот же апк еще раз. 
То есть как я это вижу: нажимаю Установить, уведомление отображется о скачивании (как и сейчас в шторке), меняется текст кнопки на "Скачивание...", затем "Установка...", затем "Открыть". Как бы все. А пока там все скачивается, можно не ждать, и рассматривать другие проги в поиске. У тебя установка даже в таком случае отлично работает из коробки.
P.S. я не настолько шарю в Андроиде, чтобы pull request'ы в работающий код отправлять:)

**Comment by yeriomin** [comment]
Seems to be complete. "Update all" button added. Background update checker now attempts to install updates instead of just showing a notification.
An app will be updated in background (by background update checker or Yalp UI) if:
* it is an update, not a new installation
* signatures of installed app and the update match
* permission lists of installed app and the update are the same

If not, the user is taken through the usual sequence of confirmation dialogs in an attempt to make him notice that he might be installing something he doesn't want (malware).

**Comment by avently** [comment]
При нажатии на "Обновить все" появляется уведомление с количеством программ для обновления. И все, ничего не происходит. Оказывается, надо зайти в настройки и выбрать пункт "Установить найденные обновления". Но оказывается, что нажать его нельзя по какой-то причине, до этого неизвестной (пункт неактивен). Пришлось лезть в код и обнаружить, что этот пункт станет активным только если в "Периодически проверять обновления" выбрать что-то, отличное от При запуске. 
Как то уж слишком непонятно этот момент сделан. 

Может, сделать пункт "Установить найденные обновления" активным постоянно (если есть рут)?
А если этот пункт не выбран, то при нажатии на "Обновить все" нужно скачать приложения и поочереди выводить диалог с установкой. Это юзер-френдли решение для тех, у кого нет рута.

При нажатии на "Скачать" в окне приложения с новой версией, запускается установка всех программ. С чего вдруг, если я хотел скачать лишь одно обновление? Крэшится тоже программа. Я отправил на почту багрепорт, глянь.
 
И еще непонятно, почему нельзя устанавливать в фоне новые приложухи, а не только обновы. Чтобы юзер ознакомился со списком разрешений, что просит прога, да?

**Comment by yeriomin** [comment]
@avently Проблема только в том, что была видна кнопка "Обновить всё", даже если пользователь не отметил "Установить найденные обновления (root)".

Многие считают автоустановку приложений антифичей, так что по-умолчанию она включена не будет.

Кстати, ты снова тестишь нестабильную ветвь. На фиче написано v0.12, так что ожидать стабильности не стоит.

**Comment by avently** [comment]
То есть ты предлагаешь оповещать тебя о багах, когда ты уже сделаешь релиз для тысяч людей? Если тебе так нравится, то ок, буду сообщать после релиза.

**Comment by yeriomin** [comment]
Когда ты пишешь о баге, код уже поменялся и бага нет.
