### ISSUE TITLE
Игра не доступна

### ISSUE THREAD

**Issue by nagayev** [yeriomin/YalpStore#441]
Решил понастольгировать и скачать игру из 2014.
Скопировал ссылку на игру и вставил в yalp.
Но Yalp сказал, что прога не доступна.
Пакет: kpichanzheng.kgamemns.create.aride
Версия Yalp: 0.40
Android 5.0.2, Samsung T531
Давно не писал сюда)

**Comment by yeriomin** [comment]
Этого приложения действительно нет в Play Store:
https://play.google.com/store/apps/details?id=kpichanzheng.kgamemns.create.aride

**Comment by yeriomin** [comment]
@nagayev значит это приложение было удалено из Play Store. Можете задать вопрос разработчику приложения...
