### ISSUE TITLE
Yalp not on list of apps that can open link to list of apps by developer in Google Play

### ISSUE THREAD

**Issue by Rikk** [yeriomin/YalpStore#442]
YalpStore is not showing in the list of apps that can handle links to list of developer's apps on Google Play, when I try opening from browsers. Sample link:
https://play.google.com/store/apps/dev?id=5700313618786177705

By contrast, links to specific apps can be open with YalpStore, for example:
https://play.google.com/store/apps/details?id=com.google.android.apps.maps

**Comment by yeriomin** [comment]
You can get apps by a specific developer by searching `pub:<developer name>` or by tapping on "Apps by <developer name>" on the details page.

Where does this link come from?

**Comment by Rikk** [comment]
It is the link for the search you suggest when we make it in a browser.
I would like to start Yalp directly in the listing of Google apps, that's why I reported this problem.
