### ISSUE TITLE
[Question] Update F-droid Apps via YalpStore

### ISSUE THREAD

**Issue by radasbona** [yeriomin/YalpStore#443]
Hi, just a short question, no issue.
I was wondering if it is a good idea to make yalp store also a (basic) f-droid client. 

Pulling Gplay Apps Updates from the Gplay Server and F-droid Updates from the F-droid Server. 
Browsing and Installation of F-droid Apps we can use the Website.

**Comment by yeriomin** [comment]
Theoretically this can be done. Unlike Google, F-droid does not actively try to prevent people from accessing it. But I don't think it *should* be done. F-Droid client is good enough to not need an alternative. And doing this would require to make a lot of changes in the UI.

Also, see #362.

**Comment by mikhoul** [comment]
@yeriomin I don't agree with you, look at my point of view: I think it could be a good thing since I would have one less app running in the background consuming memory/CPU cycle since YalpStore would do the work and I could manage all my updates from a single place. instead of using 2 apps for basically the same thing.

Please consider my points.  ✌️

Thanks for this marvelous project :octocat:

**Comment by yeriomin** [comment]
@mikhoul Thanks, I'm glad you find Yalp Store useful.

> one less app running in the background consuming memory/CPU cycle

Apps in background don't consume CPU time. The update check in both F-Droid and Yalp Store takes seconds, so it is not worth optimizing. Also, this update process will still have to be done, so the same amount of CPU time/battery will be spent; the only difference will be the app who does the work.

Yalp Store is build around a single app source. Redoing it would take months, and the only benefit is having one icon in the launcher except two. There is no good reason to make Yalp Store deal with F-Droid apps, sorry.

**Comment by tomasz1986** [comment]
> Redoing it would take months, and the only benefit is having one icon in the launcher except two. There is no good reason to make Yalp Store deal with F-Droid apps, sorry.

The newest versions of the F-Droid app require Android 4 or higher while Yalp Store has much lower requirements, so I think that there could be more benefits than just having one icon :wink:.

**Comment by mikhoul** [comment]
@yeriomin  You seem to forget that even if an app is on idle it consume RAM which is precious especially for older and low end tablet/TV-Box/Phone.

![image](https://user-images.githubusercontent.com/5678673/43211406-6bbbe7a4-8fff-11e8-94cb-a78914bb20fb.png)


Regards :octocat:

**Comment by tomasz1986** [comment]
> You seem to forget that even if an app is on idle it consume RAM which is precious especially for older and low end tablet/TV-Box/Phone.

On a side note, the F-Droid client is also buggy and keeps starting in background to update its database even if all automatic updates are disabled. I basically have to use Greenify to keep it frozen in order to prevent this.
