### ISSUE TITLE
Cannot download anything

### ISSUE THREAD

**Issue by kozross** [yeriomin/YalpStore#445]
Every time I try to download anything, it starts, sits on 0 for 15+ minutes, then errors out with 'Error receiving or processing data occurred at the HTTP level'. This happens regardless of whether I'm on WiFi or mobile data. 

I can provide more information, but I'm not sure how to get logs on Android. I'm on Android 8.1.0.

**Comment by yeriomin** [comment]
The problem is most likely with your DownloadManager. See [FAQ](https://github.com/yeriomin/YalpStore#faq) for a solution. If it does not help, please follow the issue template (which you ignored ;) ), which explains how to send me the logs.
