### ISSUE TITLE
Sometimes apps don't want to update to their recent versions

### ISSUE THREAD

**Issue by ptkovsky** [yeriomin/YalpStore#446]
### Before creating an issue
1. I try to regularly update all of the stuff including F-Droid repos as I turn the phone on, so mostly once a day.
2. Searched.
3. Will do after typing this.
4. Sure.
5. Done.

### Expected behaviour
I want my updates pop up as I tap Updates in Yalp Store

### Actual behaviour
Yalp Store shows that my app doesn't need updates (but it does)

### Steps to reproduce
I launch Yalp Store and tap on Updates

### Info about your device
mako, currently SAOSP 7.1.2   

So I was browsing Firefox roadmaps update page from my laptop and noticed that they implemented Quantum CSS for faster web page rendering on Android. After that I took my phone and decided to check if I already got an updated version of Firefox through Yalp. Sadly, I didn't. And It was still showing that version 59.0.2 is recent and doesn't need any updates. Downloaded and installed 60 version manually from other source on the web, after that opening Yalp Store was still showing me that I have 59.0.2 version and I don't need any updates. I used my phone a little bit afterwards and turned it off. Maybe an hour or two later afterwards I decided to file this issue so I took my phone to see if it still shows that. So now it says that 60.0 -> 59.0.2 so it still doesn't detect the updated version that was manually installed before.

**Comment by yeriomin** [comment]
Hello.

This is not something unique. There is even a FAQ item about it:

> For different reasons the app developer might choose not to release his app for all users at the same time. This is called a staged rollout. Be patient, the update will come.

The choice to make the update available to you does not happen on the client side. Whether or not you get the update depends on your account. I just checked firefox and one of my accounts had version 60 available and the other 59.0.2. I don't know what exactly causes this. Most probably, app developer's choice in deployment, your device info and your account activity all influence this.

If you have some specific info, please provide it, but I will most likely have to tell you to just wait. Sorry.

**Comment by ptkovsky** [comment]
Oh, right. Thanks for the clarification that there is no any sort of weird bug here. Everything works fine for the most part so no problem. Cheers. :)
