### ISSUE TITLE
Возможность открывать Yalp Store при переходе из других приложений

### ISSUE THREAD

**Issue by teod0r** [yeriomin/YalpStore#45]
Есть приложение 4PDA. Там в статьях про приложения есть кнопки открыть приложение через google play, т.е. при нажатии там выбираешь, каким приложением открыть ссылку на маркет

**Comment by avently** [comment]
Уважаемый @teodo0r, не об этом ли ты говоришь? 
![screenshot](https://cloud.githubusercontent.com/assets/7953703/22214299/2c3930d4-e1a8-11e6-83db-3353ac441da7.png)

**Comment by teod0r** [comment]
@avently, возможно, это оно, у меня просто по-другому выглядит. Но у меня нет в списке Yalp Store, только браузеры и F-Droid

**Comment by yeriomin** [comment]
Cannot reproduce.

Also, master is unstable, test it at your peril and don't expect bugs to be reproducible.

Also, English please.
