### ISSUE TITLE
No network connection

### ISSUE THREAD

**Issue by GustavMarwin** [yeriomin/YalpStore#450]
I get this "No network connection" when trying to use the app. What would be the reason? My connection is networking just fine.

**Comment by takiainen** [comment]
I have the same issue. On two different phones.

**Comment by Caliandroid** [comment]
Me too. With no my own account as well as with the built-in fake account.

It still works on my wife's phone.

Maybe we are blocked by Google based on our accounts?

**Comment by unlnown542a** [comment]
05-18 23:01:23.399 11078 11078 D LoginTask: javax.net.ssl.SSLHandshakeException caught during a google api request: Handshake failed

**Comment by unlnown542a** [comment]
could be certificate issue

**Comment by ArchangeGabriel** [comment]
Yes, it is “fixed” in version 0.41.

**Comment by 0pLuS0** [comment]
This just started acting up again!

Aurora Store has been down for 2 days and Yalp is doing the same thing, which I assumed, since they both connect to the Google Servers.

I assume Google has done something that is blocking them.

PLEASE REOPEN THIS!
