### ISSUE TITLE
Нет соединения с сетью.

### ISSUE THREAD

**Issue by buckelieg** [yeriomin/YalpStore#455]
Никогда.
Ни по вифи, ни по мобильным данным.
Обновления не скачивает. 
Приложения не ищет.
Версия 0.40.

**Comment by roguh** [comment]
Try 0.41

I downloaded the APK from [https://github.com/yeriomin/YalpStore/releases](https://github.com/yeriomin/YalpStore/releases). FDroid has not updated from 0.40 yet.
