### ISSUE TITLE
[Feature Request] List of "my apps" that are not available from Google Play Store

### ISSUE THREAD

**Issue by EgonKrenz2** [yeriomin/YalpStore#458]
### Before creating an issue
1. Make sure you are running the latest version of Yalp Store. Check [here](https://f-droid.org/packages/com.github.yeriomin.yalpstore/).
2. Search for similar issues [here](https://github.com/yeriomin/YalpStore/issues?q=is%3Aissue+is%3Aclosed).
3. Send developer a bug report using Yalp's built-in crash tool. Or go to Yalp's About page and tap on the developer's email. This creates a email with your device info and recent logs attached. 
4. Number 3 is important. Please do it. It helps a lot.
5. Use the following template to write the text of your issue.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Info about your device
Device model, android falvour

**Comment by EgonKrenz2** [comment]
Yalp lists all my apps.
If an app is not (or not longer) in the Playstore - for example Open Gapps or Oruxmaps - it says so.
So it would be pretty interesting to get a list (best with txt-export) of this apps to know which have to be cared for updates by myself.

**Comment by yeriomin** [comment]
I'm pretty sure this feature will not be used by many people. And there is no logical place for in in the UI. Sorry.
