### ISSUE TITLE
[BUG] Download initiated but stuck @0% on P-DP

### ISSUE THREAD

**Issue by 0xlne** [yeriomin/YalpStore#459]
### Expected behaviour
Download should initiate, proceed & complete.

### Actual behaviour
Download initiated (download bar appears) but gets stuck @0%

### Steps to reproduce
1. Select any app to download, press download.

### Info about your device
Sony Xperia XZ2, Android P Developer Preview

**Comment by YiiKuoChong** [comment]
Had this behavior. The download bar is not consistent either.

**Comment by yeriomin** [comment]
I don't have a real device to test it on and it doesn't happen on an emulator. Lets at least wait for when Android P has an api number to consider this a problem.

**Comment by 0xlne** [comment]
This issue is a false-positive. I've isolated the reason to Blokada.
Whitelisting Yalp solves the issue.
