### ISSUE TITLE
 The "View in Play Store" button does not fulfill its specific function.

### ISSUE THREAD

**Issue by Mariaj98** [yeriomin/YalpStore#460]
### Expected behaviour
Pressing the "View in Play Store" button should show only valid apps to reach the Play Store (Explorers, and the Play Store app)
![imagen](https://user-images.githubusercontent.com/39536526/40389859-73a0d240-5de1-11e8-8a24-09b7296f8ca8.png)

### Actual behaviour
Pressing the button "View in Play Store" shows the applications that do not take the "Play Store" tab and if we configure Yalp Store as the default option "Always" a loop is created that would only take us to the application "Yalp Store" disabling the "View in Play Store" button.
![imagen](https://user-images.githubusercontent.com/39536526/40390342-ea712586-5de2-11e8-9fa5-d3415ae9d23c.png)

### Steps to reproduce
1.Install the application.
2.Open it and enter one of the installed applications.
3.Press the "View in Play Store" button and then select the Yalp Store option and press "Always"

### Recording the error.
https://www.youtube.com/watch?v=0v7Jsjo8nqQ&feature=youtu.be

**Comment by yeriomin** [comment]
That's not something an app developer can change. The app chooser in your screenshots is triggered but is not populated by Yalp Store.

Here is how it works:
* The app (Yalp Store) says it wants to open a link. It can not choose the app to open it.
* The OS looks for all the apps which can open this link looking at their manifests.
* The user chooses the app.
