### ISSUE TITLE
Unable to install paid apps

### ISSUE THREAD

**Issue by ReekyMarko** [yeriomin/YalpStore#462]
Just bought a new app and I can't seem to install it. Also tried uninstalling another previously installed purchased app and I can't install it again. Seems that Yalp Store can't detect I have bought it.

Anyone else come across this issue?

_I can provide Logcat later if requested_ 

--- 

- **Yalp Store version:** 0.41 
- **OS:** LineageOS for microG 15.1-20180521 Android 8.1.0
- **Device:** OnePlus 3T

**Comment by JonnyTech** [comment]
Are you logged in with your account? Upon install Yalp uses a dummy account and you need to log out of that then log in with your own Play Store details.

**Comment by yeriomin** [comment]
> I can't seem to install it. 

What happens instead? An error? Something else?

**Comment by gabrielkulp** [comment]
I'm having the same problem. Apps that I have bought still show the price on the download button, as though I have not bought it. I'm logged in with the account that owns it.

- **Yalp Store version:** 0.41
- **OS:** LineageOS for microG 14.1-20180523 Android 7.1.2
- **Device:** Axon 7 (ZTE A2017U)

**Comment by yeriomin** [comment]
@ReekyMarko @gabrielkulp Does manual downloading work? If not, does clearing app data (or reinstalling Yalp Store) help?

**Comment by Jazzpilz** [comment]
I have the same issue (Bought apps show price and no download happening upon click event). I logged in and out several times without use.

- Yalp Store version: 0.41
- OS: Fairphone Open OS / Android 6.0.1 / microG Services Core 0.2.4-103-....
- Device: Fairphone 2

@yeriomin I will try your suggested steps and report back.

**Comment by ReekyMarko** [comment]
@gabrielkulp @yeriomin Same here. Manual download works but clearing app data does not help.

**Comment by Dazrok2** [comment]
@ReekyMarko @yeriomin I face the same problem, what I did is to restore old instance from titanium backup and it did work, the old one is version 0.41 but from couple of days ago.

**Comment by yeriomin** [comment]
This is linked to #396. Apparently, I made some incorrect assumptions while implementing it. It has to be rolled back, unfortunately.

**Comment by maracuja-juice** [comment]
Should this now be fixed? Because I have the same error now on the newest version I just installed.
