### ISSUE TITLE
Glitch in displayed app version string

### ISSUE THREAD

**Issue by Rikk** [yeriomin/YalpStore#463]
Look at the version displayed:
![screenshot_2018-05-24](https://user-images.githubusercontent.com/2916485/40479265-8c32441a-5f21-11e8-95e8-b96140b3ce81.png)
Is there some escaping problem?

**Comment by Rikk** [comment]
Off-topic, about the material interface, thanks for fixing the proportions of the cover image... But I think the black bar (which receives the animated title) stays over the cover too much, do you have an idea on how to make it less visible and to reduce the amount it covers the cover image? Otherwise, I would feel better with an option to disable the loading of the cover image, which would also improve the loading speed of app pages.

**Comment by yeriomin** [comment]
It is not a glitch. Version string can be in any form. Why the maintainer decided to release a package with such version string is a different question.

>But I think the black bar (which receives the animated title) stays over the cover too much

It shouldn't be there. Please send me some (any) feedback through main menu -> Report an issue. With your name on it, so that I could find it.

**Comment by Rikk** [comment]
Nvm, sorry for not taking a look in the original Play Store, the error is also visible there.

About the bar, may we talk here on GitHub (maybe in a new Issue)? Or is it better for you via e-mail?

**Comment by yeriomin** [comment]
We can talk in the corresponding issue #439 or by email if you want: yalp.store.dev@gmail.com
