### ISSUE TITLE
[BUG]Null in app page

### ISSUE THREAD

**Issue by nagayev** [yeriomin/YalpStore#465]
I open page of Talking Tom Jetski 2(coming soon).
And I saw null in app's page.
Yalp:0.40
Android:6.0
Device:Meizu U10
Link to app:
https://play.google.com/store/apps/details?id=com.outfit7.talkingtomjetski2
UPD:Something went wrong and I can't upload screenshot.
Just see app's page yourself.
Developer: Outfit7 Limited ,null,Contains ads.

**Comment by yeriomin** [comment]
Cannot reproduce.

Current version is [0.41](https://f-droid.org/en/packages/com.github.yeriomin.yalpstore/).

**Comment by nagayev** [comment]
@yeriomin this bug was fixed in 0.41
I see Depends on:nothing
Thanks for fixing!
