### ISSUE TITLE
Auto update for Yalp-store-OTA

### ISSUE THREAD

**Issue by momo42** [yeriomin/YalpStore#466]
Some months ago I installed yalp-store-ota-35.zip because I wanted Yalp to be able to update apps in background. Sure, Yalp can install itself as a system app but I'm on LineageOS and in my understanding this method is not persistent regarding weekly system updates. (Please correct me if I'm wrong!)
I have installed F-Droid privileged extension and Yalp OTA on all of my family's Android devices to make sure everything (apart from LineageOS) can be updated without user interaction.

Today I recognized that all of our Android devices are still on Yalp 35. F-Droid was not able to update Yalp because of different signatures...

Other built in system apps seem to be updatable by newer versions signed by the same signature. So is it possible to have the Github builds signed by the same signature than the F-Droid builds? Or if this is not possible would you please implement a way for Yalp OTA to update itself?

Or do I overlook something? What can I do to have a persistent solution for automated background updates for all apps incl. Yalp?

**Comment by yeriomin** [comment]
> So is it possible to have the Github builds signed by the same signature than the F-Droid builds?

Technically impossible.

> Or if this is not possible would you please implement a way for Yalp OTA to update itself?

As far as I know no app can update itself (f-droid can only update itself in foreground, because a system window runs the update, not f-droid itself). An app needs to be terminated for its apk to be replaced. Yalp Store tells you if an update is available, and lets you download it, but not in background.

Also, there is no need to update the actual OTA apk. It is kept in the system for signature checking purposes only. The updates are installed into the ordinary user accessible space, so both apks are present in the system.

> What can I do to have a persistent solution for automated background updates for all apps incl. Yalp?

Right now you can do the following to let f-droid update Yalp Store:
1. take the OTA zip from the [releases page](https://github.com/yeriomin/YalpStore/releases)
2. download Yalp Store apk from [f-droid](https://f-droid.org/packages/com.github.yeriomin.yalpstore/)
3. rename it into YalpStore.apk
4. put into the OTA zip replacing the original apk
5. fully uninstall Yalp Store from your device (both in system partition and user partition)
6. flash the zip you made

Or you can let Yalp Store self-update in foreground.
![screenshot_yalp_store_20180528-014517](https://user-images.githubusercontent.com/554737/40591390-f2bb8b34-6218-11e8-914f-1938d34f3d24.png)

**Comment by momo42** [comment]
Hello yeriomin,
thanks for this very helpful and clear explanation (and of course for this great app).
I use the (now automated) whitelist in yalp and only put apps on it I installed by Yalp. Yalp itself was not ticked till now! So I didn't even recognize that Yalp store is able to pull "Yalp updates" (from Github?) while it itself is not in google play. :-) (I know that updating the OTA itself is not necessary but I thought the only possible way to "update" the OTA was to manually download new APKs from Github.)

Great to hear that Yalp is able to update itself in the foreground. I did this on my own phone now but I think flashing the modified OTA and having auto updates is the best way to go for my family's phones.

Three more questions:

1) How do I correctly uninstall a previously flashed Yalp-OTA? (Don't want to break something)

2) Would it be possible to put a "F-Droid signed" OTA as flashable ZIP into F-Droid too? F-Droid uses something like this too to distribute its own OTA.zip to the people. See: https://f-droid.org/packages/org.fdroid.fdroid.privileged.ota/ (You can download the ZIP to your pc or "install" it to your phone by F-Droid but you have to flash the zip by TWRP afterwards of course.)

I assume a lot of people who install your OTA version would like to have it (auto) updated by F-Droid. So it would be nice to have your explanation in the Wiki section and even better your explanation plus a link to the yalp-ota.zip on F-Droid. ;-)

3) You said that there is no app that is able to update itself in the background (what absolutely makes sense to me when I think about it). Wouldn't it be nice to have F-Droid backround-updated by Yalp and vice versa? Just thinking ... ;-)

**Comment by yeriomin** [comment]
1. The same way you delete any other system app.
2. 

> Would it be possible to put a "F-Droid signed" Yalp-OTA as flashable ZIP into F-Droid too?

This requires talking to f-droid devs. I cannot answer this right now.

> So it would be nice to have your explanation in the Wiki section

It is mentioned in the README. I don't think explaining anything further is required. It is an ordinary flashable zip. The process of flashing is not something which needs to be explained in this repo. It does not concern Yalp Store specifically and is easily googlable. People who know what they are looking for will find it, people who don't - won't be tempted to do a potentially destructive operation.

3. That would require making Yalp Store an F-Droid client. This has been asked before. I'm not planning to implement any other apk source in Yalp Store. Sorry. Also, see this: #362.

**Comment by momo42** [comment]
> The same way you delete any other system app.
Ok thanks for that info. Didn't have to uninstall a system app before. Now I know what to search for.

> The process of flashing is not something which needs to be explained in this repo.
No, I didn't think of the process of flashing a .zip but of replacing the apk inside the .zip by a F-Droid signed one to get a F-Droid updateable Yalp system app. I didn't know that this is so easy. This is a precious piece of information and should be conserved in the wiki faq instead of some closed issue! :-)

> I'm not planning to implement any other apk source in Yalp Store. Sorry.
Thank you anyway. I understand and fully respect this decision.

By the way: I'm on Android Nougat and I really like the way Yalp looks. Don't let yourself be rushed with implementing some material design stuff. Me and my whole family like Yalp very much for its functionality. Design guidelines come and go. If Yalp has material design some time its ok too but it is absolutely not essential to us.
