### ISSUE TITLE
Not downloading the assets from "World of Yo-Ho"

### ISSUE THREAD

**Issue by arthurlutz** [yeriomin/YalpStore#467]
### Expected behaviour
Tell us what should happen yalp should download the APK and the assets content

### Actual behaviour
Yalp downloads the APK for https://play.google.com/store/apps/details?id=com.volumique.yoho but not the media files (> 400Mo)

### Steps to reproduce
1. select "World of Yo-Ho"
2. Download
3. Install APK
4. The application fails not finding the assets

Maybe this is a bug of the upstream application, if so can you suggest me how to report it back to the developers ?

**Comment by nagayev** [comment]
@arthurlutz 
Yalp Store's version?

**Comment by arthurlutz** [comment]
@nagayev2002 sorry for the late response yalp version 0.43

**Comment by yeriomin** [comment]
@arthurlutz Both 0.42 and 0.43 successfully downloaded obbs for the app you mentioned. And even if Yalp Store fails to download them, the app itself must be able to download them on launch. See the documentation quote above.
