### ISSUE TITLE
[Request] Downloading obb updates to Downloads folder...

### ISSUE THREAD

**Issue by leopard20** [yeriomin/YalpStore#470]
Can you please add an option to download the obb delta updates to Downloads folder and applying them to /data/media/obb instead of /sdcard/obb for rooted phones?
The reason I want this is because my phone has locked access to /sdcard/obb and I can't download obb updates. See this issue https://github.com/yeriomin/YalpStore/issues/469

**Comment by yeriomin** [comment]
I don't think that's a good idea:

* as you've mentioned, this is likely your device's problem only. On all devices I have `/data/media/obb` is a link to `<shared storage>/Android/obb/`
* even if the obb files are not downloaded by Yalp Store, the downloaded app should work. Quoting [docs](https://developer.android.com/google/play/expansion-files#DownloadProcess):

> Caution: It is critical that you include the necessary code to download the expansion files from Google Play in the event that the files are not already on the device when your application starts. As discussed in the following section about Downloading the Expansion Files, we've made a library available to you that greatly simplifies this process and performs the download from a service with a minimal amount of code from you.
