### ISSUE TITLE
Are the downloaded APKs automatically installed?

### ISSUE THREAD

**Issue by bsto** [yeriomin/YalpStore#474]
Assume I downloaded an APK through YalpStore.
As far as I read this APK is put into Download directory of my Android.
Ok.

But is it afterwards automatically installed as well or do I have to do this manually afterwards?

Ben

**Comment by switchtegrax1** [comment]
Yalp by default will ask you to press the install button/notification but you can enable automatic instalation in the settings

**Comment by yeriomin** [comment]
Up to you.

By default when download completes, you are shown a notification and a toast telling you what to do.

You can make Yalp Store install downloaded apks automatically in settings.

**Comment by bsto** [comment]
Is it required for auto-installation that the SmartPhone is rooted?

**Comment by switchtegrax1** [comment]
No but on unrooted devices the standard app install screen will appear when automatic install is on

**Comment by yeriomin** [comment]
@bsto If by auto-installation you mean automatic installation start as soon as the download completes, then no, you don't need root.

You need root to periodically install app updates in background.
