### ISSUE TITLE
Make icons and text in"Your Apps" list smaller?

### ISSUE THREAD

**Issue by bsto** [yeriomin/YalpStore#476]
I prefer to use smaller fonts especially in a list like "Your apps" of Yalp.

Can I somehow shrink the icons and shrink the app name font size?

If not: Can this be added in the next release?

Ben

**Comment by yeriomin** [comment]
This is a matter of taste/opinion. Making any changes based on that is a very bad idea.

Also, it is a design issue. Doing this properly requires making Yalp Store UI customizable. This contradicts with Yalp Store's priorities: size and backwards compatibility.
