### ISSUE TITLE
Ignore updates for apps installed from another source (like F-Droid)

### ISSUE THREAD

**Issue by token0** [yeriomin/YalpStore#479]
**Is your feature request related to a problem? Please describe.**
I have both YalpStore and F-Droid, but YalpStore advertises updates for all installed apps, including those from F-Droid.

**Describe the solution you'd like**
I want to see updates only for those apps that were installed by YalpStore

Thanks!

**Comment by momo42** [comment]
You can enable the automated whitelist to archive exact this behavior. Maybe you have to put some previously installed apps on the list manually, but afterwards new installed apps (by Yalp) go there automatically. I also use F-Droid and Yalp and this setup works for me. :-)

**Comment by techge** [comment]
#385, #343, #69, #39

**Comment by zilti** [comment]
While you're at it, you might also remove the Blacklist feature, because it's completely broken. It gets reset on every reboot.

**Comment by techge** [comment]
> While you're at it, you might also remove the Blacklist feature, because it's completely broken. It gets reset on every reboot.

Sorry, but for me this sounds a) very unkind and is b) not helpful to debug and c) this is (if at all) another issue and does not fit here.

**Comment by yeriomin** [comment]
@token0 
> I want to see updates only for those apps that were installed by YalpStore

There is an autowhitelist option in the settings. Turn the whitelist on and the *auto*whitelist option will become enabled. This issue is a duplicate. See the issues mentioned by @techge for more details.

@zilti 
>because it's completely broken. It gets reset on every reboot.

Cannot reproduce. It *is* unrelated to this issue. Use the built-in feedback tool, it sends me info about your device and latest logs.
