### ISSUE TITLE
Many apps marked as not compatible with the device

### ISSUE THREAD

**Issue by rugk** [yeriomin/YalpStore#483]
**Expected behavior**
All usual apps should work.

**Actual behavior**
Firefox & more marked as "Incompatible with this device".

**Steps to reproduce**
1. I changed nothing. Since a few months or so, many apps are marked as "incompatible with the dervice" and I did not even got update notifications. My settings were set to "not fake device data".

**Your setup**
LineageOS 14.1, jlfteex

When switching to a faked device flavor, I've sent you a report when YalpStore asked me, so you should be able to check out what it reported before.

**Comment by yeriomin** [comment]
> Firefox & more marked as "Incompatible with this device".

Tried it with both Google Pixel and my own device info. Success both times.

> I've sent you a report when YalpStore asked me, so you should be able to check out what it reported before.

Searching for rugk gives me no reports, they are anonymous by default. Please send me a report with your name or this issue number.

**Comment by rugk** [comment]
I had no way to enter a username or so.
And now it works though.

**Comment by yeriomin** [comment]
Both fields on the feedback form are freeform text fields. One is for the identification, one is for your message.

**Comment by rugk** [comment]
Actually it was just a message " Do you want to send feedback? " I clicked in yes and thought, that's it. Maybe I missed finding it there is another bug, but nothing happened afterwards.

**Comment by yeriomin** [comment]
There is a "Report an issue" item in the main menu.

**Comment by rugk** [comment]
Ah okay, did not use it. I just got this message directly.

**Comment by kosamja** [comment]
game town of salem marked incompatible for android 4.4 but can be installed
