### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jessemclaren** [yeriomin/YalpStore#485]
An "erase search" option.  (And thanks again for this development.  Superb app.)

**Comment by yeriomin** [comment]
I'm not sure what you mean. Please explain.

**Comment by jessemclaren** [comment]
Not really a significant item, but if I hit the 'back' button (to exit the app, for example) when I'm on the 'update' page (or any other) it takes me through screen after screen of my previous app store searches.  A minor irritation if I've done several searches.
Maybe I'm overlooking something obvious?

**Comment by yeriomin** [comment]
That's actually a feature requested some time ago. Making it customizable without breaking backwards compatibility is not possible technically. Sorry.
