### ISSUE TITLE
Копирования текста из сводки по приложению

### ISSUE THREAD

**Issue by Baltazar500** [yeriomin/YalpStore#487]
Возможности копирования текста из инфо по приложению крайне ограничены. Текстовыделители появляются только в блоках с описанием. Очень не хватает возможности выделить и скопировать мейл разработчика или исходное имя пакета.

**Comment by yeriomin** [comment]
> Возможности копирования текста из инфо по приложению крайне ограничены

Они есть. Yalp Store не текстовый редактор. Чего может не хватать?

> Очень не хватает возможности выделить и скопировать мейл разработчика

Email разработчика - ссылка.

> исходное имя пакета

Можно добавить.

**Comment by Baltazar500** [comment]
[quote]Yalp Store не текстовый редактор.[/quote]Так я и не собираюсь там ничего редактировать, мне лишь нужно получить данные :)[quote]Чего может не хватать?[/quote]Ну например этих данных http://sendpic.org/view/1/i/yQh5i2ur3vAw1GxNI9grIetP3ye.jpg или этих http://sendpic.org/view/1/i/czLzWcRuy6XVB9RPsdNATgnkDKi.jpg[quote]Email разработчика - ссылка.[/quote]У меня открывается почтовый клиент, которым я не пользуюсь http://sendpic.org/view/1/i/3T8KyBOD4QL4u00EKGg7ihx5jai.jpg

**Comment by yeriomin** [comment]
> Ну например этих данных http://sendpic.org/view/1/i/yQh5i2ur3vAw1GxNI9grIetP3ye.jpg или этих http://sendpic.org/view/1/i/czLzWcRuy6XVB9RPsdNATgnkDKi.jpg

Целиком скопировать не удастся, так как это разные View, а по отдельности смысла не вижу.

> У меня открывается почтовый клиент

Так и задумано. Ad-hoc решение вместо предложенного операционкой и рекомендуемого разработчиком операционки - не выход.
