### ISSUE TITLE
Additional Mock Device Request

### ISSUE THREAD

**Issue by gadget78** [yeriomin/YalpStore#489]
Any chance of adding Mock device, **Roku Stick+ ?**
mainly because this device supports iPlayer 4k streaming

there are other devices that also support this, one may even be in the large list 
[https://github.com/yeriomin/play-store-api/tree/alldevices/src/main/resources](on your playstore api area)
but its not named very well to find them it seems, unless ive missed something ?

there is a large list on the iPlayer site with models etc ... 
[https://www.bbc.co.uk/iplayer/help/live-uhd](BBC's FAQ live UHD)
have roughly tried to marry one up from the 3000 odd devices you already have but wasnt able to find a match :(

i will be using it on the Nvidia Shield TV , so it will be more than able to cope :) 
Many thanks for reading, and for this app, 
its already helped me loads in keeping other non native apps current, especially all the other UK on-demand apps

Mick

**Comment by yeriomin** [comment]
Hello.

I'm glad you find Yalp Store useful.

Unfortunately, I have no *active* way to get more device definitions. All the device definitions I got were submitted by users. Once every couple of months I take all new or updated device definitions from my bug report storage and put them into the repo you mentioned (did it today). Maybe someone submits it in future.

> but its not named very well

GitHub can search *inside* files too. There is no "Roku", though. I checked. Sorry.

Regards.
