### ISSUE TITLE
Updated German (de) translation

### ISSUE THREAD

**Issue by Switch123456789** [yeriomin/YalpStore#49]
I have updated the german translation of your application.
```xml
<!-- File "array.xml" -->
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string-array name="blackOrWhiteValues">
        <item>schwarz</item>
        <item></item>
    </string-array>
    <string-array name="uiThemeValues">
        <item>nichts</item>
        <item></item>
        <item></item>
        <item></item>
    </string-array>
</resources>

<!-- File "strings.xml" -->
<resources>
    <string name="list_line_2_updatable" formatted="false">Aktualisiert am %s</string>
    <string name="list_line_2_search" formatted="false">%s ↓, %.1f★, %s</string>
    <string name="list_empty_updates">Keine Aktualisierungen vorhanden</string>
    <string name="list_empty_search">Keine Apps gefunden</string>
    <string name="action_settings">Einstellungen</string>
    <string name="action_logout">Abmelden</string>
    <string name="action_search">Suchen</string>
    <string name="action_updates">Aktualisierungen</string>
    <string name="action_ignore">Updates ignorierennn</string>
    <string name="action_unignore">Updates nicht ignorieren</string>
    <string name="action_whitelist">Whitelist für Updates</string>
    <string name="action_unwhitelist">Ignoriere Updates</string>
    <string name="search_title">Suche nach Anwendungen</string>
    <string name="dialog_two_factor_cancel">Nicht jetzt</string>
    <string name="dialog_two_factor_create_password">Passwort erstellen</string>
    <string name="dialog_title_two_factor">2-Schritte Verifikation</string>
    <string name="dialog_message_two_factor">Für dieses Konto wurde die 2-Faktor-Verifizierung aktiviert.\n\nBitte erstelle ein seperates Passwort für die Yalp Store-App und melde dich damit im Yalp Store an.\n\nTippe auf \"Passwort erstellen\" um auf die Seite zum erstellen eines Passwortes weitergeleitet zu werden.</string>
    <string name="dialog_title_logout">Abmelden?</string>
    <string name="dialog_message_logout">Sind Sie sicher dass Sie sich abmelden möchten?</string>
    <string name="dialog_title_reviews">Empfange Vorschauen:</string>
    <string name="dialog_message_reviews">Bitte warten. Empfange Vorschauen.</string>
    <string name="dialog_title_purchasing_app">Lade die App herunter</string>
    <string name="dialog_message_purchasing_app">Bitte warten. Der Download der gewählten App wird gestartet.</string>
    <string name="dialog_title_loading_app_details">Hole Details</string>
    <string name="dialog_message_loading_app_details">Bitte warten. Es werden Details zu der gewählten App geladen.</string>
    <string name="dialog_title_loading_app_list_search">Suchen</string>
    <string name="dialog_message_loading_app_list_search">Bitte warten. Es wird nach Apps gesucht.</string>
    <string name="dialog_title_loading_app_list_update">Suche nach Aktualisierungen</string>
    <string name="dialog_message_loading_app_list_update">Bitte warten. Es wird nach neueren Versionen ihrer App gesucht.</string>
    <string name="error_incorrect_password">Email-Adresse oder Passwort sind falsch</string>
    <string name="error_credentials_empty">Bitte bestätigen Sie zuerst Ihr Google Konto.</string>
    <string name="error_no_network">Keine Netzwerkverbindung</string>
    <string name="error_network_other" formatted="false">Netzwerk error: %s</string>
    <string name="error_not_purchased">Diese App wurde scheinbar nicht gekauft.</string>
    <string name="error_downloads_directory_not_writable">Download-Ordner konnte nicht erstellt werden oder ist nicht beschreibbar.</string>
    <string name="details_installs" formatted="false">%s ↓</string>
    <string name="details_rating" formatted="false">%.1f★</string>
    <string name="details_rating_specific" formatted="false">%d★ %d</string>
    <string name="details_updated" formatted="false">Aktualisiert %s</string>
    <string name="details_size" formatted="false">Apk größe %s</string>
    <string name="details_description">Beschreibung:</string>
    <string name="details_changelog">Was gibt es neues?</string>
    <string name="details_screenshots">Bildschirmaufnahmen:</string>
    <string name="details_reviews">Vorschauen:</string>
    <string name="details_rate_this_app">Bewerte diese App:</string>
    <string name="details_you_rated_this_app">Du bewerteste diese App:</string>
    <string name="details_permissions">Berechtigungen:</string>
    <string name="details_developer" formatted="false">Bereitgestellt von %s</string>
    <string name="details_versionName" formatted="false">Version %s</string>
    <string name="details_versionName_updatable" formatted="false">Version %s → %s</string>
    <string name="details_download">Herunterladen</string>
    <string name="details_install">Installieren</string>
    <string name="details_downloading">Herunterladen…</string>
    <string name="details_download_impossible">Fehler. App-Version konnte nicht ermittelt werden.</string>
    <string name="details_review_dialog_title">Noch etwas hinzuzufügen?</string>
    <string name="details_review_dialog_review_title_hint">Titel</string>
    <string name="details_review_dialog_review_comment_hint">Kommentar</string>
    <string name="details_review_dialog_fields_optional">Du kannst alles leer lassen.</string>
    <string name="details_apps_by_this_dev">Weitere Apps von diesem Entwickler</string>
    <string name="details_similar_apps">Ähnliche Apps</string>
    <string name="details_users_also_installed">Apps die Nutzer auch installierten</string>
    <string name="suffix_million">Million</string>
    <string name="suffix_billion">Billion</string>
    <string name="credentials_hint_email">E-mail</string>
    <string name="credentials_hint_password">Passwort</string>
    <string name="credentials_title">Google Konto Zugang</string>
    <string name="credentials_message">Damit diese App funktioniert werden eine Google Mail Adresse und ein Passwort benötigt. \nSeinen Sie sich bewusst dass die Benutzung dieser App die ToS des Play Stores verletzt. Es ist wahrscheinlich sicherer ein wegwerf Google Konto zu benutzen, mit dem man sich schon einmal im Play Store angemeldet, und die ToS akzeptiert hat.</string>
    <string name="activity_title_updates">Aktualisierungen</string>
    <string name="activity_title_search" formatted="false">Suche: \"%s"</string>
    <string name="notification_download_complete">Herunterladen abgeschlossen. Tippen zum Installieren.</string>
    <string name="notification_download_complete_toast" formatted="false">%s heruntergeladen. Benachrichtigung antippen zum Installieren.</string>
    <string name="pref_hide_nonfree_apps_summary_off">Kostenpflichte Apps werden angezeigt</string>
    <string name="pref_hide_nonfree_apps_summary_on">Kostenpflichtige Apps werden nicht angezeigt</string>
    <string name="pref_hide_nonfree_apps">Verstecke kostenpflichtige Apps</string>
    <string name="pref_auto_install_summary_off">Apps werden installiert sobald die Benachrichtigung des abgeschlossenen Downloads angetippt wird</string>
    <string name="pref_auto_install_summary_on">Apps werden installiert sobald der Download abgeschlossen ist.</string>
    <string name="pref_auto_install">Apps sofort installieren.</string>
    <string name="pref_update_list_white_or_black_black">Nur für Ausgewählte Apps werden keine Aktualisierungen gesucht</string>
    <string name="pref_update_list_white_or_black_white">Nur für Ausgewählte Apps werden Aktualisierungen gesucht</string>
    <string name="pref_update_list_white_or_black">Black- oder Whitelist für App-Aktualisierungen verwenden</string>
    <string name="pref_update_list_black">App-Blacklist verwalten</string>
    <string name="pref_update_list_white">App-Whitelist verwalten</string>
    <string name="pref_ui_theme">Design</string>
    <string name="pref_ui_theme_none">Standard</string>
    <string name="pref_ui_theme_light">Hell</string>
    <string name="pref_ui_theme_dark">Dunkel</string>
    <string name="pref_ui_theme_black">Schwarz</string>
    <string name="download_manager_ERROR_UNKNOWN">Unbekannter Fehler.</string>
    <string name="download_manager_ERROR_FILE_ERROR">Unbekannter Datei Speicherfehler.</string>
    <string name="download_manager_ERROR_UNHANDLED_HTTP_CODE">Es wurde ein HTTP-Code empfangen den die Download-Verwaltung nicht verarbeiten kann. Dies ist ein Serverfehler.</string>
    <string name="download_manager_ERROR_HTTP_DATA_ERROR">Fehler beim Empfangen oder Verarbeiten von Daten auf der HTTP-Ebene.</string>
    <string name="download_manager_ERROR_TOO_MANY_REDIRECTS">Zu viele Umleitungen.</string>
    <string name="download_manager_ERROR_INSUFFICIENT_SPACE">Ungenügend freier Speicher.</string>
    <string name="download_manager_ERROR_DEVICE_NOT_FOUND">Es wurde kein externer Speicher gefunden. Möglicherweise ist die SD-Karte nicht eingehangen.</string>
    <string name="download_manager_ERROR_CANNOT_RESUME">Es trat ein möglicherweise vorübergehender Fehler auf, der Download kann nicht fortgesetzt werden. Versuche es später noch einmal.</string>
    <string name="download_manager_ERROR_BLOCKED">Das Herunterladen ist fehlgeschlagen weil der Netzwerk-Richtlinien-Manager die Kontrolle über die anfordernte App hat.</string>
</resources>


```
*Translation made with [Stringlate](https://github.com/LonamiWebs/Stringlate).*

I love this app, thanks for your effort! <3

**Comment by bezcitu** [comment]
@Switch123456789 
Sorry, but your "updated German translation" is full of mistakes.

For instance:
- `<string name="action_ignore">Updates ignorierennn</string>` → ignorieren
- `<string name="dialog_title_two_factor">2-Schritte Verifikation</string>` → Zwei-Faktor-Authentifizierung
- `<string name="details_changelog">Was gibt es neues?</string>` → Neues
- `<string name="suffix_billion">Billion</string>` → Milliarde

These are only examples. **There are many more mistakes, not only wrongly translated words, but also sentences which differ from German spelling rules.**

**Comment by Switch123456789** [comment]
Thanks! Tbh, I fixed all mistakes which came from the source file. But for some reason Stringlate deleted them/did not save them, it only saved the new ones. I'm sorry, I will have to investigate that. I'm all new to the technical aspects, but I'm very convinced about my german skills. :)

**Comment by Switch123456789** [comment]
I switched to Android Studio Translation Editor to make sure everything is fine this time (Stringlate is still not working for me). I also double-checked all strings by examining the raw code.

`<resources>
    <string name="list_line_2_updatable" formatted="false">Aktualisiert am %s</string>
    <string name="list_line_2_search" formatted="false">%s ↓, %.1f★, %s</string>
    <string name="list_empty_updates">Es müssen keine Apps aktualisiert werden</string>
    <string name="list_empty_search">Keine Apps gefunden</string>
    <string name="action_settings">Einstellungen</string>
    <string name="action_logout">Abmelden</string>
    <string name="action_search">Suchen</string>
    <string name="action_updates">Aktualisierungen</string>
    <string name="action_ignore">Ignoriere Updates</string>
    <string name="action_unignore">Ignoriere Updates nicht mehr</string>
    <string name="action_whitelist">Whitelist für Updates</string>
    <string name="action_unwhitelist">Ignoriere Updates</string>
    <string name="search_title">Suche nach Apps</string>
    <string name="dialog_two_factor_cancel">Jetzt nicht</string>
    <string name="dialog_two_factor_create_password">Passwort erstellen</string>
    <string name="dialog_title_two_factor">Zwei-Faktor-Authentifizierung</string>
    <string name="dialog_message_two_factor">Für dieses Konto wurde die Zwei-Faktor-Authentifizierung aktiviert.\n\nBitte erstelle ein separates App-Passwort für Yalp Store und melde dich damit hier an.\n\nTippe auf \"Passwort erstellen\" um auf die Seite zum Erstellen eines Passwortes zu gelangen.</string>
    <string name="dialog_title_logout">Abmelden?</string>
    <string name="dialog_message_logout">Bist du sicher dass du dich abmelden möchtest?</string>
    <string name="dialog_title_reviews">Lade Bewertungen</string>
    <string name="dialog_message_reviews">Bitte warten! Empfange Vorschauen.</string>
    <string name="dialog_title_purchasing_app">Lade App herunter</string>
    <string name="dialog_message_purchasing_app">Bitte warten! Starte das Herunterladen der gewählten App.</string>
    <string name="dialog_title_loading_app_details">Lade Details</string>
    <string name="dialog_message_loading_app_details">Bitte warten! Details der gewählten App werden ermittelt.</string>
    <string name="dialog_title_loading_app_list_search">Suche</string>
    <string name="dialog_message_loading_app_list_search">Bitte warten! Suche nach Apps.</string>
    <string name="dialog_title_loading_app_list_update">Suche nach Aktualisierungen</string>
    <string name="dialog_message_loading_app_list_update">Bitte warten! Deine Apps werden auf Aktualisierungen geprüft.</string>
    <string name="error_incorrect_password">Email-Adresse oder Passwort falsch.</string>
    <string name="error_credentials_empty">Bitte trage die Anmeldedaten des Google Kontos ein.</string>
    <string name="error_no_network">Keine Netzwerkverbindung.</string>
    <string name="error_network_other" formatted="false">Netzwerk-Fehler: %s</string>
    <string name="error_not_purchased">Diese App wurde scheinbar nicht gekauft.</string>
    <string name="error_downloads_directory_not_writable">Download-Ordner konnte nicht erstellt werden oder ist nicht beschreibbar.</string>
    <string name="details_installs" formatted="false">%s ↓</string>
    <string name="details_rating" formatted="false">%.1f★</string>
    <string name="details_rating_specific" formatted="false">%d★ %d</string>
    <string name="details_updated" formatted="false">Aktualisiert %s</string>
    <string name="details_size" formatted="false">Apk größe %s</string>
    <string name="details_description">Beschreibung:</string>
    <string name="details_changelog">Neuigkeiten:</string>
    <string name="details_screenshots">Bildschirmfotos:</string>
    <string name="details_reviews">Bewertungen:</string>
    <string name="details_rate_this_app">Bewerte diese App:</string>
    <string name="details_you_rated_this_app">Du bewertest diese App:</string>
    <string name="details_permissions">Berechtigungen:</string>
    <string name="details_developer" formatted="false">Angeboten von %s</string>
    <string name="details_versionName" formatted="false">Version %s</string>
    <string name="details_versionName_updatable" formatted="false">Version %s → %s</string>
    <string name="details_download">Herunterladen</string>
    <string name="details_install">Installieren</string>
    <string name="details_downloading">Herunterladen…</string>
    <string name="details_download_impossible">Fehler. App-Version konnte nicht ermittelt werden.</string>
    <string name="details_review_dialog_title">Noch etwas hinzuzufügen?</string>
    <string name="details_review_dialog_review_title_hint">Titel</string>
    <string name="details_review_dialog_review_comment_hint">Kommentar</string>
    <string name="details_review_dialog_fields_optional">Du kannst alles leer lassen.</string>
    <string name="details_apps_by_this_dev">Weitere Apps von diesem Entwickler</string>
    <string name="details_similar_apps">Ähnliche Apps</string>
    <string name="details_users_also_installed">Apps die Nutzer auch installierten</string>
    <string name="suffix_million">Million</string>
    <string name="suffix_billion">Milliarde</string>
    <string name="credentials_hint_email">E-Mail</string>
    <string name="credentials_hint_password">Passwort</string>
    <string name="credentials_title">Google Konto Zugang</string>
    <string name="credentials_message">Für die Verwendung dieser App wird eine Google E-Mail Adresse und ein Passwort benötigt.\nVergiss nicht das die Verwendung dieser App gegen die Play Store Nutzungsbedingungen verstößt. Wahrscheinlich ist es sicherer ein unwichtiges Google-Konto zu verwenden, welches mindestens einmal im Play Store eingeloggt war um den Nutzungsbedingungen zuzustimmen.</string>
    <string name="activity_title_updates">Aktualisierungen</string>
    <string name="activity_title_search" formatted="false">Suche: \"%s"</string>
    <string name="notification_download_complete">Herunterladen abgeschlossen. Tippe zum Installieren.</string>
    <string name="notification_download_complete_toast" formatted="false">%s heruntergeladen. Tippe Benachrichtigung zum Installieren.</string>
    <string name="pref_hide_nonfree_apps_summary_off">Kostenpflichtige Apps werden angezeigt</string>
    <string name="pref_hide_nonfree_apps_summary_on">Kostenpflichtige Apps werden nicht angezeigt</string>
    <string name="pref_hide_nonfree_apps">Verstecke kostenpflichtige Apps</string>
    <string name="pref_auto_install_summary_off">Apps werden installiert wenn die Abschluss-Benachrichtigung angetippt wird</string>
    <string name="pref_auto_install_summary_on">Apps werden installiert sobald der Download abgeschlossen ist</string>
    <string name="pref_auto_install">Apps sofort installieren.</string>
    <string name="pref_update_list_white_or_black_black">Nur für Ausgewählte Apps werden keine Aktualisierungen gesucht</string>
    <string name="pref_update_list_white_or_black_white">Nur für Ausgewählte Apps werden Aktualisierungen gesucht</string>
    <string name="pref_update_list_white_or_black">Black- oder Whitelist für App-Aktualisierungen verwenden</string>
    <string name="pref_update_list_black">App-Blacklist verwalten</string>
    <string name="pref_update_list_white">App-Whitelist verwalten</string>
    <string name="pref_ui_theme">Design</string>
    <string name="pref_ui_theme_none">Standard</string>
    <string name="pref_ui_theme_light">Hell</string>
    <string name="pref_ui_theme_dark">Dunkel</string>
    <string name="pref_ui_theme_black">Schwarz</string>
    <string name="download_manager_ERROR_UNKNOWN">Unbekannter Fehler.</string>
    <string name="download_manager_ERROR_FILE_ERROR">Unbekannter Datei Speicherfehler.</string>
    <string name="download_manager_ERROR_UNHANDLED_HTTP_CODE">Es wurde ein HTTP-Code empfangen den die Download-Verwaltung nicht verarbeiten kann. Dies ist ein Serverfehler.</string>
    <string name="download_manager_ERROR_HTTP_DATA_ERROR">Fehler beim Empfangen oder Verarbeiten von Daten auf HTTP-Ebene.</string>
    <string name="download_manager_ERROR_TOO_MANY_REDIRECTS">Zu viele Umleitungen.</string>
    <string name="download_manager_ERROR_INSUFFICIENT_SPACE">Ungenügend freier Speicher.</string>
    <string name="download_manager_ERROR_DEVICE_NOT_FOUND">Es wurde kein externer Speicher gefunden. Möglicherweise ist die SD-Karte nicht eingehangen.</string>
    <string name="download_manager_ERROR_CANNOT_RESUME">Es trat ein möglicherweise vorübergehender Fehler auf, der Download kann nicht fortgesetzt werden. Versuche es später noch einmal!</string>
    <string name="download_manager_ERROR_BLOCKED">Das Herunterladen ist fehlgeschlagen weil der Netzwerk-Richtlinien-Manager die Kontrolle über die anfordernte App hat.</string>
</resources>`

**Comment by yeriomin** [comment]
@Switch123456789 Thank you for your contributions! Could you please make `suffix_million` and `suffix_billion` 3-char abbreviations? The reason I have them is to replace "000,000,000" which Play Store puts into number of downloads, which is too long for some screens.

Also, why don't you fork my repo and send translations as pull requests? Github will mark you as a code contributor then!

**Comment by Switch123456789** [comment]
Hey yeriomin, I'll look into it tomorrow and change them.

The simple answer to this question is: I'm a greenhorn. I just registered to github and I'm not aware of how all these routines work here. Thanks for your advice and patience, I will figure this out tommorow too.
