### ISSUE TITLE
how to set vulkan prop support?

### ISSUE THREAD

**Issue by Anehta** [yeriomin/YalpStore#491]
i want to download com.studiowildcard.wardrumstudios.ark
but google return an error:
> This app is incompatible with your device.

maybe i dont set vulkan library prop support?
i need help..

**Comment by yeriomin** [comment]
> vulkan library prop support

Yalp Store has no such option.

> i need help..

Try spoofing some device which supports your game. [Xiaomi MI 5](https://raw.githubusercontent.com/yeriomin/play-store-api/master/src/main/resources/device-gemini.properties) worked for me.
