### ISSUE TITLE
Old FroYo device cannot sign in to google store with builtin account

### ISSUE THREAD

**Issue by freecycler** [yeriomin/YalpStore#493]
I left a post at https://forum.f-droid.org/t/yalp-store-not-able-to-get-apps-from-play-store/2906/10 and user Licaon_Kter suggested I report this here

Copying the other post here:

> On 9 Jun I installed 0.41 (downloaded from f-droid web page, I can’t use the f-droid app because my device is too old) and have this issue(s). Tonight I installed 0.42 (also downloaded from f-droid - is there any difference from the one on github aside from the signature?) and it has the same issue.
> 
> When I try to start it I immediately get the notice that it has crashed and it tries to gather the error report, asks me to describe the problem and brings up the keyboard to type in my comments, but keeps cycling between that and the message that " you can help by describing…" which is again replaced by the keyboard in a loop that runs a dozen or more times. It does not allow me to type anything before repeating the cycle which goes by too quickly to even see all of the error message.
> 
> I did get some progress - I uninstalled, rebooted, reinstalled, then this time did NOT open the app immediately but instead rebooted one more time. Now when I open the app it shows me a list of installed apps and lets me adjust settings. Now when I try to update anything I am asked whether to use my google account or the built-in account. Either way I am immediately told “No network connection” even before I have time to select a choice, I have tried both choices but it is still always the same result. This too is the same for both versions 0.41 and 0.42.
> 
> My device is quite old, so much so that play store cannot run nor can its old browser even visit that page to manually download anything, that is why I wanted to use this app. Huawei Ideos U8150, it runs 2.2 FroYo in case that matters, I was hoping this app would work since so many others are not compatible. Wuijbfek’s solution of using APKUpdater won’t work for me as that needs at least 2.3 Gingerbread but my device is older.
> 
> Any suggestions?
> 

**Steps to reproduce**
1. DL and install Yalp Store
2. Do not open app immediately, instead reboot device first
3. Open Yalp Store, try to check for updates
4. When asked, select to use builtin account

**Expected behavior**
App should open properly at step 3 and after step 4 should complete google signin as needed
**Actual behavior**
If reboot from step 2 is skipped, trying to open app at step 3 gets repeating loop between error message and trying to get keyboard input describing what happened.

Step 4 got error message about no network connection despite working wifi (but no cellular service - is this the problem? What about non-phone tablet type devices?)

**Your setup**
Device model = Huawei Ideos aka U8150-B, 2.2 FroYo, Yalp Store version(s) 0.41, 0.42

(I will try to get in-app report tomorrow, it is getting late right now)

**Comment by freecycler** [comment]
Well I thought I would get the in-app report but it turns out I can't. Trying to do that results in the same repeating loop between an error message and trying to open the keyboard that I got if I skipped the reboot from step 2.

However it seems the device is rooted and I do have a terminal app installed, so I can look through the whole filesystem (albeit tediously due to the very small screen and awkward onscreen keyboard)... are there any file contents it would be useful to look at?

**Comment by yeriomin** [comment]
This *should* be fixed.

No network issue is connected to NetCipher (#447) and is most likely fixed. Circular crashes are definitely fixed, so the in-app feedback tool will work.

> is there any difference from the one on github aside from the signature?

No

> but no cellular service - is this the problem?

No.
