### ISSUE TITLE
Magisk Priv-extension module

### ISSUE THREAD

**Issue by switchtegrax1** [yeriomin/YalpStore#495]
I Would Like to ask permission to publish an magisk module to give yalp the ability to install apks in the background without root systemlessly (without altering the system partition),my module places yalp into a (virtual) priv-app folder which yalp can get all the necessary system permissions for background app installs,if you allow me i will maintain the module with each yalp store update

**Comment by yeriomin** [comment]
Sure. Can I see the source? As long as it is open source, I don't mind.

Please tell the users I'm responsible for the app and not you; tell them you are responsible for the module and not me.

**Comment by switchtegrax1** [comment]
ill build the repo and don't worry i have no intention of taking any credit,you created this app all i did was package it into a magisk module

**Comment by switchtegrax1** [comment]
https://github.com/switchtegrax1/Yalpstorepriv here is the source code

**Comment by switchtegrax1** [comment]
ill wait for your appoval before i submit it to the official magisk repository

**Comment by soredake** [comment]
@yeriomin ping

**Comment by yeriomin** [comment]
Sorry for making you wait. I checked the repo. Please publish, whenever you are ready.

**Comment by switchtegrax1** [comment]
Done,its now on the magisk repo for everyome to enjoy,thank you for making this awesome app and thank you for allowing me to make this into a magisk module
