### ISSUE TITLE
The ability to login to your own Google account

### ISSUE THREAD

**Issue by briantyler7171** [yeriomin/YalpStore#498]
Hi,
I use your app to usually download older versions of apps if I accidentally update and don't like the new features/look/permissions (eg. Snapchat and it's trashy design)

- Problem:  I've downloaded Snapchat 10.21.0.0 and I wanted to theme it with substratum (specifically Swift Black) (which I purchased) but I keep updating that app as they keep fixing theme problems caused by updated apps (eg. Gmail, Instagram, Chrome, etc) and they don't support that version of Snapchat anymore (they keep the 2 latest versions) 

- Probable Solution: Giving us the ability to login to our account, so that we can download paid apps as APK files. (Only if we've purchased it obviously)

- Alternative: The only alternative I've found is getting the app from third party websites which provide them for free but with the risk of installing a malware (I'm not condoning piracy and wouldn't do it myself but this is kind of an alternative)

- Additional Information: Using “[App Watcher](https://play.google.com/store/apps/details?id=com.anod.appwatcher)” I found out that version 12.6 (141) supports Snapchat 
10.21.0.0 and when I tried downloading it with the auto generated login credentials it obviously didn't work..
![screenshot_20180706-020331 01](https://user-images.githubusercontent.com/25663642/42347041-35b730e2-80c2-11e8-9020-f12bb890b42d.png)

**Comment by yeriomin** [comment]
> The ability to login to your own Google account

This has been a feature in Yalp Store since before the ability to log in without. Like @JonnyTech said, Main menu -> Log Out.
