### ISSUE TITLE
updates do not match playstore 

### ISSUE THREAD

**Issue by RootedNewbie** [yeriomin/YalpStore#499]
1. I have many apps initially downloaded and installed from the official Playstore. When I go to Yalp and search for updates, Yalp shows me numerous available updates, almost all old updates (by date). But none of these updates appear in the playstore because they were updated long ago. Why is that? Why the discrepancy? 

I  have screenshots showing 'no updates' in the official playstore and 2 screens of 'updates' available in Yalp.

2. If I accept the (redundant) Yalp updates, does that mess up the update sequence in the playstore? 

Thanks

**Comment by RootedNewbie** [comment]
Thanks for replying.
In settings/spoofing, I am set as 'your original device information'

**Comment by RootedNewbie** [comment]
But your comment may have pointed me in the correct direction. I am rooted and use Xprivacylua which for privacy sends out faulty data. I'll check how to exclude Yalp from Xprivacylua.

**Comment by yeriomin** [comment]
> almost all old updates (by date)

Date does not mean much. The only thing compared is the version code. Yalp Store will show apps as updatable if Play Store says there are apks with greater version codes.

> I have screenshots showing 'no updates' in the official playstore and 2 screens of 'updates' available in Yalp.

Also, Play Store checks for updates for apps which are in the current user's "library". Yalp Store checks for updates for all apps installed on device.

> If I accept the (redundant) Yalp updates, does that mess up the update sequence in the playstore?

There is no such thing as "update sequence". If the version code is greater or equal to the one installed, the update will happen. If the version code is less, the OS will simply deny the update.

> for privacy sends out faulty data

Play Store checks app compatibility using the info sent at login. This "faulty data" would lead to random apks, sometimes incompatible with your device.
