### ISSUE TITLE
Install instead of just downloading

### ISSUE THREAD

**Issue by teod0r** [yeriomin/YalpStore#5]
It'll be more comfortable to not just download an app, but also to run installation automaticaly after downloading

**Comment by yeriomin** [comment]
Pressing "download" doesn't send the user to download manager anymore. Instead, either installation starts (this might be intrusive), or a notification is created. User can choose it in the settings.

**Comment by teod0r** [comment]
У меня сейчас версия 0.4 и при нажатии Download только скачивает, установка не начинается.
Но хотелось бы чтобы это было опционально, тоесть иногда просто скачать, иногда установить. Может, опцией в настройках? Или заместо одной кнопки сделать 2: одну для скачки, другую для установки, сделать одну в левой половине, другую в правой, так что больше места занимать не будут.

**Comment by avently** [comment]
В настройки зайди и посмотри вторую опцию: устанавливать приложения сразу.

**Comment by teod0r** [comment]
Точно. Работает
