### ISSUE TITLE
YalpStore Android Tv

### ISSUE THREAD

**Issue by ankurpathak** [yeriomin/YalpStore#503]
We should have a separate version of YalpStore for Android Tv, which shows only tv apps. This version does not show tv appss.

**Comment by yeriomin** [comment]
> We should have a separate version of YalpStore for Android Tv, which shows only tv apps.

There is no such thing as tv apps. TV apps are ordinary android apps, just like Yalp Store. Some apps might require something tv-specific, but there is no clear distinction between tv and non-tv apps.

> This version does not show tv appss.

It does.

Compatibility filtering is happening on Google's side. If the app you are searching for is not shown, then your device does not support it; consider spoofing a device which does.
