### ISSUE TITLE
Explain contemporary version

### ISSUE THREAD

**Issue by fkoester** [yeriomin/YalpStore#505]
I tried to figure out what the difference is between the "classic" apk and the "contemporary" one but could not find any information on that.

There are now 4 different apks and i think it would be good to have a section explaining them right on the to README.

Thanks for your work!

**Comment by switchtegrax1** [comment]
the contemporary is the material (prettier one) and the other is the standard version

**Comment by fkoester** [comment]
I see, thanks for the explanation! I created [a PR adding this information to the README.md](https://github.com/yeriomin/YalpStore/pull/507).

**Comment by yeriomin** [comment]
There is a discussion about that in #439. I'll be adding an explanation to the release page from now on.
