### ISSUE TITLE
app updates cause crashes

### ISSUE THREAD

**Issue by RootedNewbie** [yeriomin/YalpStore#506]
Lineageos 14.1 with microG on a nexus 5.

Yalp identifies a series of available app updates but when I try to download and install these updates they download but Yalp crashes when attempting to install the updates it identified. Result is I can't use Yalp to replace the playstore. Using Yalp account login.

I've sent several of the automated crash reports.

How do I fix this problem? Please help.

Jeff

**Comment by tomasz1986** [comment]
I had the same problem. It can be fixed by disabling delta updates in the Yalp Store's settings.

**Comment by yeriomin** [comment]
We talked about this through email, haven't we?
