### ISSUE TITLE
Can't download region locked apps

### ISSUE THREAD

**Issue by iceorfire95** [yeriomin/YalpStore#510]
I use yalp to download region locked apps before, but since the last update, this is not possible anymore. They're all free apps, by the way.

**Comment by yeriomin** [comment]
There were no changes in the previous version to affect this. There is also nothing specific in Yalp Store which lets it download region-locked apps. No such feature. See [FAQ](https://github.com/yeriomin/YalpStore#faq).

> not possible

What does it mean? What are you doing? What is happening? Are there errors?

> last update

Which one is it? What version are you using?

**Comment by iceorfire95** [comment]
I'm using the latest version of yalp store on f-droid.
I check for updates for the installed app and when I click on download, it buffers for a while and nothing happens. I used just be able to download the the latest apk. But if there are no specific changes with yalp, then it's probably because of latest updates to Google apps.

**Comment by yeriomin** [comment]
> it's probably because of latest updates to Google apps.

Yalp Store does not depend on Google apps.

Your logs would help.
