### ISSUE TITLE
Unable to log-in to Google account with font / display size increased

### ISSUE THREAD

**Issue by tomasz1986** [yeriomin/YalpStore#517]
I have no access to the device right now, so I cannot provide a screen shot, but the issue basically is that the password field is completely missing from the screen when font and display size are increased in the Android's settings (following https://support.google.com/accessibility/android/answer/6006972).

Without the password field, it is impossible to log in to your own Google account, and you have to use the built-in account. I think that you should be able to simply scroll to the password field if the font or other elements are too large to display both the e-mail and password fields at the same time.

Device: Samsung Galaxy S4 Active LTE-A, Android 7.1 (LineageOS).

**Comment by yeriomin** [comment]
Login dialog has been reworked. The ToS violation disclaimer is going to be shown in a separate dialog.
