### ISSUE TITLE
Unlock Regional Apps

### ISSUE THREAD

**Issue by EMK2000** [yeriomin/YalpStore#52]
Is it possible to support apps that are only available for certain countries? For example, if my Play Store is US version, but I want to download apps that is only available in the China Play Store...

**Comment by yeriomin** [comment]
Short answer is no.

Play Store chooses which apps to show based on your current ip address. Another option is adding a foreign billing address (and only one) and making an actual purchase with it. So you either have to use a proxy, or get a foreign credit card. Neither of those can be accomplished in my app. An apk aggregator  would have to be used for this. Sorry.
