### ISSUE TITLE
There was a problem parsing the package

### ISSUE THREAD

**Issue by janot** [yeriomin/YalpStore#524]
Always getting this when trying to install apks downloaded by Yalp Store on Oreo 8.1 MIUI 9

**Comment by yeriomin** [comment]
Please, follow the issue template, or I won't be able to help you.

You can get the specific reason of failure in android general logs - package installer logs failures.

If it really is happening with ALL the apks, then the problem is probably unique and related to your device/os.

**Comment by janot** [comment]
Sorry, haven't seen templates because of mobile version.

Also it looks like it was indeed somehow connected with another rom. I don't have this problem on current one.
