### ISSUE TITLE
Show notifications on packages being updated

### ISSUE THREAD

**Issue by ildar** [yeriomin/YalpStore#525]
Just see a toast "Package installed"
Installation method: root

**Comment by yeriomin** [comment]
Notification should be shown during background updates installation only. What purpose would the notifications serve when you manually launch the installation by pressing "install"? This would be against [android usability guidelines](https://material.io/design/platform-guidance/android-notifications.html#usage).

**Comment by ildar** [comment]
This is exactly my case. I tap "download" and navigate out (e.g. browse
other apps). I expect that Yalp will download then install then notify me
when done. But currently I don't receive any sign it finished its job

**Comment by ildar** [comment]
Oh, I noticed some toasts: "Application updated". But hey:
(a) they are easy to miss;
(b) not informative

**Comment by yeriomin** [comment]
Toasts should now be shown only if Yalp Store is in foreground. Otherwise - notifications.
