### ISSUE TITLE
Can not access downloaded apks using yalp store mini download manager

### ISSUE THREAD

**Issue by erfanara** [yeriomin/YalpStore#527]
### **Before creating an issue**
version: 0.43
### **Expected behavior**
Downloading apks and having access to them with file manager 
### **Actual behavior**
I disabled android download manager with adb then mini yalp store download manager didn't enable and when I want to download an apk , yalp gives me this error:
 `"unknown file storage error"`.

I enabled mini download manager with setting download location to internal storage in yalp settings.
now I can download apks but when yalp calls apk installer  it gives me this error:
`"there is a problem parsing the package" `.
I think this is not signature mismatch error because yalp gives this error for every app.
I think  because downloaded apk is inaccessible by user , this happened.
usually this error disappear when I open apks from file manager but I can't access to /data/data folder .
### **Your setup**
amazon kindle fire 8
fire os 5.4.1.2

> any help I appreciate it...
> thank you very much ...

**Comment by yeriomin** [comment]
Sorry for answering with such a delay. I cannot be sure, but it seems both internal and external downloaders run into the same problem. Logs might help.

**Comment by erfanara** [comment]
You resolved this problem in version 0.45
But the new download manager has problems that I don't think needs to be reported
Thank you very much :)

**Comment by erfanara** [comment]
In the future I will report important problems
Hope this helps

**Comment by jackTaw88** [comment]
"unknown file storage error" is still happening.
