### ISSUE TITLE
Downloaded APKs with signature missmatch cannot be ignored.

### ISSUE THREAD

**Issue by DPTJKKVH** [yeriomin/YalpStore#528]
Okay, this is an annoying bug. When you install an app with e.g. f-droid and then yalp finds an update to this app on playstore it naturally downloads the new apk, tries to apply it and fails due to signature mismatch. This is what "ignore updates" is for, of course.

But if you fail to ignore updates beforehand and actually download and fail to install the app the "ignore updates" option is gone from the app menu. Instead yalp notifies every hour that there is an update ready to install since it has an apk ready in its internal download folder. There is also no way to remove the downloaded apk.

EDIT: I also noticed that the app is disappearing from the installed apps list (only in yalp) after a failed install due to signature mismatch. Still yalp produces an update notification every hour. When I open the notification yalp opens the update tab but fails to find any app to update.

So what should be done is ~~two~~ three things:

1. Allow ignoring updates even after the apk was downloaded.

2. Give a GUI option within yalp to delete downloaded apks.
 
3. Don't remove apps from the installed apps list after a failed update attempt.

**Comment by Grossdm** [comment]
@DPTJKKVH, I think this may be a bigger issue than even what you have described in such detail.

Let's say that the "ignore updates" list gets fixed, and the F-Droid apps are no longer pestering to be updated.

This still leaves the open question of what happens when the F-Droid repo gets updated to match the app version listed in Google Play. Is the update still going to be ignored?

More than just fixing the "ignore list" issues, I think that Yalp must discriminate by both app version and signature.
How best to present the different updates is another open question.

Thanks to @yeriomin for Yalp,

Doug®

**Comment by yeriomin** [comment]
Looks like the app was considered uninstalled after update installation failure. Doesn't happen in master.

Keep in mind, there are a lot of ways to add an app to update blacklist:
1. in the notification, when there is any problem with attempted installation, like signature mismatch
2. in a dialog when you tap "install" button on the details page
3. in the overflow menu
4. on the preferences page

> Give a GUI option within yalp to delete downloaded apks.

That is very hacky. In such cases the underlying problem must be fixed.

**Comment by Grossdm** [comment]
I have real difficulty getting something to either of the lists - app entirely and the version-specific.

The menu options are there, but they just don't work.

I can add a package name manually (I use an app for this).

I have not found a manual method for the version-specific list, as I don't know the format of the version numbers.

**Comment by yeriomin** [comment]
@Grossdm This is not related to this issue. Please refer to #520. If you have any specific steps which you can repeat to recreate the problem, please mention them there. I cannot reproduce this yet.
