### ISSUE TITLE
Option to disable checking update

### ISSUE THREAD

**Issue by EMK2000** [yeriomin/YalpStore#53]
Could you add an option to disable checking update every time when start the app? Only check update when I manually click the button for checking update.

**Comment by yeriomin** [comment]
Will do.

**Comment by paride** [comment]
It would also be nice to have more choices for the update check interval (at least: hourly/daily/weekly).

**Comment by 5chdn** [comment]
Or: manually check for updates. Currently the app is hardly usable because it's checking for updates each time you get back to it. (otherwise nice app!)
