### ISSUE TITLE
app whitelist shows all apps

### ISSUE THREAD

**Issue by BO41** [yeriomin/YalpStore#533]
**Expected behavior**

app update whitelist should only "real" apps, like the ones I see on the "your apps" tab.

**Actual behavior**
it shows all apps, including system apps which can't be installed or removed and belong to AOSP

**Your setup**
huawei p8 lite, android 7.1 lineage 14.1, yalp: newest from f-droid 0.43

**Comment by yeriomin** [comment]
This is how it is supposed to work.

Your apps activity has a switch for turning system apps on/off. Adding more switches to settings would make it overly complicated.

All the apps shown are "real".

>which can't be installed or removed

With root they can. Also, even if they can not be removed, they can be updated, so they need to be able to be blacklisted.
