### ISSUE TITLE
deprecated android methode

### ISSUE THREAD

**Issue by BO41** [yeriomin/YalpStore#534]
opening the app in android studio, a message prompts
>The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..

I think this sounds serious and should be fixed soon.
But I don't know what it is about and what "removed" will mean for the app

**Comment by BO41** [comment]
gradle build reports this warning

**Comment by yeriomin** [comment]
This option is required to make Yalp Store work on older devices. See #352.
