### ISSUE TITLE
Can't buy Nvidia Shield TV games anymore (NSTV profile is greyed out) 

### ISSUE THREAD

**Issue by Death840** [yeriomin/YalpStore#537]
**Expected behavior**
I should be able to buy Nvidia Shield TV games on my account, but...

**Actual behavior**
...for a few months can't buy Nvidia Shield TV games anymore...:( My account (logged on PC) says that games (like Resident Evil 5 etc.) are not compatible with any of my devices. Of course I have Your Nvidia Shield TV profile in my devices list, despite this can't chose this profile, is grayed out.... If You can, please do something with this (maybe new Nvidia Shield TV template helps???), 4-5 months back it's worked fine (i have few games buyed by exacly this way).
Of course previously purchased Nvidia Shield games are downloable from Your Yalp Store app. Only problem with this 'not yet' purchased apps...

**Steps to reproduce**
1. Following this instruction: https://www.xda-developers.com/how-to-legally-install-unsupported-android-tv-or-nvidia-shield-games-on-any-android-device/ (changed my device to Nvidia Shield TV 2015 profile)
2. Logged in my personal google play account on PC (Firefox, Chrome, Egde, IE)
3. For exemple search Resident Evil 5, Metal Gear Rising: Revengeance and trying buy it.
4. Google says the application is compatible with some of my devices but when I click "Buy" button it's says those games are unsupported by any of my devices (like i said, I have Your "Nvidia Shield TV" profile on my devices list, it's grayed out).

**My setup**
Galaxy Note 8 (rooted), Android 8.0, Yalp Store 0.43 (tested on earlier versions, effect is the same)

**Comment by yeriomin** [comment]
> I should be able to buy Nvidia Shield TV games on my account

Buying was never supported by Yalp Store. Only downloading free apps and apps you've bought already.

> My account (logged on PC) says
> Logged in my personal google play account on PC (Firefox, Chrome, Egde, IE)

That was never supported or even tested. Yalp Store creates a device in a way which is enough to search and download apps within Yalp Store.

> that games (like Resident Evil 5 etc.) are not compatible with any of my devices.

These games show up in the search when Nvidia Shield TV device definition is used (and do not when an ordinary phone/tablet is used). Which means they are considered supported by Google Play. Checked this with both 0.43 and current master.

> maybe new Nvidia Shield TV template helps?

In 0.44 it is going to be updated, but I don't think it will help...

I'm sorry, there doesn't seem to be an issue with Yalp Store here.

**Comment by Death840** [comment]
Thanks yeriomin for answer!:)

I know Your app is not for buying apps but still few months back it's working anyway...:) Ok, if you can, do not forget about new Nvidia Shield TV (maybe 2018 edition?) profile in future update, it a chance to get this future work again... it's really helpful for some people...

Thx for Your hard work!:-)
Best regards!

**Comment by Death840** [comment]
Hello yeriomin:)
Thx for new 0.44 version. I have a question, Did You upgraded Nvidia Shield TV? If not, what You need to upgrade it, because i have acces to newest build.prop (attach 01) of this device (v. 7.1.0 ).

PS. If You can make Nvidia Shield Table template, Attach 02 may help You (newest 5.2.0 version).
Best regards:)

[NVIDIA_SHIELD_ANDROID_TV_Pro_build.prop.zip](https://github.com/yeriomin/YalpStore/files/2479099/NVIDIA_SHIELD_ANDROID_TV_Pro_build.prop.zip)
[NVIDIA_SHIELD_Tablet_LTE_RoW_build.prop.zip](https://github.com/yeriomin/YalpStore/files/2479100/NVIDIA_SHIELD_Tablet_LTE_RoW_build.prop.zip)
