### ISSUE TITLE
Should not download apps from other stores (avoid certificate mismatch error)

### ISSUE THREAD

**Issue by flohall** [yeriomin/YalpStore#539]
**Is your feature request related to a problem? Please describe.**
When using alternative stores like F-Droid and Yalp Store at the same time all apps installed via F-Droid cannot be updated from Yalp Store. This is OK for me as F-Droid is my primary source for apps and Yalp Store helps me to get all the apps not available on F-Droid. When looking for updates Yalp Store tries to update the F-Droid apps anyway even though it can't because of certificate mismatch. Then an annoying error is shown. (Can be quite a few errors if you have a lot of F-Droid Apps).

**Describe the solution you'd like**
Yalp Store should simply not show the app as update-able if the user searches for updates or when an auto update takes place. So no error is shown - apps from F-Droid (or other stores in general) should simply be ignored. Yalp Store should only update apps from Google Play store and Yalp Store itself. May this feature can be made optional by a setting so that is only activated for users using another app store like F-Droid.

**Describe alternatives you've considered**
There is a workaround actually, but still for me it's a workaround which is not so handy.
A user can add all apps from F-Droid to a Black-List in Yalp Store and has to update this list every time new apps are installed on the device. I use this workaround at the moment, but it would be easier this wouldn't be necessary.

**Additional context**
This relates to the problem described in Issue: #41 - but I suggest another solution.
F-Droid actually behaves like described in my solution it never tries to update an Google Play or Yalp Store app.

**Comment by yeriomin** [comment]
There have been more than a dozen of issues about that. The things you suggested are either implemented already, impossible to implement or undesirable. Points to consider:

* There is an option to automatically whitelist all apps installed through Yalp Store.
* It is impossible to know which store the installed app comes from.
* Downloading apps from different app stores is not the only reason of signature mismatch.
* Even if all of the above wasn't true, ignoring/hiding app updates by default is not a good idea, many users want the opposite.
