### ISSUE TITLE
Add "Update all" button 

### ISSUE THREAD

**Issue by hansWURSCHT10000** [yeriomin/YalpStore#54]
Hi, first thank you for your great work.
Could you please add an "Update all" button so we don't have to update each app seperatly?

Btw:
I used [Blankstore](https://github.com/mar-v-in/BlankStore)  as alternative PlayStore before but development is discontinued at this time.

**Comment by yeriomin** [comment]
Thanks for your suggestion! This will have to wait until I utilize root (issue #44). Right now the most I can do is autodownload updates which is a bit useless considering you will still have to click "install" on each of them. Closing as duplicate for now.

**Comment by dimqua** [comment]
>Right now the most I can do is autodownload updates

Please do it, it is very helpful on non-rooted devices.

**Comment by yeriomin** [comment]
@dimqua It's in 0.12. For non-rooted devices it is useless, you would have to get into every app and click install anyway.

**Comment by hansWURSCHT10000** [comment]
But right now you have to click on every app and click everytime on download. It would be a big improvement if these steps can be packed in one button. Root is not needed for this. 
Then if the apps are downloaded a notification would be nice where you can tap on and then the package manager opens where you click on install.

**Comment by dimqua** [comment]
Yes, but at least all updates are downloading by just one click, which is useful on low-speed Internet connections.

**Comment by yeriomin** [comment]
@hansWURSCHT10000 Root IS needed for this. Yalp (and any other non-system app, f-droid without privileged extension for example) can not install apps. You will have to click "Install" on every app and go through the system-provided install dialog with permissions list.

**Comment by hansWURSCHT10000** [comment]
@yeriomin I said it would give a notification when all updates are downloaded not that it automatically installs them. Root is just needed for installation not for downloading.
