### ISSUE TITLE
F-Droid fails to build Yalp

### ISSUE THREAD

**Issue by rojoweko** [yeriomin/YalpStore#543]
The F-Droid build server fails with the following error message (https://f-droid.org/wiki/page/com.github.yeriomin.yalpstore/lastbuild_44):

"ERROR: Could not build app com.github.yeriomin.yalpstore: Unexpected version/version code in output; APK: '0.44-legacy' / '44',  Expected: '0.44' / '44'"

Is there a "current" and a "legacy" branch of yalp now? Which one should be built by F-Droid?

**Comment by licaon-kter** [comment]
Yup: https://github.com/yeriomin/YalpStore/commit/18a4c2d38138bdb064bffa1cb21880fd410f899c

Unfortunately F-Droid can't (bugs with parsing iirc) pick up the suffix thing so we'll need to manually edit the metadata on each new version. :(

/LE: https://gitlab.com/fdroid/fdroiddata/commit/6a582a2b8c62c122366ca737fef3bc8547ede90a

**Comment by licaon-kter** [comment]
@yeriomin Can you drop the `-legacy` suffix? You'll still know what version is.... since it's "not-contemporary" :)

**Comment by Bubu** [comment]
The build succeeded now, but it's apparently not really installable on any device.

It has `uses-feature: name='android.hardware.ram.low'` which blocks android from installing it even on my low-end 1 GB ram phone.

Was that intended?

**Edit:** actually android installs the package just fine, but f-droid doesn't allow installing it because the uses feature is marked as required. :thinking:

**Comment by beholders-eye** [comment]
I had to install version 44-legacy from Yalp  itself, can't do it from f-droid.

**Comment by beerisgood** [comment]
Can confirm. On my LOS 15.1 (Android 8.1) with 4GB Ram I can't install version 0.44 nor 0.45 because the -legacy prefix

**Comment by Krawei** [comment]
Amy Updates Here?

**Comment by beerisgood** [comment]
*Push*
Still not fixed

**Comment by licaon-kter** [comment]
Fix it bot! Lol

**Comment by ZJaume** [comment]
F-droid users still cannot update :disappointed:

**Comment by Bubu** [comment]
For the record, g-droid apparently ignores the uses-frature thing and will happily update yalp.

**Comment by beerisgood** [comment]
@Bubu but that doesn't fix the problem and g-droid come from F-Droid itself

**Comment by Bubu** [comment]
I'd add another build to fdroid that removes this uses definition so people can upgrade to that.

It would be good if yalp could skip version code 46 for the next release then.

**Comment by rojoweko** [comment]
Seems to work now! ;-)  Thanks a lot!
