### ISSUE TITLE
Add a way to install a split APK even when root is disabled

### ISSUE THREAD

**Issue by Rudloff** [yeriomin/YalpStore#547]
**Is your feature request related to a problem? Please describe.**
Yalp 0.4.5 refuses to install a split APK when root is not enabled.
But some apps like Google Maps can work even if only the first APK is installed (but the app will be in English only).

**Describe the solution you'd like**
It would be useful to have a way to force the installation of a split APK.

**Describe alternatives you've considered**
I think this could be either:
* A per-app option (maybe a warning with "Are you sure you want to install this? It might not work."
* A global option in the settings

**Comment by romanblanco** [comment]
I have a problem with the split APKs since https://github.com/yeriomin/YalpStore/releases/tag/0.44

Even though I've enabled root access for apps, I'm still getting the message "The apk is split. Choose root or privileged installers". The app does not seem to even try to require root access to install the app.

Does the app need to be listed in some list of allowed apps other than "Install unknown apps", to be able to proceed the installation?

**Comment by Rudloff** [comment]
You probably need to enable the root installation method in Yalp preferences.

**Comment by Machion** [comment]
I see more and more APKs are split on playstore, but I have a non-rooted device. So solving this problem would be great.

**Comment by johntam** [comment]
> I see more and more APKs are split on playstore, but I have a non-rooted device. So solving this problem would be great.

Yes, I have non-rooted device too. The most important app that is split is YouTube. I am falling several versions behind now.

**Comment by Catfriend1** [comment]
Does this post help to see a direction how to solve this? https://stackoverflow.com/questions/42494382/how-to-share-split-apks-created-while-using-instant-run-within-android-itself/42873816#42873816

**Comment by Catfriend1** [comment]
https://gist.github.com/WanghongLin/12eb8c0a6880c6b63dc476a78ef9eb72

**Comment by anuraag488** [comment]
https://github.com/Aefyr/SAI

**Comment by je-vv** [comment]
I guess aurora suffering the same fate?

**Comment by je-vv** [comment]
AFAIK, [**Aurora Store**](https://gitlab.com/AuroraOSS/AuroraStore) is allowing split APKs installations.

**Comment by comzeradd** [comment]
Indeed. I switched to Aurora and finally got to update some apps.

**Comment by qazip** [comment]
Ya, how am I supposed to install split packages while using Yalp? Is "install as root" in yalp's preferences safe? Is it recommended?

**Comment by aki-k** [comment]
@qazip Use "Get local apk" in Yalp store ... menu and then use a file manager to install the apk from Downloads. There will be two apks for one app but only one is needed for the update.

**Comment by rancidfrog** [comment]
There are open source solutions.
If aurora has the option, it should be backported, as aurora is just a fork of this project.
Also, SAI installs without root.
So there are multiple working open-source solutions
Why can't yalpstore handle split apks, since there are open source solutions?

SAI works well, no root required
https://github.com/Aefyr/SAI 

Also, have not tested -
https://gist.github.com/WanghongLin/12eb8c0a6880c6b63dc476a78ef9eb72

**Comment by jhoc2000** [comment]
Aurora store does not download using Orbot and anonymous for me. I'm using android version 9.

**Comment by sebma** [comment]
Do you have plans to release a new version in 2019 that fixes this issue ?

**Comment by Aspire1Inspire2** [comment]
Paypal cannot be updated. 
This issue is one of the critial issue on non-root device. 
Is there any update on this?

**Comment by ghost** [comment]
Aurora does not even ask for root privileges for me and installing the Revolut app fails.

**Comment by adlisval** [comment]
I have the same problem. More and more apps are split and using YalpStore is not helping anymore. Tried Aurora, but it cannot install split apk:s either. Please release a fix for this.

**Comment by gregoa** [comment]
On Tue, 02 Jul 2019 06:40:31 -0700, adlisval wrote:

> I have the same problem. More and more apps are split and using YalpStore is not helping anymore. Tried Aurora, but it cannot install split apk:s either. Please release a fix for this.

There are 2 "Auroras":

The older one at
https://f-droid.org/en/packages/com.dragons.aurora/

and the newer (linked from there) at
https://f-droid.org/en/packages/com.aurora.store/

and the latter handles split apks fine.


Cheers,
gregor

**Comment by johntam** [comment]
There is a way, albeit not ideal, to install the split apk apps. Just go to your file manager in Android, go to the Downloads folder or wherever the apks are temporarily downloaded to, and then just open the .apk files from there. They should install as normal. This is how I update the Youtube app nowadays, I just use Yalp Store for the 90% of apps that are not split apks.

**Comment by sebma** [comment]
> On Tue, 02 Jul 2019 06:40:31 -0700, adlisval wrote: I have the same problem. More and more apps are split and using YalpStore is not helping anymore. Tried Aurora, but it cannot install split apk:s either. Please release a fix for this.
> There are 2 "Auroras": The older one at https://f-droid.org/en/packages/com.dragons.aurora/ and the newer (linked from there) at https://f-droid.org/en/packages/com.aurora.store/ and the latter handles split apks fine. Cheers, gregor

I'm sorry but on my Android 5.0 on my Galaxy Note 3, the later "Auroras" is not able to handle split apks either.

**Comment by je-vv** [comment]
v3.0.6 should, it's the one currently working for me (g-photos and g-drive)

**Comment by Welteam** [comment]
For some reasons the f-droid website gives the 3.0.6 but the f-droid app installs the 2.0.5. The later doesn't handle split apk

**Comment by sebma** [comment]
> v3.0.6 should, it's the one currently working for me (g-photos and g-drive)

I do have Aurora v3.0.6 (see the 1st screenshot) on my Galaxy Note 3 (android 5.0) but the installation of any apk (split or not) always fails, it says "App not found" (see the 2nd screenshot).

![myAurora_Version](https://user-images.githubusercontent.com/4569306/60713967-56753a00-9f1a-11e9-85a4-d241ad08e556.png)

![Aurora_Issue_App_not_found](https://user-images.githubusercontent.com/4569306/60714283-0d71b580-9f1b-11e9-9916-788deaac5b98.png)

**Comment by codethief** [comment]
For me, installing split apks with the new Aurora (v3.0.6) (which I installed through F-Droid) works fine.

@sebma I suggest you report the bug to the Aurora developer (https://gitlab.com/AuroraOSS/AuroraStore/issues) and link to it here? On a different note, maybe [this commit](https://gitlab.com/AuroraOSS/AuroraStore/commit/a674c53ff43ffa8c988062ca053f5c2186784ca6) from 6 days ago is going to fix your issue?

**Comment by sebma** [comment]
@codethief Thanks, codethief. I hope you're not a code thief, though, just kidding, lol.

I have create the issue https://gitlab.com/AuroraOSS/AuroraStore/issues/113.

**Comment by jhoc2000** [comment]
I've now replaced Yalp Store with Aurora Store on my phone. AS works much better than YS. 

Thanks for the tip.
