### ISSUE TITLE
Does YalpStore have "Dynamic Delivery" and "Android App Bundle" Support?

### ISSUE THREAD

**Issue by n0x-io** [yeriomin/YalpStore#549]
Hello there!

Thank you for this cool project!

I have a question. Maybe it is even a feature request... but does YalpStore support Apps that use "Dynamic Delivery" and "Android App Bundle"? If not could and/or will it add Support in the future?

I'm asking because yesterday I ran into the first app I am using that switched to this new delivery system ["Joey for Reddit"](https://play.google.com/store/apps/details?id=o.o.joey&hl=en_US). It added this new system with version 1.5.9

I searched a little online and found out that Dynamic Delivery seems to be the new big thing when it comes to app installation: https://www.androidpolice.com/2018/05/30/android-app-bundles-dynamic-delivery-will-change-way-phone-gets-software/
So I am guessing that more and more apps will start using the Android App Bundle System.

Sooo... how will the future look of Yalp regarding this new system? 

Thanks for taking your time!

Greetings from Germany

Tim.

**Comment by kb-1000** [comment]
I don't think it will support Dynamic Delivery, because that will likely depend on GMS. But if YalpStore and MicroG developers cooperate, it could be possible.
App bundle support is much more likely, but since I'm not the developer of *this* app, I can't guarantee anything.

**Comment by kb-1000** [comment]
Will this ever get implemented?

**Comment by whew-inc** [comment]
Same happened with Sync for Reddit. I have to install via the play store now to get it working.

**Comment by kb-1000** [comment]
I don't know if it's possible for 3rd party apps to install split apks, but I guess it should be possible. Anyone knows an Intent extra for this?

**Comment by muelli** [comment]
Sounds like https://github.com/yeriomin/YalpStore/issues/565

**Comment by pm-pm** [comment]
I have seen a public document from google how to install split apk without root. it look a little bit difficult, but it should be possible. Please use google to find it.
This point is also very important for me.

**Comment by muelli** [comment]
I bet you'd increase chances for somebody else performing a task for you if you don't mention a blurry google search but provide the actual documentation.

**Comment by pm-pm** [comment]
You are right, but sometime you do not have the possibility/resources to do a complex internet reseach. The hint for the documentation is better than nothing!

Instead of complaining, YOU could help to solve the problem. ;-)

If i have some time i will search for the documentation and add the information. Sorry for inconvenience in the moment. Please wait for the while.
