### ISSUE TITLE
Aurora store shows update that yalp Store doesn't

### ISSUE THREAD

**Issue by Krawei** [yeriomin/YalpStore#553]
Dear @yeriomin,

I've noticed a strange "bug":

I've installed aurora store and checked the updates section.

Aurora offers me to update "Busliniensuche" from v3.26 to v3.27 where yalp "freezes" on 3.26 and doesn't asks to update the app.

I've searches for updates several times in yalp but thr problem persists. Even a device spoofing doesn't help.

Is there a reason for this,  like a built-in rule to just update the cache once a day and lock the local db afterwards?

Hope you can shed some light in the dark :).

Kind Regards,

Krawei

**Comment by ghost** [comment]
Please read stage roll out in the read me.  And if no questions left please don't forget to close the issue.

**Comment by LuccoJ** [comment]
For reference, the thing being referred to is this FAQ entry:

> A: For different reasons the app developer might choose not to release his app for all users at the same time. This is called a [staged rollout](https://support.google.com/googleplay/android-developer/answer/6346149?hl=en). Be patient, the update will come.
