### ISSUE TITLE
Apps Not Getting Installed - Yalp as System App

### ISSUE THREAD

**Issue by bugnot** [yeriomin/YalpStore#554]
Apps get downloaded but not installed. Only shows "Installing..." notification. Yalp is installed as a system app to have complete sets of permission required to perform this function.

Anything broken?

**Comment by Grossdm** [comment]
I used TiBu to migrate Yalp to a system app.
Yalp crashed on my first try to open it after the "systemization".

Currently, it is running as well as it was before the change. (It is still imperfect for me, but it may be my phone's age or config.)

My best recollection of the few things I had to do after making Yalp a system app:

1. Clear Yalp's cache. I suspect the large fdroid.xml file, but that's just my guess.

2. Yalp opened and ran after this, but behaved like a user app. I went back to the "Installation method" setting, and it had reverted to its default. So I again set it to "Using system permissions".

I think this is all I had to do to get it running properly as a system app.

BTW, the most apparent change (I still have installs set to manual) is that you only have to tap once for it to install/update an app. There are no prompts or notices; it simply installs (Yalp does stay in the foreground, mind you.)


I hope this helps. Good luck!


Doug®

**Comment by bugnot** [comment]
So you meant to say that you have to at least hit the Install/Update app notification once in order for this to work?

**Comment by Grossdm** [comment]
@bugnot,
Sorry for the delay.

When I said that I only need to tap once to install, I was referring to the actual "Install" button.

This is the button that you would see after opening the app's details page - either from a notification or from its listing in "Your Apps".

I hope that helps to clarify things.

Also, it does appear that I did not follow the standard procedure to install Yalp as a system app.

**Comment by bugnot** [comment]
Thank you for the update! I will be checking this soon and let you know.

**Comment by siegheilx** [comment]
Вроде как только в Contemporary версии данный баг

**Comment by Grossdm** [comment]
@siegheilx,
I only understood the word "Contemporary" in your post - sorry.

If it helps, I am using the 0.45-Legacy version of Yalp.

**Comment by siegheilx** [comment]
@Grossdm, 
this is a bug of the Contemporary version only

**Comment by Kcchouette** [comment]
problem still here

**Comment by Grossdm** [comment]
@stale[bot] is unfriendly. :-(
