### ISSUE TITLE
Does Yalp really need 7 (!) taps to update a single App?

### ISSUE THREAD

**Issue by pstein** [yeriomin/YalpStore#558]
I am trying now Yalp for a while in order to avoid defining a Google Play Store account.

However I am very disappointed by Yalp.

Currently I need 7 (!) taps to update a single App on my Android system.
Have a look at the attached snapshot for the update procedure for the example "Google App".

Can this really be?

Yes, I am willing to accept no automatic update like in Google Play Store but 7 steps/taps ....?
Thats extremely tedious and user unfriendly.
Can this be somehow faster (only 2 or 3 taps)?

Thank you
Peter

![papp-update procedure with yalp](https://user-images.githubusercontent.com/2775875/48614196-faab7000-e98d-11e8-8ed4-0d669e73ab1c.jpg)

**Comment by ale5000-git** [comment]
I think that it would be nice to have an update button for every app directly in the "Updates" page that trigger a background installation without confirmation.

**Comment by tuxayo** [comment]
> that trigger a background installation without confirmation.

Impossible without root if I'm not mistaken. F-Droid have developed a Privileged Extension to install in background.
https://f-droid.org/packages/org.fdroid.fdroid.privileged/

**Comment by tuxayo** [comment]
> Does Yalp really need 7 (!) taps to update a single App?

> However I am very disappointed by Yalp.

> Can this really be?

Hi, thanks for your feedback @pstein
The way some things are written might not help to discuss how to improve Yalp in a pleasant (many people do want to work with healthy and nice interactions) and efficient way.

**Comment by ale5000-git** [comment]
If Yalp is installed as privileged app it can have the same function of the Privileged Extension without the Privileged Extension (if I'm not wrong).
