### ISSUE TITLE
White/Black listing does not save/remember when done from app list.

### ISSUE THREAD

**Issue by gohanko** [yeriomin/YalpStore#559]
**Before creating an issue**
1. Running version 0.45 contemporary.
2. None
3. Done
4. Done
5. Done

**Expected behavior**
White/Black listing from app list should carry on after app is killed.

**Actual behavior**
White/Black listing resets if set from app list after app is restarted. User needs to set from settings for the changes to be saved.

**Steps to reproduce**
1. Change black/white list from app list.
2. Kill app by quiting and remove from tasks.
3. Open app, walla black/whitelist is resetted.

**Your setup**
Lenovo P2, Android 8.1 (LineageOS 15.1), Yalp Store 0.45 contemporary.

**Comment by gohanko** [comment]
After I did a reflash of YalpStore 0.45-contemporary, it seems that this whitelist problem is not appear.

**Comment by gohanko** [comment]
Seems like the problem happens again. This time with the basic version. Reflashed 3 times, and it doesn't auto whitelist properly.

**Comment by SebiderSushi** [comment]
This bug is still present and very annoying.
Please consider removing that stale bot...This is a duplicate of #490 possibly made into a new issue since the old one has been closed : /
