### ISSUE TITLE
Download arrives in 3 parts

### ISSUE THREAD

**Issue by johanw666** [yeriomin/YalpStore#561]
**Expected behavior**
I download  an upgrade for an ebook reader (https://play.google.com/store/apps/details?id=org.geometerplus.zlibrary.ui.android). I expect one apk file.

**Actual behavior**
I get 3 apk files, one containing most stuff, one contailing the /lib files for my system and one containing some /res stuff.

**Steps to reproduce**
1. Download https://play.google.com/store/apps/details?id=org.geometerplus.zlibrary.ui.android
2. Check Download folder.

**Your setup**
Sony Z3 compact, Android 6.0.1, Yalp 0.45 (System app). Delta updates deselected in the settings.

Edit: when I do the same on an Android 4.4.4 device I do get a single apk. Maybe this has something to do with the new app bundle functionality?

**Comment by Whisprin** [comment]
How do you get 3 APK files? I'm getting just one, which, when installed, just causes the app to crash.

**Comment by johanw666** [comment]
I get 3 files with the apk extension. When I unzip them I see one with the Java parts of the program which I can install but crashes on start (probably because it misses the second one: one with the native libraries, and one called ...split.config.xhdpi.apk with some resources. After some study I found out this is indeed an apk bundle.

To prevent this behaviour one should fake an Android 4.4 device that does not support apk bundles (apk bundles only work on Android Runtime, which came with Android 5). Bus as some apk's might not exist for older Androids this might become a problem. These parts can be merged with [bundletool](https://developer.android.com/studio/command-line/bundletool) but that requires the apk signing key. Perhaps it could be done with another key that would replace the original signing key?

Yet another way to tie people to Google Play. :-(

**Comment by Nirose** [comment]
The same thing happened to me with spotify lite app. then asked for chroot installation on error message

**Comment by tenchman** [comment]
Same here with Komoot:  https://play.google.com/store/apps/details?id=de.komoot.android

In some versions yalp asked for root/system permissions. After installing yalp as system app, yalp just crashed.

**Comment by muelli** [comment]
Is this the same issue as https://github.com/yeriomin/YalpStore/issues/565 ?

**Comment by ghost** [comment]
It is called app bundling or split apps. You can install it when you choose install method " using root"

**Comment by thierrybo** [comment]
I unrooted my device because my bank apps does not install on a rooted device, so other yalp install options can't just be 'alternatives'

**Comment by johanw666** [comment]
> 
I unrooted my device because my bank apps does not install on a rooted device, so other yalp install options can't just be 'alternatives'
 
Fortunately my bank has no problems with rooted devices, but otherwise there is still https://repo.xposed.info/module/com.devadvance.rootcloak2 and similar solutions for Magisk.

**Comment by pm-pm** [comment]
Dear bot. :-)
It is not solved, sorry.

**Comment by thierrybo** [comment]
Dear bot. :-)
It is not solved, sorry.

**Comment by angela-d** [comment]
The split apk issue wasn't present in 0.43, downgrade and give it a try: https://github.com/yeriomin/YalpStore/releases/tag/0.43

Aurora also is not subject to it: https://f-droid.org/en/packages/com.aurora.store/

Edit: 0.43 instead of 0.44; added new Aurora version.

**Comment by thierrybo** [comment]
downgraded to 0.44 and still the same issue.

**Comment by thierrybo** [comment]
but thanks for Aurora, with it I can update YT.

**Comment by johanw666** [comment]
Otherwise you can make Yail tell Google your device runs Android 4.4 - which does not support split apk's. So if the app still supports 4.4 you could try that.

**Comment by angela-d** [comment]
@thierrybo My mistake - I'm running 0.43 -- not sure why I thought I was on 0.44: https://github.com/yeriomin/YalpStore/releases/tag/0.43

Anyway, since @yeriomin is MIA / lost interest / hopefully not injured or ill, Aurora is a nice alternative to Yalp with an active developer.

https://forum.xda-developers.com/android/apps-games/galaxy-playstore-alternative-t3739733 - A newer version looks to have been published on the 13th: https://f-droid.org/en/packages/com.aurora.store/

**Comment by thierrybo** [comment]
Thanks, I will switch to Aurora now.
