### ISSUE TITLE
Search function in Amazon Fire tablet

### ISSUE THREAD

**Issue by Canelwwer** [yeriomin/YalpStore#568]
It works great in the Fire Stick, but in the fire table the search function opens the browser like if im searching from a search engine like Google or Bing instead of showing the list of apps from the store to install.

**Comment by AdrianKoshka** [comment]
On my kindle fire HDx 3rd gen pressing the search function brings up the unified search bar instead of letting my search something on the yalp store.

**Comment by Canelwwer** [comment]
> On my kindle fire HDx 3rd gen pressing the search function brings up the unified search bar instead of letting my search something on the yalp store.

Exactly my problem and i Don t know what to do to fix it.

**Comment by AdrianKoshka** [comment]
I now have a Kindle fire HD8 (8th gen) and this still occurs fwiw.
