### ISSUE TITLE
Yalp store doesn’t show all apps on search

### ISSUE THREAD

**Issue by drciicii** [yeriomin/YalpStore#571]
Hi, 
**facing an issue in Yalp store that installed on my Mi Box, as Yalp store doesn’t show all apps on search such as chrome, firefox, youtube**

**Mi Box S, Oreo, tried last 4 versions**

Regards

**Comment by Num25r** [comment]
was going to report same issue i know before it had same apps as norm playstore

**Comment by 0pLuS0** [comment]
I just made an issue for this...

I've been playing around with Aurora Store and Yalp in the past, but not really paying attention, that the entire time I have used these, they never show all the same search results... :(

**Comment by 0pLuS0** [comment]
Well it would be nice if the DEV(s) could step forward and tell if this has been resolved?

**Comment by slawkis** [comment]
Same here.
Redmi note 2, Android 7.1.2, LineageOS 14.1
