### ISSUE TITLE
Problem with activities?

### ISSUE THREAD

**Issue by lllmio** [yeriomin/YalpStore#573]
I'm not 100% if it's actually activities problem, just remember I was fixing something similar in my app loooong time ago.

- Yalp store has multiple instances in Recents screen
- If you tap on the app to open it's page or use share from browser to open it in Yalp Store it usually opens page of some other apps you opened previously, so you have to go back multiple times through them to actually open the one you want. Same behaviour happens when you search for the app: it frequently displays some old search results. There are other manifestations of the problem, I don't remember all of them.

You mentioned in some issue that you use old device. Maybe it just kills the app in background too soon, so the issue was left unnoticed.

My device has Android 8.1 MIUI

**Comment by SaLiXeM** [comment]
I can confirm this annoying bug. This has made Yalp Store really unstable for continues use in the background, for me. 

Because sometimes I have to completely close Yalp to be able to get out from a particular app page.
