### ISSUE TITLE
Cannot reliably blacklist apps

### ISSUE THREAD

**Issue by emacsomancer** [yeriomin/YalpStore#574]
Is there a trick to getting blacklisting to persist with Yalp? I've sometimes successfully blacklisted apps, but generally the next time I open Yalp it's 'forgotten' apps that I've recently blacklisted.

**Comment by tuxayo** [comment]
I still have the same issue for months. For some apps it works. For others, not and they keep coming again.

Note that I use "Ignore updates" and not blacklist from settings.

See also #520 #540 #427

**Comment by emacsomancer** [comment]
I've always been trying to blacklist using "Ignore updates". There seems to be some sequence of events which will make the 'ignore'/'blacklist' stick, since sometimes an app I've repeatedly blacklisted will actually remember its blacklisting, but I'm not sure what it is.

**Comment by gohanko** [comment]
Happens to me too. The workaround would be adding it from the settings menu.

**Comment by toxpal** [comment]
Have exactly the same issue, but only for recent installs.

I mean, that if phone had old version of Yalp installed and some apps were blacklisted, blacklist always remains in place, even when using latest Yalp. However, if I make a fresh installation of Yalp (latest version), blacklist resets after app is closed. 

Tested with 3 devices this week - the issue is identical. Once fresh installation of latest Yalp is performed, blacklist doesn't work. So it looks old versions worked properly, but recent versions can't create blacklisted entries properly (but can read them in case of upgrade from old version).

**Comment by AreYouLoco** [comment]
I can also confirm that behavior. Some recent apps are not being blacklisted. Will try the workaround of setting ignore via settings menu. And post if it helps.

**Comment by pm-pm** [comment]
I remember a workaround, but i am not 100% sure:
Set app (only one) to blacklist and **exit** app by back-button (<) until homescreen appears.
Check if app is blacklistet.

**Comment by AreYouLoco** [comment]
Too late. I already blacklisted app successfully via settings menu.

I could chceck again your proposition but I have to remove it from the blacklist first. Give a second...

**Comment by AreYouLoco** [comment]
nope @pm-pm. Your proposition doesnt work. Only choosing app from the settings menu put an app on the blacklist.

**Comment by pm-pm** [comment]
Yes @AreYouLoco. We are talking NOT about choosing of an app, but reliaby blacklisting of the app. ;-)
I was talking about reliably storing in blacklist not selecting.

**Comment by AreYouLoco** [comment]
A misunerstanding then. @pm-pm by choosing i meant adding to the blacklist. And via settings menu it seems to work. Its bit anoyying to go to settings each time a new app pops up in the updates but workaround is a workaround.

Could some more skilled user check logs if it says something when we try to blacklist directly from the updates list?

**Comment by emacsomancer** [comment]
It still occurs though, @stale

**Comment by breversa** [comment]
I noticed a weird thing :
If I install Yalp Store, then blacklist an app by long-pressing on it, blacklisting doesn't seem to stick.

However, if I go to the settings and check the blacklist (or toggle black/whitelist mode) THEN blacklist an app by long-pressing it, it seems to stick.
Not 100% sure though.

**Comment by AreYouLoco** [comment]
https://github.com/yeriomin/YalpStore/issues/603

<del>It seems fixed for me with some new release.
Could anybody confirm for their device?</del>
Edit: Nope I was mistaken.

**Comment by toxpal** [comment]
What new release do you refer to? According to Fdroid and this page itself, the latest version is 0.45, released months ago.

**Comment by AreYouLoco** [comment]
I am using 0.45-legacy from January and cannot reproduce the bug anymore. Weird.

**Comment by toxpal** [comment]
I use the same version, and bug exists on 3 different devices (running different ROMs) for me.

**Comment by AreYouLoco** [comment]
I edited the post to not to make a mess. The bug persists. I just didnt check correctly.

**Comment by qouoq** [comment]
Hey bot, thanks to not close, the issue is still very relevant.

**Comment by qouoq** [comment]
Confirming Aurora Store is a fully functioning alternative to Yalp Store as far as I'm concerned, including not being affected by this issue. (Don't need any black/white list there actually, it does a wonderful job at autodetecting which 'store' your installed apps belong to.)

Also it's availabe on F-Droid, alongside Yalp, so the switch is trivial for F-Droid users.

_Commenting here with the hope it may help anyone facing, or being confused with, this -- now closed -- issue._
