### ISSUE TITLE
Is this repository no longer being maintained?

### ISSUE THREAD

**Issue by jxhn** [yeriomin/YalpStore#576]
Whilst I can appreciate the pressure of maintaining a project as large as this one and with the understanding I am not blaming anyone, I am concerned that this project has been abandoned. 

There hasn't been any updates since [October 16th 2018](https://github.com/yeriomin/YalpStore/commit/37f24c2fc2078cefc141d03c1379a650298ee2a8) and since then more and more apps aren't working. This is the default method of installation for anyone using [MicroG on LineageOS](https://lineage.microg.org/). Apps quite important to me no longer work due to [no support for bundling](https://github.com/yeriomin/YalpStore/issues/565).

1. Do we know if this project is actually abandoned? 
2. Is it worth forking & fixing if this is the case? 
3. What other options exist?

Unfortunately my development experience lies in another domain so my usefulness is limited.

**Comment by dimqua** [comment]
3. Aurora Store, which is a fork of this project.

**Comment by JonnyTech** [comment]
Does [Aurora Store](https://gitlab.com/AuroraOSS/AuroraStore) support app bundling? I see no commits relating to it.

**Comment by jxhn** [comment]
@JonnyTech @dimqua I just tested on some apps I know use bundling and it doesn't work

**Comment by kb-1000** [comment]
Aurora Store looks abandoned to me too

**Comment by ghost** [comment]
App bundling is working in yalp store
when you choose installing method ' using root' I tested it with glasswire and l Speed
and it is working
*the developer of aurora store said he is working on a new update

**Comment by Rorschach1010** [comment]
For some reason, Yalp isn't working for me anymore for maybe a month now. It downloads the apks but it can't install them. I have to install the apks with my file browser after yalp downloads the apk. I don't get an error message (beside the toast message saying that it wasn't possible to install). Since I didn't change anything at all and even tried it on a different phone where the same happens, I don't know what the actual problem is.

I haven't connected my google account with my phone for more than a year but now I'm kinda forced to. Its sad to see that there is no lifesign here.

What is app bundling btw?

**Comment by maxbla** [comment]
~This repository does not seem to be abandoned, even if updated are not as frequent as would be ideal. see [this](https://github.com/yeriomin/YalpStore/commit/75cde0bf793c67b9006f7af3e32095bdb144688a) commit on January 14. You might have been looking only at commits to master?~
That commit was from was January **2018** not 2019...

**Comment by samiraguiar** [comment]
@maxbla that commit was on January 14, 2018, that is, one year ago.

**Comment by johanw666** [comment]
Yalp reported to me that there would be a 0.46 but it can't download it?

**Comment by Rorschach1010** [comment]
> Yalp reported to me that there would be a 0.46 but it can't download it?

Actually, its not 0.46 but 0.45. However, I have no clue what the difference between 0.45-legacy from 19.10.18 and 0.45-legacy from 29.01.19 (both in f-droid) is as its looks like they are exactly the same release.
Anyway, Yalp Store isn't usable anymore and this sucks. Without root, it doesn't install saying that it can't install split apks without root and with root it just tells me that it wasn't able to install.

**Comment by spok9** [comment]
@johanw666 how did Yalp report to you that there would be a 0.46 ??  And why is there no 0.45-legacy in github? i cant find it. its only on f-droid...where did that come from with no latest commit on github?

If the developer replied, it would be great.

**Comment by johanw666** [comment]
![screenshot_2019-02-10-13-21-07](https://user-images.githubusercontent.com/8427572/52533659-470d0e80-2d37-11e9-892e-8e35531cce45.jpg)
When I click download I get a file com.github.yeriomin.yalpstore.46.apk, the AndroidManifest in it claims it to be 0.45 but the file differs from the 0.45 I have.

This only happens on an Android 4.4.4 device, on my Android 6 and higher devices I don't see this.

**Comment by whyorean** [comment]
> Aurora Store looks abandoned to me too

Not actually, new update is awaiting, all issues are being addressed.

**Comment by johanw666** [comment]
>  And why is there no 0.45-legacy in github? i cant find it.

com.github.yeriomin.yalpstore_45.apk on the releases page.

**Comment by brandsimon** [comment]
@whyorean Can you post a source of this information?
Last commit in Aurora Store is 2 months ago on gitlab.

**Comment by Rorschach1010** [comment]
Seems like the newest update of Raccoon (4.4.0) is implementing app bundle. Its great news to see that this is possible and hopefully, Yalp store will get it implemented too. This would solve 80% of all the problems Yalp Store has right now. Now all we need is a life sign of this project still being worked on.

**Comment by vadiof** [comment]
@brandsimon whyorean is the only developer of Aurora

**Comment by fabianruben** [comment]
Bad bot.

**Comment by Rorschach1010** [comment]
Aurora Store recently got a new major update. Its now coded from scratch and not based of Yalp Store plus it implemented Split Apk installation. Since the maintainer of Yalp Store is absent for longer then 6 months, it might be wise to just move on and use Aurora Store.

**Comment by johanw666** [comment]
We've indeed seen no reaction at all for a long time - I hope Sergey Yeriomin is OK.

**Comment by Mhowser** [comment]
Anything new regarding this?

**Comment by yidakra** [comment]
@johanw666 seems like he's still very active on [GitLab](https://gitlab.com/users/yeriomin/activity)

**Comment by johanw666** [comment]
@arkadiyjs from the looks of it it seems he has switched to F-Droid development. Not that that site doesn't need improvements, but some reports here about to be expected (or not) progress would be nice.

**Comment by johnb-xp** [comment]
Aurora Store only runs on Android 5.0+, not possible for my BlackBerry lol. Fingers crossed an update will come out.

**Comment by SebiderSushi** [comment]
Having a look at Yeriomins [activity graph at GitLab](https://gitlab.com/yeriomin) it merely seems as if he just has less time since 2018-10 and is generally prioritizing on F-Droid development.

**Comment by SebiderSushi** [comment]
Next step: Stale bot automatically closes the whole repository if no futher activity occurs ;)

**Comment by SebiderSushi** [comment]
bad bot

**Comment by kb-1000** [comment]
@SebiderSushi Please stop spamming. We all know now Yalp Store got abondoned, and keeping this open using spam doesn't change anything about that.
