### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by teod0r** [yeriomin/YalpStore#58]
Could you please add an ability to enlarge fonts? Font of apps description is too smal for my eyesight.

**Comment by teod0r** [comment]
Ещё когда выбирешь приложение из поиска, строка сверху с названием программы снизу обрезана: не хватает нескольких пикселей снизу у букв названия приложения

**Comment by avently** [comment]
Блин, нафига столько идиотских issues? Ты вообще нормальный? У проги нет множества основных функций, а ты говоришь про шрифты. После подобных запросов у автора просто может желание пропасть заниматься программой. Думай, прежде чем писать

**Comment by yeriomin** [comment]
Font size in Yalp and Play Stores are the same. You can change system-wide font size in Settings - Display - Font Size. Both Yalp and Play Stores are affected by this setting.
Yalp Store:
![Yalp Store](https://www.dropbox.com/s/54jgn55kpysntk3/Screenshot_20170207-100952.png?raw=1)
Play store:
![Play Store](https://www.dropbox.com/s/w5mi9q79f2jowsw/Screenshot_20170207-101121.png?raw=1)

**Comment by teod0r** [comment]
В настройках системы у меня шрифт и так на максимум. Но в Yalp Store всё равно мелкий шрифт.
