### ISSUE TITLE
UI glitches when downloading single package on a long list of updates

### ISSUE THREAD

**Issue by genodeftest** [yeriomin/YalpStore#584]
This is not a crash, thus there is no crash report.

**Expected behavior**
Only show download indicator for a single package.

**Actual behavior**
Yalp shows the download indication on several packages, about one per screen.

**Steps to reproduce**
1. Open yalp store
2. Show updates. This issue only happens if there are more updates than what fits the screen. In my case that's about 7 packages.
3. Press the download button for a single app
4. Scroll down at least a whole screen

**Your setup**
Yalp version: 0.45-legacy (from f-droid store)
Android: 9, security patch level 2019-01-01, mostly stock (Nokia).
Device: Nokia 5 (TA-1053)

**Additional information**
This issue may be related to #523 as I sometimes see signature mismatches when the issue happens. I will report back when running in this combination of issues.

I was told by an android developer that this issue happens because the number of UI items is limited and instead of creating a UI item for each package, yalp (wisely) reuses the list elements replacing both strings and icons. It does however seem to fail to remove/set the "is downloading" status.

**Comment by genodeftest** [comment]
Do you need any more information?

**Comment by Chewie9999** [comment]
I have the same problem, using YalpStore 0.45-legacy on Fairphone 2 (Android 6.0.1).
I think it's more than just a UI glitch, as I'm also getting "too many request" errors, so I think it really is trying to download updates that I didn't click on.

**Comment by genodeftest** [comment]
@stale: You're annoying. Please reopen.
