### ISSUE TITLE
Split apk's and app bundling not installing with root/manually in 0.45-legacy

### ISSUE THREAD

**Issue by spok9** [yeriomin/YalpStore#585]
So the passed few days been having a lot of difficulty logging in with "yalp credentials"
Has something changed on playstore api?  Because Aurora Store also has the same issue (just by the way)

Yesterday i had a chance logging in after persisting and continuously pressing login with Yalp.

@yeriomin Can you please tell whats going on? is this still project still being updated or not?

Also having root install apk's on ROM - Pie is not working, have to do it manually.
Using 0.45 from F-Droid.

**Comment by spok9** [comment]
Update:
I have managed download 0.45-legacy from F-Droid, and it seems logging in is fine now.

However the only and real problem is installing the apps.. problem with split apk's and root. Not installing manually neither with root.  This is a big problem and most of the latest issues on here has to do with that and app bundling.

Please can you fix this issue?

**Comment by Rorschach1010** [comment]
Seems like Raccoon got app bundles and split apks working now. Lets hope, Yalp Store will get it too some day.

**Comment by rancidfrog** [comment]
Why can't yalpstore handle split apks, since there are open source solutions?
I.E. Raccoon and SAI
SAI works well, no root required
https://github.com/Aefyr/SAI 

Also,
https://gist.github.com/WanghongLin/12eb8c0a6880c6b63dc476a78ef9eb72

**Comment by ManuLinares** [comment]
Tried updating Google Photos from 4.16 yo 4.17
With root, auto or manual install doesn't work
