### ISSUE TITLE
Yalp as a F-Droid repository

### ISSUE THREAD

**Issue by je-vv** [yeriomin/YalpStore#586]
As yalp is facing problems with split apks, requiring root privileges, I'm wondering if yalp could instead work as a repository for f-droid, which privileged extension solves that issue without needing root.
Yalps mission should be then to keep apks up to date in that mode (removing old ones), and to offer a path that might work as a local repo to f-droid.
This might be a mode of operation, without removing the install capabilities yalp offers...

**Comment by Rudloff** [comment]
I think gplaycli can be used to create this kind of repository: https://github.com/matlink/gplaycli/blob/master/README.md
(But I don't think hosting the whole Play Store would be possible.)

**Comment by octoghost** [comment]
Maybe you can use [SAI](https://github.com/Aefyr/SAI) to install the splitted APKs without root privileges. I wonder if the SAI rootless installation method will be integrated on Yalp someday...

**Comment by je-vv** [comment]
Well, right now it's that split apks require root access.  But later on might be any other thing requiring root access.  So that's why I though having a f-droid local repo mode is all that's needed.
Not that it's the general case, but at least I installed yalp from f-droid, meaning I actually have 2 installer apps, when it might be possible to keep just one as installer, and the other as a repo provider...
