### ISSUE TITLE
Yalp is unable to install apps using root on Android 9 (and how you can probably fix it)

### ISSUE THREAD

**Issue by adolfintel** [yeriomin/YalpStore#591]
**Expected behavior**
Yalp installs the application

**Actual behavior**
Yalp gets an error from pm install and fails

**Steps to reproduce**
1. Enable automatic installation using root method
2. Try to install something
3. Watch it fail

**Your setup**
Any device, Android 9.0, LineageOS 16.0 in my case

**How you can probably fix it**
Google sabotaged the pm install command so that it will only install APKs from /data/local/tmp (no doubt this was done to break third party app stores like this). Move the download APK there and it will work again.

**Comment by pHr34kY** [comment]
I'm experiencing the same (LineageOS 16.0 on kltedv). The normal install method works for everything except split APKs, where I ran into this problem.

It also appears that I can't set the download directory to /data/local/tmp. The option to choose the download directory makes it relative to internal storage.

**Comment by Booteille** [comment]
I had to check the option to download to internal storage to make it work.
Thanks for the tips!

**Comment by daspuppy** [comment]
I don't know if this is against the nettiquette of this github, but there has been a fork, called Aurora, that has been mentioned in another issue. It does the same as we are used to and seems to be in active developement.

So, to @yeriomin Thank you for getting this started! Your work is being and has been appreciated by so many people! Thank you again!

**Comment by adolfintel** [comment]
@RuudschMaHinda Aurora hasn't seen an update in the past 5 months, and it's also affected by this issue (and there is no workaround for it). I already reported the issue but I've had no response. The developer was last seen on the project 4 months ago.
I don't know, it seems like both devs may have abandoned their projects, or maybe they've been abducted by Google's secret services.

**Comment by daspuppy** [comment]
Wasn't aware of that. Thank you!

**Comment by SuperITMan** [comment]
@adolfintel @RuudschMaHinda there is new fork of Aurora Store available on Gitlab which is working fine on LOS 16.0 (Android Pie) 😊
Have a look here: https://gitlab.com/AuroraOSS/AuroraStore

**Comment by adolfintel** [comment]
@SuperITMan Yea, that's what I'm using right now but it has other problems, like being unable to download purchased apps, which worked in the previous version, and most importantly for me is that when it checks for updates it basically sends the list of installed packages to google. This is unacceptable and the previous version did not do it.

**Comment by SuperITMan** [comment]
@adolfintel It's true. I hope they'll improve it soon. In any case, their current implementation is not in sync with their README... So I guess they will add back these features 😊

**Comment by quite** [comment]
Will be *automatically* closed? This is a serious functionality issue. Baffled. I'm fine with the maintainer closing it for *any* reason... but a bot.

**Comment by angela-d** [comment]
Have you tried downgrading to [0.43](https://github.com/yeriomin/YalpStore/releases/tag/0.43)?  I'm also on Pie/Lineage 16 and this was the last functional release, for me.

**Comment by adolfintel** [comment]
It's ridiculous that you let the stale bot close the issue. Do you even care about your project?

**Comment by daspuppy** [comment]
> It's ridiculous that you let the stale bot close the issue. Do you even care about your project?

For one, I do not condone this kind of personal questioning. Every OSS developed in someone's free time is for them to abandon at any time they wish. There might be very personal reasons for why there is no time to continue developing. Nobody owes us anything. If **you** care that much about this project, the beauty of OSS is, that you can just fork it and (have it) develop(ed) it yourself (by someone else).

Second, as stated further up, Aurora-Store is under active development. It just recently got an update.

**Comment by adolfintel** [comment]
I get your point, I was a bit rude. I just don't understand why someone would abandon their most popular project with no explaination whatsoever. At least archive the project so we know that you abandoned it and remove it from f-droid.
And yes I know that aurora is still being updated, but since version 3 that thing sends all your installed packages to google when checking for updates and yalp didn't do it.

**Comment by daspuppy** [comment]
As I said, if no reasons are given, always assume personal reasons. They are personal. Period.

We can only understand them leaving the project stale if we know the reasons. We are not entitled to know those reasons. We don't give money either. We just take, and demand. So if someone stops giving, they don't have to say why. And if they start giving again, they also don't need to state why they stopped. They can, but there is literally no obligation towards us.

As I said: It's open source. It can be forked.

> "There is complaining and not offering a solution, that is making yourself the victim.
> There is complaining and doing something about it. That is empowerment."

Something similar to this was quoted to me about two years ago. It rings true. I try to do my best to remind myself of it, as soon as I realize I am the one who is complaining.
