### ISSUE TITLE
cannot install any apk from yalpstore.

### ISSUE THREAD

**Issue by Heng1984617** [yeriomin/YalpStore#593]
I have installed yalpstore as the system app(preinstallation app) on LineageOS 15.
To download apk is working well.
But I found out that after downloading any apk from yalpstore and then when clicking "install button" on yalpstore, it occurs an unknown isee.

**Comment by jackTaw88** [comment]
That is happening to me too. I don't have rooted phone.

**Comment by pm-pm** [comment]
As a workaround try this tool: https://github.com/Aefyr/SAI
It can also install split apk!
