### ISSUE TITLE
How can I get updates from fdroid without any commit on this repo?

### ISSUE THREAD

**Issue by jackTaw88** [yeriomin/YalpStore#594]
Hi,

On this page: https://f-droid.org/en/packages/com.github.yeriomin.yalpstore/ you can see the last update is 2019-01-29. 

But on this repo the last commit is  Oct 16, 2018.

How can this happened?

Thank you

**Comment by tuxayo** [comment]
That might actually more a question for F-Droid

Anyway: https://github.com/yeriomin/YalpStore/releases

It seem to be related to having contemporary and ordinary (legacy?) versions. So the hypothesis is that it took some time for an F-Droid contributor to update the packages with this thing of having two flavors of the app.
