### ISSUE TITLE
[Question] Can Google Shut Down The Yap Store?

### ISSUE THREAD

**Issue by trymeouteh** [yeriomin/YalpStore#595]
I have been weary of depending on this app since I feel Google could shut this down, take legal action, or change the code and infrastructure on the Google Play Store to break Yalp from being able to download the apps. I know Google does change the YouTube video decoder once in awhile and it always break the NewPipe app which is a great FOSS YouTube app. Are any of these things possible to occur in the future and make Yalp broken or no more?

**Comment by angela-d** [comment]
They could disable use of the API, like they did for Hooktube: https://old.reddit.com/r/privacy/comments/903pxf/hooktube_is_no_more_so_i_made_a_similar_site/ - but they have not yet, so enjoy it while it's around.  Once it goes away, F-droid will be around and another Play Store replacement will surely crop up.

Alternatives always popup, https://invidio.us/ is what Hooktube once was.

Invidious is on Github, so be sure to star it: https://github.com/omarroth/invidious

Auto-replace Youtube links with Invidious (also works on Waterfox + Firefox for Android): https://addons.mozilla.org/en-US/firefox/addon/hooktube-redirect/

If you're worried about being sued for using the app? Nothing nowadays is out of the question, but you're a small fry to them.  If anything, they'd go after the dev.. which may have happened, based on his silence.  He could have also lost interest.

At this point, using it, your main risk is enjoying the app and one day having it stop working.

Who's to say one day Gmail won't be a $20/month service, too?  Google dominates every market they've entered, they definitely have the muscle to destroy every service you enjoy from them.

The best thing you could really do, is ween yourself off of their offerings.  F-Droid has some **excellent** Google-free apps.  Look there, before you even turn Yalp on.

**Comment by johanw666** [comment]
Youtube can still be accessed by parsing their website, like NewPipe does. However, downloading from the Play Store will be more complicated.

About Google going after this - I doubt it. Raccoon is still being worked on, and the repository is still up. But maybe having a few forks around would be safer.

**Comment by trymeouteh** [comment]
> Youtube can still be accessed by parsing their website, like NewPipe does. However, downloading from the Play Store will be more complicated.
> 
> About Google going after this - I doubt it. Raccoon is still being worked on, and the repository is still up. But maybe having a few forks around would be safer.

It getting the apk download that is tricky. Youtube is accessible by any browser so NewPipe can never really be stopped, just needs updates to ensure it can fetch the video.
