### ISSUE TITLE
Route downloads over Tor network

### ISSUE THREAD

**Issue by anoadragon453** [yeriomin/YalpStore#6]
Simply adding Yalp Store to Orbot's list of proxified apps only sends app lookups over Tor, not the downloads themselves. 

This would be useful for people wanting to download apks directly from Google without wanting to share their IP address with them.

**Comment by murkom** [comment]
Downloads are made via Download Manager, not the app itself. You should also add it to Orbot list. Not the best solution but should work.
Really nice app!

**Comment by yeriomin** [comment]
@murkom is right. Also, orbot has transparent proxying for rooted devices and there is no point in torifying one part of your traffic and not torifying another from a security point of view.
So, if it is an issue, it is not an issue with yalp.
I will consider running downloads without android built-in manager, though.
Thank you for writing an issue.

**Comment by rugk** [comment]
> there is no point in torifying one part of your traffic and not torifying another from a security point of view.

That's not true-. Maybe you only want to torrify Google connections. And maybe you do not have root. (Okay, VPN mode is possible.)

Also from https://github.com/yeriomin/YalpStore/issues/13:
> Orbot becomes kind of pointless if you're using an account but thanks for answering

It does not. What if you want to prevent Google from knowing your IP and using the IP your location in a more or less detailed fashion? This would already be helpful.

Also you do not need an account when you only download free apps.

---

So I'd argue for reopening this issue. Technically I'd argue for adding proxy support, which basically adds Orbot support as then you can just enter the IP/port of Orbot there. Many other privacy-conscious apps (DuckDuckGo, etc.) have this option built-in. So it's also easy to implement.

**Comment by rugk** [comment]
@yeriomin Could you please reopen this issue?

**Comment by marat1995** [comment]
@rugk +1

**Comment by rugk** [comment]
(You can just use the :+1: button to upvote comments.)

**Comment by marat1995** [comment]
@rugk I know

**Comment by yeriomin** [comment]
@rugk @marat1995 Please note that the issue is rather old. There was no built-in account in Yalp and no built-in download manager at that time.

Also, the issue is not about tor in general, but about sending download traffic through Yalp.

Also, even at the time of writing, it was possible to make android's DownloadManager work through orbot.

> This would already be helpful.

It is helpful. And can already be done without any modification of Yalp Store.

> So it's also easy to implement.

That's not a good reason to implement it. I'd rather focus on things which can not be done using external tools.

**Comment by rugk** [comment]
Then why not at least re-open the issue and mark it with "help wanted" so you make clear you accept PRs for this feature?
