### ISSUE TITLE
please ignore FDroid-managed apps out-of-the-box

### ISSUE THREAD

**Issue by TjrGithub** [yeriomin/YalpStore#600]
Currently, if you have both FDroid and Yalp installed, Yalp will try (and fail) to update any apps installed with FDroid. Those apps (and any preinstalled apps) will still clutter its display. Ideally, there would be some solution so that out-of-the-box, Yalp automatically hides and leaves alone any apps managed by other appstores.

There is a workaround with auto-whitelisting yalp apps or blacklisting FDroid apps, but (a) that is pretty unintuitive for new users, and (b) it doesn't work, see #580 and #574.

**Comment by TjrGithub** [comment]
Aurora store does this by ignoring apps with the FDroid signature.

**Comment by trymeouteh** [comment]
I would like this too. Aurora does this but if Yalp can do this then Yalp can focus on updating apps installed by Yalp and not any other source.

**Comment by TjrGithub** [comment]
The issue persists.
