### ISSUE TITLE
Getting "Could not install" for every app installed using root method on Pie

### ISSUE THREAD

**Issue by hieu-van** [yeriomin/YalpStore#601]
**Expected behavior**
Apps should be installed or updated as normal.

**Actual behavior**
Getting "Could not install" or "Update installation failed" when trying to do any relevant actions to every app. This is observed to be happening only in Android 9.

**Steps to reproduce**
1. Switch to root installation method.
2. Update or install any app.

**Your setup**
Device: _Xiaomi Mi A1_
OS: _LineageOS 16.0_
Yalp Store version: _0.45-legacy_

**Comment by johanw666** [comment]
I think this is a duplicate of https://github.com/yeriomin/YalpStore/issues/591 .
