### ISSUE TITLE
Blacklist not working

### ISSUE THREAD

**Issue by stemy2** [yeriomin/YalpStore#603]
Hello,

I put some apps in the blacklist, but yalp stills propose me updates of these apps.

**Comment by DPTJKKVH** [comment]
I can confirm this but only for the "ignore this update" option. The "ignore all updates" option works fine afaik.

**Comment by stemy2** [comment]
For me, the option «ignore all updates» doesn't work either.

**Comment by Echolon** [comment]
Hi, here another user co firming.

I have three apps which will repetively come back to the update screen. I usually blacklist apps because I retrieve them from Fdroid. Actually automatic recognition of this, if possible, would be cool.
