### ISSUE TITLE
What happened to Sergey Yeriomin?

### ISSUE THREAD

**Issue by momo42** [yeriomin/YalpStore#609]
Has anyone of you heard something from Sergey since October 2018?
It seems he was swallowed up by the soil on/after October 16, 2018. I did a bit research on the internet but wasn't able to find any sign of life. As he is from Russia (Saint-Petersburg) and I don't  understand the Cyrillic alphabet my options are very limited unfortunately. Any russian speaking people here?

**Comment by JonnyTech** [comment]
https://github.com/yeriomin/YalpStore/issues/576#issuecomment-488305235

**Comment by ploink** [comment]
Have a look [at this](https://liberapay.com/yeriomin/).
Sergey seems to have another account on gitlab where is [working right now](https://gitlab.com/users/yeriomin/contributed).
