### ISSUE TITLE
Can't find firefox aurora

### ISSUE THREAD

**Issue by Krawei** [yeriomin/YalpStore#61]
Dear developer,

I wanted to search and install firefox aurora (https://play.google.com/store/apps/details?id=org.mozilla.fennec_aurora) via the Yalp store, but it seems that Yalp doesn't allow to install "non-official-released-apps".

Is it possible to implement a method to install those "in-development/alpha" apps, maybe via a checkbox in the Yalp store settings, in the future? That would be great :).

Kind Regards,
Krawei

**Comment by yeriomin** [comment]
Thanks for the suggestion. I'll check why unstable apps are not shown.

**Comment by yeriomin** [comment]
Fix is in master.
