### ISSUE TITLE
Why can't I find this app?

### ISSUE THREAD

**Issue by Geremia** [yeriomin/YalpStore#610]
I'm using [LineageOS](https://lineageos.org/) (Android 7.1.2) on a Samsung Galaxy S4. Why can't I find the [com.banksimple](https://play.google.com/store/apps/details?id=com.banksimple) app using Yalp? (I can't find it with [Aurora](https://f-droid.org/en/packages/com.aurora.store) either, either with the default Google Play account or with my own.)

**Comment by tuxayo** [comment]
I confirm that one can't find it by the name.
But by "com.banksimple" it works.

Weird. Note that the on the PlayStore website, clicking on the name of the developer (Simple Finance Technology Corp.) gives an error.

**Comment by Geremia** [comment]
> by "com.banksimple" it works.

Yes, that works for me, too, but it prompts me saying that there already exists an app with that name…
