### ISSUE TITLE
Updates: error 500

### ISSUE THREAD

**Issue by barkingbandicoot** [yeriomin/YalpStore#613]
**Expected behavior**
Click 'check updates' - get list of updates available

**Actual behavior**
click 'check updates' - get 'server error 500'

**Your setup**
Device models: Oneplus 5T, Xiaomi Mi Pad plus, Xiaomi Redmi Note 5A
 android falvor: Pie
Yalp Store version: 0.45-legacy

**Comment by Pharaoh2k** [comment]
Same here

**Comment by Loigzorn** [comment]
Me too

Device:
Oneplus 5, Android 9.0.6
Android TV Box, Android 6.x.x

**Comment by abesty** [comment]
Same here

Device:
Asus Z00A, android 7.1.2
Yalp Store ver. 0.45-legacy

**Comment by heapifyman** [comment]
Same here. Fairphone 2, LineageOS 16

**Comment by monsieurpouet** [comment]
Same thing for me: RedmiNote 5 Pro - LineageOS 15 with MicroG - Yalp 0.45 Legacy

No problem with Aurora Store

**Comment by motorious1** [comment]
+1
Huawei Honor 5X
LineageOS 15 microG
0.45 Legacy from fdroid

**Comment by miloslavnosek** [comment]
The issue still persists and considering it's a major one preventing many people to use this app, it should not be closed due to inactivity.
