### ISSUE TITLE
How to remove the ota.zip

### ISSUE THREAD

**Issue by ghost** [yeriomin/YalpStore#615]
As yalp does not work anymore on my device. Has anyone an idea how to remove the ota.zip.

In the past there was a remove ota zip. But I can't find it.

Thanks for help ;)

**Comment by momo42** [comment]
+1

**Comment by johanw666** [comment]
Try Titanium Backup.

Edit: that didn't work on my device, but Lucky Patcher uninstalled it easily.

**Comment by pm-pm** [comment]
Sorry for my qestion, but can someone explain the problem please.

Where is the ota.zip and what is the function of this file.
When i uninstall an APP normally all files are removed. Or not?

Thanks

**Comment by johanw666** [comment]
If you install the apk it gets installed as a user app and can be uninstalled normally. The ota zip is used to flash Yalp into the system partition with a custom recovery, and system apps can not so easily be removed.

**Comment by pm-pm** [comment]
Oh, i understand.
Thanks for explanation. :-)

**Comment by JKingweb** [comment]
Removing it fairly easy:

1. Boot to TWRP
2. Select "Mount" and check "system"
3. Go back and select "Advanced" and then "File Manager"
4. Navigate to `/system/priv-app/YalpStore`
5. Tap the floating folder button in the lower-right corner and select "Delete"

**Comment by ghost** [comment]
Thanks - I forgot to mount thats why I asked initially ^^
