### ISSUE TITLE
Token dispenser returned an auth error

### ISSUE THREAD

**Issue by stemy2** [yeriomin/YalpStore#620]
Hello,

The app is unusable because of this error. I can't even search any app.

**Comment by JonnyTech** [comment]
YalpStore is abandoned. Please use Aurora Store instead.
Info page: https://f-droid.org/en/packages/com.aurora.store/
Current download: https://f-droid.org/repo/com.aurora.store_6.apk

**Comment by johanw666** [comment]
Aurora Store is great but it only works on Android 5 or later. Is there a solution for 4.4 as well (except from using Google Play Store)?

**Comment by dadosch** [comment]
> Aurora Store is great but it only works on Android 5 or later. Is there a solution for 4.4 as well (except from using Google Play Store)?

You might want to use Raccoon on your computer (but this is very unhandy)
