### ISSUE TITLE
Settings Are Not Obeyed Or Saved

### ISSUE THREAD

**Issue by puppykickr** [yeriomin/YalpStore#624]
**Before creating an issue**
1. Make sure you are running the latest version of Yalp Store. Check [here](https://github.com/yeriomin/YalpStore/releases/latest).
2. Search for similar issues [here](https://github.com/yeriomin/YalpStore/issues?q=is%3Aissue).
3. Send developer a bug report using Yalp's built-in crash tool. Please identify yourself - the reports are anonymous by default.
4. Number 3 is important. Please do it. It helps a lot.
5. Use the following template to write the text of your issue.

**Expected behavior**
Tell us what should happen
Open app, and use settings to customize.

**Actual behavior**
Tell us what happens instead
Open app, use settings to customize, and the app ignores them.

**Steps to reproduce**
1. Open app
2. Adjust settings
3. Use app
4. Notice settings are ignored
5. Notice that settings are back to default upon reopening app

**Your setup**
Device model, 
ZTR 558VL
android falvor,
7.1.1
Yalp Store version
0.45-legacy

This app does not save settings in regard to the blacklist.

It also starts downloading updates immediately, even though I have turned that setting off repeatedly.

Not to mention that it completely ignored me as I frantically tapped 'CANCEL' over and over again while this stupid thing downloaded Google, Facebook, Messenger, and tons of other junk that I spent a large amount of time disabling and getting rid of.

Even getting the app out of recent apps didn't make the stupid thing stop, I tapped 'UNINSTALL' and got rid of the bastard.

So now I have to go digging around looking for all the bastard Google apks for the apps that I don't want on my device, and look to see if any of that crap got updated.

How convenient!
(sarcasm, if you are not aware)

This app is like stubbing a toe on a dark staircase!

And by the way, it doesn't work on 8.1.0 at all.

**Comment by JonnyTech** [comment]
This project is abondoned. Please close this issue and use `Aurora Store` instead: http://auroraoss.com/

**Comment by puppykickr** [comment]
@JohnnyTech

Then why, if this thing is broken (worthless) isn't it pulled off of F-Droid?

A few dumpster fires like this one are all that is needed to give an app store a bad name.

**Comment by JonnyTech** [comment]
@puppykickr please discuss at https://gitlab.com/fdroid/fdroiddata/issues

**Comment by puppykickr** [comment]
I tried Aurora Store and it is even worse.
Can't login, can't download, just nothing.

Done farting around with apps like these, Aurora was the third one I tried that does not work.

Just going to use my browser for ApkPure, UpToDown, and the like.

**Comment by puppykickr** [comment]
I tried Aurora Store and it is even worse.
Can't login, can't download, just nothing.

Done farting around with apps like these, Aurora was the third one I tried that does not work.

Just going to use my browser for ApkPure, UpToDown, and the like.
