### ISSUE TITLE
"No apps found" when searching in Yalp store

### ISSUE THREAD

**Issue by mkborregaard** [yeriomin/YalpStore#625]
**Expected behavior**
When I search for apps to download, I expect a list of search results.

**Actual behavior**
After searching for ~30 seconds (with the circling wheel upper right), a blank screen is shown, with the words "No apps found". Surprisingly, the autocompletion in the search field works, so I can see the name of the app I want to download. But selecting it results in no results. Updates to already installed apps work unproblematically.

I've tried ticking "download to internal storage" (following some advice on an older issue), and also registering my own account rather than the built-in one. Same issue for both. I don't believe I have a firewall installed. I've also reported the issue using Yalp's inbuilt bug tracker.

**Steps to reproduce**
1. Search yalp for an app that isn't installed already.

**Your setup**
I've got a Fairphone 2 with Fairphone Open OS based on Android 7.1.2, Yalp store 0.45-legacy

**Comment by JonnyTech** [comment]
This project is abondoned. Please close this issue and use `Aurora Store` instead: http://auroraoss.com/

**Comment by ildar** [comment]
The bug effectively fixed in https://f-droid.org/en/packages/com.github.kiliakin.yalpstore/

**Comment by mkborregaard** [comment]
Great - though that app is incompatible with my phone and won't install from f-droid. I've gone to aurora instead.
