### ISSUE TITLE
Changing installation method to system service resulted in a boot loop.

### ISSUE THREAD

**Issue by hollusion** [yeriomin/YalpStore#626]
**Actual behavior**
I changed the installation method in yalpstore settings to root and it did not solve the problem installing keybase.io - afterwards i tried the third option "system service" and yalp rebooted my device and since then it got stuck in a boot loop.

This is what i found in the error logs: http://dpaste.com/3Y7940T

I tried to remove the yalpstore app in order to be able to boot again but im not able to locate the package anywhere. (not found in /data/app): http://dpaste.com/0NT790C

Can you tell me how to revert the yalpstore setting or how to remove the yalpstore app?

**Your setup**
Device: Motorola G5S Plus
LinageOS 15

**Comment by Lineage2019** [comment]
I had the same problem, I resolved it by following the below steps.
Thanks to  JKingweb for the instructions: https://github.com/yeriomin/YalpStore/issues/615

1. Boot to TWRP
2. Select "Mount" and check "system"
3. Go back and select "Advanced" and then "File Manager"
4. Navigate to /system/priv-app/YalpStore _(Last folder name was different for me, but it had Yalp in the name )_
5. Tap the floating folder button in the lower-right corner and select "Delete"
