### ISSUE TITLE
404 when using a google account

### ISSUE THREAD

**Issue by niccokunzmann** [yeriomin/YalpStore#628]
**Expected behavior**
Tell us what should happen

I would like to see a message telling me that I can now use the account I added.

**Actual behavior**
Tell us what happens instead
I type in username and password and I get "client error 404"

**Steps to reproduce**
1. click menu
2. click account
3. click on add account
4. enter username and password
5. click ok
6. error message pops up

**Your setup**
Device model, android falvor, Yalp Store version

**Comment by buddabrod** [comment]
Same here.

Sony Xperia SP (huashan)
LineageOS 15.1 (2019-11-11)

**Comment by fake-fur** [comment]
likewise - 404 error and unable to log in with either yalp store account or my actual account

**Comment by Klimmbimmel** [comment]
Same
Honor 5X
LineageOS 14.1 (aka Android 7.1.2)

Checked the firewall settings, also turned it off, still 404

Tried with Aurora: it said "Check your password". Then I got a "Security alert" in Gmail, which offered me to verify that this was me. Checked that. Now logging in with Aurora works. Still same error with Yalp

**Comment by AreYouLoco** [comment]
I can confirm same error. ~~404 (internal)~~ or 405 (own account). Maybe the API changed a bit. 

Ok I am not a programmer but this doesnt work anymore:
https://github.com/yeriomin/play-store-api/blob/master/src/main/java/com/github/yeriomin/playstoreapi/GooglePlayAPI.java ~~(line 28)~~

In summary: https://android.clients.google.com/auth gives 405. ~~Someone knows/willing to find out new URL?~~

~~The easiest would be to sniff traffic from some stock android with new play store and try to log in and see the updated url.~~

Someone is up to?

**Comment by AreYouLoco** [comment]
Or maybe they require some new additional request query parameters or what? Aurora doesnt work for me either. Stuck on logging in. 

EDIT: Aurora worked!

**Comment by AreYouLoco** [comment]
According to this: https://gitlab.com/AuroraOSS/AuroraStore/issues/217 sometimes google might require you to solve captchas when logging. And also this suggest that we should go to new google API as there are clearly improvement over one used now: https://github.com/yeriomin/play-store-api/compare/master...whyorean:master#files_bucket

I dont know why but i still prefer yalp interface more.

Some workaround for you to try could be also solving this:
https://accounts.google.com/DisplayUnlockCaptcha
And then retrying to log in again.

**Comment by ildar** [comment]
@deerp , mine works using 2FA and using app password (not the MASTER
password)

**Comment by AMTQ** [comment]
> Some workaround for you to try could be also solving this:
> https://accounts.google.com/DisplayUnlockCaptcha
> And then retrying to log in again.

Does not work, unfortunately, but thanks for the tip. I still get the error 404 with the Yalp Login as well with my other login.

**Comment by LeviLucena** [comment]
Pocophone F1
MIUI 11.0.5 
0.1045

**Comment by MordicusEtCubitus** [comment]
Using "shared yalp store account" failed for I
So entering my own account failed too with 404 error
phone is Fairphone 2

**Comment by boonaun** [comment]
哈哈哈哈哈哈哈哈哈哈/郁郁///郁郁u7好好好好好好好好好哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈个=给=哈哈哈/哈哈哈哈哈哈哈哈/哈哈/哈哈哈哈=与v暴雨被？从

**Comment by BlankerL** [comment]
Same issue here
Sony BRAVIA X9500G

**Comment by MJimitater** [comment]
Same problem using Samsung A3 (a3xelte) with LineageOS for microG.

Thanks @AreYouLoco for your workaround tip, unfortunately it didn't work for me.

Does anyone have a solution for this?

**Comment by ildar** [comment]
Yalp Store (fork) (Download apks from Google Play Store) -
https://f-droid.org/app/com.github.kiliakin.yalpstore ?

**Comment by MJimitater** [comment]
@ildar thanks cheers! I tried the fork and the error message did not appear! But I couldn't figure out an easy way to bypass gmail sms verification, I researched several workarounds, none of them worked the way I wanted them to. So instead, I switched to Aurora Store, which works well

**Comment by Nikolai-Dergocich** [comment]
I have a Ulefone Armor 7E
