### ISSUE TITLE
No search on Android 2.3?

### ISSUE THREAD

**Issue by waweic** [yeriomin/YalpStore#63]
The Update-function seems to work, the search function does not. I can not see a search icon. I am usin a Galaxy Ace with stock rom.

**Comment by yeriomin** [comment]
Are you sure you are not forgetting to press the "menu" hardware button? App bar where you would see the "search" icon did not exist until honeycomb. You could also press the "search" hardware button. Both options work on my HTC Bravo.

**Comment by waweic** [comment]
Oh, I'm sorry. I was just setting up the Phone for a friend of mine and it looks like i just forgot to press the hardware button. I have to confess, i never used a Version of android before KitKat. Thanks for your Help! ;)
