### ISSUE TITLE
Login API Fixing

### ISSUE THREAD

**Issue by FriendlyNeighborhoodShane** [yeriomin/YalpStore#630]
As everybody here probably knows, Google changed the login API and now it probably requires a captcha on every request, and thus, both the normal and anonymous logins don't work on Yalp anymore.

Thankfully this is nothing to be concerned about, since [AuroraStore](https://gitlab.com/AuroraOSS/AuroraStore) dev Whyorean already put a new system in place for both types of login that is hopefully more future-proof that GApps themselves use. It uses webview and open a login session as an embedded browser window.

Alternatively, someone in Aurora's issues managed to make the old system work by forcing certain encryption protocols through a proxy, but dunno if that's possible at app level.

I normally use Aurora, but right now I need Yalp on an old device.

I don't know java at all, and I know yeriomin has gone MIA, so I hope @kiliakin or some other interested contributor will update the Yalp source and update their dispenser with the fixed one from the AuroraOSS's repo.

**Comment by ale5000-git** [comment]
Bump.

**Comment by ghost** [comment]
bump

**Comment by FriendlyNeighborhoodShane** [comment]
Hello @ale5000-git ! 
Uhhm this might not be the most ideal place to contact you, I realise (⌒_⌒;) But I do need to request you something.

I make a microg pack myself and am part of a community that uses that and NanoDroid, and NLP is broken on Android Q. There are pull requests on the github that should solve this issue.

I won't mind even if you ignore me, I see you don't maintain your pack anymore and probably don't wanna deal with all the hassles og µG, but if possible, could you please merge the PRs and (IDK if you have access) trigger the build system for the official repo? Marvin seems to be MIA (again).

Thanks either way!
