### ISSUE TITLE
Is it dead

### ISSUE THREAD

**Issue by ghost** [yeriomin/YalpStore#631]
@yeriomin Is this project officially dead? Thanks.

**Comment by DamienCassou** [comment]
Apparently. There is this fork: https://github.com/kiliakin/YalpStore.

**Comment by JonnyTech** [comment]
This project is abondoned. Please close this issue and use `Aurora Store` instead: http://auroraoss.com/

**Comment by ghost** [comment]
Closing the issue, I found my answer...
