### ISSUE TITLE
The version from fdroid does not work anymore 

### ISSUE THREAD

**Issue by exebook** [yeriomin/YalpStore#632]
It won't connect with the built-in account, neither with my email /password (client error 404).

**Comment by evelineraine** [comment]
Same with the (more) up-to-date fork - https://github.com/kiliakin/YalpStore.

**Comment by ildar** [comment]
And that apk is available here: Yalp Store (fork) (Download apks from
Google Play Store) - https://f-droid.org/app/com.github.kiliakin.yalpstore

**Comment by jzuellig** [comment]
any updates?

**Comment by ildar** [comment]
why?
using (your) login Yalp works (the above fork).
Anonymous login doesn't work (yet). Aurora implemented a fix but nobody
backported it to Yalp.

**Comment by TheyCallMeSD** [comment]
Ancora non ci sono aggiornamenti per il problema Yalp store?
Xiaomi 5 redmi plus 
Android 8.1.0

**Comment by IslandJohn** [comment]
Same issue, Client error 404, with both this and the "up-to-date" one. The fork does not seem to work.

**Comment by ildar** [comment]
this? https://f-droid.org/en/packages/com.github.kiliakin.yalpstore

**Comment by IslandJohn** [comment]
Yes. Neither that one linked immediately above (46/47), nor the forked one on GitHub (46) work for me.

**Comment by ildar** [comment]
Works just fine. Remember that anonymous logins do not work anymore

**Comment by TheyCallMeSD** [comment]
Il problema ora è che quando installo un'applicazione più grande , mi
divide l'applicazione in 2 .apk e non permette l'installazione...

Il mer 22 apr 2020, 3:14 AM Juan Islando <notifications@github.com> ha
scritto:
