### ISSUE TITLE
Yalp store inaccessibile.

### ISSUE THREAD

**Issue by TheyCallMeSD** [yeriomin/YalpStore#633]
Ciao a tutti, dopo aver letto i vari post, ancora non ci sono aggiornamenti per il problema  Yalp store ad oggi risulta inaccessibile per aggiornamenti? Grazie
Xiaomi 5 redmi plus
Android 8.1.0
Yalp store 0.45 anche con Yalp store (fork)

**Comment by Klimmbimmel** [comment]
Adding the deepL translation:

Hi everyone, after reading the various posts, still no updates for the problem Yalp store to date is inaccessible for updates? Thanks

**Comment by TheyCallMeSD** [comment]
Yes, the translation it's ok .

Il mer 15 apr 2020, 9:15 AM Klimmbimmel <notifications@github.com> ha
scritto:
