### ISSUE TITLE
can't login 

### ISSUE THREAD

**Issue by Imveryweird** [yeriomin/YalpStore#636]
**Before creating an issue**
1. Make sure you are running the latest version of Yalp Store. Check [here](https://github.com/yeriomin/YalpStore/releases/latest).
2. Search for similar issues [here](https://github.com/yeriomin/YalpStore/issues?q=is%3Aissue).
3. Send developer a bug report using Yalp's built-in crash tool. Please identify yourself - the reports are anonymous by default.
4. Number 3 is important. Please do it. It helps a lot.
5. Use the following template to write the text of your issue.

**Expected behavior**
I should be able to log in and use the app

**Actual behavior**
I cannot 

**Steps to reproduce**
1.Open app
2. Try to login
3. can't 

**Your setup**
Samsung s8+, android 8.0, Yalp store 0.46

**Comment by jmaris** [comment]
still persists

**Comment by flipreverse** [comment]
Same here. Yalp store 0.45-legacy. Android 6.0.1 (CM13.0). Google Galaxy Nexus

**Comment by SubZero5** [comment]
Same here. Yalp Store 0.45-contemporary. Android 9.0 (OxygenOS 9.0.5). OnePlus 3

**Comment by ewtoombs** [comment]
I'm pretty sure this entire project is dead now.

**Comment by mycal123** [comment]
same,look like default credentials banned by google

**Comment by HemanthJabalpuri** [comment]
Same issue here, I had to use yalp store only since I am using Android x86 2.2 in my virtual box. Aurora Store does not support <5.0. #627

**It is fixed in the fork of Aurora Store dev at https://github.com/whyorean/YalpStore**
