### ISSUE TITLE
Wear OS device option?

### ISSUE THREAD

**Issue by hacker1024** [yeriomin/YalpStore#637]
**Is your feature request related to a problem? Please describe.**
I'd like to download a region-locked Wear OS app, but there are no watches available in the device selection list.

**Describe the solution you'd like**
It'd be great if at least one armv7 Wear OS device was an option. I'd be happy to give any info neccesary from my Mobvoi Ticwatch Pro (catfish), for example.

**Describe alternatives you've considered**
There aren't really any, as far as I can tell.

**Comment by hacker1024** [comment]
Anyone?

**Comment by ildar** [comment]
nope )))
abandoned.
