### ISSUE TITLE
failed obb file downloading

### ISSUE THREAD

**Issue by killoid** [yeriomin/YalpStore#64]
it only downloads the apk, doesn't download any obb files. is it possible to be able to download obb file downloading? thanks.

**Comment by yeriomin** [comment]
Its possible. Could you provide an example of apps which can't download the obbs? The ones I know download obbs by themselves.

**Comment by killoid** [comment]
yeah, i downloaded a game called 'tap titans 2'. here it is-
https://play.google.com/store/apps/details?id=com.gamehivecorp.taptitans2

**Comment by yeriomin** [comment]
Implemented in master. Obb files are put into the [required place](https://developer.android.com/google/play/expansion-files.html#StorageLocation) before app installation.
