### ISSUE TITLE
Threema crashes yalp store

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [yeriomin/YalpStore#70]
Hi there,
on yalp 0.6 when I displayed the app page of the threema app in yalp, it would just show an empty page with no button to download and no info. 
Now with yalp 0.8, I still get the empty page, but when I hit the back button, yalp crashes.

For all other apps, all is working great, it is just Threema.

Anyone else experiencing this?

**Comment by yeriomin** [comment]
Issue #71 better describes this problem. Closing as duplicate.
