### ISSUE TITLE
[BUG] Cant view apps that I rated

### ISSUE THREAD

**Issue by teod0r** [yeriomin/YalpStore#71]
In 0.6 can't view apps for which I leaved a review. Such apps just don't load: the zarea of Yalp Store below main upper bar stays blank

**Comment by teod0r** [comment]
Только что обновил до 0.8 -- проблема остаётся

**Comment by 1337sup3rh4x0r** [comment]
This might be related to #70 since I also ratet that app

**Comment by TobiasBielefeld** [comment]
i have the same issue with rated apps. These apps also produce the following exception:

> com.github.yeriomin.yalpstore.DetailsActivity$1: Unknown exception java.lang.IndexOutOfBoundsException Invalid index 0, size is 0

On version 0.8 yalp crashes when pressing the back button on empty pages with this exception:

> java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.yeriomin.yalpstore.DownloadOrInstallManager.unregisterReceiver()' on a null object reference

**Comment by yeriomin** [comment]
Fix is in master.
