### ISSUE TITLE
[BUG] If network error occures, Yalp Store stops working forever

### ISSUE THREAD

**Issue by teod0r** [yeriomin/YalpStore#72]
If network error occures, Yalp Store doesn't search after connection restores

**Comment by yeriomin** [comment]
Cannot reproduce. Please be more specific. Does it crash? Anything suspicious in the logs?

**Comment by teod0r** [comment]
Вобщем при старте, когда проверяет обновления, если в этот момент нет инета, то после появления инета всё-равно говорит, что нет соединения и даже поиск не работает, приходится перезапустить программу.

**Comment by yeriomin** [comment]
Ни на одном из моих устройств (api 10, 21, 25), ни на эмуляторе с kitkat-ом не воспроизвести. Возможно проблема только с вашим устройством. Поскольку решеине такое простое как перезапуск, то проблема не велика. Закрываю.

**Comment by tmolitor-stud-tu** [comment]
I seem to have this problem, too.
I can not open googleplay urls to apps or seach for apps anymore.
