### ISSUE TITLE
Crash when entering details of applications

### ISSUE THREAD

**Issue by oktay454** [yeriomin/YalpStore#73]
Crash when entering details of applications after version 0.8
My english ver bad. I am sorry

**Comment by killoid** [comment]
provide a log of the crash & also details of your device (device name, rom, android version etc.).

**Comment by yeriomin** [comment]
This is very vague, but seems to be the same as #71.
What app makes Yalp crash? Can you provide the logcat? What device are you using? It is impossible to reproduce your problem without this info.

**Comment by oktay454** [comment]
Cyangenmod 13 for wileyfox swift on general mobile 4g
Kernel 3.10.49
Need more information? If so, with what software can I learn?

**Comment by yeriomin** [comment]
Version 0.9 is out on f-droid. Please check if the problem is still happening.

**Comment by oktay454** [comment]
Thanks =) There was no problem. Good and fast work
