### ISSUE TITLE
unable to show app info

### ISSUE THREAD

**Issue by syl3nt** [yeriomin/YalpStore#74]
i had spotify installed, i uninstalled .
i try to install it again, and the app screen stays black (i'm on dark theme) 
no install button, no nothing, just the header of the app that i am currently seeing , but no icon or name.

**Comment by yeriomin** [comment]
This seems to be the same as #71. Have you rated this app?

**Comment by syl3nt** [comment]
no, i didn't

**Comment by yeriomin** [comment]
Version 0.9 is out on f-droid. Please check if the problem is still happening.

**Comment by syl3nt** [comment]
Yes, it still happens overtime, when i installed over it, it was fine, then it happened again, i cleared the app data,  uninstalled the app, installed it clean, didn't choose my account, but the new method without account ( it works better for me, since i dont have to do create an app passwd to associate everytime) and it still doesnt open certain apps, for example, plague inc, spotify

**Comment by yeriomin** [comment]
@syl3nt Please give examples of apps which cannot be opened.

**Comment by syl3nt** [comment]
after i updated the app to 0.10 i no longer saw more apps not being displayed, you can close the issue now, if i see it again, i'll report .

**Comment by yeriomin** [comment]
Thanks.
