### ISSUE TITLE
Don't use Downloads Folder

### ISSUE THREAD

**Issue by Nutomic** [yeriomin/YalpStore#79]
It should be possible to update or install applications without filling up the downloads folder. 

A good alternative location might be [Context.getExternalFilesDir(null)](https://developer.android.com/reference/android/content/Context.html#getExternalFilesDir(java.lang.String)). This folder can be accessed without any permissions, and is removed automatically when the app is uninstalled.

**Comment by yeriomin** [comment]
Issue #65 deals with preventing "filling up the downloads folder". Context.getExternalFilesDir(null) is located on the same storage device, so it is going to fill up the same space. And downloads directory is a lot more well known by users.

From docs getExternalFilesDir:
> These files are internal to the applications, and not typically visible to the user as media

That's not what I want. These files are supposed to be visible to the user.

So why not Downloads?

**Comment by Nutomic** [comment]
The thing is, I don't want to keep any .apks after I installed them. Google Play and F-Droid do this by downloading to an internal folder, and deleting the .apks after. So how about using the downloads folder, but deleting the .apk after installation? Possibly with a setting to configure this.
