### ISSUE TITLE
add support for downloading paid apps

### ISSUE THREAD

**Issue by CarlosEkisde** [yeriomin/YalpStore#8]
This app would be perfect for replace official Google Play Store if you could add support for downloading pay apps (I'm talking of legitly paid apps, of course)

**Comment by 1337sup3rh4x0r** [comment]
Is this something that can be achieved at all without the framework in place?

**Comment by yeriomin** [comment]
I don't think it is a good idea. Google punishes users by blocking their accounts leaving them unable to use apps they paid for.
However, I have used fake accounts extensively to test yalp and none of them are blocked yet, and neither is my main account. So I will probably add this feature in future.
Thank you for writing an issue.

**Comment by 1337sup3rh4x0r** [comment]
Thanks for considering this!

The thing for me, as probably for many others too, I could totally go without google framework, it's only some paid apps that aren't available anyplace else than play store.

I currently have gapps on my phone only to be able to install and update paid apps.

So you could definitely fill that gap!
