### ISSUE TITLE
"View in Play Store" button

### ISSUE THREAD

**Issue by yeriomin** [yeriomin/YalpStore#81]
If Google Play Store is found on the device, a button appears in the details activity which takes the user to the app's Play Store page.

**Comment by avently** [comment]
У меня нет плэй стора, но вместо него стоит заглушка blankstore, чтобы остальные приложения не ругались на отсутствие плэй стора. Так вот, эта кнопка для открытия появляется, а она вовсе ни к чему (я отдаю себе отчет в том, что программно не получится определить, от гугла это плэй стор, или "левый" апк). Думаю, люди используют твое произведение искусства не в дополнение к гугловскому магазину, а вместо него. И эта кнопка просто лишняя получается.

**Comment by yeriomin** [comment]
@avently Люди используют приложение по-разному. И хотят противоположных вещей. Кнопка останется.
