### ISSUE TITLE
ability to update f-droid apps.

### ISSUE THREAD

**Issue by killoid** [yeriomin/YalpStore#82]
it would be nice to have this function as i have quite a few opensource apps in my device. but i don't want to install another store app (f-droid) just to update them. we can have a separate list of opensourced apps so that they only check for update on f-droid. so will it be possible to include it?

**Comment by yeriomin** [comment]
This is out of scope of the project.

For me implementing this would require a lot of work and no functionality would be gained, because F-droid client exists and is open source. F-droid client is a well-written software. Unlike Play Store app, there is no reason to replace it. You should use it.
