### ISSUE TITLE
ability to download beta/alpha version of apps.

### ISSUE THREAD

**Issue by killoid** [yeriomin/YalpStore#83]
as i am using the built-in account, i can't download beta/alpha version of many apps. i don't know using personal account can solve this issue. please let me know otherwise including this function would be great.

**Comment by yeriomin** [comment]
I cannot check that unless you provide a specific package name. There is no distinction in the Google API responses.
Also, this looks like #61.

**Comment by killoid** [comment]
for example this app [https://play.google.com/store/apps/details?id=com.paget96.lspeed](url)
the beta versions of this app can be accessed by signing up in this link [https://play.google.com/apps/testing/com.paget96.lspeed](url)
then it will show the beta versions upload into google play to download them.

**Comment by yeriomin** [comment]
Nothing on the app page indicates that testing versions are available, there is no way to get the second url you posted from the app page. Looks like the sign-up process is unique for every app and depends on the app developer.

So it is impossible to do it unless you are a human. Sorry.

**Comment by Exagone313** [comment]
I have this issue, using an account I created and signed up to a "beta" program with. Should I create another issue?
