### ISSUE TITLE
Search not finding specific apps

### ISSUE THREAD

**Issue by LinuxLowell** [yeriomin/YalpStore#86]
This worked on a previous version of yalp but can't gud this app any more using yalp.

Steps to duplicate issue
1) in yalp search for "commissary rewards"
2) no apps found
3) open browser and go to play.google.com
4) search for "commissary rewards"

This is the only app yalp can't seem to find...but did in previous versions. Screen shots attached.

**Comment by LinuxLowell** [comment]
![screenshot_20170303-062605](https://cloud.githubusercontent.com/assets/24941597/23555016/1f023846-ffdc-11e6-82c9-9d7e3982bf79.png)
![screenshot_20170303-062654](https://cloud.githubusercontent.com/assets/24941597/23555018/2222bb4a-ffdc-11e6-87c8-95e5333423f8.png)

**Comment by yeriomin** [comment]
@LinuxLowell I don't even see it on play.google.com:
![screencapture-play-google-store-search-1488580591141](https://cloud.githubusercontent.com/assets/554737/23573318/20bc2778-0086-11e7-8107-b851dfe241fe.png)

And neither in Play Store app. The developer must have changed its compatibility. Or it might be locked geographically. Is it an app of some local business?

**Comment by LinuxLowell** [comment]
Yes, it is probably locked down by geography... only available in the United States.  If Yalp is not reporting location now, it makes sense why the app would not show up.  However, I was able to find it and download it when I was using Yalp 0.3.

I don't have the Play App on my phone.. no Google Services at all. Hence wanting to use Yalp.

![selection_032](https://cloud.githubusercontent.com/assets/24941597/23574341/4331e63e-0032-11e7-864e-e19e438d0c42.png)

**Comment by yeriomin** [comment]
I cannot check this myself, but I might have found a workaround. You can go to http://www.commissaries.com/rewards/ and click the Play Store button. If the only Store app on your device is Yalp, it will take you to Yalp Store details activity with the download button.

When I go to this specific app's page I'm being told "This item isn't available in your country". This is not something Yalp can fix, Play Store filters users by ip address and/or by billing address.

**Comment by LinuxLowell** [comment]
Thanks for the thorough investigation. that's more than I expected. You did help me find the problem, had nothing to do with location. Some how since the first time I installed it via yalp and new they've changed the device requirements. It now tells me the app is not compatible with my device.

**Comment by LinuxLowell** [comment]
Thanks for the thorough investigation. that's more than I expected. You did help me find the problem, had nothing to do with location. Some how since the first time I installed it via yalp and new they've changed the device requirements. It now tells me the app is not compatible with my device... Nothing has changed on my device and it works fine when I side load it. Totally not a yalp issue. Please close and thank you very much.

**Comment by yeriomin** [comment]
You are welcome.
