### ISSUE TITLE
Version 0.10 crashes

### ISSUE THREAD

**Issue by ratsalad70** [yeriomin/YalpStore#88]
After last upgrade (0.10), Yalp crashes when I tap on an app in the store.
I get a message which says "Sorry, Yalp store crashed", and I tells to send a mail to developer.
Update- checking, search and settings menu work well. Previous versions work perfectly.
I use Android 6

**Comment by yeriomin** [comment]
@ratsalad70 Its a duplicate of #84. I've tagged v0.11 a day ago, it will be on f-droid in a couple of days.
