### ISSUE TITLE
TokeDispenserException Error 404

### ISSUE THREAD

**Issue by phuyuk** [yeriomin/YalpStore#90]
Network error: com.github.yeriomin.yalpstore.TokenDispenserException Error 404

**Comment by yeriomin** [comment]
When does it happen? Does it happen all the time? How do I reproduce it?

You can send me an email with some debug info by tapping on the developer email on the "About" page of Yalp Store. Please answer the questions above in the letter or here.

**Comment by phuyuk** [comment]
Sorry, I should have elaborated. This error would immediately appear, centered against a black screen, at launch. It did not FC, but was impassable. Reinstalling 'fixed' this problem.

However, a second issue then presented itself: FC upon selection of any app, from the presented list of available updates. I was able to send you a crash report for this second issue - and then I reverted to 0.9 (which seems to be working).

**Comment by yeriomin** [comment]
That was fixed in #84 3 days ago. The fix is in v0.11. F-droid will soon compile it.
