### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by EMK2000** [yeriomin/YalpStore#91]
I am currently have the v0.9 from F-Droid. 
When I download v0.10 from F-Droid it installed normally. 
But when I download v0.11 from GitHub, it cannot be installed and says that the package name is conflicted with another app, which is actually v10. 
Is that the F-Droid and the GitHub version are not compatible?

**Comment by JonnyTech** [comment]
They are signed with a different key. Android insists that app upgrades use the same key. This is so that a fake app does not get access to the data of an existing app. So to install any app from a different source one must uninstall the existing version first which will also remove the data too.

**Comment by EMK2000** [comment]
So in your opinion, which one is better to use? The F-Droid one or the GitHub one?

**Comment by JonnyTech** [comment]
They are both exactly the same code, just compiled by different people. I prefer F-Droid as it automatically checks for updates and life is too busy for me to remember. If a bug is found and fixed then I can wait several days for F-Droid to build and upload or I can downgrade a version. But some people like the very latest and absolutely cannot wait...

**Comment by EMK2000** [comment]
If GitHub version is compiled by the developer himself, will it be more safe?

**Comment by JonnyTech** [comment]
F-Droid guarantee to compile the source as is. It is all about trust. If you are concerned then you are free to check and compile it yourself. That is the freedom of open source.

**Comment by yeriomin** [comment]
@JonnyTech is exactly right. I recommend using the f-droid version, it comes out 3-4 days after I tag a new release. In case you wonder, the apk on the release page is compiled by travis-ci.

> will it be more safe?
Depends on your definition of safety. Yalp is open source, so anyone can compile it with some malware inside and distribute the apk. I can tell you that the apk from releases page is safe and genuine, but there is no way for me to prove that I am the author. I am just some guy on the internet. With f-droid though you know that a) the app is compiled form original source b) it was f-droid who compiled it and no one else.
