### ISSUE TITLE
Sorry, Yalp Store crashed. Can't Download Any Apps.

### ISSUE THREAD

**Issue by evilrobotted** [yeriomin/YalpStore#95]
Ever since last night, I can't get Yalp Store to download anything, including Updates, Free, and Paid apps (using my Google account sign-in). All I get is an error message saying to send the error data to the developer, which I have done. It was working wonderfully up until then... now I can't download anything from the store, even after Clearing Data, Uninstalling/Reinstalling, Force Stopping, signing in with the generic info, signing in with my Google account info, and after rebooting many times.

**Comment by JonnyTech** [comment]
It is a known problem with v0.10 (#84, #88) and is fixed in v0.11 so either download that or downgrade to v0.9 and wait for F-Droid to build it.

**Comment by evilrobotted** [comment]
Thanks. That worked perfect.
