### ISSUE TITLE
Updating System Apps

### ISSUE THREAD

**Issue by vapingisgood4you** [yeriomin/YalpStore#97]
could you please consider adding​ in the ability to update system apps such as system webview and any preloaded OEM apps that are updated through the play store?

**Comment by Technowix** [comment]
Thoses ares system app, and for changing system app you need root access / flashing them.
Even with, I don't think all thoses apps are universals and can be shared between devices, you can try to search for some on [Apkmirror](http://www.apkmirror.com/) and manually install them to see

**Comment by yeriomin** [comment]
I am looking to it

**Comment by vapingisgood4you** [comment]
Thank you very much
