### ISSUE TITLE
"null, incompatible"

### ISSUE THREAD

**Issue by Technowix** [yeriomin/YalpStore#99]
I tryed several query / version and using my main google account + Yalp's one : each time I try to search an app I get this :
![screenshot_20170310-124427](https://cloud.githubusercontent.com/assets/1571367/23794257/917734fe-058f-11e7-9a34-5387c453138a.png)

**Comment by syl3nt** [comment]
Same here ! , i have video feed of replicating the issue, ill edit it once i've uploaded

**Comment by Technowix** [comment]
Did you just installed it or it was working yesterday like me ?

**Comment by Eskuero** [comment]
Can confirm this, yesterday was working just fine but at night it started no being able to search for apps.
It sees the new updates and is able to open the page for that app but the search function returns nothing.
It's not the 0.11 update causing the issue as it was working, so probably something on Google's side

**Comment by yeriomin** [comment]
I am looking to it

**Comment by syl3nt** [comment]
for me i think it was working .. yesterday i haven't the urge to search for the app that i searched today .. so .. i don't know if it was working yesterday, but i know that 

i really would like for you to see a video feed of it, to have a better perspective, but i seem to be unable to upload it through any video service ( youtube . . vidme..  seems the encoder is acting weird .. )

**Comment by Switch123456789** [comment]
This happend to me either since yesterday, I tried v0.9, v0.10 and v0.11. A temporary workaround is to search for apps in PlayStore via browser and if you choose an app, let redirect to yalpstore. My rookie opinion is, google changed something on his side.

**Comment by LittleGamie** [comment]
Same here. Was working yesterday and then sometime last night it stopped working and gave me the same issue.

**Comment by LittleGamie** [comment]
It seems to be working for me again!

**Comment by yeriomin** [comment]
@LittleGamie @Technowix @syl3nt @Eskuero @Switch123456789 

> It seems to be working for me again!

Same. They changed some stuff, and reverted it. It's a nightmare!

I have a fix, but considering that it works now, I won't tag the new version right away. I'd like to test some more.

For anyone interested: When you query Google for a list of apps, it **does not return a list** of results, it returns a horrible tree-like structure. Sometimes with **books** and **music albums** mixed in! The actual app list might be **anywhere** in that tree. A similar problem happened before, so I had two hard-coded locations of the lists. The fix i made is a recursive search of every leaf in that tree. I wonder if Play Store app does that. This should make Yalp work even if they change the output in some way I've never seen before. Considering that there are usually 20 items in the returned structure the search is not going to be slow.

Implementation is [here](https://github.com/yeriomin/play-store-api/blob/master/src/main/java/com/github/yeriomin/playstoreapi/SearchIterator.java).

**Comment by Technowix** [comment]
Same on my side, working again
